### ISSUE TITLE
New map issue with more than one parents host

### ISSUE THREAD

**Issue by joseaguardia** [NagiosEnterprises/nagioscore#100]
Hi!

I've this issue with new map in latest stable Nagios version.

I've configured a host like this:

define host{
use                        host-no-critico,host-pnp         
host_name            helpdesk_svrsistemas   
alias                       App helpdesk en svrsistemas
parents                  apache_svrsistemas,mysql_svrsistemas
icon_image            website256.png
statusmap_image  website.gd2
address                 192.168.1.222
}

As you can see in attached files, in legacy map helpdesk_svrsistemas host is linked to both hosts, however in new map system, that host is not linked to mysql_svrsistemas.

Regards.
![nagios_map_legacy](https://cloud.githubusercontent.com/assets/16305835/11811466/f7110708-a335-11e5-8da5-7f22aeda19c0.png)
![nagios_map_new](https://cloud.githubusercontent.com/assets/16305835/11811465/f70fa444-a335-11e5-85a7-e394ef782b73.png)

**Comment by jfrickson** [comment]
The new map definitely has problems with multi-parent objects. It's a limitation in the d3 system. Usually the object shows up twice, attached to both parents separately.

This issue is most likely a duplicate of or closely related to https://github.com/NagiosEnterprises/nagioscore/issues/34

**Comment by joseaguardia** [comment]
I didn't realised that my host were duplicated until now. So, yes, it's the same issue. I'll close this one.

Thanks.
