### ISSUE TITLE
Reg:  version deprication error in graph pluign

### ISSUE THREAD

**Issue by sundarrdeveloper** [NagiosEnterprises/nagioscore#1002]
![graph2](https://github.com/user-attachments/assets/8e001a05-f888-4f00-970c-6dbe8af639ce)

![graph](https://github.com/user-attachments/assets/e9add68f-d54c-4c76-bbe4-7dffd4b2a78d)

I'm trying to view the graph point after entering the host details , but it is showing version deprecation. Please help me to solve this ASAP.

**Comment by aaronagios** [comment]
This looks like a pnp4nagios issue to me. Perhaps make an issue at https://github.com/pnp4nagios/pnp4nagios
