### ISSUE TITLE
New map doesn't work with incorrect icon_image 

### ISSUE THREAD

**Issue by joseaguardia** [NagiosEnterprises/nagioscore#102]
Hello.

This ii¡ssue is regarding to Nagios® Core™ Version 4.1.1

When I set up a correct icon_image file name, new map works fine. However, if you insert a incorrect name for the png file, new map keep loading, and it doesn't display anything.

Regards.

**Comment by jfrickson** [comment]
Try Version 4.1.2-Pre1 at https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1
This problem should be fixed there.

**Comment by jfrickson** [comment]
No response for almost a month, so I'm assuming the 4.1.2-Pre1 version took care of it.
