### ISSUE TITLE
Map Enhancement Request for 'Nagios Process' 

### ISSUE THREAD

**Issue by hooolden** [NagiosEnterprises/nagioscore#103]
By default, everything for the 'Nagios Process' node is showing as 'unknown' in the map.  It would be very nice to have some information here that could be useful.  Here is a forum post from the Nagios support forums requesting this: https://support.nagios.com/forum/viewtopic.php?t=36431#166608

**Comment by scottwilkerson** [comment]
Maybe better would be to just not show anything if the node is the Nagios Process as we don't actually monitor that as a node.

**Comment by jfrickson** [comment]
It turns out it was easier to set some values than to not show anything.

Fixed by commit https://github.com/NagiosEnterprises/nagioscore/commit/3882f151c5d77d82b2ecae9534631cde50598a50
in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1
