### ISSUE TITLE
In host view if you have exactly 100 hosts you do not see host number 100

### ISSUE THREAD

**Issue by mnehlsen** [NagiosEnterprises/nagioscore#110]
In host view if you have exactly 100 hosts you do not see host number 100 if the limit results is set to 100 hosts.

Only 99 hosts are shown and there is no way to go to the next page.

If I change to A limit of 50 or 250 it works fine, that is host number 100 is displayed.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/b993c9bfa38f510784e24b008c2d862cccc0d752.
