### ISSUE TITLE
external command during reload doesnt work

### ISSUE THREAD

**Issue by mimianddaniel** [NagiosEnterprises/nagioscore#112]
running on 4.0.8.
pacakged from the source. 
on centos 6.7 
during restart 
nagiso.cmd is removed so there is clear error of not being able to write to the FIFO
during reload
cmd file exists yet the external cmd issued doesnt get applied  and doesnt show up in the log even after the completion of reload

**Comment by tmcnag** [comment]
Link to thread for reference:  https://support.nagios.com/forum/viewtopic.php?f=7&t=36801

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/605f731e00c16948dfdcdab97995f9989eb8c131.

**Comment by pm426** [comment]
With this change, submitting passive command during reload caused while loop to never terminate in my testing.  `sigrestart` variable is never set to `FALSE`.

Instead, `if(sigrestart) return 0;` at the beginning of `command_input_handler()` did the trick for me.

Steps taken to reproduce this:
- reload running nagios process
- submit passive command to nagios.cmd

At this point strace of main nagios process showed repeating `nanosleep()`.

NOTE: Temporarily adding `sleep()` before `sigrestart = FALSE` in base/nagios.c will allow to submit passive command to demonstrate the issue.
