### ISSUE TITLE
Core workers looping

### ISSUE THREAD

**Issue by jfrickson** [NagiosEnterprises/nagioscore#113]
In certain situations, a worker process will start looping in the `gather_output()` function calling `read()` and take up 100% of CPU.

See thread at https://support.nagios.com/forum/viewtopic.php?f=7&t=36767

**Comment by jfrickson** [comment]
I will have a better fix soon(ish)

**Comment by MalcolmPreen** [comment]
No panic (the temp fix is still working)... but do you have a more detailed estimate as to when "soon(ish)" might be ?

**Comment by jfrickson** [comment]
Fixed with commit https://github.com/NagiosEnterprises/nagioscore/commit/e4b00a3e09e2de5d1f73be6b61b09f857bcd0012. Ended up going with the original fix. Sorry for the delay!
