### ISSUE TITLE
avail.cgi patch submission

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#114]
Cross-posting this from the forums:

https://support.nagios.com/forum/viewtopic.php?f=34&t=37396#p174615

**Comment by jfrickson** [comment]
The `time_t` fix was put in via commit https://github.com/NagiosEnterprises/nagioscore/commit/97f6b01862dcdd0281392fd16c4c4160c37b85eb and is now in production.

**Comment by jfrickson** [comment]
Reopened after a comment on the thread mentioned above. Now closing as the fix is now in place via commit https://github.com/NagiosEnterprises/nagioscore/commit/0560b8da5266ddb6595f6f4f279cb175aaf4ec05
