### ISSUE TITLE
[Featurerequest] Add colors to status map

### ISSUE THREAD

**Issue by rcknag** [NagiosEnterprises/nagioscore#118]
On a map if all hosts and their services are Ok it reads Up in green under the host.
If any of the hosts have any services that are Critical it reads "Services Critical" in red under that host.
If any of the hosts services are in Warning and no Criticals it reads "Services in Warning" in yellow under the host.
Allow anyone to see the status map - https://support.nagios.com/forum/viewtopic.php?t=37460

**Comment by jfrickson** [comment]
Adding text would be difficult, and tend to unnecessarily clutter the display. The hostname itself will now be colored the same colors as the services in the popup. Red for critical, orange for unknown, yellow for warning, and gray for pending.

Now in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/92848d3d10453fb0ef83bc494bea06516556c12b
