### ISSUE TITLE
Template error doesn't cause validation to fail

### ISSUE THREAD

**Issue by pdugas** [NagiosEnterprises/nagioscore#119]
Running `nagios -v /etc/nagios/nagios.cfg` exposed a typo in my configs where I had one host template "use" two others but one of them didn't exist.  Something like this.

```
define host {
  name a
  use b,c
  register 0
}
```

In my setup, `b` existed but `c` didn't and the expected error was generated when validating the config.
```
Error: Template 'c' specified in host definition could not be not found (config file '/etc/nagios/conf.d/eg.cfg', starting on line 123)
```

The trouble is, the end of the validation output reported zero total errors and the program exited successfully.  I had been restarting the Nagios service expecting the successful validation meant no such error existed in my configs.

Shouldn't this error increment the total errors?

**Comment by jfrickson** [comment]
I assume the validation output you're talking about is `nagios.conftest`. If `-v` fails on an object error such as yours, nagios does not get to the point where it writes the `nagios.conftest` file. It quits with a return code of `1`. You are most likely looking at an old conftest file. Check the return code first.

If that isn't your problem, please reopen this issue.
