### ISSUE TITLE
on-demand host checks triggered by service checks cause attempt number increments

### ISSUE THREAD

**Issue by fredericve** [NagiosEnterprises/nagioscore#121]
I discovered a bug in nagioscore which causes the attempts counter to increment when a service check triggers an on-demand host check.

This behaviour is different from version 3.x and ultimately renders the `check_interval` and `retry_interval` timers useless since any service check will trigger an on-demand check and increment the counter.

Say you have a host configured like this:

```
define host
{
   use generic-host
   host_name host.name
   address host.name.domain.local
   check_interval 5
   retry_interval 1
   max_attempts 20
}
```

Then assume that you have 10 services assigned to that host, each with `check_interval` of 1 minute.

When that host becomes unavailable you would expect it to go into HARD DOWN state after about 20 minutes. Instead, each service check that fails will trigger another host check and increment the counter counting towards max_attempts. I have seen such a host to reach HARD DOWN state after only 2 minutes depending on the amount of service checks defined for it.

I think I narrowed this down to the changes in commit a466b8f75d19819ca329069b555ea8c3fb872717. This commit cause all the checks to be scheduled. Previously, the on-demand host checks would be executed like this:

```
run_async_host_check(temp_host, CHECK_OPTION_NONE, 0.0, FALSE, FALSE, NULL, NULL);
```

The 4th argument being FALSE is used to indicate that it is not a scheduled check.

Now it is executed this way:

```
schedule_host_check(temp_host, current_time, CHECK_OPTION_NONE);
```

This causes `run_async_host_check()` to be executed with the 4th argument set to TRUE.

I'm not familiar with the nagios code so I could be completely off here of course.

**Comment by tmcnag** [comment]
Forum post where this is discussed:

https://support.nagios.com/forum/viewtopic.php?f=7&t=37973

**Comment by fredericve** [comment]
After digging some more, I found that in nagios 3.5.1 it is using the cached state:
[Fri Apr 15 09:16:15 2016.250010] [016.1] [pid=20113] Service is in a non-OK state!
[Fri Apr 15 09:16:15 2016.250014] [016.1] [pid=20113] Host is currently UP, so we'll recheck its state to make sure...
[Fri Apr 15 09:16:15 2016.250018] [016.1] [pid=20113] * Using cached host state: 0

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/5430ccace894a6c813fdd7f2f9ea79ea93371d32 (pull request #122)
