### ISSUE TITLE
corewindow parameter can be used to perform Malicious URL Redirect

### ISSUE THREAD

**Issue by rakesh-patnaik** [NagiosEnterprises/nagioscore#125]
on nagios deployment with apache2 one can use corewindow parameter as follows to direct the user to a different site and sneak out information from unsuspecting users.

https://my-nagios.url.com?corewindow=https://www.wikipedia.org/

above page opens wikipedia.org under the main frame of nagios page. A malicious url could be built to make unsuspecting users input sensitive information on a snooping page.

Observerd in: Nagios core 3.5.1
Code in master branch still has this bug according to this line: https://github.com/NagiosEnterprises/nagioscore/blob/master/html/index.php#L12

![image](https://cloud.githubusercontent.com/assets/5775993/14866568/f2f07e5c-0c89-11e6-9129-214101705137.png)

**Comment by jfrickson** [comment]
There are uses that depend on this functionality. I've set the milestone to 4.3.0, and labeled it as an enhancement. We may be able to do something if there's a configuration option. We are discussing it internally and will update this issue when appropriate.

**Comment by jfrickson** [comment]
This has now been fixed in the "maint" branch which should be released some time this month.
