### ISSUE TITLE
when HOST is UP after UNREACHABLE, eventhandler is not executed

### ISSUE THREAD

**Issue by PepeOnAChair** [NagiosEnterprises/nagioscore#128]
This behaviour I found on Version 4.1.2-Pre1, 4.1.1 and 4.0.8 - I haven`t tried to find this bug on other versions.
Pepe

**Comment by jfrickson** [comment]
This seems to be working in the current `maint` branch. Can you try it and see if it's working for you?

**Comment by jfrickson** [comment]
No response since Feb 16, so I'll assume current branch fixes the problem. Closing.
