### ISSUE TITLE
nagios host URL parameter for NEW map doesn`t work - Network Map for All Hosts 

### ISSUE THREAD

**Issue by PepeOnAChair** [NagiosEnterprises/nagioscore#129]
Hello,

even if I click on icon for map close to HOST definition (in the attachment) NEW map is generated and shown for all HOSTs - we have a few thousands of HOSTs, so it crash Firefox or at least slow it down to unusability.

Version 4.1.1 and 4.1.2-Pre1

http://IP.AD.RE.SS/nagios/map.html?host=some_host_name

Pepe
![new map problem](https://cloud.githubusercontent.com/assets/19305232/15180045/9390c4ac-177f-11e6-9610-6ccba324f80c.JPG)
![map for just one host - but all hosts are printed](https://cloud.githubusercontent.com/assets/19305232/15180046/983bd41a-177f-11e6-838a-ec3c44c5726b.JPG)

**Comment by jfrickson** [comment]
Neither the old nor new maps limited the number of hosts displayed when the link is clicked on in the host summary page. So there's nothing I can do about that right now.

But I did notice that the new map doesn't highlight the selected hostname, so I added that. It's in place now on the maint branch via commit https://github.com/NagiosEnterprises/nagioscore/commit/91614dbc755a7ce2454afae2d06c0c1d9b2b793d

If you want to limit the number of hosts, you can submit a feature request, explaining which hosts you would like to see, and if you want the Nagios process to show. Then we can discuss it internally and make a decision.
