### ISSUE TITLE
Install Nagios 4.0.8 on Ubuntu 14.04

### ISSUE THREAD

**Issue by sysads** [NagiosEnterprises/nagioscore#13]
Hi

I have tried to install nagios 4.0.8 on ubuntu 14.04 and ran into few issues like

sudo make install-webconf

which failed because its pointing to httpd and not apache2, that I have worked around it but when i try to acess localhost/nagios/, site does not exist. I followed this instruction http://assets.nagios.com/downloads/nagioscore/docs/Installing_Nagios_Core_From_Source.pdf.

Anyone successfully installed it on Ubuntu 14.04. thanks

**Comment by nesajeevan** [comment]
hi what was the solution for that.. please doe share I am also getting the same error like

**Comment by box293** [comment]
The configure string needs to be:
```
./configure --with-nagios-group=nagios --with-command-group=nagcmd --with-mail=/usr/bin/sendmail --with-httpd-conf=/etc/apache2/sites-enabled
```

Here's a handy guide:
http://sites.box293.com/nagios/guides/installing-nagios/4-0-x/ubuntu-14-04
