### ISSUE TITLE
Nagios exiting on SIGTERM

### ISSUE THREAD

**Issue by marce1000** [NagiosEnterprises/nagioscore#131]
Nagios 4.1.1 - About every 3 or 4 weeks we see NAGIOS exiting with following entry
in nagios.log

                    [time-stamp] Caught SIGTERM, shutting down...

M.

**Comment by Mike-Sbg** [comment]
Did you got an answer, or found out, how to fix it?

**Comment by marce1000** [comment]
On Mon, Jul 11, 2016 at 7:47 AM, Mike <notifications@github.com> wrote:

>     >Did you got an answer, or found out, how to fix it?
>

       No,

Marc.

**Comment by box293** [comment]
I recommend that you ask for help about this on the Nagios Support Forum:

https://support.nagios.com/forum/viewforum.php?f=7

**Comment by Mike-Sbg** [comment]
The support forum is limited to paying customers only ... that's a pitty ...

**Comment by ericloyd** [comment]
The link that box293 supplied you with takes you to the General Support forum for Nagios Core.  This is public, for everyone, not just customers.

**Comment by marce1000** [comment]
> >The support forum is limited to paying customers only ... that's a pitty
> ...
>

  Very true , I guess; of course the original bug report was filed as such
(meaning to file an encountered-bug);  wether the bug-maintainers choose to
keep this bug
report or not is  up to their choice.

Marc.

>
>

**Comment by marce1000** [comment]
> >The link that box293 supplied you with takes you to the General Support
> forum for Nagios Core. This is public, for everyone, not just customers
>

 Ok, thanks for the info,

Marc

**Comment by Mike-Sbg** [comment]
Ich bin von Mo, 15.08.2016 bis Mo, 29.08.2016 abwesend.

Ich werde Ihre Nachricht sobald wie möglich beantworten, jedoch bitte ich
gleich vorweg um Entschuldigung für etwaige Verzögerungen - eine
automatische Weiterleitung erfolgt nicht!

In dringen Fällen bitte an Hr.Vitzthum (vit@wuestenrot.at) wenden!





























Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[NagiosEnterprises/nagioscore] Nagios exiting on SIGTERM (#131)" gesendet
am 24.08.2016 22:48:18.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by marce1000** [comment]
> >I don't see anything about this in forums. Is it still a problem (ref.
> nagios exiting on SIGTERM)
>

 John, thanks for your reply, in between, I have upgrade NAGIOS to *4.2.0*;
so this is no longer relevant
(in the sense that should I encounter problems with 4.2.0 , *I can always
file a new bug report)*.

Marc.

>
>

**Comment by Mike-Sbg** [comment]
Ich bin von Mo, 15.08.2016 bis Mo, 29.08.2016 abwesend.

Ich werde Ihre Nachricht sobald wie möglich beantworten, jedoch bitte ich
gleich vorweg um Entschuldigung für etwaige Verzögerungen - eine
automatische Weiterleitung erfolgt nicht!

In dringen Fällen bitte an Hr.Vitzthum (vit@wuestenrot.at) wenden!





























Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[NagiosEnterprises/nagioscore] Nagios exiting on SIGTERM (#131)" gesendet
am 25.08.2016 9:57:01.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by jfrickson** [comment]
Ok, closing for now. Thanks!

**Comment by Mike-Sbg** [comment]
Ich bin von Mo, 15.08.2016 bis Mo, 29.08.2016 abwesend.

Ich werde Ihre Nachricht sobald wie möglich beantworten, jedoch bitte ich
gleich vorweg um Entschuldigung für etwaige Verzögerungen - eine
automatische Weiterleitung erfolgt nicht!

In dringen Fällen bitte an Hr.Vitzthum (vit@wuestenrot.at) wenden!





























Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[NagiosEnterprises/nagioscore] Nagios exiting on SIGTERM (#131)" gesendet
am 25.08.2016 16:09:32.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
