### ISSUE TITLE
Feature Request: return code xxx out of bounds - include message as well

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#132]
When a plugin returns an exit code other than 0,1,2,3 it reports "return code xxx out of bounds".

However the output / error message from the plugin is not included. This means you need to go off on a troubleshooting adventure to find the source of the problem.

I would be really helpful if the output from the plugin was also included in the service status. This should make troubleshooting the issue slightly easier.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/ad9d527ef488a748344509b2232bd95b49ab6f9e
