### ISSUE TITLE
empty lines in plug-in output

### ISSUE THREAD

**Issue by kaganeli** [NagiosEnterprises/nagioscore#137]
Nagios 4.1.1 translates empty lines output by a plugin into "\n". 

So this test plugin
```
#!/bin/sh
echo TEST
echo line 1
echo line 2
echo
echo line 4
exit 0

```
produces this output
```
TEST
line 1
line 2
\nline 4

```

**Comment by jfrickson** [comment]
Running a test and looking up the result in the ndo2db database, I see this:
```
output | long_output
TEST   | line 1\nline 2\n\nline 4
```
which looks ok to me. Where are you seeing the problem?

**Comment by kaganeli** [comment]
Running the above test plugin produces this on the web gui:
![image](https://cloud.githubusercontent.com/assets/20050190/19117771/328d77fe-8ae8-11e6-997c-60135ccfe425.png)
I would expect to see a blank line between "line 2" and "line 4" rather than a "\n"

**Comment by jfrickson** [comment]
I did make some changes for version 4.2, and that must have fixed it as a side effect. Here's what I get:
![capture](https://cloud.githubusercontent.com/assets/13370023/19118310/a835b676-8ae1-11e6-904b-a306857a469e.PNG)
I'll close this, but if you upgrade to the current version and still have a problem, you can reopen it.
