### ISSUE TITLE
Nagios Core 4.1.1 bug: Tactical Overview - Disabled Flap Detection Link

### ISSUE THREAD

**Issue by cbadeau** [NagiosEnterprises/nagioscore#139]
Hi, Noticed in 4.1.1 that the link to services with flap detection disabled from the tactical overview page takes you to the wrong page.  Thanks.

**Comment by truedays** [comment]
Are you expecting these old URLs shown here:
https://github.com/NagiosEnterprises/nagioscore/commit/7fba64ed48a86f74fe6bcdea42efd4f302058cb9 ?

If so, can you elaborate on what's wrong with the current URLs? #48 may have introduced a regression. 

Mentioning #48 folks..
@scottwilkerson 
@tmcnag

**Comment by cbadeau** [comment]
Hi Ray,
On the ‘Tactical Overview’ page, when you have flap detection disabled for some services, you get a link under ‘Monitoring Features’ > ‘Flap Detection’ (i.e. a red box containing ‘X Services Disabled’).  Clicking on this link should return the list of services with flap detection disabled.  It does not.  It returns a list of all hosts in the system. I have not found a way in 4.1.1 to get a list of services with flap detection disabled.

Hope this helps.

Thanks,
Chuck

**Comment by jfrickson** [comment]
Fixed in the nagios-4.1.2-RC2 branch via the commit referenced above.
