### ISSUE TITLE
Better support of HTTP attributes

### ISSUE THREAD

**Issue by jvuibert** [NagiosEnterprises/nagioscore#140]
A better support of HTTP attributes from Nagios would be appreciated : "content-type" of HTTP header for Nagios GUI of syndication (RSS) flows.
For instance, Nagios core does not inform the HTTP attribute content-type.

**Comment by jfrickson** [comment]
I'm having trouble locating a place where we don't provide the content-type header. Can you provide a sample URL?

**Comment by jfrickson** [comment]
No response to my last question, so I'm closing the issue. Please reopen if you have further information.

**Comment by jvuibert** [comment]
Dear John,

First, please accept all my apologises for a such late answer to your question.

In fact my customer looked at the html source code of a Nagios page and did not see the http attributes like
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

Do you think it will be possible to include ths in a future version of Nagios ?
Do I need to re-open the issue ?

Thanks for your answer.

Best regards


De : John C. Frickson [mailto:notifications@github.com]
Envoyé : mercredi 24 août 2016 22:30
À : NagiosEnterprises/nagioscore
Cc : Vuibert, Jerome; Author
Objet : Re: [NagiosEnterprises/nagioscore] Better support of HTTP attributes (#140)


No response to my last question, so I'm closing the issue. Please reopen if you have further information.

**Comment by jfrickson** [comment]
Reopening. Note to self: a couple of static pages, but mostly CGIs.

**Comment by jfrickson** [comment]
It looks like these were all fixed via commit https://github.com/NagiosEnterprises/nagioscore/commit/b2c1ae082d1482550467cb5cea67da51fe55dff1 back on Sep 7, 2016, and released with version 4.2.2 on Oct 24, 2016.
