### ISSUE TITLE
clear flapping state

### ISSUE THREAD

**Issue by mcapra** [NagiosEnterprises/nagioscore#142]
User would like the ability to clear the flapping state (and maybe the underlying data) with the push of a button

Reference: https://support.nagios.com/forum/viewtopic.php?t=39358#189803

**Comment by ericloyd** [comment]
I'll agree that this would be nice to have.  Maybe, for now, just a new command to send to nagios.cmd, allowing one to write a quick script to reset it.  That would almost be "easy peasy" to set up and roll out a patch for.  GUI updates could be made later for those less inclined to write directly to the pipe.

**Comment by jfrickson** [comment]
Added in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/5c828588ff865318fea6442c41773b682c988191. Will most likely be released next week.
