### ISSUE TITLE
status.cgi high CPU utilization in nagios-4.1.1

### ISSUE THREAD

**Issue by notfol** [NagiosEnterprises/nagioscore#143]
In nagios-4.1.1 status.cgi is utilizing 100% CPU making the web UI extremely slow. Removing a large servicegroup (8 distinct services X ~500 hosts) appears to improve the condition. I should mention this servicegroup participates in a service dependency. We do not encounter this issue in nagios-4.0.8. In the strace I observed a lot of time spent for the following calls:
- brk(..)
- stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0

OS: Centos 6.7
Memory Total: 8G
CPU: 8 X 2.3GHZ 

nagios version: nagios-4.1.1

truncated strace:
brk(0x11244000)                         = 0x11244000
brk(0x11265000)                         = 0x11265000
brk(0x11286000)                         = 0x11286000
brk(0x112a7000)                         = 0x112a7000
brk(0x112c8000)                         = 0x112c8000
brk(0x112e9000)                         = 0x112e9000
brk(0x1130a000)                         = 0x1130a000
...
mmap(NULL, 5140480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f16309f8000
mmap(NULL, 135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f16309d7000
open("/usr/local/nagios/var/status.dat", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=9666680, ...}) = 0
mmap(NULL, 9666680, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f163009e000
open("/etc/localtime", O_RDONLY)        = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1636d7e000
read(4, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\4\0\0\0\4\0\0\0\0"..., 4096) = 2819
lseek(4, -1802, SEEK_CUR)               = 1017
read(4, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 1802
close(4)                                = 0
munmap(0x7f1636d7e000, 4096)            = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
....

**Comment by jfrickson** [comment]
Unfortunately, there not much that can be done right now. But changes for Core 5 will take care of it. So I'm scheduling this for Core 5.

**Comment by hedenface** [comment]
I'm closing all tasks related to improvements in reports. These are all going to undergo some serious refactoring in the next major release.
