### ISSUE TITLE
Bug in map.php on Nagios Core 4.2.0

### ISSUE THREAD

**Issue by thale13** [NagiosEnterprises/nagioscore#145]
Just installed nagios core 4.2.0 on RHEL7 and found this when trying to look at the map:

[Tue Aug 02 10:17:12.004387 2016] [:error] [pid 19762] [client x.x.x.x:58239] PHP Notice:  Undefined variable: img in /usr/share/nagios/map.php on line 58, referer: http://<server hostname>/nagios/map.php?host=all

Looking at map.php, line 58 is         <body ng-controller="mapCtrl" <?php echo $img; ?>>
and $img is defined in an if block starting on line 12.  

Effectively, if 'statusmap_background_image' is unset in cgi.cfg, $img never gets initialized/instantiated and then errors out on line 58.

I don't know for sure if this is causing the map not to display for me, but it certainly isn't helping.

**Comment by thale13** [comment]
I did hack it like so:  <?php if (isset($cfg["statusmap_background_image"])) { echo $img; } ?>>

I'm a sysadmin and not a programmer so I don't know if that is 'good' or not but the error went away.  Map still doesn't display, just the spinner in the upper left, but the error went away.

Thanks.

**Comment by jfrickson** [comment]
The other way would be `$img = "";` just before the `if` statment on line 12.

**Comment by thale13** [comment]
that way would make much more sense.

**Comment by jfrickson** [comment]
Was the map was working before the install of 4.2.0?

**Comment by thale13** [comment]
yes.  I had 4.0.8 installed, build an RPM for 4.1.1 and installed it.  Then noticed 4.2.0 was out and did the same.  It seems like the map links aren't working right as the 'View Status' links are missing the cgi-bin reference, but from what I can find on the host, the map-links.html file is correct.  I am betting it's something on my host that got screwed up, just haven't figured out what yet.

**Comment by jfrickson** [comment]
Try two things:
1) Use the `[Legacy]` link next to `map` and make sure the old cgi still works for you
2) If that works, try v4.1.1 and see if the new map works there

**Comment by thale13** [comment]
Legacy works as expected (Just checked).  Earlier this morning 4.1.1 worked as expected.  I will try that again shortly.

**Comment by thale13** [comment]
Uninstalled 4.2.0 and installed 4.1.1, applied config to get host objects, etc.  Map works as designed.

**Comment by thale13** [comment]
Although interestingly enough, I get "The requested URL /nagios/status.cgi was not found on this server." when I select any of the "View Status..." links on the upper left menu.

**Comment by jfrickson** [comment]
That _should_ be `/nagios/cgi-bin/status.cgi`. Something has definitely gone sideways.

Rerun configure like this: `./configure --whatever-options-you-enter > config.out 2>&1` then attach `config.out` and `config.log` to a comment here.

**Comment by thale13** [comment]
I will, but I didn't run ./configure.  I ran 'rpmbuild -ta nagios-4.1.1.tar.gz (or nagios-4.2.0.tar.gz) on a different host to build an RPM.  I know that ran configure, but it's a slightly different process I think.

**Comment by thale13** [comment]
Here is the config.log from the rpmbuild for 4.1.1
[config.log.txt](https://github.com/NagiosEnterprises/nagioscore/files/397388/config.log.txt)

Also, thank you for helping me with this.  I had not intended to get this detailed when I sent in the bug, I was just excited that I might be able to contribute somehow and figured it was an easy fix.

**Comment by jfrickson** [comment]
At first glance, it looks fine. I'll look into it more and see if I can find the problem. It probably will be an easy fix, just hard to find the problem ;-)

Thanks for all the input!

**Comment by thale13** [comment]
as an additional point of information, when I hover over the Nagios Processes, I see this:
![screen shot 2016-08-02 at 1 37 41 pm](https://cloud.githubusercontent.com/assets/20796791/17338687/60cfd788-58b6-11e6-849a-98ad7ce3106a.png)

**Comment by jfrickson** [comment]
The problem with the links to status info, and the popup for the Nagios process were fixed in 4.2.0.

I did an `rpmbuild` of 4.2.0 on a CentOS 7 machine and an `rpm -i` to install it. Using the default configuration (only a few localhost checks), the map showed up fine.

Go back to 4.2. Open the javascript console and try to pull up the map. If it shows errors, let me know. If not, try it with the default configuration and see if that works. If it does, try commenting out sections of your config.

**Comment by thale13** [comment]
Will do.  Didn't even think about the javascript console....

**Comment by thale13** [comment]
Now it works just fine.  I don't get it, but the map is running as I would expect, and the status links work as well.

Thank you for all the help, I really do appreciate it.

**Comment by jfrickson** [comment]
Sunspots. Gremlins. Cosmic rays. Sometimes it just doesn't work for no apparent reason.

Glad it's working now, though!

**Comment by bee272** [comment]
I encountered this as well after updating from 4.1.1 to 4.2.1. Clearing the browser cache solved the issue...if I only had though about this half an hour earlier ;-)
