### ISSUE TITLE
many gcc unused-result warnings

### ISSUE THREAD

**Issue by imsedgar** [NagiosEnterprises/nagioscore#149]
When compiling nagios 4.2.0 on Fedora 24 (for rpm package creation), there are many unused-result warnings from gcc. I think it would make nagios saver if these warnings will be fixed.

Here the results of compiling with warning message.

[Uploading nagios-4.2.0-warning-unused-result.txt…]()

**Comment by knweiss** [comment]
FWIW: The `nagios.spec` RPM spec file in the nagios-4.2.0 tarball is aware of this issue and tries to disable the compiler warning ("fixing the symptom") - however, **only for el6**:
```
# Allow newer compiler to suppress warnings
%if 0%{?el6}
  %define myXcflags -Wno-unused-result
%else
  %define myXcflags %{nil}
%endif
```
See [DistTag](https://fedoraproject.org/wiki/Packaging:DistTag) for details.

**Comment by jfrickson** [comment]
I'm going to be enabling a _**bunch**_ of warnings in Core 5, so I can clean it all up. Just FYI. I doubt I'll do too much with 4.x.

**Comment by hedenface** [comment]
Closing the issue to get it off the list. This is something that will make it into 5. If you still have a lot of compiler warnings after that, re-open it and we'll take it from there. Thanks!
