### ISSUE TITLE
Nagios Core on Mac OS 10.11 Segmentation Fault

### ISSUE THREAD

**Issue by Josh3955** [NagiosEnterprises/nagioscore#151]
I downloaded Nagios Core 4.2.0 source and compiled on Mac OS 10.11 aka El Capitan. Upon execution I get a segmentation fault.

bash-3.2$ ./nagios /Library/Server/Web/Data/Sites/Default/nagios/etc/nagios.cfg 

Nagios Core 4.2.0
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 08-01-2016
License: GPL

Website: https://www.nagios.org
Nagios 4.2.0 starting... (PID=79592)
Local time is Sun Aug 07 18:59:29 PDT 2016
nerd: Channel hostchecks registered successfully
nerd: Channel servicechecks registered successfully
nerd: Channel opathchecks registered successfully
nerd: Fully initialized and ready to rock!
wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 79594;pid=79594
wproc: Registry request: name=Core Worker 79595;pid=79595
wproc: Registry request: name=Core Worker 79596;pid=79596
wproc: Registry request: name=Core Worker 79593;pid=79593
wproc: Registry request: name=Core Worker 79597;pid=79597
wproc: Registry request: name=Core Worker 79598;pid=79598
Segmentation fault: 11
bash-3.2$ 

I'm willing to work with someone and provide debug, logs, etc.  Just let me know what you need.

**Comment by darylrichards** [comment]
Not help, just a me too. Different OS

FreeBSD logging.oxfordcounty.local 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64


Nagios Core 4.2.0
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 08-01-2016
License: GPL

Website: https://www.nagios.org
Nagios 4.2.0 starting... (PID=1250)
Local time is Mon Aug 22 11:24:23 EDT 2016
nerd: Channel hostchecks registered successfully
nerd: Channel servicechecks registered successfully
nerd: Channel opathchecks registered successfully
nerd: Fully initialized and ready to rock!
wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 1251;pid=1251
wproc: Registry request: name=Core Worker 1253;pid=1253
wproc: Registry request: name=Core Worker 1252;pid=1252
wproc: Registry request: name=Core Worker 1254;pid=1254
Segmentation fault

**Comment by darylrichards** [comment]
wrong actually.. I applied the patch for #154 and it solved my startup problem.

**Comment by jfrickson** [comment]
@Josh3955, I've made some changes that might fix your problem. Try using https://github.com/NagiosEnterprises/nagioscore/archive/maint.tar.gz and see if you still segfault.

**Comment by Josh3955** [comment]
I can confirm this build works!.  There are compile-time warnings/errors, but compile does finish and it will launch successfully without a default.  Very nice!

**Comment by jfrickson** [comment]
Great! I'll close this issue. In an upcoming release, I'll try to clean up those warnings and errors. Not in 4.2.1, but probably 4.2.2.

**Comment by Josh3955** [comment]
Thanks so much!
