### ISSUE TITLE
nagios security

### ISSUE THREAD

**Issue by qknight** [NagiosEnterprises/nagioscore#152]
# nagios version

Nagios® Core™

Version 4.0.8

# problem
check_ssh for instance returns:
```
SSH OK - OpenSSH_7.2 (protocol 2.0) 
```

but i've noticed that one can just return:
```
<script>alert()</script>
```
and it will execute that code. 

# solution 
escape returned html and don't just put it inside the dom and execute it. this is a real security problem!

**Comment by jfrickson** [comment]
Unfortunately, some third-party apps (such as check_multi) will return copious amounts of html and javascript. Some users also include javascript in check returns. So despite the security problem, we have to allow html and javascript.

On your own system, you can set `escape_html_tags=1` in `cgi.cfg` to disable html and javascript.
