### ISSUE TITLE
Running nagios -v on 4.2.0 takes 90+ seconds.

### ISSUE THREAD

**Issue by davidnewhall** [NagiosEnterprises/nagioscore#154]
Hello,

After upgrading from 4.1.1 to 4.2.0, the `nagios -v` takes 90 seconds to return. Pre-upgrade run-time was less than 2 seconds. I traced it down to a specific commit, but my ability beyond debugging to providing a patch is limited. For now I'm running 4.2.0 without this change and it seems stable. 

https://github.com/NagiosEnterprises/nagioscore/commit/35371f54cb9df0153ba5dd2fa7403799bf4d3c45

Opened a thread here with a bit more info: https://support.nagios.com/forum/viewtopic.php?f=7&t=39826&p=193112#p193112

Thanks for looking into it for me,
-david

**Comment by jfrickson** [comment]
A probable fix is in the 'maing' branch at https://github.com/NagiosEnterprises/nagioscore/tree/maint

You can download it from https://github.com/NagiosEnterprises/nagioscore/archive/maint.tar.gz
or apply the fix in commit https://github.com/NagiosEnterprises/nagioscore/commit/ac0a96f61a58776329d5003a1e93fba9878de50b

Please test and let me know if this fixes it for you.

**Comment by davidnewhall** [comment]
I'll try it out this week. Thank you!

**Comment by jfrickson** [comment]
@davidnewhall did you get a chance to try it?

**Comment by jfrickson** [comment]
@davidnewhall did you get a chance to try it?

**Comment by jfrickson** [comment]
No response so I'll assume at this point that it's fixed. Closing.
