### ISSUE TITLE
Passive problems not showing as "unhandled"

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nagioscore#157]
If you have a service with passive checks in a warning or critical state, they do not show up on the list of unhandled problems, but they do show up on the list of all problems.

Issue reported by nozlaf on the Nagios Core support forum here: https://support.nagios.com/forum/viewtopic.php?t=39957

I was able to recreate the issue in Nagios 4.2.0.

**Comment by jfrickson** [comment]
Fixed in branch maint via commit https://github.com/NagiosEnterprises/nagioscore/commit/eb7f24b59fa1a34e579054438a6c94e183b82178
