### ISSUE TITLE
nagios-4.2.0.tar.gz.gz

### ISSUE THREAD

**Issue by knweiss** [NagiosEnterprises/nagioscore#159]
The  [official nagios-4.2.0.tar.gz tarball](https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.2.0.tar.gz) (md5sum 750a9a6c80b0cec39c989b8c6b2f1599) on the official download page was **compressed twice** with gzip.

**Comment by jfrickson** [comment]
Very strange. A new one will be uploaded shortly. Thanks!
