### ISSUE TITLE
Nagios dies silently if you reload the configuration and resource.cfg is not readable by the nagios user

### ISSUE THREAD

**Issue by maxwellhaydn** [NagiosEnterprises/nagioscore#164]
I originally submitted this on the [old bug tracker](http://tracker.nagios.org/view.php?id=640) but it looks like it hasn't been migrated to GitHub. It was closed as won't-fix, but I think the closer misunderstood the problem. Apologies if opening a new issue is the wrong thing to do.

Reloading the configuration (e.g. `systemctl reload nagios`) causes nagios to die silently if resource.cfg is not readable by the nagios user:

```
$ ls -l /usr/local/nagios-4.2.0/etc/resource.cfg
-rw-r----- 1 root root 1340 Sep  2 14:31 /usr/local/nagios-4.2.0/etc/resource.cfg
$ systemctl start nagios
$ systemctl status nagios
* nagios.service - LSB: Starts and stops the Nagios monitoring server
   Loaded: loaded (/etc/rc.d/init.d/nagios)
   Active: active (running) since Fri 2016-09-02 14:35:02 MDT; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 20524 ExecStart=/etc/rc.d/init.d/nagios start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nagios.service
           |-20543 /usr/local/nagios-4.2.0/bin/nagios -d /usr/local/nagios-4.2.0/etc/nagios.cfg
           |-20545 /usr/local/nagios-4.2.0/bin/nagios --worker /usr/local/nagios-4.2.0/var/rw/nagios.qh
           |-20546 /usr/local/nagios-4.2.0/bin/nagios --worker /usr/local/nagios-4.2.0/var/rw/nagios.qh
           |-20547 /usr/local/nagios-4.2.0/bin/nagios --worker /usr/local/nagios-4.2.0/var/rw/nagios.qh
           |-20548 /usr/local/nagios-4.2.0/bin/nagios --worker /usr/local/nagios-4.2.0/var/rw/nagios.qh
           `-20551 /usr/local/nagios-4.2.0/bin/nagios -d /usr/local/nagios-4.2.0/etc/nagios.cfg

Sep 02 14:35:02 mcmes21.cgd.ucar.edu systemd[1]: Starting LSB: Starts and stops the Nagios monitoring server...
Sep 02 14:35:02 mcmes21.cgd.ucar.edu nagios[20524]: Starting nagios: done.
Sep 02 14:35:02 mcmes21.cgd.ucar.edu systemd[1]: Started LSB: Starts and stops the Nagios monitoring server.
$ systemctl reload nagios
$ systemctl status nagios
* nagios.service - LSB: Starts and stops the Nagios monitoring server
   Loaded: loaded (/etc/rc.d/init.d/nagios)
   Active: active (exited) since Fri 2016-09-02 14:35:02 MDT; 16s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 20585 ExecReload=/etc/rc.d/init.d/nagios reload (code=exited, status=0/SUCCESS)
  Process: 20524 ExecStart=/etc/rc.d/init.d/nagios start (code=exited, status=0/SUCCESS)

Sep 02 14:35:02 mcmes21.cgd.ucar.edu systemd[1]: Starting LSB: Starts and stops the Nagios monitoring server...
Sep 02 14:35:02 mcmes21.cgd.ucar.edu nagios[20524]: Starting nagios: done.
Sep 02 14:35:02 mcmes21.cgd.ucar.edu systemd[1]: Started LSB: Starts and stops the Nagios monitoring server.
Sep 02 14:35:15 mcmes21.cgd.ucar.edu nagios[20585]: Running configuration check...
Sep 02 14:35:15 mcmes21.cgd.ucar.edu nagios[20585]: Reloading nagios configuration...
Sep 02 14:35:15 mcmes21.cgd.ucar.edu nagios[20585]: done
Sep 02 14:35:15 mcmes21.cgd.ucar.edu systemd[1]: Reloaded LSB: Starts and stops the Nagios monitoring server.
Sep 02 14:35:17 mcmes21.cgd.ucar.edu nagios[20543]: Error: Cannot open resource file '/usr/local/nagios/etc/resource.cfg' for reading!
$ pgrep nagios
$
```

In the original ticket, jfrickson said:

>We *could* regain root privileges to read it, but having root privileges for anything accept the bare minimum time for startup or shutdown is generally frowned upon. Plus, in newer init systems, the daemon *never* has root. So if the file is owner root:root, nagios will never start up. 

Nagios starts up fine with systemd. Besides, the problem is not that the reload failed; the problem is that it failed *silently*. When I originally reported this, our Nagios installation was down for two days because the reload didn't report an error to screen.

It should be abundantly clear that the nagios process is no longer running when a reload fails. For example:

```
$ systemctl reload nagios
Job for nagios.service failed because the control process exited with error code. See "systemctl status nagios.service" and "journalctl -xe" for details.
```

This is what Apache does.

**Comment by jfrickson** [comment]
Ok, I understand now.

That's because systemd is starting/stopping/reloading nagios based on the `/etc/rc.d/nagios` script. The current version of core doesn't come with a systemd file.

Put a `nagios.service` file in `/usr/lib/systemd/system`, delete `/etc/rc.d/nagios`, run `systemctl daemon-reload` then `systemctl enable nagios` and `systemctl start nagios`.

After that, a `systemctl reload nagios` will fail with the appropriate error message if it can't read `resource.cfg` or if it fails for any other reason.

Here's the one I'm using, which will be pretty close to the one that will be distributed in nagios core v4.3.0. Adjust as necessary:

```
#
# nagios.service
#
# Copyright (c) 2016 Nagios(R) Core(TM) Development Team
#
[Unit]
Description=Nagios Network Monitoring
Documentation=http://www.nagios.org/documentation
After=var-run.mount nss-lookup.target network.target local-fs.target \
    remote-fs.target time-sync.target syslog.socket
Before=getty@tty1.service plymouth-quit.service xdm.service
Wants=ndo2db

[Install]
WantedBy=multi-user.target
Alias=monitoring_daemon.service

[Service]
Type=forking
Restart=on-abort
EnvironmentFile=-/etc/sysconfig/nagios
PIDFile=/usr/local/nagios/var/nagios.lock
ExecStartPre=/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
ExecStart=/usr/local/nagios/bin/nagios -d /usr/local/nagios/etc/nagios.cfg
ExecReload=/bin/kill -HUP $MAINPID
ExecStopPost=/bin/rm -f /var/run/nagios/nagios.lock
ExecStopPost=/bin/rm -f @pkglocalstatedir@/status.dat
ExecStopPost=/bin/rm -f /var/run/nagios/nagios.cmd
TimeoutStopSec=90
User=nagios
Group=nagios
PrivateTmp=true
ProtectSystem=true
ProtectHome=true
OOMScoreAdjust=-500
```

**Comment by saydulk** [comment]
I am using Ubuntu 16.04 LTS 64 bit. systemctl status nagios.service failed 



![screenshot from 2017-11-02 05 21 49](https://user-images.githubusercontent.com/1058663/32302625-d393e554-bf8d-11e7-8dd7-915fb1d46c48.png)
![screenshot from 2017-11-02 05 21 53](https://user-images.githubusercontent.com/1058663/32302628-d3d3ec1c-bf8d-11e7-9edd-204aef0619dd.png)
![screenshot from 2017-11-02 05 22 07](https://user-images.githubusercontent.com/1058663/32302629-d416cd52-bf8d-11e7-8fe1-a6db48efaad5.png)

**Comment by govindmaddula** [comment]
Ok, I understand your problem
I think we edited your configuration file and that configuration file having some mistakes that'y we are getting those "journalctl  -xe" and  it won't start nagios seervice

can plesase run below command inside your objects,
"sudo  /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg"
may be it will work try it.
