### ISSUE TITLE
September reported as Sept instead of Sep

### ISSUE THREAD

**Issue by orbison** [NagiosEnterprises/nagioscore#165]
There is a long-standing bug which makes Nagios format the name of the month September as **Sept** instead of **Sep**.

The incorrect month name occurs for instance in the LONGDATETIME environment macro. Any software which depends on this macro and tries to parse its value using `strptime` fails:

```
NOTIFY job 28765 from worker Core Worker 25825 is a non-check helper but exited with return code 1
[...]
  stderr line 17: ValueError: time data 'Sat Sept 3 23:59:32 CEST 2016' does not match format '%a %b %d %H:%M:%S %Z %Y'
  stderr line 18:
  stderr line 19:  - Expression: "datetime.datetime.strptime(n.LONGDATETIME, '%a %b %d %H:%M:%S %Z %Y').strftime('%-d.%-m.%Y %H:%M:%S')"
```

The attached patch fixes this issue.
[nagios-sept.txt](https://github.com/NagiosEnterprises/nagioscore/files/454575/nagios-sept.txt)

**Comment by jfrickson** [comment]
Fixed in branch maint via commits https://github.com/NagiosEnterprises/nagioscore/commit/dd1862dbfbee69469141761c7d966991cbf0dc68 and https://github.com/NagiosEnterprises/nagioscore/commit/fcf369af6717de968c2fd0af432d447e5eaa3b2e
