### ISSUE TITLE
Add a statusCRITICALACK

### ISSUE THREAD

**Issue by ianbamforth** [NagiosEnterprises/nagioscore#166]
Acknowledging a service status, it would be nice if that changed the colour of the Status column on the status.cgi page too.  The background of the rest of the row changes class (although the css has the same colour for ACK as for not).

The reason for this is that we occasionally have issues that cannot be fixed immediately (e.g. if they are outside our control) and wish to ACK them.  If the bright red CRITICAL is still there, it makes it harder to spot new problems arising.

**Comment by ericloyd** [comment]
I'm liking this idea, since it bypasses the age-old question of "can we have another color for XXX status?"  Changing the background to 25% gray would be good, I think.  It would still leave the big red "CRITICAL" box.

**Comment by ianbamforth** [comment]
@ericloyd - the big red CRITICAL box is exactly what I want to be able to customise through css.  The background is already set to #FFBBBB by .statusBGCRITICALACK.

**Comment by ericloyd** [comment]
I understand.  I think you would have an easier sell to be able to change the row background to a gray value, rather than sell the idea of changing the red CRITICAL to something "less red."  That's my opinion, but in an ideal world, both would be customizeable.

**Comment by jfrickson** [comment]
Currently in place in branch `nagios-4.4.0-alpha1`. Watch the `nagios-4.4.0*` branches as they get renamed.
