### ISSUE TITLE
Servicegroups cannot contain service checks that are assigned via hostgroups

### ISSUE THREAD

**Issue by ericloyd** [NagiosEnterprises/nagioscore#168]
From forum post https://support.nagios.com/forum/viewtopic.php?f=6&t=40187

Servicegroups cannot contain service checks that are assigned via hostgroups.  In other words, if I have a host group called X that has four hosts in it, and create a service called Y that runs on hostgroup X, I cannot create a servicegroup that contains Y, since Y is not assigned to specific hosts.

I'm not sure what the solution is, but a much better (and long-term development) goal would be to create an object-oriented approach to things within Nagios, so there is no differentiation (configuration-wise) between a host and a service. It's just "thing to be monitored." Then a group of things is a just a group, a dependency is just a parent/child relationship, which could easily replace dependencies, and greatly simplify life in general.  So many of my abnormal problems would just melt away.

**Comment by ericloyd** [comment]
Update - one can go to the service and add it to a servicegroup, but one cannot go to the servicegroup and add services.

Also, BPI groups cannot contain services that are assigned via hostgroups. 

This is a bit of a show stopper for a number of our larger customers that use hostgroups to assign services.

**Comment by hedenface** [comment]
I like the idea of all things being objects, but this is another Pretty Big Change, so I'll tentatively schedule it for 5, and we'll talk about it.

**Comment by ericloyd** [comment]
I love two year anniversaries as much as the next person, but any further word on this as part of a roadmap?

**Comment by ericloyd** [comment]
Still need closure on the original problem, though.  Any thoughts?

> Servicegroups cannot contain service checks that are assigned via hostgroups. In other words, if I have a host group called X that has four hosts in it, and create a service called Y that runs on hostgroup X, I cannot create a servicegroup that contains Y, since Y is not assigned to specific hosts.

> Also, BPI groups cannot contain services that are assigned via hostgroups.

That second one is about to be a BIG problem for a large university.

**Comment by scottwilkerson** [comment]
I just tested the second point and it works as expected.

**Comment by ericloyd** [comment]
Yeah, I just tested both points too and they work.  I think I need a vacation.  Both of these things seem to work these days.  Forget it.  Sorry.  Go back to Thursday.
