### ISSUE TITLE
CSV output based on groups

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#169]
https://support.nagios.com/forum/viewtopic.php?t=29146&start=9999#bottom

User would like to have CSV export based on servicegroups and hostgroups, as opposed to just all services and all hosts.

**Comment by jfrickson** [comment]
Looking into this. Should be possible.

**Comment by jfrickson** [comment]
Fixed in branch "nagios-4.4.0-alpha1" via commit https://github.com/NagiosEnterprises/nagioscore/commit/6f0ec5a05044dd1c43c18465f735ad8fe8425e99

See the commit for notes
