### ISSUE TITLE
Empty check_timeperiod on active checks can cause rescheduling log spam

### ISSUE THREAD

**Issue by abrist** [NagiosEnterprises/nagioscore#17]
Tested on core 4.0.8.
To reproduce:

Create a host with active checks enabled and a timeperiod like:

define timeperiod {
        timeperiod_name                         none
        alias                                   No Time Is A Good Time
        }

Now stop the nagios service, delete retention.dat, and then restart nagios.  Afterwards, force an immediate check.  Once checked, it will schedule the next check based on its interval.  From here on, it will continue to try to check, fail due to the timeperiod, but reschedule it even though the time period is empty.  Every time it tries to check, it will spam your logs with:

Warning: Check of host 'xxxx' could not be rescheduled properly. Scheduling check for [xxx]

I would argue that the check should not be rescheduled at all it nagios cannot find a valid time period to do so instead of defaulting to rescheduling the check on the next the check_interval.

**Comment by tmcnag** [comment]
Not seeing this in 4.1, even checked nagios.debug with debug level set to -1.

Might have been resolved here:  https://github.com/NagiosEnterprises/nagioscore/blob/master/base/logging.c#L67-69
