### ISSUE TITLE
No root group in FreeBSD and Apple OS X

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#173]
In FreeBSD and Apple OS X there is no "root" group, it's called "wheel".

In Makefile.in I needed to change this line:
```
INIT_OPTS=-o root -g root
```
To this:
```
INIT_OPTS=-o root -g wheel
```

Detailed installation guide can be found here:
https://support.nagios.com/kb/article.php?id=96

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/d7f690014455ad6608893651cfa448f0f8afe453

**Comment by box293** [comment]
Tested maint branch and confirmed fixed.
