### ISSUE TITLE
install-exfoliation and install-classicui don't work FreeBSD and Mac OS X

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#174]
In FreeBSD and Apple OS X there are issues when install-exfoliation or install-classicui is run. 

The "for file in" loop fails, something to do with that behaviour being different on FreeBSD and Mac OS X.

In Makefile.in I needed to change this:
```
install-exfoliation:
	@cd contrib/exfoliation; \
	for file in $$(find . -path "./stylesheets/*" -o -path "./images/*" -type f); do \
		install -m 644 $(INSTALL_OPTS) -D $${file} $(DESTDIR)$(HTMLDIR)/$${file}; \
	done; \
	cd ../..

	@echo ""
	@echo "*** Exfoliation theme installed ***"
	@echo "NOTE: Use 'make install-classicui' to revert to classic Nagios theme";
	@echo ""

install-classicui:
	@cd html; \
	for file in $$(find . -path "./stylesheets/*" -o -path "./images/*" -type f); do \
		install -m 644 $(INSTALL_OPTS) -D $${file} $(DESTDIR)$(HTMLDIR)/$${file}; \
	done; \
	cd ..

	@echo ""
	@echo "*** Classic theme installed ***"
	@echo "NOTE: Use 'make install-exfoliation' to use new Nagios theme";
	@echo ""
```
To this:
```
install-exfoliation:
	cp -rf contrib/exfoliation/stylesheets/* $(DESTDIR)$(HTMLDIR)/stylesheets
	cp -rf contrib/exfoliation/images/* $(DESTDIR)$(HTMLDIR)/images

	@echo ""
	@echo "*** Exfoliation theme installed ***"
	@echo "NOTE: Use 'make install-classicui' to revert to classic Nagios theme";
	@echo ""

install-classicui:
	cp -rf html/stylesheets/* $(DESTDIR)$(HTMLDIR)/stylesheets
	cp -rf html/images/* $(DESTDIR)$(HTMLDIR)/images

	@echo ""
	@echo "*** Classic theme installed ***"
	@echo "NOTE: Use 'make install-exfoliation' to use new Nagios theme";
	@echo ""
```

I'm sure there's a nicer way of doing this.

Detailed installation guide can be found here:
https://support.nagios.com/kb/article.php?id=96

**Comment by Semirben** [comment]
Same issue on Solaris 11. After reverting the commands in Makefile to them of Nagios 4.1.1 (same as posted  above), everything is working again. 
Is it possible to change it back?

**Comment by box293** [comment]
Thanks @Semirben for highlighting that, I completely forgot to add the steps to fix this for Solaris in the installation guide. I've just updated the installation guide to reflect this. Once the problem is fixed and part of a release I'll update the guide.

**Comment by jfrickson** [comment]
The `for file in $$(` must be a bash-ism. Maybe we can require bash? Nah, probably not.

I guess I could revert to the old way, then add in `chmod` and `chown` commands. Thoughts?

**Comment by box293** [comment]
I think the old way with chmod and chown is probably the simplest method.

**Comment by Semirben** [comment]
I would also say that the old way is better. I also think the main problem isn't located at ```for file in $$(``` but in the ```find``` command afterwards which (at least on default Solaris 11) isn't handled properly

**Comment by jfrickson** [comment]
Ok, I found the problem, fixed it, and tested on Solaris 11, FreeBSD, ans OS/X El Capitan. Should be good to go!

Fix is in 'maint' branch vi commit https://github.com/NagiosEnterprises/nagioscore/commit/1c8bb0194d2bc474d5361c976abe1e0d03337243

**Comment by Semirben** [comment]
Just as an information: It's working on Solaris 11 (SPARC and i386)

**Comment by box293** [comment]
Tested maint branch for Mac OSX and FreeBSD and confirmed fixed.
