### ISSUE TITLE
Reduce reconfiguration time by forking nagios process

### ISSUE THREAD

**Issue by willemdh** [NagiosEnterprises/nagioscore#176]
As apply configurations are taking longer and longer. It can take up to 40 seconds before Nagios is back online. A system should get implemented where a parent process is spawned which takes over the monitoring with the old configuration. The new configuration is loaded in a duplicate child process. When the new configuration is loaded completely, the parent process with the old configuration is killed and the new process takes over, resulting in a supposed 'downtime' of only 3-5 seconds.

**Comment by MyCatHasEyes** [comment]
I would like to +1 this. The idea of zero down time to add an update or make a change is worth looking into. This would benefit the entire Nagios community.
Thanks
Steve B

**Comment by jfrickson** [comment]
I'm hoping to implement zero downtime in Core 5, without forking.

**Comment by willemdh** [comment]
@jfrickson Imho solving the downtime during apply configuration issue would be a huge improvement to Nagios for 250+ hosts setups.

**Comment by hedenface** [comment]
I'm closing the issue to clear up space on the github tracker, @willemdh . This is actually on our list, and will definitely be in Core 5.

**Comment by willemdh** [comment]
@hedenface Good to hear that it will be in Core 5! Thanks!
