### ISSUE TITLE
Add sanity checks to malloc()/calloc() in nagios-3.4.3 and nagios-plugins-1.4.16

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#178]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000410](http://tracker.nagios.org/view.php?id=0000410)  - Please follow that link for details.
> Originally submitted on 2012-12-19 by dogbert2

**Comment by jfrickson** [comment]
This is an ongoing concern that won't be corrected all at once, and is on my list of code improvements. So I'm closing this issue.
