### ISSUE TITLE
enforce a need for comment for action taken on host and services

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#180]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000052](http://tracker.nagios.org/view.php?id=0000052)  - Please follow that link for details.
> Originally posted 2009-07-09 by shadhin71

Currently only acknowledging problem requires to input a comment. It would be great for tracking if we can enforce all action requiring a comment. Specially for disabling checks and disabling notification.

Note: related to https://github.com/NagiosEnterprises/nagioscore/issues/82

**Comment by jfrickson** [comment]
On 2010-11-07, rkcarter posted:

> Related to this, I'd like to see nagios.cfg options for enforcing/not enforcing various types of comments. I agree with what you're saying here, but in our case, we'd like to NOT be forced to comment on all acknowledgements, but rather ack and get on with the work, and follow up later.

**Comment by jfrickson** [comment]
Fixed in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.4.0-alpha1 via commit https://github.com/NagiosEnterprises/nagioscore/commit/f885e90478abbc6cba368ac3eb9a4d49e85f3a48
