### ISSUE TITLE
nested servicegroups: duplicated services information

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#183]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000223](http://tracker.nagios.org/view.php?id=0000223)  - Please follow that link for details.
> Originally submitted on 2011-05-27 by hahnn

Seems a bug to me:

I create a servicegroup A
I create a servicegroup B
I create a servicegroup T

servicegroup A contains 4 passive service checks on a unique host X
servicegroup B contains 3 passive service checks on a unique host Y

servicegroup T contains two servicegroup members: A and B

When I display the service groups summary in nagios web interface, for my servicegroup T I can see:
the number 2 in the host status summary, which is correct
the number 14 in the service status summary, which is not correct, because I've a total of 7 services. Here, it displays twice the correct total.

Now, when I click on the servicegroup name T to have the detailed view of what is contained in it, I see the correct data:
in the host column, I see two hosts (X and Y)
in the services column, I see 4 services for host X, and 3 services for host Y

Now, taking a look at the individual servicegroups A and B, this is all correct everywhere.

I can see the same problem extracting the information from nagios using mklive status plugin.

Creating a request to view the content of servicegroup T, all information in it are simply duplicated. I have:
twice all information for first passive check of host X,
twice all information for second passive check of host X,
twice all information for third passive check of host X,
twice all information for fourth passive check of host X,

twice all information for first passive check of host Y,
twice all information for second passive check of host Y,
twice all information for third passive check of host Y

I did a diff between all couples of information to be sure it was exactly twice the same, and it is.

I forgot to mention that:
the servicegroup T (which contains both A and B service groups) is itself member of another servicegroup, let's call it K. And in this servicegroup K, I'll have to add other T like servicegroups.

Also, X and Y hosts are members of several hostgroups each, which for some can be the same.

**Comment by jfrickson** [comment]
Unable to duplicate. Using the suggested config, I do not get any service duplication in the counts. I'm assuming this issue was fixed sometime in the past 5.5 years. Closing.
