### ISSUE TITLE
flapping notification in acknowleged service

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#186]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000275](http://tracker.nagios.org/view.php?id=0000275)  - Please follow that link for details.

**Comment by jfrickson** [comment]
The original issue is from 2011 against version 3.3.1. Notifications are sent for each hard critical event and recovery, and flapping and recovery whether or not previous events have been acknowledged.
