### ISSUE TITLE
Macro URL Encoding Bug

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#187]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000316](http://tracker.nagios.org/view.php?id=0000316)  - Please follow that link for details.
> Originally submitted on 2012-04-03 by irix

If a notes URL has a `$SERVICEDESC$` macro, and the service description has a space, the space is converted to "+". When the notes URL macro is processed, it is URL encoded, so the prior "+" gets converted to %2B, which causes the plus to be used literally instead of as a space. The parameter becomes `"foo+bar"` instead of `"foo bar"`, which will cause unexpected results.

**Comment by jfrickson** [comment]
Unable to reproduce. I'm assuming it's been fixed sometime in the last 4.5 years.
