### ISSUE TITLE
Building nagios-plugins from the included SPEC file errors

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#188]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000365](http://tracker.nagios.org/view.php?id=0000365)  - Please follow that link for details.

**Comment by jfrickson** [comment]
Should have been (and now is) moved to https://github.com/nagios-plugins/nagios-plugins - https://github.com/nagios-plugins/nagios-plugins/issues/179
