### ISSUE TITLE
Layout of Nagios Core Services

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#189]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000376](http://tracker.nagios.org/view.php?id=0000376)  - Please follow that link for details.
> Originally submitted on 2012-08-20 by pyshen

See page for info http://support.nagios.com/forum/viewtopic.php?f=7&t=6930 [^]

So with it set to display 100 services.

My last host on the page has 5 services.
3 of the 5 services display on the frst page
2 of the 5 services display on the 2nd page.

What I am saying is it should be max of 100 services rather then 100 services. So display 97 services since with the last host not all services fit on the same page. This way for that last host it can put the services all on the 2nd page.

**Comment by jfrickson** [comment]
I've done some preliminary checking on this. It might be more trouble than it's worth, especially since nobody has commented or upvoted in over four years. We'll discuss internally.

**Comment by hedenface** [comment]
Closing since community feedback was scarce at best.
