### ISSUE TITLE
line1 & line2+ not separated by space in $SERVICEPERFDATA$

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#190]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000378](http://tracker.nagios.org/view.php?id=0000378)  - Please follow that link for details.

**Comment by jfrickson** [comment]
The original issue was opened in 2012 for version 3.4.1. Testing v4.2.1, I am unable to reproduce the bug, so I'm assuming it was fixed sometime in the past four years.
