### ISSUE TITLE
illegal_macro_output_chars strips single quotes from *PERFDATA macros

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#192]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000404](http://tracker.nagios.org/view.php?id=0000404)  - Please follow that link for details.
> Originally submitted on 2012-11-24 by jhankins

Originally reported in issue 13: http://tracker.nagios.org/view.php?id=13

Marked as fixed, but it isn't. Service perfdata that has single quotes around the labels per:

    http://nagiosplug.sourceforge.net/developer-guidelines.html#AEN203

shows the single quotes in the CGI output, but when the $SERVICEPERFDATA$ macro is used later, the quotes have been stripped. Likewise, if you enable saving perfdata to a file in nagios.cfg, the quotes have been stripped at this point.

The comment in issue 13 says "This appears to have been fixed sometime between ages ago and now." I am using 3.4.1, and single-quotes are still being stripped in perfdata.

**Comment by jfrickson** [comment]
Paraphrasing the comment from tracker issue 13, "This appears to have been fixed sometime between 3.4.1 and now". I created a plugin that included single quotes, and my nagios.cfg includes a signle quote in `illegal_macro_output_chars'. I see the single quotes in the perfdata.
