### ISSUE TITLE
Rotated log files should use YYYY-MM-DD for date in filenames

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#193]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000412](http://tracker.nagios.org/view.php?id=0000412)  - Please follow that link for details and two comments.
> Originally submitted on 2013-01-10 by matt

The rotated log files created by Nagios use filenames that do not sort naturally when getting a directory listing. This is because the filenames look like "nagios-MM-DD-YYYY-00.log"

It would help greatly if the filenames used YYYY-MM-DD for the date so they would sort in temporal order when getting a directory listing.

**Comment by jfrickson** [comment]
Looking into this for a possible change in 4.4.0.

**Comment by jfrickson** [comment]
We're probably going to be changing logging for Core 5, so I'm scheduling this for 5.0

**Comment by hedenface** [comment]
I'd like to just ask a simple question: why aren't we using logrotate for this? And installing our own logrotate files at install time?

This is the obvious solution.. that's kind of what it was meant for. We could likely get rid of a lot of unnecessary code this way. Let's do that.

I'm closing this issue and tentatively scheduling replacing our custom log rotation with logrotate functionality for 5.0.0
