### ISSUE TITLE
additional service check intervals...

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#194]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000452](http://tracker.nagios.org/view.php?id=0000452)  - Please follow that link for details.

**Comment by jfrickson** [comment]
Duplicate issue is #239

**Comment by jfrickson** [comment]
This will require the addition of another check interval in the host/service definition. So it will have to wait for Core 5.

**Comment by hedenface** [comment]
Closing this, since it is a duplicate, but because the other issue has more detail.
