### ISSUE TITLE
Status Map Include/Exclude Doesn't Fully Work - Map Layer Remains The Same

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#197]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000473](http://tracker.nagios.org/view.php?id=0000473)  - Please follow that link for details.
> Originally submitted on 2013-08-12 by chrisp

From: http://support.nagios.com/forum/viewtopic.php?f=18&t=11396

When trying to get a simpler view of the network of hosts by including only a particular hostgroup in the '/nagios/cgi-bin/statusmap.cgi' the excluded hosts are removed from the map, but their positions within the network remain, so not actually excluding them properly at all & making the operation useless for the intended use (simplifying the view).

http://support.nagios.com/forum/viewtopic.php?f=18&t=11396#p60142

I have sorted this by using an old patch (for a different Nagios version) on the new statusmap.c (the old patch did not apply automatically using "patch statusmap.c statusmap.c.patch", so it was a laborious manual task).

There were 2 sections which I couldn't quite get my head around, so I inserted the potential patches as comments, hoping that someone might tell me they-re not needed (likely) or how to best apply them (if needed at all).

The change in include/exclude functionality that I had intended, seems to have worked exactly as I'd hoped. However, while I was testing this, I noticed that because there's an automatic refresh in place, that, combined with the fact that the cgi script uses "POST" rather than "GET", the page gets reset to the default view (which is a blank URL), every <refresh_rate> seconds - annoying. I altered the method to "GET" & this is no longer a problem.

I've attached a diff between the original statusmap.c from Nagios Core v3.5.0 & my current one, which includes the patches from: http://exchange.nagios.org/directory/Patches/Nagios-Core/Show-service-state-in-statusmap--2D-Nagios-3-2E3/details and now most of the patches from: http://ten-fingers-and-a-brain.com/2011/03/getting-more-out-of-the-nagios-statusmap/ - I hope I've done it right and that it's useful to others.

**Comment by jfrickson** [comment]
We're not really doing anything with the old cgi map any more, and the new one doesn't support inclusions/exclusions.
