### ISSUE TITLE
serviceextinfo doesn't honor allow_empty_hostgroup_assignment

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#198]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000478](http://tracker.nagios.org/view.php?id=0000478)  - Please follow that link for details.

**Comment by jfrickson** [comment]
This may have been fixed already. Even if it hasn't, `serviceextinfo` is deprecated and no longer subject to fixes.
