### ISSUE TITLE
HOSTSTATEID returns 0 even if host does not exist

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#200]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000490](http://tracker.nagios.org/view.php?id=0000490)  - Please follow that link for details and one comment.
> Originally submitted on 2013-09-20 by yann-fertat

The macro HOSTSTATEID returns even if the host supplied does not exist.

In the case of a bad configuration (wrong host provided) a check can return "OK".

This macro is used for checks like "check_host_cluster" that can return 0 (OK) status even if the supplied hosts does not exist.

I believe it should return 2 (UNREACHABLE) if the host is not present in Nagios.

This was tested on 2 instances of Nagios 3.4.4 both on CentOS 5.X.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/4ccd1f0b15cf5b849a1f73b067ac1305b246857c
