### ISSUE TITLE
Feature request: OK notifications only if other notification sent

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#202]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000508](http://tracker.nagios.org/view.php?id=0000508)  - Please follow that link for details.
> Originally submitted on 2013-10-16 by ericdives

Say I have a service with an escalation or other notification level set to c,r (alert on Criticals and Recovery). Thing is, if the service goes from OK, to Warning, back to OK, and this is an overnight setting, we'd prefer not to get the Warning->OK notice.

I know this may be a bit to ask.

We have an on-call rotation set up, and for some services on some hosts, we have the service set to notify via pager only when the service goes in to Critical state. However, if the service corrects itself before the on call person gets a chance to check it, then they'd like to get the "OK" as well. However, if the service goes in to Warning, they (appropriately) don't get notified (we do have it send an email for notification purposes, but no paging). However, if it goes back to OK from Warning, they get woken up being told the service is "OK". In addition, if the service stays Warning long enough, everyone will get the "OK" page, even though no one was paged for the Warning state.

Essentially, we'd like a notification option that says "Notify of OK only if non-OK notification sent."

**Comment by jfrickson** [comment]
My testing shows that this is working properly with the current version of core (4.2.2). It was probably fixed in 4.1.x.
