### ISSUE TITLE
Notifications on Summer time

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#203]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000517](http://tracker.nagios.org/view.php?id=0000517)  - Please follow that link for details.
> Originally submitted on 2013-10-22 by rgreiner

Following a sugestion from user "abrist", I'm reporting a bug on DST with Nagios Core 3.5.1.

This weekend, Summer Time started here in Brazil. When it started, my Nagios Core 3.5.1 install, running on a Debian 6.0.7 - 32bit, installed from source (not apt-get), generated an insane amount of notifications on user.log (37,280,771 notifications to be exact). It's a relatively small install: Note: 0000120 monitored hosts, Note: 0000500 monitored services. I don't use nrpe, only direct tests (icmp, tcp) and snmp.

I've reported this in the forums in http://support.nagios.com/forum/viewtopic.php?uid=42986&f=7&t=21763&start=0&sid=bff0dd5dbfe9843cf8bb5aa63c38087e

My config files don't have many modification. nagios.cfg is untouched, except for the addition of the following files (obvious use):

```
cfg_file=/usr/local/nagios/etc/objects/services.cfg
cfg_file=/usr/local/nagios/etc/objects/hosts.cfg
cfg_file=/usr/local/nagios/etc/objects/hostextinfo.cfg
```

resource.cfg only has two lines added, where I included my most common snmp communities:

```
$USER7$=<my snmp community>
$USER8$=<another snmp community>
```

Nothing else was touched in nagios/etc.

All notifications in user.log where of the type "service X is OK" or "HOST Y is OK". Examples:

```
Oct 19 23:00:00 sirius nagios: CURRENT HOST STATE: 3Com8-4500;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 2.25 ms
Oct 19 23:00:00 sirius nagios: CURRENT HOST STATE: DLink-anexo;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 2.27 ms
Oct 19 23:00:00 sirius nagios: CURRENT HOST STATE: DLink-datacenter;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 2.28 ms
Oct 19 23:00:00 sirius nagios: CURRENT HOST STATE: DLink-poe-datacenter-1;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 1.07 ms
Oct 19 23:00:00 sirius nagios: CURRENT HOST STATE: Linksys-ap-nead-auditorio;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 0.67 ms
Oct 19 23:00:00 sirius nagios: CURRENT HOST STATE: Linksys-auditorio;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 26.43 ms
Oct 19 23:00:00 sirius nagios: CURRENT HOST STATE: Linksys-cantoria;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 5.48 ms
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: canopus;SSH;OK;HARD;1;SSH OK - OpenSSH_6.0p1 Debian-4 (protocol 2.0)
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: canopus;Uptime;OK;HARD;1;SNMP OK - Timeticks: (149696117) 17 days, 7:49:21.17
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: cat-core.net.unesp.br;PING;OK;HARD;1;PING OK - Packet loss = 0%, RTA = 20.66 ms
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: ceti;CPU_Linux;OK;HARD;1;CPU Load : 1%
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: ceti;Carga;OK;HARD;1;86 process matching ^[a-zA-Z]* (> 5) (<= 1000):OK
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: ceti;Discos Todos;OK;HARD;1;/var: 5%used(1099MB/20151MB) /: 12%used(879MB/7123MB) (<90%) : OK
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: ceti;Mailq;OK;HARD;1;SNMP OK - "OK: mailq (99) is below threshold (500/1000)
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: ceti;PING;OK;HARD;1;PING OK - Packet loss = 0%, RTA = 16.89 ms
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: ceti;SMTP;OK;HARD;1;SMTP OK - 0.074 sec. response time
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: ceti;SSH;OK;HARD;1;SSH OK - OpenSSH_5.5p1 Debian-6+squeeze3 (protocol 2.0)
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: cygni;CPU_Linux;OK;HARD;1;CPU Load : 1%
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: cygni;Carga;OK;HARD;1;68 process matching ^[a-zA-Z]* (> 5) (<= 1000):OK
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: cygni;HTTP;OK;HARD;1;HTTP OK: HTTP/1.1 200 OK - 326 bytes in 0.033 second response time
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: cygni;Linux Load;OK;HARD;1;Load : 0.00 0.00 0.00 : OK
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: cygni;PING;OK;HARD;1;PING OK - Packet loss = 0%, RTA = 12.71 ms
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: edutec;CPU_Linux;OK;HARD;1;CPU Load : 0%
Oct 19 23:00:01 sirius nagios: CURRENT SERVICE STATE: edutec;Carga;OK;HARD;1;156 process matching ^[a-zA-Z]* (> 5) (<= 1000):OK
```

Reproduction of the problem is somewhat difficult, since I would have to put the machine back to Summer Time beggining, and I can't do that in my production environment. After that amount of messages was generated, everyting was working fine. Nagios continued to monitor and report correctly. Also, all messages where also copied to my central syslog server.

Is any other type of info required?

Thank you,

Roberto Greiner

**Comment by jfrickson** [comment]
This is an old (3 years) issue reported against core 3.5.1 and as far as I can find, nobody else has reported the problem since. I am unable to reproduce. If anyone still has a problem, please open a new issue.
