### ISSUE TITLE
Nagios 4.0 - problems mixing result_limit and non-default column sorts.

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#205]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000531](http://tracker.nagios.org/view.php?id=0000531)  - Please follow that link for details.
> Originally submitted on 2013-11-07 by MalcolmPreen

I've noticed what appears to be an oddity with the web display having upgraded to nagios 4.0.

I have over 1500 live services being monitored... and almost 100 hosts.

The default web interface limits the output to 50 results... which makes sense for speed of display refresh....

Typically I use a number of views, sorted by different columns... depending on what I am looking for...

However, using both Chrome and Firefox, I have noticed an odd bug / feature...

If I sort by, say, SERVICE (ascending) it shows me the first 50 in alphabetical order.... but if I click on page 2, then the display reverts to the default sort order... which then doesn't show the service I am looking for....

The same happens if I change the "limit results" from 50 to All.... it shows all the results... but changing the sort... reverts back to 50 results.

What I would like, is for the "limit results", column sort selection, and page number (if applicable) to remain selected following a click....

I have a "sort of" avoidance, whereby I set the result_limit to unlimited... which allows me to sort... and then scroll to find the "page" I want... by setting `result_limit=0` in cgi.cfg

But this isn't really what I want to do...

I created this as a query on the forum (http://support.nagios.com/forum/viewtopic.php?f=7&t=21961&sid=c2d2995433aabba686f1b6cf37ab81cc), and was advised:
> I just tested this. It is a bug with core 4. Works fine in 3.5.x. Please file a bug report.

Hence, this report.

**Comment by jfrickson** [comment]
Unable to reproduce. Must have been fixed sometime in the last 3 years.

**Comment by MalcolmPreen** [comment]
interesting.... I've just checked on nagios 4.2.1 and can confirm I can't reproduce the problem !

Thanks to whoever fixed it in the meantime !!

Malcolm
