### ISSUE TITLE
[PATCH] daemon_dumps_core=1 has no effect on Linux when Nagios started as root

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#206]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000532](http://tracker.nagios.org/view.php?id=0000532)  - Please follow that link for details.
> Originally submitted on 2013-11-11 by atj

Under Linux, system calls that manipulate process UIDs and GIDs (such as setuid) cause the "dumpable" flag to be reset to 0. This is described under the PR_SET_DUMPABLE section in the prctl man page:

http://man7.org/linux/man-pages/man2/prctl.2.html#DESCRIPTION

This means that when Nagios is started as root and subsequently calls setgid/setuid it will not dump core regardless of the value of daemon_dumps_core. The attached patch fixes this by adding a header check for "sys/prctl.h" and if found a call to prctl() in drop_privileges() (base/utils.c).

Note that this change requires the configure script to be updated by running autoconf.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/00394b24a26577e5a6b0dc4d41523615b89733cc

Note: core dumps (if any) will go in $HOME if set, or the directory containing the nagios.log file, or "/".
