### ISSUE TITLE
Configuration Parsing allows bad directives in host definition

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#207]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000547](http://tracker.nagios.org/view.php?id=0000547)  - Please follow that link for details.
> Originally submitted on 2013-12-04 by klb327

Configuration parser appears to allow the directive "name" to be used in host definitions, rather than throwing an error (should be "host_name"). This causes strange behavior; Nagios accepts the definition, but cannot use it anywhere. Attempting to join the host to a group or service causes errors saying that it was unable to find the host/unable to expand hostgroup.

Trying to create a second host with the same "name" directive will cause a duplicate definition error, but creating a second host with the "host_name" directive will not.The bad definition also doesn't show up in the web interface.

Seems strange that the configuration will accept the "name" directive but I don't see that listed as a valid directive for a host in any documentation.

**Comment by jfrickson** [comment]
`name` is used for host templates, `host_name` is used for actual devices. At the point these fields are being parsed, there is no way to know if the definition is for a template or a device. (Except if the field is `name`, then it's a template.)

So, if an actual device definition uses `name`, it's created as a template. There's not really anything we can do about that.
