### ISSUE TITLE
Creating a contactgroup made only of a contactgroup ignores the configuration

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#209]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000552](http://tracker.nagios.org/view.php?id=0000552)  - Please follow that link for details.

**Comment by jfrickson** [comment]
This was written against version 4.0.1. I was unable to duplicate the problem running 4.2.x. Closing.
