### ISSUE TITLE
heredity of host contacts and contact groups to a service not working as expected

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#212]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000603](http://tracker.nagios.org/view.php?id=0000603)  - Please follow that link for details.
> Originally submitted on 2014-04-23 by nook

Hi,

I created a host and defined some contacts and a contact group. In the second step i created a service wich should inherit the contacts from the host and notify a own contact group. But this is not working in nagios 4 like in nagios 3.x. So i noticed that the C files are different an i wrote a little patch to fix this bug.

This is my config file:

This is working in nagios3 (and in nagios 4 with my patch):
define host {
 use generic-host
 host_name inherit
 alias contact inherit
 address 127.0.0.1
 check_command check-host-alive
 max_check_attempts 3
 contact_groups info
 contacts daniel,nook
 notification_interval 1440
 notification_period 24x7
 notification_options d,r
 flap_detection_enabled 0
}

define service {
 use LAN_PING
 host_name Vererbung
 flap_detection_enabled 0
 contact_groups test
}

With the Patch nagios will notify the contact groups test and the contacts daniel and nook

If you run the same configuration in an unpatched version of nagios 4 it only will notify the contact group "test". 

Best regards,

Daniel

**Comment by jfrickson** [comment]
This is working as designed. See the comment in http://tracker.nagios.org/view.php?id=0000314
