### ISSUE TITLE
Configuration check don't work within hostgroup

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#215]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000614](http://tracker.nagios.org/view.php?id=0000614)  - Please follow that link for details.
> Originally submitted on 2014-05-13 by shorty2380

If you make a typo inside the hostgroup definition, nagios won't check this. Not with the check (/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg)nor with restarting the nagios service.

For example:
Hostname in the hostdefinition: ...TEST03...

Typo in the hostgroup definition: TEST01, TEST02, Test03, TEST05, TEST06

Nagios will performe checks for TEST01 and TEST02, the other hosts will ignored (not loaded wihtout an error or warning. you just wondering why nagios restart without an error but won't display your services / hosts.

I have Nagios Core 4.0.6 installed (is not availbe in the drop down, yet).

Cheers

I use in the service configuration hostgroup_name and not the host_name:
```
define service{
    use local-service
    hostgroup_name Test
    check_command check_ping!100.0,20%!500.0,60%
    } 
```

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/f7b759f355cddb6ba3471fdb5b1e7d19fb2cd7a0
