### ISSUE TITLE
contacts or contact_groups directive with no value should not be allowed

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#217]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000649](http://tracker.nagios.org/view.php?id=0000649)  - Please follow that link for details.
> Originally submitted on 2014-10-23 by box293

I came across an issue where for one reason or another the host object had the contact_groups directive defined but it had no value. Because of this the contact_groups defined in template it was using were ignored.

When you verify the config it reports "Warning: Host 'winserver' has no default contacts or contactgroups defined!".

It is my suggestion that it should fail the verification if the directive exists but has no value. 

This happens with both contacts and contact_groups.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/190f462089fc6aff14ddc931c3614edfb98a8233
