### ISSUE TITLE
next_problem_id is improperly initialized

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#219]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000671](http://tracker.nagios.org/view.php?id=0000671)  - Please follow that link for details.

**Comment by jfrickson** [comment]
Fixed in maint branch via commit https://github.com/NagiosEnterprises/nagioscore/commit/71e159fe82ecb03689bcfdbdefc755e0d606cf2a
