### ISSUE TITLE
Fix early event scheduling

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#220]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000673](http://tracker.nagios.org/view.php?id=0000673)  - Please follow that link for details and two comments.
> Originally submitted on 2015-03-10 by pmalek

Due to "100 milliseconds allowance for firing off events early" in events execution loop, reoccurring events are scheduled earlier and earlier over time. Remove this logic to prevent that from occurring.

At least in my case, the patch fixes 'load spikes' when moderate enough number of checks are being executed (Note: 0000900 checks on single cpu vm). Normally, spikes have been seen every couple hours. With this patch, load became more consistent/leveled.

See http://support.nagios.com/forum/viewtopic.php?f=7&t=27068 for description of the problem.

Test has been running for multiple days with success, but testing by others experiencing this issue would be greatly appreciated to verify as well.

This is likely to address / or have impact on other non check events that are time sensitive.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/5e44ca7d71f7bc13059feeb4f94477b798e4d654
