### ISSUE TITLE
Event EVENT_LOG_ROTATION rescheduled repeatedly due to early execution

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#222]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000676](http://tracker.nagios.org/view.php?id=0000676)  - Please follow that link for details.
> Originally reported on 2015-04-07 by georgeh

When rotating the nagios.log file, Nagios schedules a timed event EVENT_LOG_ROTATION

If this event is executed early (milliseconds early), it is rescheduled for the same time as the original event.
This event is executed, and rescheduled again, over and over until the clock ticks over the boundary of the second.

It is difficult to ensure that the execution of the event EVENT_LOG_ROTATION falls exactly in the 'right' second, possibly due to rounding from microseconds to milliseconds in tv_delta_msec()

Given that the most frequent schedualing is hourly, it is safe to calculate the time for the next event EVENT_LOG_ROTATION based on a small increment of the current time.

(see attached patch)

This problem has an existing work-around in base/logging.c in rotate_log_file()
The work-around prevents the archive file from being (repeatedly) truncated and rewritten by the EVENT_LOG_ROTATION events, this problem still has an adverse effect if there is any downtime in effect, or if the broker module 'livestatus' (from check_mk) is in use.

Host or service downtime results in additional log messages being inserted at the start of each logfile, like this:

[1428328799] HOST DOWNTIME ALERT: myhost;STARTED;mycomment
[1428328799] SERVICE DOWNTIME ALERT: myhost;hp-system-snmp;STARTED;Multiple Downtime Comments

The livestatus module generates additional log entries of the form:

[1427335199] TIMEPERIOD TRANSITION: 24x7;1;1

Both the DOWTIME and TRANSITION messages are repeated each time the event EVENT_LOG_ROTATION executes, and can result in hundreds of such log entries being generated.

The issue described in '0000673: Fix early event scheduling' results the event EVENT_LOG_ROTATION being executed 100ms early, and being repeatedly rescheduled, hundreds of times, before the event falls into the 'right' second and is rescheduled correctly.

The attached patch remedies this by making get_next_log_rotation_time() less sensitive to the current time.

**Comment by jfrickson** [comment]
This should be fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/5e44ca7d71f7bc13059feeb4f94477b798e4d654 for issue #220
