### ISSUE TITLE
Possibility to only show HARD states in tac.cgi

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#225]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000016](http://tracker.nagios.org/view.php?id=0000016)  - Please follow that link for details and one comment.
> Originally submitted on 2009-06-01

Several users want a feature to enable/disable display of only show HARD stats in tac.cgi.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/52582f8d5f90f438f9a8e355dc6704287c786194
