### ISSUE TITLE
avail.cgi should have new funtion to force scheduled downtimes as up

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#226]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000048](http://tracker.nagios.org/view.php?id=0000048)  - Please follow that link for details and two comments.
> Originally submitted on 2009-07-08 by joergrauscher

Avail.cgi should have a new function to force errors during scheduled downtimes as up. Alternative it should have a column scheduled downtime in Main View for all errors. Like the detailed Host / servioce Availability view.

This function is helpful to see host that are unscheduled unavailable

**Comment by jfrickson** [comment]
There are a couple ways to do this. I'm looking into it.

**Comment by hedenface** [comment]
I'm closing all tasks related to improvements in reports. These are all going to undergo some serious refactoring in the next major release.
