### ISSUE TITLE
RFE: Services can define different notification_periods on a notification_option basis

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#228]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000116](http://tracker.nagios.org/view.php?id=0000116)  - Please follow that link for details.
> Originally submitted on 2009-12-08 by apocalyptech

For most of my services, I get notified 24x7 regardless of whether a state change goes to WARNING/CRITICAL/OK, etc. For some services, however, like diskspace checks, I typically don't want to hear about WARNING messages in the middle of the night. Right now, in order to implement this, I have to either define multiple contacts for the same person (one contact with 24x7 notification, another which only gets WARNINGs during the day, and another which only gets CRITICALs) and assign them that way, or I've got to define two services, one which only runs during the night and will only alarm on CRITICAL, and another which runs during the day.

Neither of those options is ideal, really... What I'd love to be able to do is simply define a different notification_period depending on a notification_option inside the service definition. What I'd envision is something like this:

```
define service {
  name foo
  notification_period 24x7
  notification_options u,c,r
  notification_period_override w daytime
  ...
}
```

So the service would send notifications 24x7 for UNKNOWN, CRITICAL, and RECOVERY, but only send WARNINGs during the "daytime" period. IMO that's a much cleaner way to do that than what's currently available.

**Comment by jfrickson** [comment]
If we do this, it will have to wait for Core 5.

**Comment by hedenface** [comment]
I think this suggestion is a far more convoluted way of the present day way to handle it. Closing unless there is more community feedback regarding the matter.
