### ISSUE TITLE
new status for check dependencies

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#229]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000160](http://tracker.nagios.org/view.php?id=0000160)  - Please follow that link for details.
> Originally submitted on 2010-07-30 by chrpinedo

When a host or a service is not checked by a dependency its last status is hold (OK, DOWN, UNREACHABLE). It should be better to have an specific status to show that the service or host has not been checked, for example PENDING host or PENDING service.

When the host or the service is not checked because of a "parent" relationships the status is UNREACHABLE. It would be interesting a similar feature for host/service dependencies.

**Comment by jfrickson** [comment]
This would have to be a global option. Looking into it.

**Comment by jfrickson** [comment]
Fixed in branch `nagios-4.4.0-alpha1` via commit https://github.com/NagiosEnterprises/nagioscore/commit/e32ba314de522fd74aea8f4c70555bb66f94d230
