### ISSUE TITLE
Option to Change Service Escalation Behavior

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#230]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000163](http://tracker.nagios.org/view.php?id=0000163)  - Please follow that link for details and three comments.
> Originally submitted on 2010-08-09 by Brett Proctor

Sorry if this is the wrong list. Please let me know where I can forward this if this isn't the right forum.

We just ran into a problem where we only want to escalate on the second critical notification. We found out if we get a warning notification, then a critical and have first_notification 2 and escalation_options c, the escalation still matches.

It was our understand that having set escalation_options c would only match if there had been 2 _critical_ notifications, not 2 of any non-OK notifications.

I haven't tested this yet, but this is what I think it should be doing:

```
/* checks to see if a service escalation entry is a match for the current service notification */
int is_valid_escalation_for_service_notification(service *svc, serviceescalation *se, int options){
...
/* skip this escalation if we haven't been in this same hard state for first_notification notifications */
if(svc->last_hard_state_change > ( current_time - ((se->first_notification - 1) * (svc->check_interval * 60)))
    return FALSE;
```

 I realize this will break (or fix) a lot of current escalations. It might be worth adding an optional config to service_escalation such as strict_notification_counts or something that explains that using that config means to only count matching states that have been in that state for at least first_notification number of notifications. Then in the above if statement just check to see if that option is set.

Either way, thanks for nagios, I absolutely love this thing!

**Comment by jfrickson** [comment]
If we do this, it would probably be as part of the changes for Core 5

**Comment by hedenface** [comment]
I'm closing this because the escalation logic is going to be slightly re-written in Core 5. I don't know if at this time this will be included or not. But if there are any issues after the release, please re-open or create a new issue. Thanks!
