### ISSUE TITLE
Let Hypermap show service issues

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#232]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000232](http://tracker.nagios.org/view.php?id=0000232)  - Please follow that link for details.
> Originally submitted on 2011-07-18 by Malcz86

 It would be great to be able to see service issues on the Hypermap. Possibly have hosts turning yellow when one of their services has a problem?

**Comment by jfrickson** [comment]
Fixed. See issue #118
