### ISSUE TITLE
Add audit external commands.

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#233]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000236](http://tracker.nagios.org/view.php?id=0000236)  - Please follow that link for details and patches.
> Originally submitted on 2011-08-05 by benatti

I created the option for audit external commands.

This feature add user and comments in all actions of is hosts and services.

For do it is only add in cgi.cfg the option "nagios_audit=1"

**Comment by jfrickson** [comment]
I think this can be handled the same way as #82 and #180. If there is a need for a separate Audit type of comment, there may be more involved.

**Comment by hedenface** [comment]
Closing since resolved.
