### ISSUE TITLE
Feature-Request: Contact Definition: notify_only_hostgroup

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#234]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000254](http://tracker.nagios.org/view.php?id=0000254)  - Please follow that link for details.
> Originally submitted on 2011-09-09 by _naixios_

Hello everybody out there!

It would be very useful, if I can specify from which Hostgroup i will be notified.

Example:

```
define contact {
  contact_name naixios
  use contact-template
  notification_hostgroups PRODUCTIVE-SRV
}
```

So i will only be notified, from the Services in the Hostgroup "PRODUCTIVE-SRV".

I miss an option like this. That would be very useful!

**Comment by jfrickson** [comment]
This will probably be possible with the planned changes for Core 5.

**Comment by hedenface** [comment]
This adds an awful lot of complexity to what should be essentially a simple solution. Don't add your contact to hostgroups or hosts you don't want to be notified from? Maybe I misunderstand, regardless: I'm closing. If there is greater community request for this issue, we'll re-open and take another look. Thanks!
