### ISSUE TITLE
Update status.c to display passive check icon for hosts when passive checks are enabled and actives disabled

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#235]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000256](http://tracker.nagios.org/view.php?id=0000256)  - Please follow that link for details.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/90c8a6d20b9db93c126d9a7b7d2bff10e17ae46f
