### ISSUE TITLE
Downtime comment is not presented

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#236]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000261](http://tracker.nagios.org/view.php?id=0000261)  - Please follow that link for details.
> Originally submitted on 2011-10-07 by wferi

 When you submit a downtime to a host or service, you're requested to enter a comment, and a comment icon indeed shows up next to the downtime icon in that status report. However, the comment does not contain your text entered above, it's another comment automatically generated by Nagios describing the period and the effect of the downtime (which would be better presented in structured form in the host/service status box in my opinion). The user name of the original submitter and his or her comment (describing the reason for the downtime) is still available via the Downtime report, but this is both unintuitive and inconvenient. Please make this information more accessible. Thanks.

**Comment by jfrickson** [comment]
Fixed in `maint` branch via commit https://github.com/NagiosEnterprises/nagioscore/commit/374865627dd9019cfba27ae3c53d156ce74b75eb
