### ISSUE TITLE
Add ability to specify downtimes with timeperiod definitions.

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#237]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000262](http://tracker.nagios.org/view.php?id=0000262)  - Please follow that link for details.
> Originally submitted on 2011-10-12 by PMDubuc

Please consider adding a downtime_period configuration option for hosts and services that can use a timeperiod definition to schedule regular periodic downtimes. The add-on scripts that I've see in Nagios Exchange aren't as flexible in scheduling downtimes as using a timeperiod would be. (Example: scheduling a fixed downtime of one length every Saturday evening and a longer downtime on the 4th Saturday of every month.)

**Comment by jfrickson** [comment]
Looking into this for Core 5.

**Comment by hedenface** [comment]
The recurring downtime script is likely the way this will continue to be done - it is undergoing major transformation, and should be submitted upstream shortly after XI 5.5 is released.
