### ISSUE TITLE
idea: command expansion in command directives

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#238]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000317](http://tracker.nagios.org/view.php?id=0000317)  - Please follow that link for details and 16 comments.
> Originally submitted on 2012-04-08 by calestyo

Hi.

This is (ATM) rather just an idea and probably nothing that will be implemented by tomorrow.
But IMHO it would be very useful so having it in the records seems to be a good idea.

Right now, it's not really possible to chain commands just by the configuration. What do I mean with chaining commands:
Well take two examples:
1) notify commands
Usually on has a transport (e.g. email, or jabber or SMS) mean for notification and a content (e.g. default warning about a host or a service, or detailed warning, or in case of a failed RAID disk a formal letter to the retailer asking for a replacement under the warranty) that should be sent.
Right now (AFAIU) I have to specify one command for each possible combination, e.g.:
notify_email_host_basic
notify_email_host_detailed
notify_jabber_host_basic
notify_jabber_host_detailed
etc.

But the two parts of the command, transport and content generation are typically largely independent.
So what one would like to do is something like
command=notification-message_host!basic|notify-via-email
where notification-message_host is a command that has the printfs to generate the contend and notify-via-email is a commend to send an email.
"basic" in the above example would be $ARG1$ to the first command, telling that a short report should be done,... an alternative would be e.g. detailed.

In the above example, what one wants to do is piping one command to the other.
But as the next example shows, this is not really generic enough.

2) remote-execute-by-[e.g. ssh] commands
There are many cases where one wants to remotely execute a command, most notably for checks and event handlers.
There are several ways to do this, nrpe (which I'll show in some weeks is inferior to ssh even in performance), ssh, rsh, telnet, etc.

Again, what I want to do is "chain" two commands, e.g. remote-exec-via-ssh and check_load.
Obviously piping makes no sense here, as the actually executed command would be something like:
ssh $HOSTNAME$ "/usr/.../check_load -W ..."
There is just no piping.

So IMHO the generic solution for ALL of this was a way to do "command expansion" in the command directives (of e.g. hosts, services, contacts).
An example syntax would be:
$(<nagios_command>[|argN]*)
When this is encountered it's replaced as ONE argument, buy what the nagios_command and ALL its macros (not just the arguments but also the other macros) expands to.

So one could eventually do something like:
1)
*_command pipe!$(notification-message_host!basic)!notify-via-email

ARG1 was: $(notification-message_host!basic)
where notification-message_host could be defined as
command_line /usr/local/bin/print_my_message -H $HOSTNAME$ -S $HOSTSTATE -type $ARG1$
which would e.g. expand to
/usr/local/bin/print_my_message -H exmaple.org -S UP -type basic

ARG2 was:
where notify-via-email could be defined as
command_line /usr/bin/mailx $CONTACTEMAIL$
which would e.g. expand to
/usr/bin/mailx root@example.com

pipe would be just another command, that pipes his arguments to each other... so the overall command would be something like
/usr/local/bin/my_nagios_piper "/usr/local/bin/print_my_message -H exmaple.org -S UP -type basic" "/usr/bin/mailx root@example.com"
which actually does not much more but
/usr/local/bin/print_my_message -H exmaple.org -S UP -type basic | /usr/bin/mailx root@example.com

2) The remote execute example would work similar
*_command remote-exec-via-ssh!$(check_load!10!20)

This time we have no pipe,...
remote-exec-via-ssh would be defined as e.g.
command_line /usr/bin/ssh nagios@$HOSTNAME$ $ARG1$
Obviously, after expansion, one would get
/usr/bin/ssh nagios@host.example.org /usr/lib/nagios/plugins/check_load -W 10 -C 20
(depending on how check_load is defined).

I first tried to implement the above with a external plugin, which parses all configuration files (including the included ones) and looks for commands.
But I quickly realised that this wouldn't work, as I can't expand all the internal macros.

So after all, I think the above feature of command expansion would be quite useful in order to "chain" / modularise commands.
It should be easily possible to make this backwards compatible, e.g. my saying that $(...) as argument can be quoted with a leading "\" that the following is not to be expanded.

Cheers,
Chris.

Reported the same for Icinga, as bug #2506 (https://dev.icinga.org/issues/2506), [so perhaps efforts can be joined somehow :)

**Comment by jfrickson** [comment]
As @ageric mentioned in the original request, it's not something we're actively looking at doing. I'm going to close this issue, but label it as "archive/future" so we can revisit it at some point.
