### ISSUE TITLE
Issue with Check scheduling

### ISSUE THREAD

**Issue by tstelmach** [NagiosEnterprises/nagioscore#24]
<b>Request: </b>
Possibility to disable new feature from 4.0.8 [Check scheduling has been modified to prevent bunching checks at the start of their timeperiod]

<b>Description:</b>
After upgraded core to version 4.0.8. Nagios is schedulling checks randomly within allowed time frame. This is by design as described in release notes but would be nice to have poosibility to disable this.

Release notes for 4.0.8:
-JSON API output has been better aligned with the standard, and output size limits have been lifted
<b>-Check scheduling has been modified to prevent bunching checks at the start of their timeperiod</b>
-Auto-rescheduling of checks has been reimplemented. This can be enabled by setting auto_reschedule_checks=1 in nagios.cfg, and adjusted by setting auto_rescheduling_interval and auto_rescheduling_window as described in the Core 4 Documentation. Auto-rescheduling smoothes the check schedule as it changes over time, and together with the previous improvements, helps to give a more uniform system load.

Problem which I am facing is that I have some checks scheduled once a day and with core 4.0.6 those checks have been runing always at precise time eg. 06:30 am. Now they are executed randomly at 06:43 06:37 etc. I would like to have possibility that Nagios will schedule automatically at precise time 06:30. Is possible to set this somehow implement switch for [check schedulling] which will disable this feature?

This is direct follow up of thread from Nagios Support forum:
http://support.nagios.com/forum/viewtopic.php?f=7&t=31266

**Comment by tmcnag** [comment]
This could potentially go in as a config option, but I have always found that if you need something on a precise schedule it's best to set it as a cron job and send in the results passively.  Especially in this case where it is a once-a-day thing, cron is definitely the right tool for the job.

Issue should be closed.

**Comment by jfrickson** [comment]
If there's some reason why this couldn't be done with cron, I may reopen this issue. But for now, I'm closing it.
