### ISSUE TITLE
Support implied inheritance and additive inheritance together

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#240]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000320](http://tracker.nagios.org/view.php?id=0000320)  - Please follow that link for details.
> Originally submitted on 2012-04-11 by jwinkle

I'd like to set up Nagios contact_groups in the following way:
1) In general, contact_groups for a host are notified about problems with the host and any service on the host.
2) Occasionally, we'd like other contact_groups to be notified about problems with certain services on the host.

I'd like to do this using implied inheritance and additive inheritance together.

For example, if I define:

```
define host{
        host_name linux-server
        contact_groups linux-admins
        ...
        }

define service{
        host_name linux-server
        service_description l_proc_sshd
        contact_groups +management
        ...
        }
```

I would like this to be equivalent to:

```
define service{
        host_name linux-server
        service_description l_proc_sshd
        contact_groups linux-admins,management
        ...
        }
```

But instead, the implied inheritance of "linux-admins" is ignored, and it's equivalent to:

```
define service{
        host_name linux-server
        service_description l_proc_sshd
        contact_groups management
        ...
        }
```

I found many people who also expected it to work this way while searching the web for this issue.

I reported this on the nagios-devel list, and people seemed to like the idea and suggested how it could be implemented. See the thread from 26-March-2012 to 2-April-2012 with the subject "Nagios implied and additive inheritance; possible bug?" for possible implementation notes.

Thanks for considering this!

**Comment by jfrickson** [comment]
Note: The discussion referenced is at https://sourceforge.net/p/nagios/mailman/message/29051444/

**Comment by jfrickson** [comment]
This might be a Core 5 issue. I'm looking into reworking the inheritance and escalation logic, and this might be one of the things to add.

**Comment by hedenface** [comment]
Duplicate. #87
