### ISSUE TITLE
Allow for optional cfg_file and cfg_dir includes

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#241]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000324](http://tracker.nagios.org/view.php?id=0000324)  - Please follow that link for details.
> Originally submitted on 2012-04-28 by standaloneSA

In a large environment with multiple teams responsible for discrete aspects of the infrastructure, there may be widely disparate groups responsible for different aspects of the infrastructure, yet all of them need monitored.

With this being the case, any one business group which submits a configuration snippet into a cfg_dir can bring down the entire monitoring infrastructure (or at least make it refuse to start).

The existing workaround is to either implement configuration builds on the fly after verifying syntax (read: very complex) or to refuse to shut down a running Nagios instance if any of the configuration changes would make it not start back up (read: almost as complex, plus it blocks valid changes in other parts of the config).

Implementing a cfg_file_optional and a cfg_dir_optional allows failures in configuration to be tolerated in specific cases and prevents one team from negatively impacting the entire rest of the monitored infrastructure.

**Comment by jfrickson** [comment]
This will probably be part of Core 5.

**Comment by hedenface** [comment]
Some of our internal discussions revolving around the Nagios Core 5 startup/shutdown procedures actually have a lot to do with this functionality. It's already planned, and I'm closing the task. If anyone feels that's out of line, please re-open.

**Comment by douglasawh** [comment]
If it is planned should it really be closed? In any case, it seems if you specify a cfg_file that is in your cfg_dir, then you cannot restart nagios. This seems like a bug, though I can see the argument for it being a feature request. In any case, it seems the work for 5.0 might fix this issue. Should I file a separate bug? I'm currently on 4.4.6.
