### ISSUE TITLE
Service hard state generation and host hard or soft down status

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#242]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000333](http://tracker.nagios.org/view.php?id=0000333)  - Please follow that link for details and two comments.
> Originally submitted on 2012-05-15 by paulez

Hi,

According to the documentation, one of the condition to create a hard
non-ok state for a service is to get a check in a non-ok state while the
associated host is down. But it is not stated if the host should be down
HARD or not.

The current behavior of Nagios is clearly ignoring if the host is in
SOFT or HARD down state, for example :

```
[1336039429] INITIAL HOST STATE: ces;UP;HARD;1;PING OK - Packet loss =
0%, RTA = 0.42 ms
[1336039429] INITIAL SERVICE STATE:
ces;SV-SE-Linux-Memoire;OK;HARD;1;OK: Memory Usage (W> 95): 12%Swap
Usage (W> 95, C> 99): 0%
[1336039429] INITIAL SERVICE STATE: ces;SV-SE-Linux-SWAP;OK;HARD;1;SWAP
OK - 100% free (3999 MB out of 3999 MB)
[1336039747] HOST ALERT: ces;DOWN;SOFT;1;CRITICAL - Host Unreachable
(10.235.72.159)
[1336039812] HOST ALERT: ces;DOWN;SOFT;2;CRITICAL - Host Unreachable
(10.235.72.159)
[1336039822] SERVICE ALERT:
ces;SV-SE-Linux-SWAP;CRITICAL;HARD;1;Connection refused or timed out
[1336039822] SERVICE ALERT:
ces;SV-SE-Linux-Memoire;CRITICAL;HARD;1;Connection refused or timed out
[1336039877] HOST ALERT: ces;DOWN;HARD;3;CRITICAL - Host Unreachable
(10.235.72.159)
[1336040122] SERVICE ALERT:
ces;SV-SE-Linux-Memoire;CRITICAL;HARD;1;Connection refused or timed out
[1336040122] SERVICE ALERT:
ces;SV-SE-Linux-SWAP;CRITICAL;HARD;1;Connection refused or timed out
```

The associated service immediately get an HARD non-ok state even if the
host is in a SOFT down state.

In the Nagios code I found in base/checks.c in non-ok state processing
logic :

```
                /* if the host is down or unreachable ... */
                /* 05/29/2007 NOTE: The host might be in a SOFT problem state due to
host check retries/caching. Not sure if we should take that into
account and do something different or not... */
                if(route_result != HOST_UP) {
```

I think we should take into account the SOFT or HARD host state to
ensure consistency between host and service hard/soft state, and reduce false positive hard critical states due to occasional network glitches.

Thanks for reading,

cheers.

Paul Ezvan

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/d37684476213927a3aa363c96a31e9dc251b8b4a
