### ISSUE TITLE
Add broker-event for the end of a timed event

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#244]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000351](http://tracker.nagios.org/view.php?id=0000351)  - Please follow that link for details and patch.
> Originally submitted on 2012-07-01 by jbreams

Nagios currently brokers only the start of a timed event. Add a broker event for when timed events complete. Since the changes in Nagios that aren't thread-safe mostly happen inside timed events (like the check result reaper), notifying NEBs when the events start and end lets them do some basic global locking.

**Comment by jfrickson** [comment]
Added in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/ea8fc449f60f31c26535bbee32c10c577c84a84f
