### ISSUE TITLE
selectively disable CGI scripts at run-time

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#245]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000360](http://tracker.nagios.org/view.php?id=0000360)  - Please follow that link for details.
> Originally submitted on 2012-07-25 by stromsoe

It would be nice to be able to selectively disable CGI scripts at runtime through cgi.cfg. I do not use most of the CGI scripts and have to edit the source to remove HREF links to avail.cgi, histogram.cgi, history.cgi, notifications.cgi, and many others.

Being able to set "avail_cgi = 0" in cgi.cfg and have all of the CGI scripts that would normally link to that script not display the HREF out of the box would increase usability significantly in my case.

**Comment by jfrickson** [comment]
It's a good idea, but difficult to implement properly in the current environment. This will probably be included in the new UI design coming up.

**Comment by hedenface** [comment]
I'm closing all tasks related to improvements in reports. These are all going to undergo some serious refactoring in the next major release.
