### ISSUE TITLE
Log long plugin output

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#246]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000372](http://tracker.nagios.org/view.php?id=0000372)  - Please follow that link for details, patch and two comments.
> Originally submitted on 2012-08-20 by awiddersheim

Add configuration option to allow for long plugin output to be logged to the Nagios log files.

**Comment by jfrickson** [comment]
See also https://github.com/NagiosEnterprises/nagioscore/issues/262

**Comment by jfrickson** [comment]
Note: some plugins can output MB's of info. There would probably have to be either a hard-coded or configurable limit.

**Comment by hedenface** [comment]
Closing due to duplicate. See #262
