### ISSUE TITLE
Shouldn't extra-opts include configure's sysconfdir in it's default search path

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#248]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000391](http://tracker.nagios.org/view.php?id=0000391)  - Please follow that link for details.

**Comment by hedenface** [comment]
If I'm not mistaken, this was taken care of a while ago. I forget the specifics -if not, feel free to re-open.
