### ISSUE TITLE
Map no longer loads custom icons in Nagios Core 4.1.0-rc1

### ISSUE THREAD

**Issue by silviuvulcan** [NagiosEnterprises/nagioscore#25]
I was just testing the new map features in nagios 4.1.0-rc1 and noticed all my icons are gone.

I have them defined like this:

```
define host{
            use                     linux-server
            host_name               somehost
    ...
            icon_image              custom/esxiserver.png
            statusmap_image         custom/esxiserver.gd2
}
```

This works fine in 4.0.8 icons load everywhere (host lists, group lists, map, etc.) but in 4.1 they are gone from the map view (loadin ok in lists).

Originally reported by me here: http://support.nagios.com/forum/viewtopic.php?f=34&t=31512

**Comment by estanley375** [comment]
Check out commit e54d4b193599e7bcc93ba9623275b5ab759af247. It should have support for icons on all of the map displays.

**Comment by estanley375** [comment]
Fixed another issue, so please test with commit 26b53a8163de64fbacd3164f0da976bb7e26dcf1.

**Comment by silviuvulcan** [comment]
Confirmed, works and looks great.
