### ISSUE TITLE
Support Proxy for RSS Feed

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#250]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000430](http://tracker.nagios.org/view.php?id=0000430)  - Please follow that link for details.
> Originally posted on 2013-03-12 by jsa

Hello,

On Nagios first page it is possible to read Latest News/ Get Started ...
But if we are behind a web proxy , it does not work, we can't fetch RSS feeds.

Could you add this feature in next release ? ( get env proxy environment for example)

I succeed to add this manually in `share/includes/rss/rss_fetch.inc` file.

Line 269:

```
$client = new Snoopy();
$client->agent = MAGPIE_USER_AGENT;
```

Add proxy configuration like this for example:

```
$client = new Snoopy();
$client->proxy_host = "192.168.100.252";
$client->proxy_port = "3128";
$client->agent = MAGPIE_USER_AGENT;
```

Best Regards

JSA

**Comment by jfrickson** [comment]
Looking into it.

**Comment by jfrickson** [comment]
We no longer use the PHP RSS stuff. All RSS requests on the main page are done using javascript. So the browser's proxy setting should work.
