### ISSUE TITLE
Broken check scheduling with exclusions in format YYYY-MM-DD

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#252]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000443](http://tracker.nagios.org/view.php?id=0000443)  - Please follow that link for details.
> Originally submitted on 2013-04-16 by lmiltchev

I used the "2013-04-15" format in the exclusions, and I observed an "erratic" behavior, in terms of check scheduling. I am using Nagios Core 3.4.1. I would expect next check for "Current Load" to be scheduled for 2013-04-16 07:00:00. Instead, it's scheduled for 04-23-2013 00:00:00.

```
===============================================================================
define service {
    host_name localhost
    service_description Current Load
    use local-service
    check_command check_local_load!5.0,4.0,3.0!10.0,6.0,4.0!!!!!!
    check_period test_timeperiod
    register 1
    }
===============================================================================
define timeperiod {
    timeperiod_name test_timeperiod
    alias test_timeperiod
    exclude test_exclusions
    sunday 00:00-24:00
    tuesday 00:00-24:00
    wednesday 00:00-24:00
    thursday 00:00-24:00
    saturday 00:00-24:00
    friday 00:00-24:00
    monday 00:00-24:00
    }
===============================================================================
define timeperiod {
    timeperiod_name test_exclusions
    alias test_exclusions
    2013-04-18 07:00-24:00
    2013-04-17 17:00-24:00
    2013-04-16 00:00-07:00
    2013-04-19 00:00-24:00
    2013-04-15 15:15-24:00
    }
===============================================================================
```

![timeperiod_bug](https://cloud.githubusercontent.com/assets/13370023/19702490/86f5fb58-9ac5-11e6-8486-e8c93be60da8.PNG)

**Comment by jfrickson** [comment]
This appears to be working correctly in the current version of core. It was probably fixed sometime in the past 4 years.
