### ISSUE TITLE
There is no Macro to retrieve addresses of hostgroup members

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#253]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000453](http://tracker.nagios.org/view.php?id=0000453)  - Please follow that link for details.
> Originally submitted on 2013-05-09 by grimm26

`$HOSTGROUPMEMBERS$` will retrieve the names of hosts in a hostgroup, but not the addresses. A `$HOSTGROUPMEMBERSADDRESSES$` macro would be very useful. If I want to feed this info into a service check or host check, I currently have to feed `$HOSTGROUPMEMBERS$` into an external script that will parse the nagios configs to find the addresses.

**Comment by jfrickson** [comment]
Added to branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/4be3a5e9c98199d0f14c90d89397f69611af3177
