### ISSUE TITLE
add timeperiod option for notification commands

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#254]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000462](http://tracker.nagios.org/view.php?id=0000462)  - Please follow that link for details.
> Originally submitted on 2013-06-20 by link

Hello,
full thread is here: http://support.nagios.com/forum/viewtopic.php?f=7&t=10736&p=55993#p55993

It would be really nice if I can set different timeperiods for different notification commands. e.g. make rules when exact notifications can be sent.
Now I made this (see thread), but this is a little tricky - had to modify command script, use macro.
Thanks in advance.

**Comment by jfrickson** [comment]
There are multiple work-arounds for this, and I don't think there's much demand.
