### ISSUE TITLE
Add permalinks to pages

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#257]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000480](http://tracker.nagios.org/view.php?id=0000480)  - Please follow that link for details.
> Originally submitted on     2013-08-29 by Paul Dugas

 I notice the index.php has support for permalinks via the corewindow URL parameter. I wonder if it would be possible to add links to various pages in the web interface with links that utilize this capability. I find I am often hand-rolling these URLs in emails where I'm showing people what I'm seeing in Nagios.

**Comment by jfrickson** [comment]
Right-click, "properties" or "Page info" will get the url that can be copied into an email. I don't see any need to incorporate this into the UI.
