### ISSUE TITLE
Service execution dependency on host status

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#258]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000483](http://tracker.nagios.org/view.php?id=0000483)  - Please follow that link for details.

**Comment by jfrickson** [comment]
This request was implemented via commit https://github.com/NagiosEnterprises/nagioscore/commit/05e1dda8ccaa9d633b22b11a555d67724930a3e7 on June 3, 2015.

**Comment by tmcnag** [comment]
05e1dda was a pretty nice commit if I do say so myself  :)
