### ISSUE TITLE
nagios cgi never changes the value of nagios_process_state

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#259]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000485](http://tracker.nagios.org/view.php?id=0000485)  - Please follow that link for details and patch.
> Originally submitted on 2013-09-17 by deppy

The Nagios cgi.cfg has the user set a value for 'nagios_check_command' which seems like it should change the value of nagios_process_state based on the checks that are done throughout the cgi; However, the value of nagios_process_state is set to STATE_OK in the cgiutils.c code and there is nowhere that this can be changed.

I have attached a patch (procstate1.patch) which will change the behavior so that the value of nagios_process_state is changed based on the results of the nagios_check_command.

The patch applies cleanly to both trunk for nagios-3.x and nagios-4.x and is currently running in our production environment with over 100 users with minimal impact added to the server.

**Comment by jfrickson** [comment]
`nagios_check_command` was removed for core 3.0. Last traces of the configuration variable have now been removed from cgi/extinfo.c and cgi/cgiutils.c
