### ISSUE TITLE
Filter options in Operations Center

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#264]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000545](http://tracker.nagios.org/view.php?id=0000545)  - Please follow that link for details.
> Originally submitted on 2013-12-04 by niklasm

In operations center it would be good to be able to filter the checks.

This way getting a more dynamic view of problems and more.

Editing filters is missing a bit everywhere to be honest.

**Comment by jfrickson** [comment]
This is an XI issue that has been resolved.
