### ISSUE TITLE
configure --prefix does not work

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#267]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000654](http://tracker.nagios.org/view.php?id=0000654)  - Please follow that link for details.
> Originally submitted on 2014-11-25 by travissidelinger

 This looks like a major change to the configure scripts. We had to build my own rpm for Nagios (or at least modify the existing spec file) for a variety of items. We would have liked to relocate nagios to say /opt/nagios and keep it all self contained under that location. But, the install process looks to only support one level of location redirection. To package it correctly, it needs to support two levels of redirection. One level for --prefix at compile time and one level for "DESTDIR" used at install time by the package manager. Can this be considered in future versions?

**Comment by jfrickson** [comment]
Looking into this

**Comment by hedenface** [comment]
I believe this has all been fixed already. Re-open if not.
