### ISSUE TITLE
Request to be able to update a the host_parents directive dynamically

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#268]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000659](http://tracker.nagios.org/view.php?id=0000659)  - Please follow that link for details and two comments.
> Originally submitted on 2014-12-29 by box293

When a object definition has the host_parents defined, it usually stays that way as there is a physical relationship that doesn't change.

In the virtualization world, a VM can be running on an ESXi host one moment and then at any time be moved to another ESXi host using vMotion. In Nagios, if the VM being monitored had the parent_hosts directive defined for the first ESXi host, it would be incorrect after the vMotion.

Using an event handler, it is relatively easy to update the parent_hosts directive in the object definition files, however this only applies when Nagios restarts, the runtime environment also needs to be updated. It would be beneficial to be able to use nagios.cmd to submit a command to update a hosts' host_parents directive.

You _could_ issue a RESTART_PROGRAM command however this is not ideal if 30 event handlers all try to execute this around the same time.

**Comment by jfrickson** [comment]
This will probably be doable in Core 5. I'm marking this issue for Core 5 so this particular scenario can be included in the planning.

**Comment by hedenface** [comment]
I'm going to close this because of advanced query handler we're planning for core 5.
