### ISSUE TITLE
http://NAGIOSSERVER/nagios/jsonquery.html doesn't display scheduled_time_ok correctly

### ISSUE THREAD

**Issue by meabandit** [NagiosEnterprises/nagioscore#270]
See https://support.nagios.com/forum/viewtopic.php?f=16&t=39622&sid=64a4da422c975c0710f7f500b95dfcbd&start=10#p197746

Availability report data from core report vs json show different data.  The JSON returned values appear to be incomplete.
![availability_report-nagio core](https://cloud.githubusercontent.com/assets/1485931/19042080/4a26ac4e-8950-11e6-8e3b-f49fcd3955f2.png)
![availability_json_report-nagio core](https://cloud.githubusercontent.com/assets/1485931/19042081/4a3ef6f0-8950-11e6-93ab-e3379b46432f.png)

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/81dd7ec3369d8fe43e30483ff7f1620e6578ebf2
