### ISSUE TITLE
Host count makes status.cgi use high cpu

### ISSUE THREAD

**Issue by jfrickson** [NagiosEnterprises/nagioscore#271]
> This issue has been automatically migrated from http://tracker.nagios.org/view.php?id=0000178 - Please follow that link for details.
> Originally reported on 2010-12-01 by ferry

status.cgi is using 100% cpu time on 8 cores in our environment
We localized the problem to the following for-loop in status.c around line 1016

```
if(is_host_member_of_servicegroup(find_servicegroup(servicegroup_name),temp_host)==TRUE){
        count_host=1;
        break;
        }
```

Our environment is over 600 hosts big, we temporary disabled the host count by commenting the piece of code out of the file. With the lines it takes more then 60 seconds to load the cgi (our back-end server stops after 60 seconds) and without the lines it takes about 1 second.

**Comment by jfrickson** [comment]
This will have to wait for version 5, which should have more internal cross-referencing of objects. Until then, looping through lists is the only way to get the information.

**Comment by jfrickson** [comment]
See also #280

**Comment by hedenface** [comment]
I'm closing all tasks related to improvements in reports. These are all going to undergo some serious refactoring in the next major release.
