### ISSUE TITLE
Rename hourly_value and minimum_value attributes

### ISSUE THREAD

**Issue by jfrickson** [NagiosEnterprises/nagioscore#272]
> Migrated from http://api.nagios.com/tps/viewtask.php?task_id=1178 - please follow that link for details.
> Originally submitted on 2013-10-18

Rename the 'hourly_value' attribute for hosts and services to 'importance' and 'minimum_value' attribute for contacts to 'minimum_importance', removing all references to the old names.

This should be done in a major release (5.0.0) to avoid compatibility issues.

**Comment by jfrickson** [comment]
To do for Core 5

**Comment by hedenface** [comment]
This was already done.
