### ISSUE TITLE
Names for escalations and dependencies

### ISSUE THREAD

**Issue by jfrickson** [NagiosEnterprises/nagioscore#276]
> Migrated from http://api.nagios.com/tps/viewtask.php?task_id=1953 - please follow that link for details.
> Originally submitted on 2014-02-14

Create a new name field for escalation and dependency definitions.  Not necessary, but good for self documenting your configs.  It also would be useful from a frontend/data model developer's perspective.

Expose the names to the json api as well.

**Comment by jfrickson** [comment]
Not sure we want to do this. I'll mark it as a Core 5 issue and look into it for that release.

**Comment by hedenface** [comment]
I think this idea would be better suited as allowing for meta data across all objects. I'm going to close this issue and try and get that implemented for core 5.
