### ISSUE TITLE
Calling html target does nothing

### ISSUE THREAD

**Issue by hydrapolic** [NagiosEnterprises/nagioscore#28]
$ ./configure
$ make html
make: 'html' is up to date.
$ cd html && make
... extracts angular, d3 ...

Why doesn't `make html` work? I'm using make-4.1.

**Comment by hydrapolic** [comment]
Explained by mjo, this is because there already is a directory `html` so `make html` does nothing because it finds the directory and thinks it's ok. Opposite to that, directories "all" or "cgis" don't exist, so calling `make all` or `make cgis` will update those directories.

Wouldn't it be better to place html into the .PHONY target or name it some other way (htmls)?

**Comment by tmcnag** [comment]
Fixed in https://github.com/tmcnag/nagioscore/commit/482be9e2e3507c690e0477234bace3909524fa64

**Comment by hydrapolic** [comment]
Thanks
