### ISSUE TITLE
avail.cgi performance enhancement

### ISSUE THREAD

**Issue by jfrickson** [NagiosEnterprises/nagioscore#280]
> Migrated from http://api.nagios.com/tps/viewtask.php?task_id=6833 - please follow that link for details.
> Originally posted on 2015-11-02

Since it's the initial report run when entering the reports section of NagiosXI can we work on avail.cgi to increase performance? Perhaps make it grab data from the database instead of the flat files, or maybe even run some of the report ahead of time so that only the last X hours/minutes/seconds has to be computed for a realtime report?

**Comment by jfrickson** [comment]
Scheduled for Core 5. See #271

**Comment by hedenface** [comment]
I'm closing all tasks related to improvements in reports. These are all going to undergo some serious refactoring in the next major release.
