### ISSUE TITLE
how to configure postgres checks

### ISSUE THREAD

**Issue by fmotnaldo** [NagiosEnterprises/nagioscore#286]
Hi,

I am news in the nagiso worl and I want to create some checks for postgres database. I got some templates thea need to be include in commands.cfg and services.cfg. Waht is the way that nagios verify the user?. 

I defined the servecde in commands.cfg

define command {
        command_name    check_postgres_locks
        command_line    $USER2$/check_postgres.pl -H $HOSTADDRESS$ -u pgsql -db postgres --action locks -w $ARG1$ -c $ARG2$
}

The template for services.cfg

define service{
        use                             generic-other
        host_name                 dbhost.gtld
        service_description     dbhost PostgreSQL Service Database Locks
        check_command        check_postgres_locks!2!3
}

I need to knwo the procedure to configure a user for each server so it can handle the cheks.

Thanks

**Comment by jfrickson** [comment]
Please post your questions to the support forum: https://support.nagios.com/forum/viewforum.php?f=7

This is a place for bug reports and enhancement requests.

Thank you!
