### ISSUE TITLE
make install-webconf generates output "integer expression expected"

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#290]
```
[root@core-014 nagioscore-nagios-4.2.2]# make install-webconf
/usr/bin/install -c -m 644 sample-config/httpd.conf /etc/httpd/conf.d/nagios.conf
if [ @LN_HTTPD_SITES_ENABLED@ -eq 1 ]; then \
		@LN_S@ /etc/httpd/conf.d/nagios.conf /etc/apache2/sites-enabled/nagios.conf; \
	fi
/bin/sh: line 0: [: @LN_HTTPD_SITES_ENABLED@: integer expression expected

*** Nagios/Apache conf file installed ***
```

Problem occurs with 4.2.2 across all operating systems (from memory).

I've not see what issue it causes, the web interface seems to operate fine.

**Comment by hedenface** [comment]
Was able to replicate, and upon closer inspection - the configure file wasn't updated to match the updates made to Makefile.in

**Comment by jfrickson** [comment]
I made a change to `configure.ac` to fix issue https://github.com/NagiosEnterprises/nagioscore/commit/035eb97c54e685baa6d170eac7b57700ea21fdd2 and ran `autoconf` so a new configure script has been generated.
