### ISSUE TITLE
Feature Request - Add the ability to log every OK result in state history

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#292]
Feature Request - Add the ability to log every OK result in state history

Say that you have a passive SNMP trap service that receives two traps:

1. CRITICAL - Fan Failure
2. CRITICAL - HDD Failure

If another two traps come in:

3. OK - Fan is now okay
4. OK - HDD is now okay

The 4th one would not be logged in the state history since the state history only logs state changes. Even though the two traps are at the state of OK (no state change), they are two unique incidents and should be logged in state history (or the admin should have the ability to enable an option to achieve that functionality).

**Comment by box293** [comment]
Is this something that would be covered in State Stalking?

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/stalking.html

**Comment by ericloyd** [comment]
My understanding is that state stalking doesn't log sequential OK statuses.

**Comment by box293** [comment]
I believe state stalking already does this.

Here's a definition:
```
define command {
        command_name    check_dummy
        command_line    $USER1$/check_dummy $ARG1$ $ARG2$
        }


define service{
        use                             local-service
        host_name                       localhost
        service_description             state_history_test
        check_command   check_dummy!0!"No data received yet."
        active_checks_enabled   0
        passive_checks_enabled  1
        check_period    24x7
        stalking_options o,w,u,c
        }
```

Here's commands execute to submit passive check results:
```
now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;2;it is critical\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;0;it is ok\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;0;it is ok again\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;2;it is critical\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;1;it is warning\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;0;it is ok\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;3;it is unknown\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;0;it is ok\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;0;it is ok again\n" > /usr/local/nagios/var/rw/nagios.cmd

now_epoch=$(eval date +%s); printf "[$now_epoch] PROCESS_SERVICE_CHECK_RESULT;localhost;state_history_test;0;it is ok one more time\n" > /usr/local/nagios/var/rw/nagios.cmd
```

Here's the Service Alert History on the service:
```
Service Critical[11-13-2016 11:27:09] SERVICE ALERT: localhost;state_history_test;CRITICAL;SOFT;1;it is critical

Service Ok[11-13-2016 11:27:19] SERVICE ALERT: localhost;state_history_test;OK;SOFT;2;it is ok

Service Ok[11-13-2016 11:27:26] SERVICE ALERT: localhost;state_history_test;OK;HARD;1;it is ok again

Service Critical[11-13-2016 11:27:39] SERVICE ALERT: localhost;state_history_test;CRITICAL;SOFT;1;it is critical

Service Warning[11-13-2016 11:27:55] SERVICE ALERT: localhost;state_history_test;WARNING;SOFT;2;it is warning

Service Ok[11-13-2016 11:28:04] SERVICE ALERT: localhost;state_history_test;OK;SOFT;3;it is ok

Service Unknown[11-13-2016 11:28:13] SERVICE ALERT: localhost;state_history_test;UNKNOWN;SOFT;1;it is unknown

Service Ok[11-13-2016 11:28:20] SERVICE ALERT: localhost;state_history_test;OK;SOFT;2;it is ok

Service Ok[11-13-2016 11:28:24] SERVICE ALERT: localhost;state_history_test;OK;HARD;1;it is ok again

Service Ok[11-13-2016 11:33:20] SERVICE ALERT: localhost;state_history_test;OK;HARD;1;it is ok one more time
```

Is this what is required?

**Comment by ericloyd** [comment]
And here, all this time, I thought state stalking was only on non-OK states.  I guess I should read more. :)

**Comment by iceripper** [comment]
Actually with the 'stalking_options' parameter nagios log every OK result in the nagios.log file.
When we are talking about the state history we are talking about the  'nagios_statehistory' table in nagios database used by ndoutils which is not updated when receiving OK events after a first recovery.
When we are using the  'stalking_options' parameter it means we want to track every events and log them either in log file and in the database.

**Comment by ssaxnagios** [comment]
iceripper is correct, only state changes are logged in the nagios_statehistory table and two OKs in a row does not constitute a state change (even if the text changes), I've validated this in my lab environment.

**Comment by scottwilkerson** [comment]
Being the state history isn't actually changing I don't see why this should go in the nagios_statehistory table if the user is using ndoutils.

It was already demonstrated above that the data does go in the event log, and likewise, if the user was using ndoutils the data would be available in the nagios_logentries.

I see what the user is going for in the OP, however the state history is recording correctly for the service, it would be best for the user to search the event log table for the service description to see the data they are looking for as opposed to logging incorrect data to the nagios_statehistory table.

Either way, if this does go forward and a case is made, this would actually be done in https://github.com/NagiosEnterprises/ndoutils

**Comment by hedenface** [comment]
Unsure why this Issue was never closed, as all was covered previously.
