### ISSUE TITLE
Feature Request - Ability to enable old-style quick search

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#293]
4.2.2 changed the way quick search works. This is noted in the Changelog. Some users prefer the old method and would like the option to enable the old method.

Additional details at https://support.nagios.com/forum/viewtopic.php?t=41141&start=9999#bottom

**Comment by jfrickson** [comment]
This should be fixed in 'maint' branch because of issue #96 via commit https://github.com/NagiosEnterprises/nagioscore/commit/89dfd38610af69efde4e56f39c070eb9b21be737
