### ISSUE TITLE
configure does not error if no perl installed on CentOS 7

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#294]
CentOS install instructions at https://support.nagios.com/kb/article.php?id=96 have already been updated by Troy to include perl as a prereq, so people should not really be running into this. This has not currently been tested on any other OS.

This would seem to be introduced in 4.2.2, since 4.2.1 installed fine on CentOS 7. The upgrade from 4.2.1 to 4.2.2 also seems to have worked. Perhaps another prereq previously installed perl?

> checking for perl... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating subst
config.status: creating pkginfo
config.status: creating base/Makefile
config.status: creating common/Makefile
config.status: creating contrib/Makefile
config.status: creating cgi/Makefile
config.status: creating html/Makefile
config.status: creating module/Makefile
config.status: creating worker/Makefile
config.status: creating worker/ping/Makefile
config.status: creating xdata/Makefile
config.status: creating daemon-init
config.status: creating t/Makefile
config.status: creating t-tap/Makefile
config.status: creating include/config.h
config.status: include/config.h is unchanged
config.status: creating lib/snprintf.h
config.status: lib/snprintf.h is unchanged
config.status: creating lib/iobroker.h
config.status: lib/iobroker.h is unchanged
./configure: line 7220: perl: command not found
./configure: line 7221: perl: command not found
Creating sample config files in sample-config/ ...
./configure: line 7227: perl: command not found
./configure: line 7228: perl: command not found
./configure: line 7229: perl: command not found
./configure: line 7230: perl: command not found
./configure: line 7231: perl: command not found
./configure: line 7233: perl: command not found
./configure: line 7234: perl: command not found
./configure: line 7235: perl: command not found
./configure: line 7236: perl: command not found
./configure: line 7238: perl: command not found
./configure: line 7239: perl: command not found
./configure: line 7240: perl: command not found
./configure: line 7241: perl: command not found

This leads to 

> [root@localhost nagioscore-nagios-4.2.2]# make all
cd ./base && make
make[1]: Entering directory `/tmp/nagioscore-nagios-4.2.2/base'
make[1]: *** No rule to make target `../include/locations.h', needed by `nagios.                                       o'.  Stop.
make[1]: Leaving directory `/tmp/nagioscore-nagios-4.2.2/base'
make: *** [all] Error 2

Please let me know if I need to do additional testing.

**Comment by box293** [comment]
I think the issue has always been there, the "clean OS" machines I've used
for testing always had perl installed so I never came across this issue.

Configure appears to end OK when perl is not found. While it does appear as
like the error message reported, if your console / terminal screen wasn't
very high it would have scrolled past and wouldn't be that obvious.


Troy Lea
IT Consultant and Nagios Developer
troy@box293.com
sites.box293.com/nagios

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/c2e7e862015ee0cce51b3ba66db99f1ed7e9a132
