### ISSUE TITLE
"Quick Search" no longer returns same results as older v4.1

### ISSUE THREAD

**Issue by AMG1978** [NagiosEnterprises/nagioscore#298]
Before upgrading to v4.2.2 (I see v4.2.3 is out) I used to be able to type in to the "Quick Search" something like appdb* (or maybe it was just 'appdb') and see all the hosts that match it, with their services.  Now if i type appdb it simply returns the first alphabetical matching entry (example: returning appdb1 and not appdb2).  If I type "appdb2" it will return the services for that one host properly.  if I type "appdb*" it doesnt return any service information, but simply shows all the Host network status.

Any ideas on this?

**Comment by box293** [comment]
This is fixed in 4.2.3

https://github.com/NagiosEnterprises/nagioscore/blob/release-4.2.3/Changelog

> * Fix for quick search not showing services if wildcard used (John Frickson)

**Comment by AMG1978** [comment]
I did look, but as I can see it now (thanks to you) I can acknowledge i didn't look hard enough.  It was really obvious and I just missed it.

Validated indeed it works properly in v4.2.3 just now.  Thank you.
