### ISSUE TITLE
Nagios crashes with SIGABRT or SIGSEGV

### ISSUE THREAD

**Issue by Mike-Sbg** [NagiosEnterprises/nagioscore#299]
I'm using nagios-4.2.1-1 on centos 7 and it worked without any problems for months while it was in testmode.

I putted it in production, but from that point on, I get SIGABRT and SIGSEGV once or twice a day. 

The abrt-deamon presents me much information, but as I'm not very familiar with the internals of nagios, I would be glad, if someone could help me.

Thanks in advance

**Comment by Mike-Sbg** [comment]
I upgraded to Nagios V 4.2.3 but It is still crashing every few hours ...

**Comment by jfrickson** [comment]
In the `nagios.cfg` file, set:
```
debug_level=8
debug_verbosity=2
```
Go to the nagios source directory, then into the `base` directory. Enter `make install-unstripped`.
Restart nagios.
When it crashes, send me the contents of the `/var/tmp/abrt` directory and also the `/usr/local/nagios/var/nagios.log` and `/usr/local/nagios/var/nagios.debug` files.

**Comment by Mike-Sbg** [comment]
I've just had some crashes, how can I send you the requested data?

By the way, I didn't compile Nagios myself, I used a rpm.
So I can send you the 2 requested logs, and the content of the abort-daemon-file (about 35 MB)

**Comment by jfrickson** [comment]
Email it to me at jfrickson@nagios.com.

**Comment by Mike-Sbg** [comment]
I just sent you a e-mail with the requested logs ... I hope it helps

**Comment by Mike-Sbg** [comment]
Something interessting I just mentioned: I tried an upgrade (yesterday 2 pm) of the mk-livestatus broker-modul from Version 1.8.2.p11 to 1.8.2.p14

But the problem got much worse ... e.g. before the upgrade we crashed 3-5 times a day, after the upgrade, we crashed 19 times during the last day.

I reverted to the Version 1.2.8.p11 

@jfrickson The logs I sent you where made with the version 1.2.8.p11 (before the upgrade)

**Comment by jfrickson** [comment]
It looks like it's crashing while playing with the environment. I can't get the core dump to show me exactly what is happening.

But I looked at your `nagios.log` file, and there are over 3,000 `Error: External command failed -> PROCESS_SERVICE_CHECK_RESULT` entries. They appear to be all from passive check results. It doesn't look like a core bug. I suggest posting on the support forum: https://support.nagios.com/forum/viewforum.php?f=7

Post there your first message here, add that you use livestatus, and mention that I have all the files. Mention this issue also: https://github.com/NagiosEnterprises/nagioscore/issues/299

**Comment by Mike-Sbg** [comment]
I know the errorers of not processed External Commands ... this happens while our setup-concept includes a passiv check, sending results to nagios.

This happens until we define them in the nagios objecst. 

This is the same procedure witch nagios 3, but there we didn't have any crashes.

Could you please give me a hint, how I can help myself to locate the bug (beside posting to the forum)
