### ISSUE TITLE
Feature Request - Display the time in a 12 hour (AM/PM) format

### ISSUE THREAD

**Issue by 710powley** [NagiosEnterprises/nagioscore#300]
In addition to modifying the date format (date_format =xxxxxx) in the config file having the ability to modify the time display output.

**Comment by jfrickson** [comment]
Looking into this

**Comment by jfrickson** [comment]
This will add additional options to `nagios.cfg`, so it's being bumped back to Core5.

**Comment by jfrickson** [comment]
This is implemented in branch `nv5dev` via commit https://github.com/NagiosEnterprises/nagioscore/commit/590be190351d7f1a4e26527d89d7ad9970db09c8. Note that this branch is extremely unstable at this point, so you might want to wait for a beta version, coming later.
