### ISSUE TITLE
CGI utility cgiutil.c does not process relative config file path names properly

### ISSUE THREAD

**Issue by darylmonge** [NagiosEnterprises/nagioscore#305]
The configuration items log_file and log_archive_path in html/cgiutils.c are not processed for path names relative to config_file_dir.  

In contrast, the object_cache and status files are processed by nspath_absolute.

Background:  By using relative paths, we can maintain our configuration files in a GIT repository on development machines and test them using the nagios executable without having a full install, or without requiring overwriting a "real" install on the actual dev host.

**Comment by darylmonge** [comment]
I made this change in my own private branch to test a change to support relative paths

```
                else if(strstr(input, "log_file=") == input) { 
                        temp_buffer = strtok(input, "="); 
                        temp_buffer = strtok(NULL, "\x0"); 
                        (void) strncpy(log_file,nspath_absolute(temp_buffer, config_file_dir),sizeof(log_file)-1); 
                        log_file[sizeof(log_file) - 1] = '\x0'; 
                        } 

```

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/f1ff8ec9520d15978929356b8597998d2262e201

Will be in release 4.3.2
