### ISSUE TITLE
Feature Request - Provide an official docker image

### ISSUE THREAD

**Issue by Koopzington** [NagiosEnterprises/nagioscore#306]
I'd love to see this repo providing an official docker build so we don't have to rely on third parties for that.
Would you consider making this happen?

**Comment by tmcnag** [comment]
We're actually meeting later today to discuss our open-source development, so I'll add this to the agenda and get back to you.

**Comment by tmcnag** [comment]
Didn't get to this as it was added to the bottom of an already long list, but I'll talk with the devs and see how much interest there is.

**Comment by tjyang** [comment]
@tmcnag, Thanks for the update.

**Comment by tmcnag** [comment]
It sounds like at this time we won't be maintaining a Docker (or LXC, rkt, etc.) image, so I will be closing this Issue.

**Comment by patrickbeam** [comment]
@tmcnag Is it still your stance to not maintain a docker file? I have a docker file and kubernetes manifests for running Nagios that I would be happy to contribute to the project.

**Comment by marioja** [comment]
Hi Patrick, could you share your docker file?

**Comment by patrickbeam** [comment]
@marioja I tried to track down that docker file, and it must have been stored in a repo I no longer have access to.

**Comment by ericloyd** [comment]
Six and a half years later and there still is no official Nagios Core (let alone XI) container.  Not really surprising since it's not a direct path to monetization for Nagios Enterprises, so they've likely left it in the hands of the public to create at this point.
