### ISSUE TITLE
Bug: Downtime Comments are duplicated through Nagios reload

### ISSUE THREAD

**Issue by 1tft** [NagiosEnterprises/nagioscore#307]
We found a bug in Nagios Core 4.2.x regarding the comments generated through adding a downtime.
When you create a downtime for a service/host a persistent comment is generated automatically (that works as designed), but now these comments duplicate on every Nagios-Core reload.
After a downtime has finished only one comment is deleted. Removing comments manually will work. After a Nagios restart comments are removed correctly.
We think the following commit is the problem:
https://github.com/NagiosEnterprises/nagioscore/commit/1acdbf49cd858ac40b25c53a81ea52fe1644e25a

Best regards.

**Comment by tmcnag** [comment]
We are going to try and replicate/confirm this in-house and will get back to you.

**Comment by ludmilmm** [comment]
I was able to recreate the issue in-house, and can confirm it is a bug.

**Comment by jfrickson** [comment]
Fixed in the `maint` branch via commit https://github.com/NagiosEnterprises/nagioscore/commit/6d1569cd55a0300ea12895228282b6415ee15469

**Comment by jenhek** [comment]
bug was in re-introduced into 4.4.X

See also

https://github.com/NagiosEnterprises/nagioscore/commit/6d1569cd55a0300ea12895228282b6415ee15469
