### ISSUE TITLE
host hourly value is incorrectly dumped as json boolean

### ISSUE THREAD

**Issue by philmayers** [NagiosEnterprises/nagioscore#312]
https://github.com/NagiosEnterprises/nagioscore/blob/master/cgi/objectjson.c#L2940

I think this should be as per here:

https://github.com/NagiosEnterprises/nagioscore/blob/master/cgi/objectjson.c#L3837

**Comment by tmcnag** [comment]
Good catch!  I've labeled this issue, should be easy enough to fix.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/957992e9baa81be27d5c30b3338972a22de9b2db
