### ISSUE TITLE
xi_host/service_notification macro (%responseurl%) provides wrong rapid URL that wont close issues

### ISSUE THREAD

**Issue by sanju7** [NagiosEnterprises/nagioscore#313]
When trying to use a macro defined in xi_host_notification and xi_service_notification (%responseurl%) in event handler script for using rapid response url to close nagios issues the variable generates incomplete url . This macro is providing rapid response url correctly in every email, however it generates incomplete rapid url when called from host and service state change eventhandler command box.

The url generated by nagios is missing "UID". there is nothing before first "-" : 
http://prod-aws-nagiosmaster-xx.yy/nagiosxi/rr.php?uid=-14-d41d8cd98f00b204e9800998ecf8427e

To recreate the issue:
1. install nagiosxi as per document given
https://assets.nagios.com/downloads/nagiosxi/docs/XI_Manual_Installation_Instructions.pdf

2. login with nagiosadmin username and nagiosadmin password

3. Install "global event handler" component as per document
https://assets.nagios.com/downloads/nagiosxi/docs/Configuring-Global-Event-Handlers-In-Nagios-XI.pdf

4. go to admin>manage components> global event handler>
add the following lines in host and service state change even handler command box .

Host State Change Event Handler  :
eventhandler_test.sh
Service State Change Event Handler:
anything similar
5. 
eventhandler_test.sh
#!/bin/bash
HOSTNAME=$1
HOSTSTATE=$2
HOSTSTATETYPE=$3
HOSTOUTPUT=$4
RESPONDURL=$5
DATE=$(date)
echo "The host $HOSTNAME has changed to a host state type = $HOSTSTATETYPE and state= $HOSTSTATE  at date = $DATE with responseurl= $RESPONSEURL and the error
=$HOSTOUTPUT" > /tmp/hostinfo.txt

**Comment by jfrickson** [comment]
This appears to be an XI issue. I'm checking with them.

**Comment by jfrickson** [comment]
The XI people say that they did a bunch of testing and determined that it's working properly.
