### ISSUE TITLE
Feature Request - New Macro(s) to generate URL for host / service object to be used in notifications

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#316]
When a user receives a notification message, it would be great if a URL could be provided in the notification message that would take them to the host or service object being notified about.

Perhaps new macros could be created called $HOSTURL$ and $SERVICEURL$ that would provide the correct Host/Service information URL, for example:
http://core-013/nagios/cgi-bin/extinfo.cgi?type=2&host=localhost&service=PING

While it's possible to be able to manually construct that URL in the notification command, it would be much easier if it was automatically generated using a macro.

The goal is to give the user the quickest way of getting to the Nagios object in the Nagios interface.

**Comment by jfrickson** [comment]
Good idea. Looking into it.

**Comment by jfrickson** [comment]
Now in branch "nagios-4.4.0-alpha1" via commit https://github.com/NagiosEnterprises/nagioscore/commit/dc812e159915ac267fb39f980d2cd3af33430a5e

**Comment by box293** [comment]
Just tested and works great. Making some notes here to help others in the future until it gets added into official documentation.

Need to add the directive `website_url` to nagios.cfg, for example:
```
website_url=http://core-014/nagios
```

Then in the host or notification commands you can reference the macros `$HOSTINFOURL$` or `$SERVICEINFOURL$`, for example:
```
Host Info URL: $HOSTINFOURL$
Service Info URL: $SERVICEINFOURL$
```

Which should give the following in your emails:
Host Info URL: http://core-014/nagios/cgi-bin/extinfo.cgi?type=1&host=localhost
Service Info URL: http://core-014/nagios//cgi-bin/extinfo.cgi?type=2&host=localhost&service=HTTP


Great work John.
