### ISSUE TITLE
Availability report does not honor an exclusion in a timeperiod.

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/nagioscore#318]
When running a report and selecting a timeperiod that has an exclusion defined , the report's output doesn't seem to honor the exclusion time when running the Availability report.

**Comment by jfrickson** [comment]
This would require adding the exclusion logic to the report. We may not want to do that, at least not until Core 5.

**Comment by hedenface** [comment]
I'm going to close this issue since we are planning some pretty big report changes for Core 5. If that changes I'll re-open it.
