### ISSUE TITLE
noheader messes up displayed statuses

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#320]
"Fix" provided in second post at https://support.nagios.com/forum/viewtopic.php?t=42056&start=9999#bottom

**Comment by dvoryanchikov** [comment]
Temporary fix in this comment https://github.com/NagiosEnterprises/nagioscore/issues/96#issuecomment-276342094

**Comment by jfrickson** [comment]
This was fixed with issue #302 and will be in release 4.3.0 on Feb 25.
