### ISSUE TITLE
changing directory for temp_path in nagios.cfg seems to have no effect when getting event_handler output

### ISSUE THREAD

**Issue by sinjihn** [NagiosEnterprises/nagioscore#323]
My log, confirming that the event handler is called

    Feb 02 16:53:13 nagios-server.novalocal nagios[25106]: HOST ALERT: 8ba558d7-c03e-49ff-980e-6d8e419ed7f3;DOWN;SOFT;3;CRITICAL - Host Unreachable (220.159.28.73)
    Feb 02 16:53:13 nagios-server.novalocal nagios[25106]: HOST EVENT HANDLER: 8ba558d7-c03e-49ff-980e-6d8e419ed7f3;DOWN;SOFT;3;migrate_router

My event handler

    migrate_router.py

    with open('process_call_error.log', 'a+') as error_log:
        error_log.write(str(datetime.datetime.now())+'\n')
        error_log.write("Current path: %s" % str(os.getcwd()))
        error_log.write("Environment variables %s" % str(os.environ))
        

And the file always appears in `/tmp` with this output:

    2017-02-02 17:09:13.340351
    Current path: /tmp
    Environment variables {'LANG': 'en_US.UTF-8', 'TZ': 'Asia/Tokyo', 'SHLVL': '1', 'PWD': '/', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin', '_': '/usr/local/nagios/bin/nagios'}

The output leads me to believe that the event_handler functions are getting run as some kind of subprocess, since the environment variables from my system are not being copied at all. 

Temp paths i've tried

`temp_path=/usr/local/nagios/etc/custom_folder`
`temp_path=/home/user1/logs`
`temp_path=../`

None of which work - it'll always output the file to tmp. To be clear, it looks like I'm having two issues here. The `/tmp` directory issue and how the event_handler process is executed, in a different environment.

**Comment by rcknag** [comment]
I believe this has been handled, and deemed not a bug per. our discussion here - https://support.nagios.com/forum/viewtopic.php?f=7&t=42234&p=211414#p211428

**Comment by jfrickson** [comment]
To quote the relevant section:

> temp_path and temp_file are used ONLY while writing out status.dat and retention.dat. It is passed along with macros to checks and event handlers. But before any check or handler is run, the system changes directory to /tmp.
