### ISSUE TITLE
Config: status_update_interval can not be set to 1

### ISSUE THREAD

**Issue by Magmatrix** [NagiosEnterprises/nagioscore#324]
The documentation says that this setting can be 1 or higher...

```
Status File Update Interval

Format: 	status_update_interval=<seconds>
Example: 	status_update_interval=15

This setting determines how often (in seconds) that Nagios will update status data in the status file. The minimum update interval is 1 second. 
```

...but if i set it to 1 i get this message:

`Error in configuration file '/etc/nagios3/nagios.cfg' - Line 107 (Illegal value for status_update_interval)`

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/85c8ad050c7abd53ae492dcdfecacf40a1efc38b
