### ISSUE TITLE
Config: Comments with ';' (semi-colon) is broken for some settings

### ISSUE THREAD

**Issue by Magmatrix** [NagiosEnterprises/nagioscore#325]
Some settings doesn't accept ";" comments, and some interprets the comment as the setting value.
The ones i have found that doesn't accept semicolons at all are:
`service_check_timeout_state
auto_reschedule_checks
use_aggressive_host_checking
check_result_path
retain_state_information
use_retained_program_state
use_retained_scheduling_info
translate_passive_host_checks
check_service_freshness
check_host_freshness
enable_embedded_perl
daemon_dumps_core
use_large_installation_tweaks`

This setting probably appends the comment to the file path, because it fails on "file not found":
`p1_file`

And these two does something peculiar - they don't "w" (overwrite) or "a" (append), instead they overwrite from the beginning of the file without emptying it first. Like "a" but with a fseek(0) first.
```
host_perfdata_file_mode=a   ; Append to file
service_perfdata_file_mode=a   ; Append
```

It looks like string options and SOME numeric options have this problem.

**Comment by jfrickson** [comment]
Just to clarify, do `host_perfdata_file_mode=a` and  `service_perfdata_file_mode=a` work correctly if there are no comments on those lines?

**Comment by jfrickson** [comment]
The main `nagios.cfg` file does not allow `;` comments after valid data, only object configurations do. If any comments do not cause problems, it's most likely that it doesn't matter. For example,
```
check_workers=1    ; We only want one worker
```
would be fine, because the code is this:
```
		else if(!strcmp(variable, "check_workers"))
			num_check_workers = atoi(value);
```
and the `atoi()` function stops at the first non-digit character.

Working as intended.
