### ISSUE TITLE
Notifications and recovery with multiples contacts

### ISSUE THREAD

**Issue by tatref** [NagiosEnterprises/nagioscore#330]
Hi,

I have a configuration in which I use multiple contacts to send notifications based on the `warning `or `critical `states. I looks like the following:

```
define contact {
    contact_name                    critical_contact
    service_notification_options    c,r

define contact {
    contact_name                    warning_contact
    service_notification_options    w,u
```

When the service goes from `ok `to `warning`, to `ok`, I only see the warning notification, and no recovery.

The documentation states
> Notifications about host or service recoveries are only sent out if a notification was sent out for the original problem. It doesn't make sense to get a recovery notification for something you never knew was a problem.

Is the recovery notification sent only if the same contact was notified of the problem beforehand?
Or a problem notification sent to **any** contact may latter trigger a recovery on another contact?

**Comment by jfrickson** [comment]
A recovery notification will be sent to a contact only if that contact is set up to receive notifications of the type the service is recovering from.

In other words, `critical_contact` will be notified of critical and recovery from critical. He will not be notified of warning or recovery from warning.
