### ISSUE TITLE
4.3.0 logout link produces errors

### ISSUE THREAD

**Issue by jlykke** [NagiosEnterprises/nagioscore#332]
Upgraded from 4.2.4 to 4.3.0 via source

1. "The requested URL /nagios/dologout was not found on this server" after clicking on logout link

2. after upgrade the /cgi-bin directory is now referenced as /cgibin

**Comment by tjyang** [comment]
Hi Jlykke,
I ran into the same issue, pls see
https://support.nagios.com/forum/viewtopic.php?f=18&t=42595&sid=8ccba44ed0d792158b5eb886f3d23f8b

**Comment by jfrickson** [comment]
Working on all 4.3.0 issues. Sorry for the trouble.

**Comment by jfrickson** [comment]
4.3.1 is out, with the problem-causing code removed.
