### ISSUE TITLE
After upgrade to 4.3.0 - Apache 2.4 modules missing

### ISSUE THREAD

**Issue by smoslinux** [NagiosEnterprises/nagioscore#333]
Hi All,

I found the issue regarding httpd modules.
I see the solution of the previous issue going trough httpd form. But this modules (auth form and sessions) are missing in httpd 2.4 version installed from binary (yum install).

```
AH00526: Syntax error on line 11 of /etc/httpd/conf.d/nagios.conf:
Invalid command 'AuthFormLoginRequiredLocation', perhaps misspelled or defined by a module not included in the server configuration
```

Did Nagios team considered to resolve issue from previous version version on some another way, not adding just auth form?
Did any one resolve this issue? I spent 2h searching for module to install but without success. Centos 7 OS.

**Comment by JasonRivers** [comment]
The issue here is the new login form over the old HTTP BASIC auth window. The modules you'll need for this are:

**Comment by smoslinux** [comment]
Im using centos 7, cannot do a2enmod. How to resolve this?

**Comment by JasonRivers** [comment]
I'm not completely sure what centos do with their directory tree, however on Debian/Ubuntu you have /etc/apache2/ under here, you have: mods-available and mods-enabled. In the directory mods-enabled you find symbolic linked files pointing to the mods-available directory, here's what I have:

```
lrwxrwxrwx 1 root root 33 Feb 22 13:59 auth_basic.load -> ../mods-available/auth_basic.load
lrwxrwxrwx 1 root root 32 Feb 22 14:10 auth_form.load -> ../mods-available/auth_form.load
lrwxrwxrwx 1 root root 33 Feb 22 13:59 authn_core.load -> ../mods-available/authn_core.load
lrwxrwxrwx 1 root root 33 Feb 22 13:59 authn_file.load -> ../mods-available/authn_file.load
lrwxrwxrwx 1 root root 33 Feb 22 13:59 authz_core.load -> ../mods-available/authz_core.load
lrwxrwxrwx 1 root root 33 Feb 22 13:59 authz_host.load -> ../mods-available/authz_host.load
lrwxrwxrwx 1 root root 33 Feb 22 13:59 authz_user.load -> ../mods-available/authz_user.load
lrwxrwxrwx 1 root root 30 Feb 22 14:10 request.load -> ../mods-available/request.load
lrwxrwxrwx 1 root root 30 Feb 22 14:10 session.load -> ../mods-available/session.load
lrwxrwxrwx 1 root root 37 Feb 22 14:10 session_cookie.load -> ../mods-available/session_cookie.load
lrwxrwxrwx 1 root root 37 Feb 22 14:10 session_crypto.load -> ../mods-available/session_crypto.load
```

In my apache2.conf (httpd.conf) file I have the following:

```
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf
```

This allows Apache to load the files in this directory, The files may be named differently on CentOS and you may need to install some packages to get the modules, Hopefully this helps somewhat.

Failing all of this, you can set the nagios.conf file back to BASIC auth.

**Comment by smoslinux** [comment]
In centos 7 installed binary modules doesnt exist:
auth_form.load -> ../mods-available/auth_form.load
session.load -> ../mods-available/session.load

**Comment by JasonRivers** [comment]
According to http://stackoverflow.com/questions/34675881/apache-2-4-mod-auth-form-missing

You'll want to:

```
yum install mod_session
yum install mod_form
```

**Comment by smoslinux** [comment]
I already tried. Doesn't works at all.

**Comment by jfrickson** [comment]
I'm currently working on all 4.3.0 issues. Sorry for the problems.

**Comment by smoslinux** [comment]
Thanks a lot for understanding what is a issue.

**Comment by jmorrissey8968** [comment]
Got it going on CentOS 7, as well as adding those mod_session and mod_form you need also install apr-util-openssl.
Then un-hash the required modules in their conf files.
/etc/httpd/conf.modules.d/00-base.conf - LoadModule request_module modules/mod_request.so
/etc/httpd/conf.modules.d/01-session.conf - LoadModule auth_form_module modules/mod_auth_form.so and LoadModule session_crypto_module modules/mod_session_crypto.so

That allowed httpd to start with out errors.

**Comment by smoslinux** [comment]
Can you please upade commands and also from which repo you installed?

**Comment by jmorrissey8968** [comment]
All yum installs from base Centos repos

edit the .conf files to remove the '#' from the start of the lines mentioned

**Comment by jmorrissey8968** [comment]
Sorry correction mod_form was in epel

**Comment by smoslinux** [comment]
Yes, but when i install from epel this module the api is not matching. Install mod_session doesnt exist in epel.

**Comment by jfrickson** [comment]
I just put out 4.3.1 with the problem-causing code removed. I will figure out how to do it better next time ;-)

**Comment by maxwellhaydn** [comment]
For reference, I had to do the following to get this working on CentOS 7:

```
yum install mod_session apr-util-openssl
```

(both packages are in the base repo)

Edit `/etc/httpd/conf.modules.d/01-session.conf` to look like this:

```
LoadModule session_module modules/mod_session.so
LoadModule request_module modules/mod_request.so
LoadModule session_cookie_module modules/mod_session_cookie.so
LoadModule session_dbd_module modules/mod_session_dbd.so
LoadModule auth_form_module modules/mod_auth_form.so
LoadModule session_crypto_module modules/mod_session_crypto.so
```

Without apr-util-openssl, Apache would crash on startup but show no errors.
