### ISSUE TITLE
Quick Search no longer allows search by Alias

### ISSUE THREAD

**Issue by lvsysadm** [NagiosEnterprises/nagioscore#335]
hi,
I have updated nagios to version 4.3.1 now the search by IP works fine but (also in  version 4.2.4) the search using the host alias report the same problem of the ip quick search
```

It appears as though you do not have permission to view information for any of the hosts you requested...

If you believe this is an error, check the HTTP server authentication requirements for accessing this CGI
and check the authorization options in your CGI configuration file.
```

the quick search using alias works fine on nagios 4.1.1.

**Comment by jfrickson** [comment]
I will be getting to this shortly. Should be a simple fix.

**Comment by lvsysadm** [comment]
thank you.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/5910ccb882a28a90b9f0d2559673d1f8dbef1517
