### ISSUE TITLE
Every 15sec /var/log/messages is flooded with "nagios: set_environment_var"

### ISSUE THREAD

**Issue by sleewharry** [NagiosEnterprises/nagioscore#337]
After upgrade from 4.2.4 to 4.3.1 /var/log/messages started to fill up every 15 sec with about 200 lines of 
`nagios: set_environment_var 'NAGIOS_HOSTNAME'='(null)'`
`nagios: set_environment_var 'NAGIOS_HOSTALIAS'='(null)'`
`nagios: set_environment_var 'NAGIOS_HOSTADDRESS'='(null)'`
`. . . `

**Comment by jfrickson** [comment]
My apologies -- I left in some debugging code.

Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/e03e4fd470fbc8d4304d860d7b3b523c5d78373d
