### ISSUE TITLE
inconsistent release archive name under GitHub release page

### ISSUE THREAD

**Issue by guessi** [NagiosEnterprises/nagioscore#339]
Hi,

it's not about the source code, but integration,

I'm building customized Nagios docker image with the release archive under [GitHub release page](https://github.com/NagiosEnterprises/nagioscore/releases),
but the package naming are not always in the same format,

take the latest 10 release archives for example,

- https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.3.1.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/release-4.3.0.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/release-4.2.4.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/release-4.2.3.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.2.2.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/4.2.1.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.2.0.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.1.2-Pre1.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.1.1.tar.gz
- https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.1.0.tar.gz

there are 4 types of formats 
- nagios-x.y.z.tar.gz
- nagios-x.y.z-phase.tar.gz
- release-x.y.z.tar.gz
- x.y.z.tar.gz

maybe we could have a release script to make sure release archive could have the same naming rule. 

not a big deal, just wanna address this small issue 👍

**Comment by jfrickson** [comment]
Ok, ok ;-)

From now on, actual releases will be `nagios-x.y.z.tar.gz`

Alphas, betas, release-candidates will be `nagios-x.y.z-PHASE.gar.gz` where `PHASE` will be like `alpha4`, `beta2`, `rc1`.

Feel free to take me to task if I mess it up!

**Comment by guessi** [comment]
@jfrickson thanks 👍
