### ISSUE TITLE
Stalking for Notifications

### ISSUE THREAD

**Issue by BanditBBS** [NagiosEnterprises/nagioscore#342]
I need the stalking option expanded to also include notifications, not just log entries when the exit message changes

**Comment by jfrickson** [comment]
I'll see what I can do!

**Comment by hedenface** [comment]
Will review at next meeting.

**Comment by hedenface** [comment]
@BanditBBS You mean you want a notification every time a stalking event occurs?

**Comment by BanditBBS** [comment]
Yes!  Maybe add a config variable "alert_all_stalking" and default it to off so it doesn't affect users currently using stalking but gives others the option to enable.

**Comment by hedenface** [comment]
I think I'll just update the `stalking_options` to include a `n` flag - and then adjust whether it sends a notification based on if the stalking occurred. That way it doesn't involve any changes to the header, or the global config so we don't have to worry about people's configs breaking during upgrade.

**Comment by BanditBBS** [comment]
That'd work too.  Been a while since I looked at options waiting for this, forgot what I really wanted, you idea is what I want :D

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nagioscore/commit/0231102e34cb416afaaa0dea8f00325cdf6c43bd. And I fixed a notification issue I inadvertently created while cleaning up some chunks of code.

@BanditBBS If you have any time, I'd love it if you could throw some eyes on this. All you have to do is add `N` (make sure it's capital, as a lowercase `n` indicates "none" - alternatively you could use `notifications` as well as the option) to your host or service `stalking_options`.

**Comment by BanditBBS** [comment]
@hedenface I will try to install a test Core installation.  Right now all I have is XI at the office.

**Comment by jomann09** [comment]
@BanditBBS did you ever get a chance to look into this? Having read through the code that @hedenface added it looks like what really was added was that it logs the state event when it sends out a notification. I am testing it now someone else is having issues with this in 4.4.2

**Comment by BanditBBS** [comment]
No, been waiting for it to come into XI.

Jim

**Comment by jomann09** [comment]
It should show up in the CCM in the latest I believe, Core 4.4 is in XI 5.5+ but again I am not sure this option actually makes it send notifications.

**Comment by ericloyd** [comment]
Does this mean we can stop downgrading Core in XI to use mod_gearman?

**Comment by jomann09** [comment]
We will have mod_gearman 3 working with Core soon, and then you will not need to downgrade. Probably looking at XI 5.6 for all that to come together. I'm not sure if you'll be able to use the old mod_gearman in Core 4.4+ though.

**Comment by jomann09** [comment]
Also I fixed this stalking_options N option to work the way stalking_options work. Will add a stalking_notify soon to actually forcefully send out a notification.

**Comment by ericloyd** [comment]
Honestly don't care about gearman in core itself.  Our standard customer use case is distributed computing inside customer firewalls where a gearman box can do the work while an XI box can coordinate/report it.

**Comment by BanditBBS** [comment]
I'm just dying to stalk stuff in XI and receive notifications...that will
improve so many things for me.
