### ISSUE TITLE
 Excluding contact from contactgroup

### ISSUE THREAD

**Issue by amprantino** [NagiosEnterprises/nagioscore#344]
I would like to exclude a contact from a service or host definition using the ! symbol.
A similar configuration with host/service definition, where I can exclude a host using !host

Relevant forum post: https://support.nagios.com/forum/viewtopic.php?f=7&t=42818

Best Regards

**Comment by jfrickson** [comment]
I'll take a look, but I suspect this will be included in the new processing for inheritance, etc., in Core 5.

**Comment by brennus390** [comment]
Just curious, but is there an ETA for Core 5?
Thank you,

**Comment by jfrickson** [comment]
It depends on how much we end up wanting to do in Core 5. All the requirements are not yet defined. Rough guess would be 4th quarter 2017. (Subject to change, your mileage may vary, void in some states, etc.)

**Comment by jfrickson** [comment]
I've put in code to override notification options on either the `contacts` or `contact_groups` entries in host and service definitions. It was done mainly for issue #95 but I think it would work here, as well.

See commit https://github.com/NagiosEnterprises/nagioscore/commit/59f38d673629049795bf9e766d02600e05d1d041 for a description. In your case, if the contact you want to exclude is `mark`, the following would probably work:
```
    contacts mark:n
```

The code is in the branch `nv5dev` it you want to try it out. Note: that branch will likely be quite unstable as I work on it, but for now, it should work fine. The tarball is at https://github.com/NagiosEnterprises/nagioscore/archive/nv5dev.tar.gz
