### ISSUE TITLE
flexible downtime on a service immediately turns off notifications

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#346]
create a future flexible downtime for a known service and then force the service into a critical alarm, and the notifications are squashed. If the service is already critical, notifications are not turned off.

For more information, see internal bug report 11326.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/a261e0dc9e2d7296f34c33f828a9c0103f940eea
