### ISSUE TITLE
command pipe corruption writing to nagios.cmd

### ISSUE THREAD

**Issue by emerchantc** [NagiosEnterprises/nagioscore#35]
What I found was, if you didn't submit he command with a "\n" at the end then it wouldn't work but was "appended/kept in the buffer" and then later when a correct command was issued the previous kept information was also submitted.

You can see the location of "\n" in the following example:

    now_epoch=$(eval date +%s); printf "[$now_epoch] ADD_HOST_COMMENT;centos03;1;nagiosadmin;This host does funny stuff\n" > /usr/local/nagios/var/rw/nagios.cmd

I think it would be prudent to clear out the contents of the buf variable in command_input_handler after each process_external_command1 run. It's certainly not ideal to have corruption pop up at all, but I don't see any reason to keep bogus commands around in that variable to (possibly) be executed later.

see http://support.nagios.com/forum/viewtopic.php?f=7&t=31900

**Comment by tmcnag** [comment]
Proper attribution:  The above comment was originally posted by @Box293

http://support.nagios.com/forum/viewtopic.php?f=7&t=31900&start=10#p132182

**Comment by box293** [comment]
So if I understand what you are saying, a command submitted without a /n sits in the buffer. If more commands without a /n are received they will be appended to the buffer. Eventually a correct command comes along with a /n. At this point, the entire buffer, including the last command with the /n is processed ... however the entire buffer string is targeted at the host defined in the first command in the buffer and all the other commands never get targeted to the remaining correct hosts?

**Comment by jfrickson** [comment]
You understand correctly.

**Comment by box293** [comment]
I don't think there is any real fix for this that I can think of. If a command is submitted without a new line then it's an invalid command. It's just that the side affect is that it sits in the buffer until a correctly defined command comes along.

**Comment by jfrickson** [comment]
Sounds good to me. I'm closing this issue.
