### ISSUE TITLE
Feature Request: Additional Macro for Time Period

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#350]
While with some logic the user in https://support.nagios.com/forum/viewtopic.php?t=43022&start=9999#bottom could get what they want with the current macros, there is not one that easily returns the time period information, only one that returns a 1 or 0.

**Comment by jfrickson** [comment]
I'll check it out

**Comment by hedenface** [comment]
Approved for 4.4.0

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nagioscore/commit/5d11c9047ce61333d0e7acf367a8007c9f05502c
