### ISSUE TITLE
Feature Request: Give option to disable page tours

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#352]
user suggestion is configurable in the nagios.cfg like 'enable_page_tour=1'

More info at https://support.nagios.com/forum/viewtopic.php?t=42985&start=9999#bottom

**Comment by jfrickson** [comment]
Quoting myself from the thread:

> There is a "Never show this again" link at the top-right of the open window. It sets a cookie in your browser telling it to not load that popup window again. It's a per-page cookie, so you would have to click it on each page that has the tour window.
>
> I'll probably add a preference, but that should do the job for you in the meantime.

**Comment by jfrickson** [comment]
Quoting myself from the thread:

> There is a "Never show this again" link at the top-right of the open window. It sets a cookie in your browser telling it to not load that popup window again. It's a per-page cookie, so you would have to click it on each page that has the tour window.
>
> I'll probably add a preference, but that should do the job for you in the meantime.

**Comment by hedenface** [comment]
Approved and added for 4.4.0

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nagioscore/commit/6f4d98c8eb2b8cbf3440cf3c7538f7e4c32d1fbb
