### ISSUE TITLE
regex like * doesn't work in hostgroup > hostgroup_members

### ISSUE THREAD

**Issue by meabandit** [NagiosEnterprises/nagioscore#354]
It does work in hostgroup > members.

The documentation leads me to believe this should work:

> [Regular expressions can be used in any of the fields used in the examples below (host names, hostgroup names, service names, and servicegroup names).](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/objecttricks.html)

This behavior is the same regardless of the setting of use_regexp_matching

This is tested on Core 4.2.4

**Comment by box293** [comment]
Can you provide a hostgroup definition example please.

**Comment by meabandit** [comment]
```
define hostgroup {
        hostgroup_name                          hostgroup_test
        alias                                   hostgroup_test_alias
        members                                 *
        hostgroup_members                       *
        }
```

**Comment by hales8181** [comment]
+1 on this. I'd like the config below to create the hostgroup 'hostgroup_test', and populate it with all of the hostgroups that end with abctesting.

define hostgroup {
        hostgroup_name                          hostgroup_test
        alias                                              hostgroup_test_alias
        hostgroup_members                    *abctesting
        }

**Comment by box293** [comment]
I had a good test of this and I can confirm that it just throws the following error:

```
Error: Could not find member group '*' specified in hostgroup 'hostgroup_test' (config file '/usr/local/nagios/etc/objects/localhost.cfg', starting on line 11)
```
I tried a couple of different variations and all I could do was confirm that it doesn't work as expected.

**Comment by jfrickson** [comment]
Fixed via commit https://github.com/NagiosEnterprises/nagioscore/commit/d1f789eed869f4cf540009f73f4b23138d612a54 into branch `nv5dev`, which is the Core 5 development branch, and may become unstable at a moment's notice.

Both `*` and regexes (if enabled) will now work in `hostrgroup_members`.

**Comment by hales8181** [comment]
Thanks - what version of XI will this be fixed in?

**Comment by hedenface** [comment]
Core 5 isn't officially scheduled for a specific release date. This likely won't be in XI until the version of Core that it's released in is considered stable.
