### ISSUE TITLE
localhost.cfg service check

### ISSUE THREAD

**Issue by sdarwin** [NagiosEnterprises/nagioscore#358]
A default installation of nagios creates localhost.cfg with this section:

```
# Define a service to check HTTP on the local machine.
# Disable notifications for this service by default, as not all users may have HTTP enabled.

define service{
        use                             local-service         ; Name of service template to use
        host_name                       localhost
        service_description             HTTP
        check_command                   check_http
        notifications_enabled           0
        }
```

localhost is Nagios itself, right?

Most installations of Nagios, out of the box, have web authentication configured. A test on both Ubuntu and Redhat give the error "HTTP WARNING: HTTP/1.1 403 Forbidden - 5179 bytes in 0.003 second response time". The service shows Warning. The item is in yellow.

If basically all new installations are getting this Warning now, and they have to figure it out and resolve it, then maybe instead the service could just be removed or commented-out by default.

**Comment by sdarwin** [comment]
I was too quick in posting that.  :-) Redhat was missing a certain index.html. And web auth, while it is enabled, should only affect the /nagios folder. Closing the ticket.

**Comment by box293** [comment]
I too see what you are explaining on different OS's. I actually like that it is warning as it demonstrates how the product works, seeing it in action so to speak.
