### ISSUE TITLE
Service Description should include "$hostname" 

### ISSUE THREAD

**Issue by ameyaagashe** [NagiosEnterprises/nagioscore#360]
Hello Guys,

Currently service_description does not allow $hostname to be included in its string and it makes difficult to understand from which server the alert was generated. This would help understand from where the alert came through and filter it according to hostnames.

Kindly assist us here.

Many thanks in advance

Ameya

**Comment by jfrickson** [comment]
I see this is also being discussed on the forum. I'll watch the discussion there and figure out if this is something that needs to be added to core.

**Comment by jfrickson** [comment]
See forum post https://support.nagios.com/forum/viewtopic.php?f=7&t=43454&p=219166#p219166
