### ISSUE TITLE
Quick search with no hits shows a permission denied error

### ISSUE THREAD

**Issue by Dhyrule** [NagiosEnterprises/nagioscore#361]
We recently upgraded to 4.3.1 and are having issues with the quick search when there are no hits.
Instead of showing a "0 Matching Hosts" we get a permission denied error:
![image](https://cloud.githubusercontent.com/assets/7023216/25150589/c08d2822-2482-11e7-9933-b58f02d33ad1.png)

Noticably we are on the Host Status Detail page, in show_host_detail() in cgi/status.c, where I first hacked myself around the problem by checking for total_entries:
```
    /* if user couldn't see anything, print out some helpful info... */
    if(user_has_seen_something == FALSE && total_entries > 0) {

```

However not happy with this dirty hack and knowing the old version of nagios was showing the Service Status Details (not Host Status) on an empty search, I suspected the problem was further up and tracked it down to this snippet in main():

```
 450     /* Special case where there is a host with no services */
 451     if(display_type == DISPLAY_HOSTS && num_services == 0 && display_header) {                                                                                                          
 452         display_type = DISPLAY_HOSTGROUPS;
 453         group_style_type = STYLE_HOST_DETAIL;
 454     }

```

Where display_type is set to DISPLAY_HOSTS by default due to quick search form having the "host" field and num_services is 0 presumably due to no results.
Removing this snippet makes the quick search not show permission errors anymore and we end up on the Service Status Detail again like in the old versions.

**Comment by Dhyrule** [comment]
This problem seems to have been introduced with #96

**Comment by jfrickson** [comment]
I'm looking into it.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/5696be43e32bcdbb30cb5956ee4845954e9e20de
