### ISSUE TITLE
still got read() returned error 11

### ISSUE THREAD

**Issue by Abmans** [NagiosEnterprises/nagioscore#362]
Hello all,

i have still problems with the messages "nagios: job 0 (pid=2724): read() returned error 11". 
This started at version 4.2.0, and i have tested every version after 4.2.0 and up and it seems to happen when notifications are bin send out. 

I have done the installation on CentOS7 and this is the output on Nagios version 4.3.1:
cat /var/log/messages |grep "returned error"
Apr 21 12:13:01 test-nagios-4 nagios: job 0 (pid=2724): read() returned error 11
Apr 21 12:13:18 test-nagios-4 nagios: job 1 (pid=2736): read() returned error 11
Apr 21 12:13:33 test-nagios-4 nagios: job 2 (pid=2746): read() returned error 11
Apr 21 12:14:41 test-nagios-4 nagios: job 3 (pid=2764): read() returned error 11
Apr 21 12:17:48 test-nagios-4 nagios: job 4 (pid=23530): read() returned error 11
Apr 21 12:18:01 test-nagios-4 nagios: job 4 (pid=23542): read() returned error 11
Apr 21 12:18:18 test-nagios-4 nagios: job 0 (pid=23602): read() returned error 11
Apr 21 12:18:37 test-nagios-4 nagios: job 0 (pid=23627): read() returned error 11

It looks like this tread https://github.com/NagiosEnterprises/nagioscore/issues/172 

But it still appears in the message file and it make customers worried.

Many thanks in advance

Albert Visscher

**Comment by jfrickson** [comment]
As pointed out in issue #172, this has been degraded to a `LOG_NOTICE` and will probably be eventually removed. In the meantime, your syslog config should allow you to filter out messages that have a program of `nagios` and a log priority of `LOG_NOTICE`.
