### ISSUE TITLE
'á' causes Serivce Status Information to not be displayed

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#366]
Support thread at https://support.nagios.com/forum/viewtopic.php?f=7&t=43767

This would appear to be a more global version of https://github.com/NagiosEnterprises/nagioscore/issues/107. The main problem here is that since check_http is compiled, you can't just change the output in the check (easily).

While a fix in Core would be ideal going forward, there may also need to be fixes in the plugins, as people will run new plugins with old versions of Core (I'm thinking some way to sanitize, like the workaround in issue 107)

**Comment by jfrickson** [comment]
I'm not sure what's causing the problem, but I'll look into it.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/e95aee71f67fcbe4dc9623089e7ef913ac574233
