### ISSUE TITLE
xdata/xodtemplate.c wrong option-deprecation code warning 

### ISSUE THREAD

**Issue by alex2grad** [NagiosEnterprises/nagioscore#368]
Nagios 4.3.2.
Checking for retry_check_interval, but warning about normal_retry_interval
Attached patch

[retry_check_interval-patch.txt](https://github.com/NagiosEnterprises/nagioscore/files/990329/retry_check_interval-patch.txt)

**Comment by douglasawh** [comment]
see https://support.nagios.com/forum/viewtopic.php?t=43841&start=9999#bottom

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/39d3a709dcbd6d21d891ca2351034c76d0016e17
