### ISSUE TITLE
Error after update Naemon and Thruk

### ISSUE THREAD

**Issue by pantinanco** [NagiosEnterprises/nagioscore#369]
Hello,
I like to greet you, I write to you since I need your help. I recently did the update of our monitoring platform Naemon, which was done without problems. But when I enter the portal and see the states of the hosts, it shows me the following error:

"No Backend available
None of the backends could be reached, please have a look at the logfile for detailed information and make sure the core is up and running.

Details:
Naemon: ERROR: failed to open socket / var / cache / naemon / live: No such file or directory .. (/ var / cache / naemon / live) "

I have reviewed the error logs but I could not find the solution. As a result, if I check the configuration of objects through the web, it shows me the data of the hosts, such as IP, hostname and the hostgroup to which it belongs.

Information delivered by the systemctl status naemon.service:

"● naemon.service - Naemon Monitoring Daemon
   Loaded: loaded (/usr/lib/systemd/system/naemon.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-05-11 10:00:06 CLT; 1h 2min ago
     Docs: http://naemon.org/documentation
  Process: 20853 ExecStart = / usr / bin / naemon --daemon /etc/naemon/naemon.cfg (code = exited, status = 1 / FAILURE)
  Process: 20850 ExecStartPre = / usr / bin / chown -R naemon / var / run / naemon / (code = exited, status = 0 / SUCCESS)
  Process: 20846 ExecStartPre = / usr / bin / mkdir / var / run / naemon (code = exited, status = 1 / FAILURE)

May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: Starting Naemon Monitoring Daemon ...
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: naemon.service: control process exited, ... = 1
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: Failed to start Naemon Monitoring Daemon.
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: Unit naemon.service entered failed state.
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: naemon.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[Root @ naemon-sion-alicopsa-local ~] # service naemon restart
Redirecting to / bin / systemctl restart naemon.service
Job for naemon.service failed because the control process exited with error code. See "systemctl status naemon.service" and "journalctl -xe" for details.
[Root @ naemon-sion-alicopsa-local ~] # systemctl status naemon.service
● naemon.service - Naemon Monitoring Daemon
   Loaded: loaded (/usr/lib/systemd/system/naemon.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-05-11 11:15:12 CLT; 15s ago
     Docs: http://naemon.org/documentation
  Process: 22092 ExecStart = / usr / bin / naemon --daemon /etc/naemon/naemon.cfg (code = exited, status = 1 / FAILURE)
  Process: 22088 ExecStartPre = / usr / bin / chown -R naemon / var / run / naemon / (code = exited, status = 0 / SUCCESS)
  Process: 22083 ExecStartPre = / usr / bin / mkdir / var / run / naemon (code = exited, status = 1 / FAILURE)

May 11 11:15:12 naemon-sion-alicopsa-local systemd [1]: Starting Naemon Monitoring Daemon ...
May 11 11:15:12 pm naemon-sion-alicopsa-local systemd [1]: naemon.service: control process exited, ... = 1
May 11 11:15:12 pm naemon-sion-alicopsa-local systemd [1]: Failed to start Naemon Monitoring Daemon.
May 11 11:15:12 AM naemon-sion-alicopsa-local systemd [1]: Unit naemon.service entered failed state.
May 11 11:15:12 pm naemon-sion-alicopsa-local systemd [1]: naemon.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
"

Waiting for your help and prompt reply, I say goodbye.

Thanks in advance.

Best regards.

Pablo Antiñanco Soto

**Comment by hedenface** [comment]
Although we appreciate you reaching out to us first for help, we are not naemon. You'll probably want to try and communicate with their support.

https://github.com/naemon/naemon/issues
