### ISSUE TITLE
Network Status Map in Core 4.1 does not respect default layout settings in cgi.cfg

### ISSUE THREAD

**Issue by abrist** [NagiosEnterprises/nagioscore#37]
The new map does not respect the setting:

default_statusmap_layout=<id>

in cgi.cfg.

I do not know if this is intended, a now unsupported config option, or just overlooked.
Discovered by user "naguser" on the nagios forums:

http://support.nagios.com/forum/viewtopic.php?f=7&t=32315

**Comment by tmcnag** [comment]
The CGI statusmap does properly respect the settings it seems.  For reference, I mean this URL:

`http://192.168.1.100/nagios/cgi-bin/statusmap.cgi`

However the newer-style maps introduced in 4.1 do not.  I am speaking of this URL:

`http://192.168.1.100/nagios/map.html?host=all`

I believe this is a D3 issue:  http://d3js.org/

It's a new framework for me but I'll dig in.

**Comment by tmcnag** [comment]
It does appear to be an Angular thing.  The default seems to be set under:

`/usr/local/nagios/share/js/map.js`

Lines 102-103:

https://github.com/NagiosEnterprises/nagioscore/blob/master/html/js/map.js#L102-103

Changing 6 to another value will set the default.  There is a list of the layouts and their indices at the top of that file:

https://github.com/NagiosEnterprises/nagioscore/blob/master/html/js/map.js#L7-85

Still not sure why it doesn't properly read the defaults in cgi.cfg - there does appear to be some code present to do so.

**Comment by tmcnag** [comment]
Adding "enhancement" label for now as this is neither quite a bug nor a feature request at this point.

**Comment by jfrickson** [comment]
Fixed by commit https://github.com/NagiosEnterprises/nagioscore/commit/d31e14613087b164529f905abf30034667f42689
in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1
