### ISSUE TITLE
Question: Number of $USERn$ macro definitions in Resource File resource.cfg

### ISSUE THREAD

**Issue by 1tft** [NagiosEnterprises/nagioscore#371]
Hello,
I heard that there exists a relatively small max limit about the number of $USERn$ macros in resource.cfg file under Nagios Core 3.x
Does somebody know the max limit of $USERn$ macros (for hiding passwords) in Nagios Resource File with core 4.x ?

**Comment by m82labs** [comment]
256
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/macrolist.html#user

**Comment by box293** [comment]
If you wanted more than 256 you can change the source code in the include/macros.h file:

https://github.com/NagiosEnterprises/nagioscore/blob/463087a2c89647fdb9e20d89eaddb5c19ef25bac/include/macros.h

`#define MAX_USER_MACROS	256	/* maximum number of $USERx$ macros */`

If you were to do this you would need to make this change every time you upgrade Nagios.

**Comment by 1tft** [comment]
Thank you very much for this prompt and helpful answer!
