### ISSUE TITLE
FR - Give the option to do case insensitive matching when submitting commands

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#373]
It would be nice to be able to do case-insensitive matching on the find_host and find_service functions when submitting passive checks/commands.

This would be useful for NRDP host/service matching when submitting passive results and also for submitting standard commands:

http://old.nagios.org/developerinfo/externalcommands/commandlist.php

**Comment by jfrickson** [comment]
I can see the advantages. I'll have to think about the down-side.

**Comment by hedenface** [comment]
The downside is rather obvious - what happens if you have two or more hosts and/or services that match?

I think the behavior should be allowed, but controlled by a configuration option. This seems most reasonable.

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nagioscore/commit/b17d82bfe4eb425b1d202e7c30c342e038dd19db
