### ISSUE TITLE
notification_interval <time>

### ISSUE THREAD

**Issue by amprantino** [NagiosEnterprises/nagioscore#374]
notification_interval <time>

I am looking to configure the interval in an easy way to read (1**h** = 1hour, 1**d** = 1day , 1**m** = 1month).
At the monent Nagios is just ignoring the character after the number.

**Comment by jfrickson** [comment]
This is scheduled for Core 5. See issue #224

**Comment by hedenface** [comment]
Since this is a duplicate, I'll be closing the issue.
