### ISSUE TITLE
Mac OS Compile Errors

### ISSUE THREAD

**Issue by Josh3955** [NagiosEnterprises/nagioscore#379]
I was able to compile by using make -i to ignore all warnings and errors. Core only has a few but the plugins compile is in the hundred+ errors. Mostly due to deprecated calls or unsigned integers (apparently Darwin hates that kind of thing. I am attaching a RTF of the console log of the compile of both core and plugins. I don't have the skill to offer up fixes to the source code to the community, but will gladly offer up these logs.
[compileErrors.txt](https://github.com/NagiosEnterprises/nagioscore/files/1046500/compileErrors.txt)

**Comment by jfrickson** [comment]
Thanks, @Josh3955 I'm going to be doing some extreme fixing of warnings and errors in Core 5. Your log will help, I'm sure.

**Comment by hedenface** [comment]
Are these errors still there? This is open in another issue as well - and when I went testing it on 14.5.0 everything was fine.

Please provide additional information regarding your OS.

**Comment by Josh3955** [comment]
Then has been a while.  I compiled 4.3.4 within a couple of days of it’s release.  It generated a number of warnings, but I was able to compile without any Herculean effort.
