### ISSUE TITLE
Nagios 4 (4.10 RC1) Startup (SuSE 13.2)

### ISSUE THREAD

**Issue by omnitec** [NagiosEnterprises/nagioscore#38]
Recently upgraded a 3.5.1 machine to 4.1RC1, and I thought everything was OK until last Friday when there was a power issue; the server rebooted and Nagios did not start. Found a number of posts on the Forum that the init.d script is only valid on Debian, .. but nothing in the past 18 months. Is there an init script flavor for SuSE (or RH)?

**Comment by omnitec** [comment]
Doing some more homework, it appears this may be a fallout of a transition to systemd, .. if so, will the source tree ever reflect an systemd option?

**Comment by tmcnag** [comment]
I can't speak for the official devs, but it shouldn't be too terribly hard to write a systemd config.  Some very brief searching led me to this:  https://github.com/dkowis/smgl-systemd/blob/master/nagios.service

I'm sure there would need to be some `./configure` tie-in with the various install paths, users, and groups, but that seems relatively trivial.

**Comment by omnitec** [comment]
On Sat, 4 Jul 2015, Trevor McDonald wrote:

> I can't speak for the official devs, but it shouldn't be too terribly
> hard to write a systemd config.  Some very brief searching led me to
> this:  https://github.com/dkowis/smgl-systemd/blob/master/nagios.service
>
Doubt it would be too hard either, .. but there seems to be a resistance
for supporting systemd, so I would prefer to wait until that is resolved.

	Lee

**Comment by tmcnag** [comment]
Resistance within Nagios or in the Linux/Unix community as a whole?  Personal feelings about systemd aside, if major distros are moving toward using it then we need to keep with the times.

**Comment by omnitec** [comment]
On Mon, 6 Jul 2015, Trevor McDonald wrote:

> Resistance within Nagios or in the Linux/Unix community as a whole?
> Personal feelings about systemd aside, if major distros are moving
> toward using it then we need to keep with the times.
>
I have seen both, .. but there seems to be a disconnect with the Core4
transition - most current distros are moving to SystemD, yet there seems
to be no hint of that being done in NagiosCore.

	Lee

**Comment by jfrickson** [comment]
Just to keep you informed, I have a SystemD script set up and I'm working on updating the install to handle different systems and init types. See https://support.nagios.com/forum/viewtopic.php?f=34&t=36575

**Comment by hedenface** [comment]
There is a systemd script in 4.4.0. Please test it (current master branch, perhaps a release of 4.4.0 soon) and report back to a new issue if you find errors.

Thanks.
