### ISSUE TITLE
Availability report is showing negative values

### ISSUE THREAD

**Issue by degre** [NagiosEnterprises/nagioscore#384]
Some of my availability reports are showing negative %-values as well as incredibly high "Time"-values (e.g. "1158050440d 8h 41m 44s"), see the attached screenshot.

I narrowed the issue down to only occur when a scheduled downtime took place during the "Report Period", here "Last month".
The error occurs on any given "Report time Period", except the pre-defined "24x7" and "none". Note: The pre-defined Report time Period "workhours" also leads to incorrect data.

I found some indication on the www that this is up to an error in avail.cgi and that this should have been fixes by now, which I cannot agree to, since I just updated my system on a sandbox to Nagios Core 4.3.2.

The values are somewhat different to my live-environment (being Nagios 3.5.2). However, they're still false (the screenshot is from Nagios 4.3.2).

Some additional information:
Report-URL: https://<MY_NAGIOS_SITE>/nagios/cgi-bin/avail.cgi?assumeinitialstates=yes&assumestateretention=yes&assumestatesduringnotrunning=yes&backtrack=4&show_log_entries=yes&timeperiod=lastmonth&rpttimeperiod=sla_xxx&host=<HOSTNAME>&service=<SERVICENAME>

```
# /usr/local/nagios/bin/nagios
Nagios Core 4.3.2
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2017-05-09
License: GPL
(...)

```
I have stripped down the logs to contain only (IMHO) relevant data. This is the data worth a full month and my tests after cleaning up the logs showed the expected "faulty" result.
I have additionally attached some more screenshots as well as the entire object-definition that's used to reproduce this issue.

If there's anything more that I can do in order to help investigating this issue just let me know.

Looking forward to hearing from you soon.

cheers,
Dennis

PS: You'll surely realize, that the archive-logs start with Nagios 3.5.1. That was the previous version up until thursday last week. I thought an update of Nagios-core as well as the plugins would have solved this issue, which unfortunately did not work out quite as expected...

PPS: I already started a request in the forum prior to filing an issue here. Pls. check out https://support.nagios.com/forum/viewtopic.php?f=7&t=44107 for additional information.

[nagios.zip](https://github.com/NagiosEnterprises/nagioscore/files/1084229/nagios.zip)

**Comment by hedenface** [comment]
I'll take a look soon. We're actually looking at revamping the avail.cgi, but maybe I can get a fix in for the next bugfix release.

**Comment by degre** [comment]
Hi Bryan,

thanks a lot. Your help is greatly appreciated!

Best regards,
Dennis

**Comment by degre** [comment]
Hi @hedenface ,

any idea on when you'll have a chance to look into this issue?
I don't want to put any pressure on you, I'm just keen on getting to know when I can "expect" a possible fix in order to get the report done.

Many thanks in advance,
Dennis

**Comment by hedenface** [comment]
I do not know of a specific time - I'd hate to say this week and not be able to deliver on that. Believe it or not, I already started to look once (and something else popped up, as is the nature of coding).

Also, we are looking at avail.cgi for some major underhauling anyway (that one I can tell you is likely many months away :)

Regardless, I'll keep you posted with any updates.

**Comment by degre** [comment]
Fair enough. Just wanted to know wether it's rather going to be weeks or months.
Keeping my fingers crossed and hoping it's going to be the former... ;-)

Thanks for the update. I'm looking forward to hearing from you soon :)

**Comment by hedenface** [comment]
@degre I'm looking into this, and the math in all the sections regarding the calculations of `percent_time_critical`, etc. all look fine to me.

If you keep everything the same and change the service, does the problem disappear? (Provided that that service also has some scheduled/unscheduled critical time).

Also, if you keep these report settings exactly the same, and change the timeperiod to 24x7 does it report properly then?

Thanks!

**Comment by hedenface** [comment]
And also, does the scheduled downtime end outside of the valid timeperiod ranges?

**Comment by degre** [comment]
Hi @hedenface ,

thanks for looking into that.

I'm not really sure what you mean by saying "If you keep everything the same and change the service, does the problem disappear?". We only set downtimes for this servicegroup. The odd behaviour occurs across all services.
This behaviour does not always occur, when a downtime was set. However, it has never occured without a downtime being in place. HTH...

The problem does not occur on timeperiod 24x7, see the attached screenshots.

What I just realized when taking the screenshots: at the very end of the report time period, i.e. "12-04-2017 00:00:00", a new downtime kicks in with an event-duration of "1158050440d 16h 57"(!), so may be that's the problem? That appears on both timeperiods, though...

The downtime usually ends during business hours, which is inside the timeperiod range.

Best regards,
Dennis

![sla_xxx](https://user-images.githubusercontent.com/29534710/27780513-a066bfea-5fc9-11e7-86f1-6c5bdcff3e55.png)
![24x7](https://user-images.githubusercontent.com/29534710/27780516-a339a98a-5fc9-11e7-8eaf-2a003f385a68.png)

**Comment by degre** [comment]
Hi @hedenface ,

any update / new findings on that?

Best regards,
Dennis

**Comment by degre** [comment]
*Knock Knock*

Anybody still looking into this?

Best regards,
Dennis

**Comment by hedenface** [comment]
I did look into it, actually.

And decided, without communicating here unfortunately, how we're going to handle it.

The fix for this in any of the near future releases would be a ridiculous time suck unfortunately. We are re-writing the reports and their structures for Core5 anyway.

That sounds like a ways away - and it very well may be - but I ***don't think*** there are going to be many more maintenance or enhancement releases after the next one until 5 is released.

This may be a $#$#^#$tty anser for you - and for that I apologize - along with not keeping the thread updated - but it's for the greater good.

Once I get all my ducks in a row I'll keep GitHub updated with the progress :)

**Comment by degre** [comment]
Hi @hedenface ,

well, it's certainly not the answer I was hoping for, but at least it's an answer to work with, so thanks for the honest and open feedback ;-)

Two more quick questions:
1.) Is there any (rough) schedule on the releasedate of 5.x? I couldn't find anything usefull in the roadmap regarding a possible releasedate.

2.) Since you took a deeper look into the issue you probably know pretty well, what's causing the issue, right?! Is there any chance for me (being not a developer, but a sysadmin-person) to work around this bug?

Thanks for all the time you spent looking into this issue.

Best regards,
Dennis

**Comment by hedenface** [comment]
1) No. As stated, I'm trying to get my ducks in a row. This means that I'm testing some stuff with how feasible it is, and trying to find the time to do it. Lots and lots of changes are taking place, so it may be a while - but there will be a lot more active development happening in the nv5dev branch - so feel free to watch.

2) Yes. No. (In order). The issue ***appears*** to be related to the time periods along with downtime and not accurately detecting state based on when the timeperiods start after a state change has already occured. If that makes. If it doesn't - well that's kind of the reason I didn't fix it :)

**Comment by hedenface** [comment]
I'm going to keep the issue open for my own accountability - but I did look back into it - to no avail (heh - get it?).

**Comment by jomann09** [comment]
I'm picking this one up, this actually seems to be related only to downtime scheduled/unscheduled relationship. I made a couple changes on a test box that seemed to fix non-OK states, and looking into what to do about OK states.

The way the avail.cgi works when it comes to parsing is that it goes through each event and sets the event state to whatever it believes the state currently is during the event, then it goes through all the downtime states (start -> end) and computes durations, adding those to the state scheduled duration.

Due to the is, like Bryan mentioned, it does not know the proper state. Not only does it not know what duration and state to place the "scheduled" time in, there is also an issue on setting OK state time into scheduled/unscheduled.

**Comment by degre** [comment]
Hi @jomann09 ,

thanks for the update. But what does this mean in detail, I mean: How can I fix that behaviour or when is this likely to be fixed by Nagios?

**Comment by jomann09** [comment]
Sorry it was really late last night I didn't have time to update this issue. I believe I have a fix for this in the `avail-downtime-fixes` branch if you'd like to try it out. We are testing it internally right now.

**Comment by degre** [comment]
hmm... probably a silly question, but where do I find the "avail-downtime-fixes"-branch and what do I need to do in order to deploy that fix? :-?
Considering your latest tag, this bug is supposed to be fixed in 4.4.4. If that's correct I can also just wait, as this is the next minor release that's going to be built...

Many thanks in advance,
Dennis

**Comment by jomann09** [comment]
That is the next minor release, so you can wait if you'd like. It also probably should undergo a bit more testing before I feel confident there are no bugs.

If you'd like to try it though, and you're using standalone Core (not Nagios XI) it should be pretty easy to re-build using the branch zip file. You can download the branch here: https://github.com/NagiosEnterprises/nagioscore/archive/avail-downtime-fixes.zip and you'd unzip it and compile it like a normal release:
`./configure && make all && make install`

**Comment by degre** [comment]
Many thanks for your feedback, which is much appreciated. I'll wait for the next official minor release though.

**Comment by jomann09** [comment]
That works, I don't think it'll be more than a month until the next release, maybe sooner.

Closing this, done with testing and merged into `maint`.
