### ISSUE TITLE
segfault in nagios 4.3.2 (workers.c)

### ISSUE THREAD

**Issue by sq5bpf** [NagiosEnterprises/nagioscore#386]
i'm migrating a configuration from nagios 3.0.6 to nagios 4.3.2 on debian 9 x86_64. unfortunately the nagios process crashes after a few minutes. 

there is an obvious bug in base/workers.c :

```
static int get_job_id(struct wproc_worker *wp)
{
        return wp->job_index++;
}

static void fo_reassign_wproc_job(void *job_)
{
        struct wproc_job *job = (struct wproc_job *)job_;
        job->wp = get_worker(job->command);
        job->id = get_job_id(job->wp);
        /* macros aren't used right now anyways */
        wproc_run_job(job, NULL);
}
```

note that there is no checking of the return value of `get_worker()`, so if it returns a null pointer, then  `wp->job_index++` in `get_job_id()` will segfault. btw in other places in the code this check is present.

```
static struct wproc_worker *get_worker(const char *cmd)
{
        struct wproc_list *wp_list;

        if (!cmd)
                return NULL;

        wp_list = get_wproc_list(cmd);
        if (!wp_list || !wp_list->wps || !wp_list->len)
                return NULL;

        return wp_list->wps[wp_list->idx++ % wp_list->len];
}
```

in my case a NULL is received because `wp_list->len == 0 `

i haven't yet figured out how the workers thing works, but i've tried to do a naiive patch to `fo_reassign_wproc_job()`:

```
static void fo_reassign_wproc_job(void *job_)
{
        struct wproc_job *job = (struct wproc_job *)job_;
        job->wp = get_worker(job->command);
if ( job->wp) {
       job->id = get_job_id(job->wp);
        /* macros aren't used right now anyways */
        wproc_run_job(job, NULL);
} else {
logit(NSLOG_RUNTIME_WARNING, TRUE, "wproc: can't get_worker() in fo_reassign_wproc_job\n"); 
/* probably should do some clever cleanup here, but don't know how */
}
}
```

this does prevent the crash, but the jobs aren't ran:

after some:
wproc: iocache_capacity() is 0 for worker Core Worker 32343.
wproc: Socket to worker Core Worker 32343 broken, removing
i get:
wproc: can't get_worker() in fo_reassign_wproc_job (repeated for many lines)
Unable to run check for service 'xxxxxxxxxxxxxxxxxxxxxx' on host 'host1'
Unable to run check for service 'yyyyyyyyyyyyyyyyyyyyyy' on host 'host2'
etc....

since the workers have died i have some zombie processes, mostly check_ping

looking at bug reports on the internet, there are reports of crashes of the nagios process after messages about iocache_capacity. usually there is no followup.

this is not one bug:
- there is a bug in the lacking null pointer check
- there is a bug because the workers die (haven't checked why yet)

i have yet to investigate why the workers are dying. the some plugins which we use haven't been migrated yet, and some of them will exit with an error, while others will stall for a long time, which probably causes the workers to die. i've tried to simulate the crash with sleep 60000 for the plugins, but that works correctly. unfortunately i can't share the configuration, since it contains details of our internal hosts. 

do you have any ideas how to debug or fix the worker problem?

**Comment by hedenface** [comment]
Well, based on the information you presented, it seems that the problem is either in `get_worker` or `get_wproc_list`. It's returning `wp_list->wps[wp_list->idx++ % wp_list->len]` which seems like it should be fine, but I'm guessing the possibility of that being NULL shouldn't have any bearing on the `get_job_id`. 

In short: I have no idea.

But I will replicate and find a solution. We'll schedule this for the next bugfix release.

**Comment by sq5bpf** [comment]
it's in get_worker() 

in get_worker() get_wproc_list() returns a valid pointer. the if() fires because wp_list->len equals 0

any idea why a worker might die?

**Comment by hedenface** [comment]
I don't have any idea, but the patch you suggested seems reasonable. I'm not particularly sure off the top of my head of what has changed from 3.0.6 to 4.3.2 other than ***A LOT*** of stuff. What happens if you switch out the configuration files with the samples ones provided? Do any segfaults occur then?

I'm in the process of compiling on one of my Debian9 machines, so hopefully I can replicate this soon.

**Comment by hedenface** [comment]
I am unable to reproduce the issue, officially. Perhaps you can supply me with a sanitized configuration?

**Comment by hedenface** [comment]
Fixed (for me anyway) in: https://github.com/NagiosEnterprises/nagioscore/commit/a9656bce5b468718e7edd05dfa80ba1aad7ad2cf

**Comment by sq5bpf** [comment]
i can confirm that this bug seems fixed in 4.3.4.  thanks!

sorry, i couldn't supply our internal config. one thing that i did notice is that one of the plugins reported:
Current Status:	
  CRITICAL  
 (for 17d 18h 32m 51s)
Status Information:	(Return code of 255 is out of bounds : (No output on stdout) stderr: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@))
this is from 4.3.4, i didn't have this on 4.3.2. maybe some pattern of data on stderr caused the worker to die.

**Comment by hedenface** [comment]
@VMike1 What version of Core were you using?

**Comment by VMike1** [comment]
My version is 4.3.4

**Comment by hedenface** [comment]
Can you see if you can replicate the same in the current maint branch?

**Comment by VMike1** [comment]
Hello!
Sorry for delay.

I have 4.4.1 only in test environment without high load. I wasn't able to reproduce the problem with zombies in it.
