### ISSUE TITLE
Additive Inheritance does not test for duplicates

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#392]
I saw this recently when looking at a host definition in `objects.cache`:

```
        contacts nagiosadmin,nagiosadmin
        contact_groups admins,admins,admins
```

It seems that when you use multiple templates that all have additive defined, there is no checking to see if an object is already defined (when building the final config).

You can easily replicate with these configs:
```
define host {
	name template_one
	contacts +nagiosadmin
	contact_groups +admins
	register 0
	}

define host {
	name template_two
	contacts +nagiosadmin
	contact_groups +admins
	register 0
	}

define host {
	use template_one,template_two,linux-server
	host_name test_host_multiple_templates
	address 127.0.0.1
	}
```

The `linux-server` template only has contact_groups defined, this is why admins appears three times.

When using the JSON API there are similar results:

https://core-015/nagios/cgi-bin/objectjson.cgi?query=host&hostname=test_host_multiple_templates
```
      "contact_groups": [
        "admins",
        "admins",
        "admins"
      ],
      "contacts": [
        "nagiosadmin"
      ],
```

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/commit/435b287c7732c572ef805bf714703015b3a9e20e
