### ISSUE TITLE
Makefile - make-webconf could be improved

### ISSUE THREAD

**Issue by jrdalrymple** [NagiosEnterprises/nagioscore#40]
It might be nice to do some version checking and copy a separate http/conf.d/nagios.conf based upon the Apache version:

This fellow kindly provided a pretty good looking example.

http://support.nagios.com/forum/viewtopic.php?f=34&t=32789

**Comment by tmcnag** [comment]
The shell command

`httpd -v | grep -oP "([0-9]{1,}\.)+[0-9]{1,}"`

will detect the Apache version, at least on systems where it is named `httpd` - Debian and friends will need to use `apache2` or `apache3` if they're up that high.

From here I am not sure if it is better to maintain separate Apache configs named `<version>.conf` or use some autoconf magic to fill in proper settings based on a template.

**Comment by jfrickson** [comment]
Changes applied to the 4.1.0rc3 and maint branches
