### ISSUE TITLE
MAX_LONG_PLUGIN_OUTPUT not actually consulted/docs incorrect about long_plugin_output length limit

### ISSUE THREAD

**Issue by zcarlson-signifai** [NagiosEnterprises/nagioscore#400]
According to [Nagios Core Plugin API](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/pluginapi.html):

> Nagios Core will only read the first 4 KB of data that a plugin returns. This is done in order to prevent runaway plugins from dumping megs or gigs of data back to Nagios Core. This 4 KB output limit is fairly easy to change if you need. Simply edit the value of the MAX_PLUGIN_OUTPUT_LENGTH definition in the include/nagios.h.in file of the source code distribution and recompile Nagios Core. There's nothing else you need to change! 

I read through a few source files and this define is only actually used in one place, which is for reading the nagios status.dat file when compiled for a system not using mmap. 

To confirm, I was able to configure a check that output a little over 16384 bytes of arbitrary data and found it in status.dat again:

```
[root@centos var]# grep long_plugin_output=HI /usr/local/nagios/var/status.dat | wc -c
21865
```

(the output was "HI\n" * 5462 -- the newlines were expanded so each 'chunk' turned into 4 bytes instead of 3)

**Comment by Madlohe** [comment]
Hi, thanks for opening this issue!

This is probably much later than you wanted a response, but I just noticed that this was still open and pretty simple to fix. I've removed that section from the Core documentation. We have several customers now who rely on that functionality being broken, so unfortunately we won't be adding it back in. The website should be updated within the next day or so.
