### ISSUE TITLE
Nagios 4.3.2 not starting anymore --> wproc: 'Core Worker xxx' seems to be choked

### ISSUE THREAD

**Issue by Fr3dY2** [NagiosEnterprises/nagioscore#403]
Hi,

I've been using Nagios v4.3.2 on CentOS 7.3 without problems, but I just rebooted the server after some package updates (including nagios-commons) and it fails to start now. There were some 'needs-restarting' packages, maybe from earlier updates, affecting httpd as well (maybe kernel too).

Now the service is not starting anymore, with the following error messages in nagios.log:
```
[1501162592] SERVICE ALERT: S-JRCSVQFS006P;Volume incremental usage [1 hour max] - Users;OK;SOFT;2;Interval reached (60 minutes) or disk usage reduced, size reset to 3889GB (from 3892GB)
[1501162592] Caught SIGTERM, shutting down...
[1501162592] Caught SIGTERM, shutting down...
[1501162592] wproc: Socket to worker Core Worker 1028 broken, removing
[1501162592] wproc: Socket to worker Core Worker 1029 broken, removing
[1501162592] wproc: Socket to worker Core Worker 1026 broken, removing
[1501162592] wproc: 'Core Worker 1027' seems to be choked. ret = -1; bufsize = 125: written = 0; errno = 32 (Broken pipe)
[1501162592] wproc: Socket to worker Core Worker 1027 broken, removing
[1501162593] Successfully shutdown... (PID=1025)
[1501162593] Event broker module 'NERD' deinitialized successfully.
```

I tried again and it fails again, without the core worker messages:

```
[1501163556] Successfully launched command file worker with pid 4205
[1501163584] HOST ALERT: S-JRCSVQBK002P;DOWN;SOFT;1;CRITICAL - Host Unreachable (139.191.152.38)
[1501163621] SERVICE ALERT: S-JRCSVQBK002P;Cpu_Load;CRITICAL;SOFT;1;connect to address 139.191.152.38 and port 12489: No route to host
[1501163624] HOST ALERT: S-JRCSVQBK002P;DOWN;HARD;2;CRITICAL - Host Unreachable (139.191.152.38)
[1501163646] Caught SIGTERM, shutting down...
[1501163646] Caught SIGTERM, shutting down...
[1501163646] Successfully shutdown... (PID=4200)
[1501163646] Event broker module 'NERD' deinitialized successfully.
```

[root@S-JRCSVQNG001P nagios]# systemctl status nagios.service
```
● nagios.service - Nagios Network Monitoring
   Loaded: loaded (/usr/lib/systemd/system/nagios.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Thu 2017-07-27 15:54:06 CEST; 16s ago
     Docs: https://www.nagios.org/documentation/
  Process: 4199 ExecStart=/usr/sbin/nagios -d /etc/nagios/nagios.cfg (code=exited, status=0/SUCCESS)
  Process: 4196 ExecStartPre=/usr/sbin/nagios -v /etc/nagios/nagios.cfg (code=exited, status=0/SUCCESS)

Jul 27 15:53:41 S-JRCSVQNG001P nagios[4200]: SERVICE ALERT: S-JRCSVQBK002P;Cpu_Load;CRITICAL;SOFT;1;connect to address 139.191.152.38 and port 12489: No route to host
Jul 27 15:53:44 S-JRCSVQNG001P nagios[4200]: HOST ALERT: S-JRCSVQBK002P;DOWN;HARD;2;CRITICAL - Host Unreachable (139.191.152.38)
Jul 27 15:54:06 S-JRCSVQNG001P systemd[1]: nagios.service start operation timed out. Terminating.
Jul 27 15:54:06 S-JRCSVQNG001P nagios[4200]: Caught SIGTERM, shutting down...
Jul 27 15:54:06 S-JRCSVQNG001P nagios[4205]: Caught SIGTERM, shutting down...
Jul 27 15:54:06 S-JRCSVQNG001P nagios[4200]: Successfully shutdown... (PID=4200)
Jul 27 15:54:06 S-JRCSVQNG001P nagios[4200]: Event broker module 'NERD' deinitialized successfully.
Jul 27 15:54:06 S-JRCSVQNG001P systemd[1]: Failed to start Nagios Network Monitoring.
Jul 27 15:54:06 S-JRCSVQNG001P systemd[1]: Unit nagios.service entered failed state.
Jul 27 15:54:06 S-JRCSVQNG001P systemd[1]: nagios.service failed.
```

Another issue I've noticed is the following error message:

`[1501162920] Error: Could not open check result queue directory '/var/nagios/spool/checkresults' for reading.
`

That folder is included in the nagios.cfg file, but it wasn't in the filesystem. Was it deleted somehow?
I just created it but service fails with above messages.

UPDATE: It seems CentOS repository now includes Nagios 4.3.2 officially and it got updated (I was using a compiled version). I'll try to look into it, but this update of the official package over the compiled version broke something and maybe it overwrote my nagios.cfg file...  it seems I've lost the historical alert logs and everything is being checked as for the first time :S

Is it possible to recover my historical alert logs? The /var/log/nagios/archives is populated with files, but from Nagios I can only see updates from today :(

Regards,

**Comment by box293** [comment]
> Is it possible to recover my historical alert logs? The /var/log/nagios/archives is populated with files, but from Nagios I can only see updates from today :(

It sounds like the `log_archive_path=` in your nagios.cfg is not pointing to the correct location.

In this sort of scenario it would help if you could roll back your server to a backup before this happened. Installing a repo over a compiled can add all sorts of problems.

If this is not possible, I've had to fix a similar issue before and the steps you would need to follow are:

- Take copies of all config files and files / directories referenced by nagios.cfg
- Uninstall the repo install of Nagios via yum
- Re-install nagios from source
- Replace your original nagios config files you took a backup of
- cross fingers

Hopefully you at least have a copy of your nagios.cfg in a backup as this may have been overwritten by the repo install.

**Comment by Fr3dY2** [comment]
The log_archive_path points to the correct folder, but somehow it's not working for retrieving past alerts.
Anyway, Nagios is working again so I'll go on like this - I already locked current version with yum to avoid updating from repositories.



Thanks,
