### ISSUE TITLE
Command worker fails to handle SIGPIPE

### ISSUE THREAD

**Issue by vdarulis** [NagiosEnterprises/nagioscore#41]
In a loaded Nagios server, a process can write an external command and terminate before it gets a response back. So the write call in https://github.com/NagiosEnterprises/nagioscore/blob/master/base/commands.c#L222 will cause a SIGPIPE that is not handled:
```
Program received signal SIGPIPE, Broken pipe.
0x00007fe4d18bffd0 in __write_nocancel () at ../sysdeps/unix/syscall-template.S:82
82  in ../sysdeps/unix/syscall-template.S
(gdb) bt
#0  0x00007fe4d18bffd0 in __write_nocancel () at ../sysdeps/unix/syscall-template.S:82
#1  0x00007fe4d22e5eb1 in command_file_worker (sd=47) at commands.c:222
#2  launch_command_file_worker () at commands.c:290
#3  0x00007fe4d22d274f in main (argc=<optimized out>, argv=<optimized out>) at nagios.c:787
(gdb)
```
After handling the signal in debugger with `(gdb) handle SIGPIPE nostop noprint pass` to continue execution, things are working as normal - command worker should really handle a failing write() call back to client.

**Comment by jfrickson** [comment]
Issue is fixed in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-beta
