### ISSUE TITLE
On demand host check isn't executing with underlying service is in alarm

### ISSUE THREAD

**Issue by gtyr** [NagiosEnterprises/nagioscore#410]
Nagios 4.3.5 - The on demand host check is not executing with the underlying service is in non OK state. In release 4.2.4 it is working as expected. Replication: Use the attached cfg files on a stock 4.3.5 installation. The host check will not execute when the service times out.
[nagi_cfg.tar.gz](https://github.com/NagiosEnterprises/nagioscore/files/1218149/nagi_cfg.tar.gz)

**Comment by ludmilmm** [comment]
I was also able to recreate the problem on one of my test boxes. The issue has been described on the Nagios Support forum here: https://support.nagios.com/forum/viewtopic.php?t=44974#228398

**Comment by jogendrajangid1** [comment]
Facing the same issue. is there any timeline for 4.4.0 release?

**Comment by gtyr** [comment]
jogendrajangid1, I was able to workaround this by modifying the source with the link below and recompiled.

[https://github.com/NagiosEnterprises/nagioscore/commit/5430ccace894a6c813fdd7f2f9ea79ea93371d32](url)

**Comment by jogendrajangid1** [comment]
Thanks, @gtyr

**Comment by gtyr** [comment]
@jogendrajangid1 

I compiled and installed a git clone from today, this appears to be working as it should.

**Comment by hedenface** [comment]
This appears to be fixed based on my testing in the current 4.4.0 branch. @gtyr @jogendrajangid1 @ludmilmm Go ahead and ping me to re-open it if you find that isn't the case. Thank you!
