### ISSUE TITLE
Add a standard macro for a hosts current "notifications enabled" setting

### ISSUE THREAD

**Issue by ethangrinnell78** [NagiosEnterprises/nagioscore#419]
Hello,

I recently had the need to have a Nagios event handler know whether a hosts notifications were enabled or not. It seems that there is not an easy to accomplish this at the moment. See this thread for reference: https://support.nagios.com/forum/viewtopic.php?f=7&t=45245

It's be super if there were an easier way to obtain this information other than the curl method that was suggested in that post. I'll probably still try something like that in the mean time, but I'm all for simpler methods if possible.

Thank you!
Ethan Grinnell

**Comment by hedenface** [comment]
I think this is a good idea.

I also think that for the time being to do what you describe in that forum post you could make a plugin wrapper that appends whether the host is enabled/disabled in the output -> and then pass that to the event handler (who then strips that data probably). That should be quick and dirty and get you where you need to be.

We'll take this idea and expand on it - it would be nice to have other basic host/service information available as a macro methinks.

**Comment by ethangrinnell78** [comment]
Absolutely agree. The more information available the better, I'm sure that someone will find a use for it

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nagioscore/commit/03d063b271458976339eb338a8c9f91a55a4540c
