### ISSUE TITLE
openrc-init script variable issue

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#421]
I was testing the `openrc-init` script with 4.3.4 and came across a variable issue.

I install the script with the command:
```
/usr/bin/install -c -m 755 -o root -g root openrc-init /etc/init.d/nagios
```

But Nagios doesn't start:
```
core-043 nagioscore-nagios-4.3.4 # service nagios start
 * Verifying config files ...

Nagios Core 4.3.4
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2017-08-24
License: GPL

Website: https://www.nagios.org
Reading configuration data...
Error: Cannot open main configuration file '/etc/nagios.cfg' for reading!                                      [ !! ]
 * ERROR: nagios failed to start
```

When I look at the `/etc/init.d/nagios` script:
```
#!/sbin/openrc-run

# This is a custom variable, and has the following default value if a
# specific config file is not defined by the user.
: ${NAGIOS_CONFIG:="${prefix}/etc/nagios.cfg"}

# These two facilitate the bindir variable substitution below.
prefix=/usr/local/nagios
exec_prefix=${prefix}
```

It looks like the prefix variable is being referenced on line 5 before it is defined on line 8. If I move line 5 to under line 8 everything works fine and Nagios starts.

@orlitzky Your thoughts ?

**Comment by orlitzky** [comment]
You're right, I'll make a PR in a second. I never noticed because we set sysconfdir to `/etc/nagios` (leaving out $prefix).

**Comment by orlitzky** [comment]
That PR should fix it, but as a workaround, you can pass `--sysconfdir=/usr/local/etc` to the configure script.

**Comment by orlitzky** [comment]
Actually, in your case, it would be `--sysconfdir=/usr/local/nagios/etc`.

**Comment by hedenface** [comment]
PR #422 fixes this. Closing now. Troy, feel free to open it back up if for some reason it didn't fix it for you.

**Comment by box293** [comment]
Great thanks very much, the updated script works fine and so does the` --sysconfdir` option (makes documentation easier to follow).
