### ISSUE TITLE
Servicegroups not able to handle more than 1000 services

### ISSUE THREAD

**Issue by lizhi1989** [NagiosEnterprises/nagioscore#423]
I'm trying to group same type service from different host into one.
The servicegroup is able to handle 900+ services, anything more than 1000, it goes back not configured and without error msg.

**Comment by hedenface** [comment]
What version of Core are you using? What operating system are you using? What architecture are you on? Which Core addons are you using?

**Comment by jomann09** [comment]
Closing this since there's been no update for 1+ year
