### ISSUE TITLE
Incorrect sample config in timeperiods.cfg

### ISSUE THREAD

**Issue by thepony100** [NagiosEnterprises/nagioscore#426]
In 24x7_sans_holidays timeperiods. I think "use us-holidays" should be "exclude us-holidays" instead to cover every day and exclude holidays correctly.

**Comment by hedenface** [comment]
It doesn't look incorrect to me:

`24x7_sans_holiday`  is using every single day from midnight to midnight, and the template (timeperiod) it's using (`us-holidays`) has the specific days blocked off.

Did something not work for you recently?

**Comment by box293** [comment]
This is a great example of how flexible nagios and it's configurations can be.

@hedenface is correct.

One tip I can give you when trying to understand what is and isn't being applied when `use` is used ... look at `objects.cache`, this shows you the final config that is created.

Here is your example in `/usr/local/nagios/var/objects.cache`:
```
define timeperiod {
        timeperiod_name 24x7_sans_holidays
        alias   24x7 Sans Holidays
        december 25     00:00-00:00
        july 4  00:00-00:00
        january 1       00:00-00:00
        thursday 4 november     00:00-00:00
        monday 1 september      00:00-00:00
        monday -1 may   00:00-00:00
        sunday  00:00-24:00
        monday  00:00-24:00
        tuesday 00:00-24:00
        wednesday       00:00-24:00
        thursday        00:00-24:00
        friday  00:00-24:00
        saturday        00:00-24:00
        }
```

I will admit though that looking at the Nagios Core documentation it is not clear that `00:00-00:00` means to exclude the entire day, I think that needs some clarification.

**Comment by thepony100** [comment]
Oh, sorry. It's my mistake. I misunderstood "us-holidays" time period. At first glance at the "us-holidays", I thought that it just only lists US holidays not exclude it. So I came to that conclusion.

Nagios works great for me. I only use template as a guideline. So nothing wrong here.
