### ISSUE TITLE
host alias filed missing from status.dat

### ISSUE THREAD

**Issue by oraclesod** [NagiosEnterprises/nagioscore#435]
Unable to pull alias field from the status.dat the field is missing for hosts

Tested with Nagios Core 4.3.4

**Comment by tmcnag** [comment]
Not sure I can consider this a bug.  I see the same behavior, but `status.dat` is for status, and all that is needed to uniquely identify the host is the `host_name` field.  There is no need to include other fields.  If you need to find the alias, look in `objects.cache`.

I also don't believe the `alias` field was ever present in `status.dat`, and if so this could not be considered a bug on those grounds.

Recommend closing.
