### ISSUE TITLE
nagios core issue version 4.3.4 while starting nagios service

### ISSUE THREAD

**Issue by linuxgambler** [NagiosEnterprises/nagioscore#436]
I am getting error: Starting nagios:ERROR: Could not create or update '/usr/local/nagios/var/nagios.configtest' while starting nagios service I have given read/write/exec permission to /usr/local/nagios. Also when I perform config test it is passed successfully.

**Comment by box293** [comment]
What operating system do you have it installed on?

How did you install it, did you follow a specific guide?

**Comment by linuxgambler** [comment]
I am using Ubuntu 14.04. Have followed this [https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source.html#Ubuntu](Docs).

I have figured out the issue. The issue is that nagios init script requires shell for nagios user. So we have modified the init script accordingly and issue is resolved.

**Comment by box293** [comment]
Thanks for telling us the resolution, I'll replicate your issue and then create a KB article that explains the issue and solution.
