### ISSUE TITLE
Service Status Totals zero when wildcard searching

### ISSUE THREAD

**Issue by MHP47** [NagiosEnterprises/nagioscore#438]
Not a big problem, and understand it will get low priority, just raising it simply for the fact of finding it.

Using the "Quick Search:" bar on the left, when wildcard searching with and asterisk, the "Service Status Totals" at the top of the page are all zero. Doesn't seem to matter if the search returns 1 or multiple hosts. Limited search to a single host, without asterisk, "Service Status Totals" is correct, with the asterisk, shows all zeros.

i.e. A host called "abcd"
Using the quick search for "ab" returns as expected. Searching "ab*" returns correct results, but "Service Status Totals" is all zeros.

Running "Nagios® Core™ 4.2.1", so haven't tested with current version, but should be simple for someone to confirm on newer version

**Comment by hedenface** [comment]
Haven't confirmed yet, but added to 4.4.0. If it isn't relevant any longer, I'll update with a comment and close the issue.

**Comment by MHP47** [comment]
@hedenface This can be closed. Has been fixed in the new version: [commit](https://github.com/NagiosEnterprises/nagioscore/commit/89dfd38610af69efde4e56f39c070eb9b21be737)
