### ISSUE TITLE
Race condition in daemon-init.in file

### ISSUE THREAD

**Issue by smooge** [NagiosEnterprises/nagioscore#443]
Downstream bug: 1504814

     remove_commandfile ()
     {
        # Removing a stalled command file, while there are processes trying/waiting to write into it,
        # will deadlock those processes in a blocking open() system call. To allow such processes to
        # die on a broken pipe, the pipe must be opened for reading without actually reading from it,
        # which is what dd does here. To avoid a chicken-egg problem, the pipe is renamed beforehand.
        # In order for the dd to not deadlock when there is no writing process, it is executed in the
        # background in a subshell together with an empty echo to have at least one writing process.
        
        # see http://unix.stackexchange.com/questions/335406/opening-named-pipe-blocks-forever-if-pipe-is-deleted-without-being-connected
        
        if [ -p $NagiosCommandFile ]; then
                mv -f $NagiosCommandFile $NagiosCommandFile~
                (dd if=$NagiosCommandFile~ count=0 2>/dev/null & echo -n "" >$NagiosCommandFile~)
        fi
        
        rm -f $NagiosCommandFile $NagiosCommandFile~
     }

While this does work in the test example in the unix exchange article, it seems to be racy in the real world with the process stopping if programs like nagiosgraph are connected to the pipe.  In asking more experienced Unix admins, this was to be expected because the other items attached to the pipe may race with the dd instead of kill it.

**Comment by beckit** [comment]
I've submitted a pull request to fix this.  Its a deceptive little shell call with squiggly lines so I explained what's going on over in the unix.stackexchange.com post.

**Comment by hedenface** [comment]
Thanks @beckit I'll take a look!

**Comment by hedenface** [comment]
https://github.com/NagiosEnterprises/nagioscore/commit/ffd976293fd11aef916e6eb19f924f71b6ec3761

https://github.com/NagiosEnterprises/nagioscore/commit/e8d448e04af3e95cc2613791f4b4189c1ac75a40

Fixed in maint above, and then merged into 4.4 as well. Thank you!
