### ISSUE TITLE
failed DNS not being picked up as down host, causing Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#444]
This is related to internal support TicketID=21964.

The DNS issues manifest themselves in the notification system.

At this time, I believe the issue is related to PHP file permissions, but I told the customer I would file a bug, so here I am.

**Comment by hedenface** [comment]
For those without the ability to view our internal tickets, the bug seems like this:

1. User imports (using Nagios XI) lots of hosts/services
2. Hosts/services use FQDNs
3. FQDNs are invalid, as they no longer have proper DNS
4. ???
5. ***SEGFAULT***

The **super cool** thing about it, is that there is nothing indicative of failure in the logs, with any level of debugging enabled.

**Comment by douglasawh** [comment]
This just came in via the same ticket ID as before:

> Found something interesting to add to this earlier issue... So far everything was working as expected.. Moved to a new server to start building it out and the earlier problem started again.
> So I got rid of all the DNS non-responsive hosts and it persisted.
>  
> We have our hosts separated as Linux and Windows.. I had made some changes to the Windows Host Templates where I had a single contact under the Alert Settings to send an email if the host was down.
> Under our Unix Host Templates I had a contact group set under Alert Settings..
>  
> I noticed that the Unix hosts were failing and then the nagios server would go down on SEGV/11 like before, but the Windows servers were not taking down the server!!
> So I set the Unix Template top have individual contacts instead of a single contact group and they too started working and not killing the server like before..

**Comment by hedenface** [comment]
Would be nice to know what the contents of the contact group vs the individual contacts had. Any possibilities with obtaining that data?

**Comment by hedenface** [comment]
I can't reproduce this issue based on the current information.
