### ISSUE TITLE
Performance Chart XML <UNIT> is populated as "%%" for the percentage values after upgrade

### ISSUE THREAD

**Issue by HireChrisJohnston** [NagiosEnterprises/nagioscore#449]
After upgrade from 5.4.9 to 5.4.11 performance charts are presenting the percentage unit as "%%" when performance data of the plugin is specifying "%" as unit. This is true for all plugins that use % as a unit of measure including the ones that come with Nagios XI. 

Example performance string: 'label'=23.5%;70;90;0;100
Results in performance charts to show values as "%%"

RRD XML file indicates <Unit>%%</Unit>
This occurred immediately after upgrade to 5.4.11
Caused most likely by the recent change to performance chart unit handling . [TPS#12504]

**Comment by hedenface** [comment]
The issues here are for Nagios Core, not XI. That said, I've added the bug into our internal tracker and we'll look into it. Thanks!
