### ISSUE TITLE
Availability reports cannot be downloaded in CSV OUTPUT [Mozilla Firefox]

### ISSUE THREAD

**Issue by ShadowofReason** [NagiosEnterprises/nagioscore#452]

**Comment by ShadowofReason** [comment]
Firefox offers you to download avail.cgi instead of the .csv file...

Doesn't appear to happen with Chrome

**Comment by ShadowofReason** [comment]
*bump*

**Comment by hedenface** [comment]
What version of apache/nginx? What operating system is Nagios running on? Which version of Firefox are you using? What operating system is your browser on? Is the Chrome download fine? Did you investigate any headers by chance - if so what are the differences between Chrome and Firefox?

**Comment by ShadowofReason** [comment]
Hi.

I'm using apache 2.4.10-10+deb8u11.
Nagios is running on Debian 8.9.
I was using the latest version of Firefox.
I tested Firefox on Mac OS X Sierra, Windows 7 and Windows 10. 
Chrome download is fine on all OS's...

I also tried it with another nagios (latest version) setup. Same issue.

Unfortunately I didn't investigate any headers because I simply don't know how do check them on firefox. 

You'll be able to recreate it with firefox. 

Steps: 
Availability => Type: hosts => ** ALL HOSTS ** => Tick CSV Output => Create Availability Report!

**Comment by hedenface** [comment]
Huh. That is weird. You're right. But the data is valid. I'll take a look into it now.

**Comment by hedenface** [comment]
Actually, it happened to me in Chrome as well.

**Comment by hedenface** [comment]
Fixed in 6f7746c5ce95a06596888ce8ff8731c4bac81bb4 for 4.4.0
