### ISSUE TITLE
Contact notification failure action

### ISSUE THREAD

**Issue by MHP47** [NagiosEnterprises/nagioscore#453]
Is it possible to take an action on failure to notify a contact? By this I mean, a contact is defined with some command as its service_notification_options value. Executing that command to alert the contact fails; this is logged to the main log file as an error (providing appropriate level of logging is enabled), but is there any way to take action on this, to possibly run a backup notification method?

Reason for asking is trying to make sure that notifications are always captured somehow. If contact_1 is configured to be alerted via an SMS gateway, for example, but the service is down, the alert will fail. Having a "backup" alert via email would be nice, but of course email could be unavailable as well, because the whole network might be down... And down the rabbit hole we go...

**Comment by hedenface** [comment]
I don't think I quite understand. You want Nagios to perform a check on whether or not the notification message was sent successfully?

**Comment by MHP47** [comment]
Not a check, per se. 

If a contact notification command fails, it logs it to the nagios.log only. Is there anyway to capture this and take action? Without having to resort to a log scraper that watches for failures

**Comment by tmcnag** [comment]
My two cents:

It seems a bit of an overreach for Nagios to interfere here more than logging.  There are an almost unlimited number of actions that *could* be taken in this scenario, one of them being logging.  Someone else might want us to fall back to SMS, or SNMP trap, or smoke signal if a notification command fails, and we can't possibly cover every preference.

I think that logging is sufficient if for no other reason than the slippery slope argument.  At what point does Core have to trust the user to configure things properly?  This is a bit different than a startup-time config check for things like services without hosts, which for obvious reasons needs to exist.

To play Devil's Advocate, I could point to the fact that when a plugin fails (returns something outside of 0-3) then the status is shown as such, however all that is really doing is logging the failure as the status output.

I would argue that if you need this level of resiliency, then your notification script should do the error-checking, and then can handle the fallback appropriately.  Plugins do the same thing internally, notification scripts should be no different.

**Comment by hedenface** [comment]
I'll chime in with @tmcnag on this.

Would it be possible? Yes.

What would the configuration look like? I am assuming something like:

```
define service {
   contacts someguy
   contacts_method regular-method
   contacts_failed_1 someotherguy
   contacts_failed_1_method some-other-method
}
```

Or something similar - but I think with a bit of advanced scripting on the Nagios admin's part, this can already be done without crufting up the configurations and making things much more difficult.

I'll concede at the sight of a compelling argument (it definitely could be useful, I'll give you that), or if you want to develop it while making it easy to use and understand (don't forget the documentation :) !) - then I would also ***definitely*** concede and merge it. Otherwise, I'm closing it now.
