### ISSUE TITLE
Documentation bug: example config should reflect realistic values

### ISSUE THREAD

**Issue by JoeJasinski** [NagiosEnterprises/nagioscore#456]
This is a bit of a nitpick, but tripped me up in a production situation after upgrading to a newer version of Nagios. The example configuration for linux-server is set to notify only during workhours with an interval of 120 minutes and a max_check_attempts set to 10. This doesn't seem to reflect good defaults for something called "linux-server" (which to me would be something you'd often want to have up all the time and alerting very noisily).  Perhaps it would fit better if the host template were named "linux-server-non-critical". 

I know these configs are just examples of how you can configure Nagios, but they are also installed by default and immediately available for extending. Its easy to forget to override these defaults. I think it would make more sense to tailor the examples more closely to how Nagios would be used in production. 

```
define host{
	name				linux-server	; The name of this host template
	use				generic-host	; This template inherits other values from the generic-host template
	check_period			24x7		; By default, Linux hosts are checked round the clock
	check_interval			5		; Actively check the host every 5 minutes
	retry_interval			1		; Schedule host check retries at 1 minute intervals
	max_check_attempts		10		; Check each Linux host 10 times (max)
        check_command           	check-host-alive ; Default command to check Linux hosts
	notification_period		workhours	; Linux admins hate to be woken up, so we only notify during the day
							; Note that the notification_period variable is being overridden from
							; the value that is inherited from the generic-host template!
	notification_interval		120		; Resend notifications every 2 hours
	notification_options		d,u,r		; Only send notifications for specific host states
	contact_groups			admins		; Notifications get sent to the admins by default
	register			0		; DONT REGISTER THIS DEFINITION - ITS NOT A REAL HOST, JUST A TEMPLATE!
	}
```

https://github.com/NagiosEnterprises/nagioscore/blob/master/sample-config/template-object/templates.cfg.in#L74

**Comment by hedenface** [comment]
I understand your point - but I don't know if I agree. I can go either way on the issue. Some organizations like to not have their staff notified outside of work hours, and some like to bug them all the time. Some organizations like to not have noisy servers - some do. It really all depends on where you're at, I think.

That being said, I'm open to other possibilities - why don't you throw some examples together and submit a Pull Request? We can let the community decide what they like!

**Comment by tmcnag** [comment]
I agree with @JoeJasinski in that the examples could be more in touch with reality.  While we can't know what each and every organization will want, I think the responsible thing to do here is set it closer to a 1-hour interval.  To take it to extremes, if we had it notify every second they would at least be very well aware, and if we had it notify every year they would have no idea.

**Comment by JoeJasinski** [comment]
@hedenface @tmcnag thank you for the feedback. 

I agree that everyone may have different opinions on what should be set here.  (And I'm only really familiar with my setup, so I haven't seen a ton of configs.)

The settings for windows-server and generic-switch seem like pretty good defaults. 

    notification_period		24x7 
    notification_interval	30

Perhaps linux-server could be updated to match those, and the comment for linux-server `notification_period` could make reference to the `workhours` timeperiod, so people could easily see how to switch it back to `workhours` if they wanted to. 

I'm happy make a pull request to reflect those changes.
