### ISSUE TITLE
version 3.5 does not support php7

### ISSUE THREAD

**Issue by girgen** [NagiosEnterprises/nagioscore#467]
The fix is trivial, just use explode instead of split. This file does not exist in version 4, and I couldn't find any branch to offer a pull request against, so I'm just posting the patch here:

```
--- html/includes/rss/rss_parse.inc.orig	2017-12-21 16:55:41.032397000 +0100
+++ html/includes/rss/rss_parse.inc	2017-12-21 16:57:40.079068000 +0100
@@ -150,7 +150,7 @@
         // check for a namespace, and split if found
         $ns = false;
         if ( strpos( $element, ':' ) ) {
-            list($ns, $el) = split( ':', $element, 2); 
+            list($ns, $el) = explode( ':', $element, 2); 
         }
         if ( $ns and $ns != 'rdf' ) {
             $this->current_namespace = $ns;
```

[patch-html_includes_rss_parse.inc.txt](https://github.com/NagiosEnterprises/nagioscore/files/1655475/patch-html_includes_rss_parse.inc.txt)

**Comment by JasonRivers** [comment]
I'm not sure much will get done about this, Version 3.5 is pretty old now (more than 4 years since it was released), is there a reason why you're still using such an old version?

Nagios4 already runs on PHP7, there's nothing to be done to support it.

**Comment by girgen** [comment]
reasonable.
