### ISSUE TITLE
Status Map icons and online/offline status dots disappear in IE11

### ISSUE THREAD

**Issue by mrDub** [NagiosEnterprises/nagioscore#47]
The Nagios 4.1.0rc1 Status Map icons in Internet Explorer 11 disappear as the map loads.  This is *after* applying the fix discovered by estanley375 (https://github.com/NagiosEnterprises/nagioscore/issues/25).  I have noticed that the `statusmap_icon` directive in the configuration files does not add the images to the map.  Instead, the Status Map seems to use the `icon_image` directive; I don't know if this is intentional behavior or not.

I have `icon_image` directives in the config files, but since there were no icons displaying in IE11, I also added the `statusmap_icon` directive.  Unfortunately, I am still unable to see any icons on the Status Map.  Furthermore, I don't see any of the red/green dots on the map which indicate the host's online/offline status.  I have tried resetting my browser, cleared temporary Internet files, cookies, etc., and unchecked the Compatibility View for intranet sites (I had an issue with this because IE11, by default, throws intranet websites into Compatibility View, and our Nagios server is hosted internally)... but still no luck. IE's Developer Tools has no helpful output either.

Here's the kicker: the images are loaded successfully and display for a brief second as the map expands from a single point into the full web (using the Circular Balloon display).  So I tried to change the map display, and none of them display icons or dots... except for the Circular Markup!  I'm not sure what could account for this difference between the map displays.

I had created a topic on the Nagios Support Forum, which can be referenced for further information: http://support.nagios.com/forum/viewtopic.php?f=34&t=33253

Here is a screenshot of the Circular Balloon display of the Status Map after it has finished loading completely.  There are no icons or online/offline status dots:
![no-icons-2](https://cloud.githubusercontent.com/assets/12850708/8118080/4bd7b220-104a-11e5-97eb-68a058a0dbe1.jpg)

Here is a screenshot of the Status Map as it initially loads.  You can see that the images are successfully called, but disappear when the map finishes loading, as in the screenshot above:
![no-icons](https://cloud.githubusercontent.com/assets/12850708/8118079/4bd5e5d0-104a-11e5-8d88-a918f67832ec.jpg)

Here is a screenshot of the Circular Markup display.  This is the only display that shows the icons:
![no-icons-3](https://cloud.githubusercontent.com/assets/12850708/8118081/4bd805e0-104a-11e5-9653-4ac68e7e5fda.jpg)

**Comment by gperdu** [comment]
I have the same problem using Nagios core 4.1.1: syntax error with angular.min.js:XX:YY
The map "Legacy" is working well
The pb is the same when i use IE 11 or Firefox !

**Comment by jfrickson** [comment]
Fixed with commit https://github.com/NagiosEnterprises/nagioscore/commit/4fbf6d994fca5541089e8730719f79057cab493c in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-beta

**Comment by mrDub** [comment]
Thank you, jfrickson!  I applied the commit and it fixed the issue!
