### ISSUE TITLE
Request: Core CGIs using Livestatus

### ISSUE THREAD

**Issue by delboy1966** [NagiosEnterprises/nagioscore#475]
The core Nagios CGIs are sometimes slow to load pages after requesting information on hosts/services, especially when adding more host and service checks.

I've noticed that the custom pages I have written to pull information out of Nagios using Livestatus are so much quicker.

Having core CGIs, such as extinfo.cgi, cmd.cgi and status.cgi, using Livestatus would speed Nagios up.

**Comment by hedenface** [comment]
You're absolutely right. Unfortunately, we aren't going to be spending the time to rewrite the CGIs to utilize Livestatus, as it is a third party addon and subject to change at any time without our consent.

However, we do have some exciting changes in store for Core5, and the CGIs being re-written to use an in-memory indexed solution is on the radar. Hopefully it makes it into Core5, as the CGIs can definitely use the love.

Thank you for your submission, but I'll be closing it now. Feel free to keep checking the Core5 development status here on GitHub. Once Core4.4 is released, the changes will be merged into the Core5 branch and development for that will commence.
