### ISSUE TITLE
[PATCH] Broken links in Tactical overview

### ISSUE THREAD

**Issue by cejkar** [NagiosEnterprises/nagioscore#48]
There are atleast 6 broken links in Tactical overview. I tried to create a patch in Gist and got its link https://gist.github.com/c789f251fbf560831328.git - but it seems that it is broken, so I do not know, how to send you a patch after switch from Mantis to Github.

**Comment by tmcnag** [comment]
Remove the ".git" from the end of the URL like so:  https://gist.github.com/cejkar/c789f251fbf560831328

**Comment by tmcnag** [comment]
The patch compiles cleanly on 4.1.0rc1.  The links seem to be proper, but I am wondering if they are truly broken or just not expected.  Admittedly they do appear to show more useful info by default.
