### ISSUE TITLE
tac.c has inconsistent `noheader` behavior. 

### ISSUE THREAD

**Issue by mcapra** [NagiosEnterprises/nagioscore#481]
See this thread for a detailed summary:
https://support.nagios.com/forum/viewtopic.php?f=7&t=47448#p244452

Should display_tac_overview have a call to display_info_table in it? This seems inconsistent with how other pages handle `noheader` in the request vars. 

https://github.com/NagiosEnterprises/nagioscore/blob/6f4d98c8eb2b8cbf3440cf3c7538f7e4c32d1fbb/cgi/tac.c#L882

Also, since there is (as far as I can tell) no case in which display_header ever evaluates to TRUE, this code seems useless:

https://github.com/NagiosEnterprises/nagioscore/blob/6f4d98c8eb2b8cbf3440cf3c7538f7e4c32d1fbb/cgi/tac.c#L202-L226

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/commit/1759cfbbd60da4ffe894d36263986ff3bc92bef7.

That was an easy one. Thanks for spelling it out :)
