### ISSUE TITLE
Stopping while startup is in progress can be deterimental

### ISSUE THREAD

**Issue by beckit** [NagiosEnterprises/nagioscore#487]
If a startup is in progress, this happens while the various pids sort themselves out:
[1519026938] wproc: Successfully registered manager as @wproc with query handler
[1519026938] wproc: Registry request: name=Core Worker 2079;pid=2079
[1519026938] wproc: Registry request: name=Core Worker 2083;pid=2083
[1519026938] wproc: Registry request: name=Core Worker 2080;pid=2080
[1519026938] wproc: Registry request: name=Core Worker 2082;pid=2082

however, if a SIGTERM from a "service nagios stop" happens to come along at the right time, it can cause the starting and stopping routines to hang, but usually just one or the other (I'll see "sh /etc/init.d/nagios stop"  hanging around in the process list from "ps aux|grep nagios")

The race condition looks like this in the nagios log:
[1519026938] wproc: Successfully registered manager as @wproc with query handler
[1519026938] wproc: Registry request: name=Core Worker 2079;pid=2079
[1519026938] wproc: Registry request: name=Core Worker 2083;pid=2083
[1519026938] wproc: Registry request: name=Core Worker 2080;pid=2080
[1519026938] wproc: Registry request: name=Core Worker 2082;pid=2082
[1519026940] Caught SIGTERM, shutting down...
[1519026942] Successfully launched command file worker with pid 2106

However, to see this, you'll need to have a fixed up init script that can accurately track the nagios pid.  See issue #480 

Versions:
On Centos6 at least, and this is true for the nagioscore/maint as synched today.

**Comment by ccztux** [comment]
Its interesting, an ```strace -f -p ${pid}``` to an leftover: ```/etc/init.d/nagios stop``` process shows the following:
```
Process 28902 attached
open("/usr/local/nagios/var/rw/nagios.cmd~", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
dup2(3, 1)                              = 1
close(3)                                = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

If i change this line:
https://github.com/NagiosEnterprises/nagioscore/blob/11f274b73961d08229029c731087004659bf4538/startup/default-init.in#L182

to:
https://github.com/ccztux/nagioscore/blob/b5b1282804fd2219a677ecf14f3af3819a05529e/startup/default-init.in#L196


It doesnt happens any more on my system. The relevant part of this change seems to be to start the hole subshell in background. I have changed dd to read because i am a friend of using shell internals.

**Comment by ccztux** [comment]
Test without patch:
```
for i in {1..100} ; do service nagios restart ; done
```

Leftover procs found:
```
15:21:48 [root@nagios4]:/usr/local/src/nagioscore# ps aux | grep nagios | grep stop
root      9643  0.0  0.1 108480   820 pts/0    S    15:21   0:00 /bin/sh /etc/init.d/nagios stop
root      9791  0.0  0.1 108480   820 pts/0    S    15:21   0:00 /bin/sh /etc/init.d/nagios stop
root     11005  0.0  0.1 108480   824 pts/0    S    15:21   0:00 /bin/sh /etc/init.d/nagios stop
root     11464  0.0  0.1 108480   824 pts/0    S    15:21   0:00 /bin/sh /etc/init.d/nagios stop
root     12826  0.0  0.1 108480   816 pts/0    S    15:21   0:00 /bin/sh /etc/init.d/nagios stop
root     12905  0.0  0.1 108480   824 pts/0    S    15:21   0:00 /bin/sh /etc/init.d/nagios stop
root     14119  0.0  0.1 108480   820 pts/0    S    15:21   0:00 /bin/sh /etc/init.d/nagios stop
```




Test with patch:
```
for i in {1..100} ; do service nagios restart ; done
```

No leftover procs found:
```
15:19:43 [root@nagios4]:/usr/local/src/nagioscore# ps aux | grep nagios | grep stop
15:20:56 [root@nagios4]:/usr/local/src/nagioscore# 
```

**Comment by hedenface** [comment]
With the most current init script this is no longer an issue. If someone can get it to go back to hanging (more than the 1.5 seconds specified as timeout for the iobroker) please re-open a new issue.
