### ISSUE TITLE
Status.cgi Segmentation fault viewing hostgroups/problems

### ISSUE THREAD

**Issue by egreenspan2** [NagiosEnterprises/nagioscore#489]
[nagios_core.zip](https://github.com/NagiosEnterprises/nagioscore/files/1781515/nagios_core.zip)

status.cgi get faults when attempting to click "all problems" under a host or service group.

Running Centos 7, 64bit
Nagios Core: Version 4.3.4
VM self install environment.
Attaching ABRT/core files

To recreate the problem on cli:

export REQUEST_METHOD=GET
export QUERY_STRING="navbarsearch=1&hostgroup=hg_name_here&style=detail&servicestatustypes=28&hoststatustypes=15"
export REMOTE_USER=username_here

./status.cgi 
Cache-Control: no-store
Pragma: no-cache
Refresh: 90
Last-Modified: Mon, 05 Mar 2018 15:34:30 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-type: text/html; charset=utf-8

<html>
<head>
<link rel="shortcut icon" href="/nagios/images/favicon.ico" type="image/ico">
<title>
Current Network Status
</title>
<link rel='stylesheet' type='text/css' href='/nagios/stylesheets/common.css' />
<link rel='stylesheet' type='text/css' href='/nagios/stylesheets/status.css' />
<LINK REL='stylesheet' TYPE='text/css' HREF='/nagios/stylesheets/nag_funcs.css'>
<script type='text/javascript' src='/nagios/js/jquery-1.7.1.min.js'></script>
<script type='text/javascript' src='/nagios/js/nag_funcs.js'></script>
<script type='text/javascript'>
$(document).ready(function() {
$('#top_page_numbers').append($('#bottom_page_numbers').html() );
});
function set_limit(url) { 
this.location = url+'&limit='+$('#limit').val();
  }
</script>
</head>
<body class='status'>

Segmentation fault (core dumped)

**Comment by hedenface** [comment]
Are you able to test this with the current master branch and compile from source?

**Comment by hedenface** [comment]
Oooo - I spoke too soon. Confirmed.

**Comment by hedenface** [comment]
If you get rid of the `navbarsearch=1` does it still occur?

**Comment by hedenface** [comment]
Also, for anyone else trying to run CGIs from the command line, you can also execute them via the following method:

```
REMOTE_USER=nagiosadmin REQUEST_METHOD=GET QUERY_STRING="hostgroup=linux-servers&style=detail&servicestatustypes=28&hoststatustypes=15&navbarsearch=1" /usr/local/nagios/bin/status.cgi
```

If you're adding valgrind, do it after QUERY_STRING="" but before the cgi in question. Obviously, change your paths and values to what they need to be :)

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/commit/f09af9eb43f2c8dc0317e3dc3722816eea7f7347

**Comment by egreenspan2** [comment]
Thank you!
