### ISSUE TITLE
Broken availability report for host in a scheduled downtime 

### ISSUE THREAD

**Issue by NiksCode** [NagiosEnterprises/nagioscore#490]
I'm attaching two screenshots to this post, the second one shows what filters to choose when running the report. 
Important to know that the host was already in a critical state at the time when I scheduled the downtime. The host had been in a critical state for a few weeks by the time when I scheduled a fixed downtime. 
 During the downtime, the host never changed the state, so it has been in a critical state the whole time.
At the time when I ran the report, the downtime was still active. 

![untitled2](https://user-images.githubusercontent.com/20694095/37305565-dc22af4e-2602-11e8-89de-b3c78dac0e9e.png)
![untitled](https://user-images.githubusercontent.com/20694095/37305572-e2872450-2602-11e8-9084-d48ef1737305.png)

**Comment by jomann09** [comment]
Duplicate of #384
