### ISSUE TITLE
Nagios Core Status: Active: failed (Result: exit code)

### ISSUE THREAD

**Issue by imacher23** [NagiosEnterprises/nagioscore#492]
After successful installation and a restart of the Apache server Nagios flawless. 
After rebooting the operating system I could not access the tab 

Access hosts via the Nagios web interface.
No error messages are displayed

![nagiosservicefailed](https://user-images.githubusercontent.com/37659358/37770232-036f8210-2dd4-11e8-8f9f-05817120df77.PNG)

![reiterhost](https://user-images.githubusercontent.com/37659358/37770793-dcfeca9e-2dd5-11e8-8f81-4e7c7b853ddc.PNG)

![webinterface](https://user-images.githubusercontent.com/37659358/37770809-e4b90844-2dd5-11e8-9c7e-9a79674ac284.PNG)

![check1](https://user-images.githubusercontent.com/37659358/37770818-e8a721a2-2dd5-11e8-93bb-588de3d65874.PNG)

![check2](https://user-images.githubusercontent.com/37659358/37770823-ed217f8e-2dd5-11e8-8ff3-4eebe253f0bb.PNG)

**Comment by box293** [comment]
Can you please upgrade to the latest version.

Not sure what documentation you followed to install:
https://support.nagios.com/kb/article.php?id=96

**Comment by hedenface** [comment]
Did you enable the service to run on boot?

```
sudo systemctl enable nagios
```

**Comment by scottwilkerson** [comment]
Closing as not updated since Mar 22, 2018

**Comment by Saurabh-bisht** [comment]
update-rc.d: error: nagios Default-Start contains no runlevels, aborting.
 getting this error while enabling the nagios service

**Comment by sawolf** [comment]
Hi @Saurabh-bisht,

Your issue doesn't seem to be related to the one listed above. I would recommend either creating a new issue here or opening a thread on [our community support forums](https://support.nagios.com/forum/viewforum.php?f=7). Alternatively, if you have a proposed fix, feel free to open a pull request.
