### ISSUE TITLE
"new" map in Nagios 4.3.4 - "Locate Host On Map" icon shows all hosts on the map

### ISSUE THREAD

**Issue by PepeOnAChair** [NagiosEnterprises/nagioscore#494]
Hello,
today I`ve upgraded Nagios from 4.2.4 to 4.3.4. And I found the same issue as in 4.2.4.

The problem is when I click to "Locate Host On Map" icon (at least in "Service Overview For Host Group" and "Host State Information" page) the new style map doesn`t open to show just the HOST and some of its neighbors, but it always opens to show all the HOSTs.
![map icon which doesnt work](https://user-images.githubusercontent.com/19305232/37874850-3c7dd45c-3037-11e8-86c1-6ebc92e2e78b.JPG)
(I have around 8400 hosts monitored). In left upper corner it says "Network Map for **All** Hosts " even if I clicked to that icon - which should focus the map to host I choosed (as it worked in legacy map).

In my previous version I "solved" that by copying "status.cgi" file from Nagios version 4.0.8. That gave me the legacy map back as the default map (so it worked with the icon "Locate Host On Map").

Am I the only one, who has this kind of problem? Or is it known Nagios issue?
Does anyone know how to fix this?

Thank you in advance.
Pepe from old continent :)
-------------------------------
PS:
- Nagios is running on Debian wheezy
- uname -a
Linux Nagios 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

![new nagios map](https://user-images.githubusercontent.com/19305232/37874851-3f299b50-3037-11e8-9f15-062beb45d7f6.JPG)

**Comment by box293** [comment]
I tried to reproduce your issue so I created 8000 hosts in Nagios Core. I did this on a Core 4.0.8 server as this version was the last one before the new map was added.

I created "localhost1" that was a child of localhost and it had 1000 children. I repeated this 7 more times. Here is the bash script I used:
```
#!/bin/bash
parent=$1
total=$2
objects_dir='/usr/local/nagios/etc/objects/parent_test'
mkdir -p ${objects_dir}
object_file=${objects_dir}/${parent}.cfg
echo "define host{" > ${object_file}
echo "        use                     linux-server" >> ${object_file}
echo "        host_name               ${parent}" >> ${object_file}
echo "        alias                   ${parent}" >> ${object_file}
echo "        address                 127.0.0.1" >> ${object_file}
echo "        parents                 localhost" >> ${object_file}
echo "        }" >> ${object_file}

for i in `seq 1 $2`;
do
        object=${1}${i}
        echo "" >> ${object_file}
        echo "define host{" >> ${object_file}
        echo "        use                     linux-server" >> ${object_file}
        echo "        host_name               ${object}" >> ${object_file}
        echo "        alias                   ${object}" >> ${object_file}
        echo "        address                 127.0.0.1" >> ${object_file}
        echo "        parents                 ${parent}" >> ${object_file}
        echo "        }" >> ${object_file}
done
```

In Core 4.0.8 I go to one of the new host objects and I click the "Locate Host On Map" icon:

![selection_004](https://user-images.githubusercontent.com/8356113/37882578-33e68244-30f0-11e8-996c-8fa17f1e0468.png)

I can see that all 8000 hosts are on the map and the host I clicked is highlighted.

> The problem is when I click to "Locate Host On Map" icon (at least in "Service Overview For Host Group" and "Host State Information" page) the new style map doesn`t open to show just the HOST and some of its neighbors, but it always opens to show all the HOSTs.

I was not able to replicate this on the old version, the behaviour is to show all the hosts.

I then did the same on a Nagios Core 4.3.4 server.

![selection_005](https://user-images.githubusercontent.com/8356113/37882672-236d9f96-30f1-11e8-9f09-45ac74993ea4.png)


> In left upper corner it says "Network Map for All Hosts " even if I clicked to that icon - which should focus the map to host I choosed (as it worked in legacy map).

I can see the same thing here, this might be a bug as the legacy version would show "Network Map For Host xxxxx". 

If I use the horizontal icons at the top right corner I can change the root node to be the desired host, which changes the map layout to:

![selection_006](https://user-images.githubusercontent.com/8356113/37882736-a1d6b9a8-30f1-11e8-9392-426be5ff0335.png)

I'll have a look at the code to see what is going on here.

Also you might find this KB article useful:
https://support.nagios.com/kb/article/nagios-core-status-map-customization-725.html

**Comment by box293** [comment]
So I was able to fix this easily, it comes down to the URL arguments. When you click "Locate host on map" it goes to the following URL:
```
http://nagios_server/nagios/map.php?host=xxxxx
```
While this does highlight the host on the map, it does not make it the focus. However adding `&root=xxxxx` will make it the focus, for example:
```
http://nagios_server/nagios/map.php?host=xxxxx&root=xxxxx
```
So it's a simple matter of fixing the URL arguments being passed. For an immediate fix this will require editing the source code, recompiling and installing.

Edit the `cgi/extinfo.c` file and locate line 1126:
```
printf("<tr CLASS='command'><td><img src='%s%s' border=0 ALT='Locate Host On Map' TITLE='Locate Host On Map'></td><td CLASS='command'><a href='%s?host=%s'>Locate host on map</a></td></tr>\n", url_images_path, STATUSMAP_ICON, STATUSMAP_CGI, url_encode(host_name));
```

Change the line to this:
```
printf("<tr CLASS='command'><td><img src='%s%s' border=0 ALT='Locate Host On Map' TITLE='Locate Host On Map'></td><td CLASS='command'><a href='%s?host=%s&root=%s'>Locate host on map</a></td></tr>\n", url_images_path, STATUSMAP_ICON, STATUSMAP_CGI, url_encode(host_name), url_encode(host_name));
```
Then execute the following commands:
```
./configure
make all
make install
```

Once this is done the link should now be correct.

We'll get this fixed for the next release.

Here's an example screenshot with only 10 children per 8 parents:

![selection_004](https://user-images.githubusercontent.com/8356113/37884858-c08e11c8-30fd-11e8-8410-065245e27b73.png)

**Comment by hedenface** [comment]
Fixed with https://github.com/NagiosEnterprises/nagioscore/pull/496
