### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#497]
```
4.0.0 - 09/20/2013
------------------
See http://nagios.sourceforge.net/docs/nagioscore/4/en/whatsnew.html for a
list of the changes in Nagios Core 4
```

Need to change the URL to https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/whatsnew.html

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/commit/5fc6124e1d768f8cdef3abe296f000a4741620b9
