### ISSUE TITLE
High CPU Utilization of Nagios core 3.5

### ISSUE THREAD

**Issue by spitterabhi** [NagiosEnterprises/nagioscore#499]
Hi Team,

I am facing high CPU Utilization issue for my nagios core .
My hardware detail is: 40 core CPU
                                    126 GB of Memory
435 host is getting monitored

**Comment by hedenface** [comment]
Can you upgrade? Core 4 handles checks completely differently than core 3. Based on some of the current bugs we're experiencing, I would recommend upgrading to 4.3.0. But any Core 4 version is going to have much better performance than Core 3.

How many total checks do you have? What is "high CPU Utilization"? 80%? What is the cpu load? How much memory is being consumed? What are the disk specifications? What is the operating system?

**Comment by hedenface** [comment]
What is the cpu load? What are the disk specifications?

Are you able to upgrade?

**Comment by spitterabhi** [comment]
Hi,


Please attached screenshot for data requested.

Can we resolve this issue without upgradation.



Regards,
Abhishek Thakur


________________________________

**Comment by hedenface** [comment]
I don't see any screenshot attached.

This area is for reporting bugs, not necessarily general help. I think you'll have better luck over at the support forums where we dedicate resources to help with problems like this:

https://support.nagios.com/forum/

Just my two cents on upgrading: you should do it. Core 3.5 was released in 2013.

**Comment by hedenface** [comment]
Closing this issue.
