### ISSUE TITLE
[PATCH] Too big CPU load on FreeBSD and other systems using poll() interface

### ISSUE THREAD

**Issue by cejkar** [NagiosEnterprises/nagioscore#50]
Please see #668 in Mantis, the patch is included here. However, please do not look at original description, which is false. Please read Notes for correct description.

**Comment by tmcnag** [comment]
Link for reference:  http://tracker.nagios.org/view.php?id=668

**Comment by jfrickson** [comment]
The fix is in branch nagios-maint
