### ISSUE TITLE
Duplicate Downtime ID can occur, causing Downtime start for wrong host and other Downtime problems (Version 4.3.4)

### ISSUE THREAD

**Issue by feisenko** [NagiosEnterprises/nagioscore#506]
Problem: If downtimes are loaded from the retention file, there is a chance that the internal variable next_downtime_id will be set to the highest downtime ID from the retention file and not to the next higher number, as intended.
If this downtime, with the highest number, is in the future and I plan an additional new downtime, this new downtime gets the same ID, then when the start time of either of the two downtimes arrives, it happened that the wrong host was going into downtime. Downtime deletion is also a problem with duplicate IDs.

Supposed cause: I think, I found 2, working together, bugs in common/downtime.c

Proposed program correction:
Bug 1): Because the incoming sequence of IDs from the retention file of e.g. 1,4,3,2 causes next_downtime_id to become 1->5->5->5 , but a sequence of e.g. 1,3,4,2 causes next_downtime_id to become only 1->4->4->4:
line 151 in common/downtime.c needs to be changed:
\-    } else if (dt->downtime_id > next_downtime_id) {
\+   } else if (dt->downtime_id >= next_downtime_id) {
        next_downtime_id = dt->downtime_id + 1;
    }

Bug 2): If the next downtime is planned, next_downtime_id would have been corrected by function get_next_downtime_id, if it would work as intended.
NOT the next_downtime_id needs to be tested for "in use", but the new_dt_id, which is returned as "available", needs to be tested:
Line 1010 in common/downtime.c:
        new_dt_id = next_downtime_id++;
\-        if (!find_downtime(ANY_DOWNTIME, next_downtime_id)) {
\+        if (!find_downtime(ANY_DOWNTIME, new_dt_id)) {
            return new_dt_id;
            }

Best regards,
Franz

**Comment by hedenface** [comment]
Did you find this in master branch? Or in code from a tag?

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/commit/08d2b7340cee6f3731c275af023386d9502db8e7
