### ISSUE TITLE
Nagios service running but log files  and checks are not updating.After restarting every thing is working fine.

### ISSUE THREAD

**Issue by praveenponugoti** [NagiosEnterprises/nagioscore#507]
In my nagios server, nagios service is running but log files, checks are not updating.

After nagios service restart log files and checks are updating.This is happening frequently. I have checked in nagios.log file. Nothing is written in that file.

What could be the issue?. Can any one help me

**Comment by douglasawh** [comment]
@praveenponugoti did you ever get this resolved? I haven't been involved in a while, but probably https://support.nagios.com/forum/viewforum.php?f=5&sid=8a0f7e216019f711a2f31e3f455623b2 is a better place for this type of question.
