### ISSUE TITLE
the default-init.in not stop because no PID on NagiosRunFile

### ISSUE THREAD

**Issue by iam333** [NagiosEnterprises/nagioscore#508]
Hi!

Nagios Core 4.3.4

I´ve saw that the init script (/etc/init.d/nagios -->default-init.in ) couldn´t stop the server, because the nagios.lock has not the PID of nagios.

This could be solved puting this:

        `pidof nagios > $NagiosRunFile`

in start function, like this:

`case "$1" in

        start)
                echo -n "Starting nagios:"

                if test "$checkconfig" = "true"; then
                        check_config
                        # check_config exits on configuration errors.
                fi

                if test -f $NagiosRunFile; then
                        NagiosPID=`head -n 1 $NagiosRunFile`
                        if status_nagios; then
                                echo " another instance of nagios is already running."
                                exit 0
                        fi
                fi

                su $NagiosUser -c "touch $NagiosVarDir/nagios.log $NagiosRetentionFile"
                remove_commandfile
                touch $NagiosRunFile
                $NagiosBin -d $NagiosCfgFile

                # INSERTING PID ON LOCKFILE
                pidof nagios > $NagiosRunFile

                if [ -d $NagiosLockDir ]; then touch $NagiosLockDir/$NagiosLockFile; fi

                echo " done."
                ;;
`
thanks in advance!

**Comment by box293** [comment]
Thanks for reporting, I believe we've addressed this in the upcoming 4.4.0 release.

**Comment by hedenface** [comment]
@box293 is right. I believe the issues revolving around the PID file, init script, cmd file, have all been addressed in the current master branch. If you test with the current branch and still have these issues, please re-open this issue or open a new one.

Thanks.

**Comment by flusher** [comment]
Same issue on the fresh new 4.4.2 release.

iam333's suggested patch fixes the issue, please amend default-init.in !

Thanks

**Comment by flusher** [comment]
@box293 You're right, thank you for this suggestion !
