### ISSUE TITLE
Need to check for gperf in configure script

### ISSUE THREAD

**Issue by Madlohe** [NagiosEnterprises/nagioscore#509]
With the [latest commit](https://github.com/NagiosEnterprises/nagioscore/commit/7680758be77e47e727bae5cb33cea98fda8f91ac), ran ` ./configure --enable-debugging --enable-coverage --enable-libtap` on CentOS 7, `make all` stops with the error `/bin/sh: gperf: command not found`

**Comment by hedenface** [comment]
This actually looks like it is a non-issue. `gperf` is required for building `workers.o` in base/Makefile. That leads me to believe it was lack of dependencies installed before performing a `make all`. As in, it's a requirement outside of the `--enable-testing` suite of configure flags.

Can you confirm? Install a Cent7 VM, don't install the dependencies, and then `./configure` as normal - I suspect you'll still receive this error.

**Comment by Madlohe** [comment]
On a minimal cent 7 VM, I only had to install gcc and unzip to satisfy `./configure`. `make all` worked and `make install` & friends worked after creating just the nagios user. (glibc, glibc-common, wget, and perl were already on the system) 

As we talked about earlier, I can make a different issue that's more along the lines of 'fix autoconf', and then just give a PR when I'm done with that.

**Comment by hedenface** [comment]
Ended up being a non-issue.

**Comment by hedenface** [comment]
Were you purposely building the `wpres-phash.h` file? This is really more for use when updating the child process keys - not during a normal configure && make && make install scenario.

**Comment by knweiss** [comment]
@hedenface No. And I've just noticed that a working `wpres-phash.h` is part of the git repo.

What I remember is that I've copied the source tree into a Linux test VM which didn't have `gperf` installed yet.

Maybe this copy changed the timestamps of `wpres.gperf` so that it was newer than the provided `wpres-phash.h` and then the make rule tried to rebuild it. However, this failed as `gperf` was not installed - resulting in an empty `wpres-phash.h` which then broke my build? Let's see...

```
$ pwd
/home/knweiss/git/nagioscore
$ git status
On branch cgi
nothing to commit, working tree clean
$ ls -l base/wpres-phash.h
-rw-rw-r--. 1 knweiss knweiss 9708 Jun  8 21:45 base/wpres-phash.h
$ sudo mv /usr/bin/gperf /usr/bin/gperf.dontuse
$ touch base/wpres.gperf 
$ make nagios cgis
cd ./base && make
cd ./cgi && make
make[1]: Entering directory '/home/knweiss/git/nagioscore/base'
gperf -S 1 -t -H wpres_key_phash -N wpres_get_key wpres.gperf > wpres-phash.h
make -C ../lib
/bin/sh: gperf: command not found
make[1]: *** [Makefile:146: wpres-phash.h] Error 127
[...]
$ ls -l base/wpres-phash.h 
-rw-rw-r--. 1 knweiss knweiss 0 Jun  8 21:46 base/wpres-phash.h
```
Now install gperf and run make again
```
$ sudo mv /usr/bin/gperf.dontuse /usr/bin/gperf
$ make nagios cgis
cd ./base && make
make[1]: Entering directory '/home/knweiss/git/nagioscore/base'
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCORE -c -o workers.o workers.c
workers.c: In function ‘parse_worker_result’:
workers.c:533:7: warning: implicit declaration of function ‘wpres_get_key’ [-Wimplicit-function-declaration]
   k = wpres_get_key(key, kvv->kv[i].key_len);
       ^~~~~~~~~~~~~
workers.c:533:5: warning: assignment to ‘struct wpres_key *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   k = wpres_get_key(key, kvv->kv[i].key_len);
     ^
workers.c:538:12: error: dereferencing pointer to incomplete type ‘struct wpres_key’
   switch (k->code) {
            ^~
```
So it's still broken and the fix is to remove `base/wpres-phash.h` and then regenerate it or restore from git with `git checkout base/wpres-phash.h`.
