### ISSUE TITLE
4.3.4 maximum cfg includes issue

### ISSUE THREAD

**Issue by pomporov** [NagiosEnterprises/nagioscore#510]
Hello

i have nagios core 4.3.4 when i reach around 3000 cfg files in included objects directory it start to "ignore" them and configuration failing.

merging all files in ONE big file works so its defenetly an issue of file number or parser .

Regards

**Comment by hedenface** [comment]
Anything interesting in the logs when it fails? What operating system, version, architecture?

**Comment by box293** [comment]
What is the output of `ulimit -a` ?

**Comment by hedenface** [comment]
I think @box293 is on to something here. I did the following to try and reproduce (and couldn't):

```
cd /usr/local/nagios/etc/
mkdir objectsdir
echo "cfg_dir=/usr/local/nagios/etc/objectsdir" >> nagios.cfg
cd objectsdir
echo -e "define host{\n\tuse linux-server\n\thost_name HOSTNAME\n\talias HOSTNAME\n\taddress 127.0.0.1\n}\n\ndefine service{\n\tuse local-service\n\thost_name HOSTNAME\n\tservice_description service\n\tcheck_command check_local_disk"'!'"20%"'!'"10%"'!'"\n}\n" > template
for i in $(seq 1 4000); do cat template | sed s/HOSTNAME/host$i/ > host$i.cfg; done
sudo service nagios restart
cd /usr/local/nagios/bin/
./nagiostats
```
The relevant output of `nagiostats` command:
```
Total Hosts:                            4001
```
(I only had localhost setup before doing this).

I suspect I could keep increasing my `$(seq 1 4000)` until I reached my file limit, but like Troy said: check your `ulimit -a` and make the increases as necessary.

I'll be closing the issue now, unless some other relevant information (e.g.: other than increasing the appropriate limit) appears.
