### ISSUE TITLE
nagios-4.3.4 - Service reloading broken, missing daemonchk.cgi file

### ISSUE THREAD

**Issue by Senso** [NagiosEnterprises/nagioscore#514]
1.

The init.d file (/etc/init.d/nagios) for 4.3.4 has this for checking the process status:
```
status_nagios ()
{
        if test -x $NagiosCGI/daemonchk.cgi; then
                if $NagiosCGI/daemonchk.cgi -l $NagiosRunFile > /dev/null 2>&1; then return 0; fi
        else
                if ps -p $NagiosPID > /dev/null 2>&1; then return 0; fi
        fi

        return 1
}
```

That cgi file is not present in the 4.3.4 tarball release:
```
$ find . -name *.cgi
./contrib/traceroute.cgi
./cgi/statuswrl.cgi
./cgi/notifications.cgi
./cgi/statuswml.cgi
./cgi/statusmap.cgi
./cgi/cmd.cgi
./cgi/statusjson.cgi
./cgi/archivejson.cgi
./cgi/config.cgi
./cgi/outages.cgi
./cgi/histogram.cgi
./cgi/status.cgi
./cgi/avail.cgi
./cgi/objectjson.cgi
./cgi/history.cgi
./cgi/extinfo.cgi
./cgi/tac.cgi
./cgi/showlog.cgi
./cgi/trends.cgi
./cgi/summary.cgi
```

2. 

Same `check_status()` function references `$NagiosCGI` but this variable is not defined. `$NagiosCGIDir` is defined though.

Both issues cause reloading the service to not work at all.

**Comment by hedenface** [comment]
https://github.com/NagiosEnterprises/nagioscore/blob/master/contrib/daemonchk.c

**Comment by hedenface** [comment]
I'm currently in the middle of examining the startup files - there are quite a few issues that have been creeping up to this point. :) Thanks for the data

**Comment by hedenface** [comment]
Oooo I misunderstood anyway. Ignore me. Yeah that definitely needs updated to reference the proper var.

You're free to submit a Pull Request so you can get the sweet internet points. It may still change in the very immediate future, but having it in the commit history might be a good idea!

**Comment by Senso** [comment]
Thanks for the quick reply, I've submitted a pull request for the variable fix.

**Comment by hedenface** [comment]
I just read thru the init script - why are we importing LSB init-functions if we aren't using any, even?

Thank you for the PR - as stated in there - please add yourself to the thanks file before I merge. I'll pull your changes, and then I'm likely going to rip and replace a bit of stuff in here.

**Comment by Senso** [comment]
Done!
