### ISSUE TITLE
Reformat the source code with clang-format

### ISSUE THREAD

**Issue by knweiss** [NagiosEnterprises/nagioscore#521]
IMHO the Nagios source code is formatted in an inconsistent and (partially) unusual way.

Please consider choosing a [formatting style](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) and reformat the source code **automatically** and **consistently** with [clang-format](https://clang.llvm.org/docs/ClangFormat.html).

See also https://clangformat.com/ for an interactive tool to configure your own style description.

**Comment by hedenface** [comment]
I don't disagree with you about the styling.

The re-styling is going to have to wait for a major revision, and was already planned (not publicly) for Core 5. This will also include git hooks that help enforce that.

I'm going to close the issue. For what it's worth, the style we're going with is close to a K&R variant mashup of Stroustrup and Linux Kernel along with some custom brace/indentation definitions (and use spaces).
