### ISSUE TITLE
Error when building Nagios 4.4.0 [/usr/bin/install: cannot stat 'daemon-init']

### ISSUE THREAD

**Issue by Fr3dY2** [NagiosEnterprises/nagioscore#535]
Hi,

When executing 'rpm -ba SPECS/nagios.spec' from my rpmbuild folder, I'm getting the following error (never happened to me with previous versions):

```
...
+ /usr/bin/install -m 0755 daemon-init /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64//etc/rc.d/init.d/nagios
/usr/bin/install: cannot stat 'daemon-init': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.6h9vk1 (%install)
```

Am I missing something? I'm using CentOS 7.5.

Regards,

**Comment by hedenface** [comment]
Looks like it's trying to use the init.d file, when it should be attempting to use the systemd service file (new in 4.4.0).

Looks like the error may be here:
```
# TODO: this should be more automatically created with @initdir@, etc.
%{__install} -m 0755 daemon-init %{buildroot}/%{_initrddir}/nagios
```

I think you'll need to change the line to:

```
startup/default-service %{buildroot}/HOWEVER/YOU/GET/TO/SYSTEMD/SERVICE/FILES
```

I personally don't know what the procedure is for maintaining different versions of RPM for different OS. Is this something we should be concerned about?

Also, let me know if that works - so I can make the changes.

**Comment by Fr3dY2** [comment]
I changed the line to:
`startup/default-service %{buildroot}/etc/systemd/system/multi-user.target.wants/`

Then I got a 'Permission denied' error:
```
+ startup/default-service /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/etc/systemd/system/multi-user.target.wants/
/var/tmp/rpm-tmp.BvFalI: line 69: startup/default-service: Permission denied

```

So, I added the following before my modified line (just for testing):
`chmod 764 startup/default-service`

And it failed with the following error:
```
RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/etc/rc.d/init.d/nagios

```

I tried doing this in nagios.spec:

```
#%attr(0755,root,root) %config %{_initrddir}/nagios
%attr(0755,root,root) %config /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/etc/systemd/system/multi-user.target.wants/*

```

But it didn't work :(

```
RPM build errors:
    File not found by glob: /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/etc/systemd/system/multi-user.target.wants/*
```



Regards,

**Comment by hedenface** [comment]
```
File not found: /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/etc/rc.d/init.d/nagios
```

Makes me think it's still looking for the init.d file.

Oooh - are you changing the CFLAGS at all? Maybe update the `--with-init-dir`. It also looks like the lockfile needs to be updated (the new default location is `/var/run/nagios.lock`).

**Comment by Fr3dY2** [comment]
Bryan, I'm sorry but I'm not sure about what to do now... run the "**rpmbuild -ba SPEC/nagios.spec**" command adding the **--with-init-dir** pointing to **/etc/systemd/system/multi-user.target.wants/** ?

**Comment by Fr3dY2** [comment]
OK, try this:

yum install rpmdevtools doxygen gperf
cd /root
rpmdev-setuptree
cd rpmbuild
#Copy nagios.spec file from nagios-4.4.0.tar.gz to SPEC directory
#Copy nagios-4.4.0.tar.gz to SOURCES directory
rpmbuild -ba SPECS/nagios.spec

**Comment by hedenface** [comment]
Okay, I'll keep you posted. Should only be a few minutes. In the meantime, see #537

**Comment by hedenface** [comment]
So I've gotten to the `cd rpmbuild` step - but don't have the sources. Where did you download them to? Where did you download them from?

Also, I'm assuming I need the pre-requisites for core installed as well, correct?

**Comment by Fr3dY2** [comment]
Sure, install any pre-requisites you need - it won't affect this test.
You have to put the **nagios-4.4.0.tar.gz** file into the SOURCES folder (you can download it from https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.0.tar.gz).
Extract the nagios.spec file from that file and put it into the SPEC folder as well.

**Comment by hedenface** [comment]
Neat. Okay, I have replicated the issue. I'll keep you posted on any solutions.

**Comment by hedenface** [comment]
Okay, I have it working. But I'm not going to fix the file in the repo, as I believe there needs to be a bit more thought put into it. But this should work for you:

Add

```
BuildRequires: systemd
```
after
```
BuildRequires: gperf
```

Remove the line:

```
%{__install} -m 0755 daemon-init %{buildroot}/%{_initrddir}/nagios
```

And replace it with:

```
%{__mkdir} -p -m 0755 %{buildroot}/%{_unitdir}
%{__install} -m 0755 startup/default-service %{buildroot}/%{_unitdir}/nagios.service
```

And then remove the line:

```
%attr(0755,root,root) %config %{_initrddir}/nagios
```

And replace it with:

```
%attr(0755,root,root) %config %{_unitdir}/nagios.service
```
This seems wrong, as that probably shouldn't be executable.

**Comment by Fr3dY2** [comment]
I think the last step is not needed (old service script needed to be executable, but now the script is managed by systemctl, so it justs need to be readable).
However, I tried to build it and this is what I'm getting:

Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/lib/systemd/system/nagios.service

RPM build errors:
    File listed twice: /etc/nagios/objects/commands.cfg
    File listed twice: /etc/nagios/objects/contacts.cfg
    File listed twice: /etc/nagios/objects/localhost.cfg
    File listed twice: /etc/nagios/objects/printer.cfg
    File listed twice: /etc/nagios/objects/switch.cfg
    File listed twice: /etc/nagios/objects/templates.cfg
    File listed twice: /etc/nagios/objects/timeperiods.cfg
    File listed twice: /etc/nagios/objects/windows.cfg
    File listed twice: /var/nagios
    File listed twice: /var/nagios/rw
    Installed (but unpackaged) file(s) found:
   /usr/lib/systemd/system/nagios.service

The RPM hasn't been created, but the /usr/lib/systemd/system/nagios.service file was copied to target destination... I don't think that's the way it should be done (this could be related to #537).
Looking at the error messages, looks like the building script is putting those files in the destination - but maybe that should be done only when installing/updating the RPM, not while creating it.

**Comment by hedenface** [comment]
I'll keep the issues open and have them resolved for 4.4.1. But something like this, I could really use some community support - as far as solutions and decisions. Right now my plan is:

1. Find a way to ensure the spec file works systemd and non-systemd systems
2. Remove the processes that install the service file and do a daemon-reload
3. Place the daemon-reload into an additional step and update the documentation

But that's all I have currently. I'm looking for help regarding the first one in that list specifically.

**Comment by Fr3dY2** [comment]
For non-systemd testing, could you try installing CentOS 6?

**Comment by knweiss** [comment]
(You can build the rpms directly from the tarball using `rpmbuild -ta nagios-4.4.0.tar.gz`.)

**Comment by knweiss** [comment]
@hedenface Quoting [the packaging guide](https://fedoraproject.org/wiki/Packaging:Systemd#.25files_section):

> Systemd unit .service files must not be marked as %config files.

**Comment by Fr3dY2** [comment]
Maybe you could do something like this? (taken from https://github.com/sspans/ladvd/issues/11)

```
%define use_systemd (0%{?fedora} && 0%{?fedora} >= 18) || (0%{?rhel} && 0%{?rhel} >= 7) || (0%{?suse_version} && 0%{?suse_version} >=1210)
...
...
%if %{use_systemd}
Requires: systemd
BuildRequires: systemd
%else
Requires:           initscripts >= 8.36
Requires(postun):   initscripts
Requires(post):     chkconfig
Requires(preun):    chkconfig
%endif
...
...
%if %{use_systemd}
# install systemd-specific files
%{__mkdir} -p %{buildroot}%{_unitdir}
%{__install} -m644 %{SOURCE3} \
    %{buildroot}%{_unitdir}/%{pkgname}.service
%{__mkdir} -p %{buildroot}%{_prefix}/lib/tmpfiles.d
%{__install} -m644 %{SOURCE4} \
    %{buildroot}%{_prefix}/lib/tmpfiles.d/%{pkgname}.conf
%else
# install SYSV init stuff
%{__install} -D -m 755 %{SOURCE1} %{buildroot}%{_initrddir}/%{pkgname}
%endif
...
...

```

**Comment by knweiss** [comment]
@Fr3dY2 Maybe it has something to do with the fact the `%{_unitdir}` evaluates to (notice: no `/usr` prefix!) `/lib/systemd/system` and `/lib`is a symlink to `/usr/lib`.

**Comment by hedenface** [comment]
My %{_unitdir} is /usr/lib/systemd/system according to the rpmbuild output.

**Comment by hedenface** [comment]
https://github.com/NagiosEnterprises/nagioscore/commit/d55a6979a20d1f233dd655435ef7a1448f763bbc

Hopefully this solves your problem. You'll have to run ./configure first to get a usable spec file. Please let me know.

**Comment by Fr3dY2** [comment]
Looks like there's some /usr missing at some point (specific to my system?), as @knweiss previously pointed out:

```
make[1]: Leaving directory `/root/rpmbuild/BUILD/nagios-4.4.0'
/bin/install -c -m 755  startup/default-service /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/lib/systemd/system/nagios.service
/bin/install: cannot create regular file '/root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/lib/systemd/system/nagios.service': No such file or directory
make: *** [install-init] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.NwyIAL (%install)

```

There's no lib folder there, although usr doesn't contain 'lib' either (instead, there's a lib64 directory):

```
[root@S-JRCSVQNG001P rpmbuild]# ls -l /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/
total 0
drwxr-xr-x. 5 root root 40 Jun 21 10:40 usr
drwxr-xr-x. 3 root root 19 Jun 21 10:40 var

[root@S-JRCSVQNG001P rpmbuild]# ls -l /root/rpmbuild/BUILDROOT/nagios-4.4.0-2.el7.x86_64/usr/
total 0
drwxrwxr-x. 2 root root 36 Jun 21 10:40 bin
drwxr-xr-x. 3 root root 19 Jun 21 10:40 lib64
drwxr-xr-x. 3 root root 19 Jun 21 10:40 share
```

**Comment by knweiss** [comment]
`/usr/lib/systemd/system/nagios.service` is where it should be.

@hedenface You may want to take a look at the modifications of the `nagios.spec` file that ships with Fedora EPEL EL7 and is packaged in the following source rpm package [nagios-4.3.4-5.el7.src.rpm](https://mirror.colorado.edu/fedora/epel/7/SRPMS/Packages/n/nagios-4.3.4-5.el7.src.rpm) for RHEL7/CentOS7 with systemd:

```
mkdir nagios-4.3.4-5.el7.src/
cd nagios-4.3.4-5.el7.src/
rpm2cpio ~/Downloads/nagios-4.3.4-5.el7.src.rpm | cpio -id nagios.spec
less nagios.spec
```

**Comment by knweiss** [comment]
@hedenface In commit d55a6979 there's this hunk:
```diff
+if [ "@initname@" = "nagios.service" ]; then
+    %attr(0644,root,root) %config @initdir@/@initname@
+else
+    %attr(0755,root,root) %config @initdir@/@initname@
+fi
```
As mentioned above: Systemd unit .service files must not be marked as `%config` files.

**Comment by hedenface** [comment]
@knweiss This is being dealt with. @Fr3dY2 has been most helpful. I'll be pushing a good change here in a moment.

Thanks!

**Comment by hedenface** [comment]
With the appropriate non-%config :)

**Comment by hedenface** [comment]
@knweiss @Fr3dY2 https://github.com/NagiosEnterprises/nagioscore/commit/252c7d499ec6482210db7486dc884540e7675c73

**Comment by hedenface** [comment]
I didn't understand the bit about the tmpfiles stuff, @Fr3dY2

**Comment by hedenface** [comment]
```
[root@centos7x64 SPECS]# rpmlint nagios.spec
nagios.spec:90: W: non-standard-group Development/Utils
nagios.spec:99: W: setup-not-quiet
nagios.spec:208: W: deprecated-grep [u'egrep']
nagios.spec:209: W: deprecated-grep [u'egrep']
nagios.spec:249: W: macro-in-comment %logmsg
nagios.spec:250: W: macro-in-comment %logmsg
nagios.spec: W: invalid-url Source0: http://dl.sf.net/nagios/nagios-4.4.1.tar.gz <urlopen error timed out>
0 packages and 1 specfiles checked; 0 errors, 7 warnings.
[root@centos7x64 SPECS]#
```

As of: https://github.com/NagiosEnterprises/nagioscore/blob/aa2b337db80f556ab36b5f77e278464dfff48265/nagios.spec
