### ISSUE TITLE
'install-daemoninit' Makefile target does not respect DESTDIR

### ISSUE THREAD

**Issue by knweiss** [NagiosEnterprises/nagioscore#537]
I'm experimenting with the nagios-4.4.0 release and used the configure switch `--with-init-type=systemd` in a `nagios.spec` file. I've executed the compilation using `rpmbuild -ba nagios.spec` to generate nagios rpms.

The generated Makefile has the following `install-init` target. Notice that it **does not respect DESTDIR** and tries to install the files into the production filesystem instead of the buildroot directory (in case of `rpmbuild`)!

Also it calls `systemctl daemon-reload` on the build system.

Both should not happen during a `rpmbuild` run! It should only **install** the files into the temporary buildroot
where they will be picked up for packaging.

```Makefile
install-init: install-daemoninit

install-daemoninit:
        $(INSTALL) -m 755 $(INIT_OPTS) startup/$(SRC_INIT) $(INIT_DIR)/$(INIT_FILE)
        @if [ x$(INIT_TYPE) = xsysv ]; then \
                if which chkconfig >/dev/null 2>&1; then \
                        chkconfig --add nagios; \
                elif which update-rc.d >/dev/null 2>&1; then \
                        update-rc.d nagios defaults; \
                fi \
        elif [ x$(INIT_TYPE) = xsystemd ]; then \
                if which systemctl >/dev/null 2>&1; then \
                        systemctl daemon-reload; \
                        systemctl enable nagios.service; \
                fi; \
                chmod 0644 $(INIT_DIR)/$(INIT_FILE); \
        elif [ x$(INIT_TYPE) = xupstart ]; then \
                if which initctl >/dev/null 2>&1; then \
                        initctl reload-configuration; \
                fi \
        elif [ x$(INIT_TYPE) = xopenrc ]; then \
                if which rc-update >/dev/null 2>&1; then \
                        rc-update add nagios default; \
                fi \
        fi

        @echo ""
        @echo "*** Init script installed ***"
        @echo ""
```

The nagios-4.3.4 Makefile looks like this and respects `DESTDIR`:
```Makefile
install-init: install-daemoninit

install-daemoninit:
        $(INSTALL) -m 755 -d $(INIT_OPTS) $(DESTDIR)$(INIT_DIR)
        $(INSTALL) -m 755 $(INIT_OPTS) daemon-init $(DESTDIR)$(INIT_DIR)/nagios

        @echo ""
        @echo "*** Init script installed ***"
        @echo ""
```

Here's the respective code from `nagios.spec`:
```
%install
export PATH=%{_bindir}:/bin:\$PATH
%{__rm} -rf %{buildroot}
%{__make} install-unstripped install-init install-commandmode install-config \
    DESTDIR="%{buildroot}" \
    INSTALL_OPTS="" \
    COMMAND_OPTS="" \
    INIT_OPTS=""
```

**Comment by hedenface** [comment]
Related to #535 no doubt.

So, the `systemctl daemon-reload` was added to make the installation process easier for those compiling from source - apparently this is an issue here. What is the trade-off? A different make target for running initialization? No make target for it? Why must the daemon-init target be executed from within rpmbuild? Why can't the installation of the daemon file happen independently?

What is your recommendation and/or proposed solution?

**Comment by knweiss** [comment]
@hedenface Yes, an additional Makefile target (`activate-init`) which would be ignored by `rpmbuild` could be a solution. I'm unaware of an established standard for this use case though. Instead you also could just mention it in the installation guide. Most people will probably install Nagios using a distribution package anyway.

See: [Why don't we.... Start the service after installation?](https://fedoraproject.org/wiki/Packaging:Systemd#Why_don.27t_we....) in the Fedora systemd packaging guide.

(Reading the guide I've also noticed that the `--with-init-type=systemd` spec file needs an additional
```
BuildRequires: systemd
```
line.)

**Comment by hedenface** [comment]
That link contains a lot of helpful information, thank you. Is there a
conditional macro we can use to specify the buildrequires only if the
systemd is used?

**Comment by hedenface** [comment]
I did at least get the rpm to build. See changes in #535. How do most other projects manage the spec files? I'm assuming with macros - but is it common to just keep different spec files entirely? (That seems like a nightmare)

**Comment by knweiss** [comment]
@hedenface Information on proper handling of unit files in spec file scriptlets can be found here: [Packaging:Scriptlets#Systemd](https://fedoraproject.org/wiki/Packaging:Scriptlets#Systemd).

**Comment by hedenface** [comment]
Pushed changes we discussed here:

https://github.com/NagiosEnterprises/nagioscore/commit/d55a6979a20d1f233dd655435ef7a1448f763bbc

You'll need to run ./configure first to get a usable spec file- so I'm not sure this is the proper way to solve it. If not, we can revert and figure it out.

**Comment by knweiss** [comment]
@hedenface Well, this breaks the convenient `rpmbuild -ta <tarball>` functionality as `rpmbuild` expects a pre-existing, working `.spec` file.

(Sorry, I did not have time to check or even test your latest commits yet.)

**Comment by hedenface** [comment]
Then for me to be able to manage that, I would need to keep it in two spec files - or I can just revert those changes and let the packagers decide on the updates that should be done. With it respecting DESTDIR now (and not issuing a daemon-reload), it should be trivial to get it working on systemd systems.

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/blob/aa2b337db80f556ab36b5f77e278464dfff48265/nagios.spec
