### ISSUE TITLE
Map link always goes to undefined host

### ISSUE THREAD

**Issue by scottwilkerson** [NagiosEnterprises/nagioscore#539]
Described here:

https://support.nagios.com/forum/viewtopic.php?f=34&t=49014&p=254371#p254356

The "View Status Detail For This Host" is always set to undefined host, no matter which host is selected.

Personally I think either that particular link should go away or update to the host that us the root node.  This would still be undefined if the Nagios Process was the root node but would fix all other scenarios.

**Comment by jomann09** [comment]
Fixed infobox issues and will be out in 4.4.3
