### ISSUE TITLE
Check boxes do not work on map

### ISSUE THREAD

**Issue by scottwilkerson** [NagiosEnterprises/nagioscore#543]
If open the new status map, click the setting bars in upper right, the check boxes in the dialog box do not do what they say.  If you click them you can still do what they are supposed to disable, except for "Disable Display of the Menu Button (and also this dialog!) " this one works.

More info here
https://support.nagios.com/forum/viewtopic.php?f=34&t=49014&p=254612#p254600

**Comment by jomann09** [comment]
Fixed in maint branch, will be in 4.4.3
