### ISSUE TITLE
Nagios stops monitoring every x minutes

### ISSUE THREAD

**Issue by josnavch** [NagiosEnterprises/nagioscore#544]
Nagios Stats 4.3.4
CentOS release 6.9 (Final)
Total Services: 34706
Total Hosts: 2702
Latency: 29.354 sec

**Symptom**

We started to have the following behavior in the logs of our Monitoring Production server:
The Monitoring Server  has died at 16:56:51 with the following messages in the nagios.log
 
wproc: Job with id '163406' doesn't exist on Core Worker 61583.
wproc: Job with id '163409' doesn't exist on Core Worker 61583.
wproc: Job with id '163398' doesn't exist on Core Worker 61583.
wproc: Job with id '163407' doesn't exist on Core Worker 61583.
wproc: Job with id '163410' doesn't exist on Core Worker 61583.
wproc: Job with id '163450' doesn't exist on Core Worker 61583.

After restarting the nagios service everything returned to normal until 19:48 when he again died, with the following log

Error: External command failed -> PROCESS_SERVICE_CHECK_RESULT;XXXXXXXXX;Capacidad de Puertos;0;OK: El equipo se encuentra utilizando 204 (70.83%) de sus interfaces de un total 288 puertos | Percent_Usage=70.83%;;80%;90%;  | Puertos_Fisicos=288;;;;;  Puertos_Utilizados=204;;;;; Puertos_Disponibles=84;;;;;

External command error: Command failed
wproc: iocache_capacity() is 0 for worker Core Worker 12959.
wproc: Socket to worker Core Worker 12959 broken, removing
wproc: Error: can't get_worker() in fo_reassign_wproc_job
wproc: Error: can't get_worker() in fo_reassign_wproc_job
wproc: Error: can't get_worker() in fo_reassign_wproc_job
wproc: Error: can't get_worker() in fo_reassign_wproc_job
wproc: Error: can't get_worker() in fo_reassign_wproc_job
wproc: Error: can't get_worker() in fo_reassign_wproc_job
wproc: Error: can't get_worker() in fo_reassign_wproc_job
Unable to run check for service 'INT_port-channel857' on host 'XXXXXXXXXXXXXX'
Unable to run check for service 'INT_port-channel70' on host 'XXXXXXXXXXXXXX'
Unable to run check for service 'INT_Vl51' on host 'XXXXXXXXXXXXXX'
Unable to run check for service 'INT_Ethernet7/21' on host 'XXXXXXXXXXXXXX-ESFERAS'
Unable to run check for service 'INT_Ethernet124/1/13' on host 'XXXXXXXXXXXXXX596H'
Unable to run check for service 'CPU Load' on host 'XXXXXXXXXXXXXX45H'
Unable to run check for service 'INT_Gi1/0/7' on host 'XXXXXXXXXXXXXX60M'
Unable to run check for service 'CPU Load' on host 'XXXXXXXXXXXXXX48H'
Unable to run check for service 'INT_port-channel805' on host 'XXXXXXXXXXXXXX'

**Comment by hedenface** [comment]
Can I see the output of:

```
ulimit -a
```

**Comment by josnavch** [comment]
After reviewing in multiple forums and reviewing information on the web, we find these two points of reference:
https://github.com/NagiosEnterprises/nagioscore/issues/429
https://github.com/NagiosEnterprises/nagioscore/issues/455

But although they were related to our situation, our server did not present memory leak, only service latency leak.
![screen shot 2018-06-22 at 3 18 43 pm](https://user-images.githubusercontent.com/17910232/41799701-ab60bdba-762f-11e8-8f43-7bd76e8e6968.png)

**Comment by hedenface** [comment]
Are you able to test against the 4.4.1 (maint) branch by chance?

**Comment by josnavch** [comment]
continued to work tracking down the problem.

What is happening is something is killing off the "core workers". When the last worker dies (there is typically 48 started on these systems ... based on # of system cores), everything hangs up.

There seems to be 4 workers killed, every 13 minutes. The 13 minute spacing is fairly consistent, which leads me to believe there is some regular check in there that corrupting the monitoring engine. Still trying to trace it down, and will continue here tomorrow.

**Comment by josnavch** [comment]
@hedenface 
we found that it was not a nagios version issue or conflict with the OS version

**Comment by josnavch** [comment]
@hedenface 
Part of the commands used to do the troubleshooting

grep -i "Core Worker. * broken \ | nagios. * starting" /var/log/nagios/nagios.log | perl -pe 's / (\ d +) / localtime ($ 1) / e' | tail

**Comment by josnavch** [comment]
Part of the solution was to determine when this behavior began and what changes had been made?

Once identified, look for a pattern.

At the end our problem was a service two Windows servers of Database

They connected to the database and executed a stored procedure, every 10 minutes.

**Comment by hedenface** [comment]
What do you mean not a nagios version issue? Did you run it against a non 4.3.x version and confirm the same behavior?

**Comment by josnavch** [comment]
@hedenface 

When the check's were disabled, the problem was solved.

We did not make any changes to the configuration level of nagios, once we determined that it was not a problem for the version.

This is a bit complicated but at the same time simple, if something is working properly it can not simply stop working.

Before making changes to version and OS level (which would be very expensive in my case) we decided to see what change at the level of checks

Something that helped us (again in my case) is that both environments prod and develp die at the same time

**Comment by josnavch** [comment]
This is how server latency behaves now: avg 27 seconds
![screen shot 2018-06-22 at 3 43 36 pm](https://user-images.githubusercontent.com/17910232/41800498-0ec25654-7633-11e8-9094-7eddf56c6835.png)

**Comment by hedenface** [comment]
No what I mean is - if you have your checks enabled, on an older version - or on the maint version - is the problem still present?

There were numerous issues in 4.3.4 that have since been resolved.

**Comment by hedenface** [comment]
Oh wait - are you saying you've determined that this is NOT a nagios problem?
