### ISSUE TITLE
Version 4.4.0 has a "using freed memory" problem, if enable_environment_macros=1

### ISSUE THREAD

**Issue by feisenko** [NagiosEnterprises/nagioscore#546]
Problem:  If enable_environment_macros=1 is set, Version 4.4.0 behaves completely unpredictable.

Cause: A bug in base/workers.c in function wproc_run_job.
In line 1165 a buffer is freed "my_free(env_kvvb->buf);", but a pointer to this freed memory is used afterwards. 
Line 1161: kvvec_addkv_wlen(kvv, "env", strlen("env"), env_kvvb->buf, env_kvvb->buflen);
kvvec_addkv_wlen does not duplicate  env_kvvb->buf into kvv, it only references it, so freeing env_kvvb->buf in line 1165 and using kvv, with a pointer to this memory inside, afterwards, is fatal. 

Proposed program correction: The logic for freeing the buffer was correct in 4.3.4, so reimplement it from there.

Best regards,
Franz

**Comment by hedenface** [comment]
This has been fixed in the maint branch already. See #538 and #534
