### ISSUE TITLE
TO change the Kibana name to InternalThreats

### ISSUE THREAD

**Issue by vamse15** [NagiosEnterprises/nagioscore#547]
Hello, i need yr help please, i'm a new member of wazuh, i've just follow the wzush online document 2.0 guide for system installation. The installation was done, i saw the "Management / Kibana" when click on Index Patterns  button under Management Tab, when i click on Index Patterns tab it showing "Management / Kibana" , how to change from "Management / Kibana" to "Management / InternalThreats" [no results found]. May you help me ?

In screen shot two marked with red color, what i am going to change name Kibana to InternalThreats .

kibana version 5.6.3
wazuh ---2.1

![screenshot1](https://user-images.githubusercontent.com/28727493/42019369-9d16ec6e-7ad2-11e8-96de-a4bdc3da0485.png)
![screenshot2](https://user-images.githubusercontent.com/28727493/42019371-9d4b9e32-7ad2-11e8-9f99-1cc5b3f68af8.png)

**Comment by hedenface** [comment]
This doesn't appear to have anything to do with Nagios at all, so I'm closing the issue. I'm not sure if the products you're using have their own forums or not.
