### ISSUE TITLE
Nagios incorrectly shows service status totals for service group

### ISSUE THREAD

**Issue by VMike1** [NagiosEnterprises/nagioscore#548]
Hello!

Nagios 4.3.4

There is a 'Service Status Totals' table in status.cgi. It shows incorrect counters when 'Service Status Details For Service Group ...' is selected (http://xxx/nagios/cgi-bin/status.cgi?servicegroup=XXX&style=detail).
Numbers are counted for all services on hosts in service group. But the service group may contain only subset of services from host.

For example, there are 10 hosts, each of them contain 5 services. The service group contain only one service for each host. It is 10 items at all. But the service status totals shows number 50 in 'Ok' and 'All Types' cells.

The problem occurs only for service groups. For hosts the numbers are counted correctly.

**Comment by hedenface** [comment]
Are you able to verify that this behavior is the same in 4.4.1?

**Comment by VMike1** [comment]
Yes, the behavior is the same in 4.4.1.

Here is sample configuration with one host, two services, one of them is included in service group. The 'Service Status Totals' table for test-service-group shows 2 instead of 1.

define host{
        host_name       testhost1
        use             linux-server
        address         127.0.0.1
}
define service{
        use                     generic-service
        host_name               testhost1
        service_description     service in group
        check_command           check_ping!3000.0,80%!5000.0,100%
        }

define service{
        use                     generic-service
        host_name               testhost1
        service_description     service not in group
        check_command           check_ping!3000.0,80%!5000.0,100%
        }

define servicegroup{
        servicegroup_name       test-service-group
        members                 testhost1,service in group
}

**Comment by ccztux** [comment]
I can confirm this issue.

Wrong counting with status.c from maint branch:
![unpatched_version](https://user-images.githubusercontent.com/11867479/43449318-70b9be4c-94b0-11e8-8896-2284397889bd.PNG)


Fixed in my patched version (#564):
![patched_version](https://user-images.githubusercontent.com/11867479/43449345-7ba0c904-94b0-11e8-8776-94b09c6cd339.PNG)

**Comment by VMike1** [comment]
The fix #564 isn't working.
With the fix applied, the 'Service Status Totals' table works only when it is showed for service group. But when the 'Services' main menu item selected, the table shows zeroes now.

**Comment by hedenface** [comment]
Should be fixed https://github.com/NagiosEnterprises/nagioscore/commit/7fbb312c592eae7279bdb338b8c7848290cec3f3

**Comment by ccztux** [comment]
@VMike1 Thank you for pointing this out.
@hedenface Thanks for fixing it.

**Comment by hedenface** [comment]
Welcome :) Thank you for the original!

**Comment by VMike1** [comment]
Confirm that 'totals' is working in all modes.
Thanks!
