### ISSUE TITLE
Comments get doubled on nagios reload

### ISSUE THREAD

**Issue by jenhek** [NagiosEnterprises/nagioscore#549]
Hi,

looks like issue #307 is back again in 4.4.1.

We had over the last week lot's of trouble with doubled comments.

It looks as if they get doubled whenever we do config changes and send SIGUP to nagios.

Best regards, Jens

**Comment by marcr77** [comment]
Same problem here. All comments with type "Acknowledgement", "User" and "Downtime" are doubled on nagios reload. On nagios restart the comments keep as they are.

**Comment by hedenface** [comment]
The fix for this is here I believe as it was already reported on the forum. https://github.com/NagiosEnterprises/nagioscore/commit/42dd3b1e9

I thought this made it into 4.4.1, but it doesn't appear that way. Are you able to patch your system with the following and recompile:

```
sed -i 's/cleanup_downtime_data();/cleanup_downtime_data();free_comment_data();/' base/nagios.c
```

**Comment by jenhek** [comment]
Hi Bryan,

at first glance this looks good.
No more doubling after reload.

If I stay silent, it's ok.

Best regards, Jens

**Comment by hedenface** [comment]
Fixed
