### ISSUE TITLE
[feature-request]  Notification recipients

### ISSUE THREAD

**Issue by wh1test** [NagiosEnterprises/nagioscore#55]
This reature was discussed here: http://support.nagios.com/forum/viewtopic.php?f=20&t=33430
In large companies will be very useful to know how recieved this notify except you: are you alone or not?
IT managers receives e-mail notifications about bussines-critical services and they want to know how will be invloved to reslove problem. 
Could you please add to Nagios Core macro, that can be used for notification in the same way as $CONTACTNAME$ or $CONTACTGROUPMEMBERS$?

**Comment by tmcnag** [comment]
To clarify, an appropriate name for the macro might be $NOTIFIEDCONTACTS$ which could be a comma-separated list of contact aliases, names, or emails.  Possibly three macros, one for each.

**Comment by scottwilkerson** [comment]
@wh1test - The $NOTIFICATIONRECIPIENTS$ already exists

http://nagios.sourceforge.net/docs/nagioscore/4/en/macrolist.html#notificationrecipients

**Comment by tmcnag** [comment]
That's just the shortname though, doesn't list the email or full name.  I think that was the intention.

**Comment by scottwilkerson** [comment]
But once you have the shortname you can get the other info

e.g.
$CONTACTEMAIL:john$
$CONTACTNAME:john$

http://nagios.sourceforge.net/docs/nagioscore/4/en/macros.html

**Comment by scottwilkerson** [comment]
Or,

$CONTACTEMAIL:contactgroup_name:,$

**Comment by tmcnag** [comment]
Did not know about the delimiter trick, thanks!  So to take it a step further, could this be done?

`$CONTACTEMAIL:$CONTACTGROUPNAME$:,$`

In other words, can you use one macro to build up another on-demand macro?  I would imagine this would break the parsing of the dollar signs a bit and leave you with:

`$CONTACTEMAIL:$`

and

`$:,$`

**Comment by wh1test** [comment]
Thank you guys! It works!

**Comment by scottwilkerson** [comment]
Perfect!  But to answer tmcnag's question, Yes, on the command line for the command, something like the following with bachticks should work

$CONTACTEMAIL:`echo $CONTACTGROUPNAME$`:,$
