### ISSUE TITLE
LUN and FileSystem Display Issue

### ISSUE THREAD

**Issue by iFeelUing** [NagiosEnterprises/nagioscore#555]
Hi all,

I met a problem recently. I use Nagios to monitor my storage device and the web page only display the first 20 LUNs and FileSystem at its part.

the web page also shows the following information:
"There are 57 FileSystems are normal : Only 20 pieces of data can be displayed, due to the display limit. "
"There are 287 LUNs are normal : Only 20 pieces of data can be displayed, due to the display limit. "

How can I view the other LUNs and FileSystem? the web page don't provide a button "next page" or something like this.

**Comment by hedenface** [comment]
I have no idea what you're talking about, quite frankly.

What is "the web page"? What are the plugins you're using? How have you configured the host/services?

Nagios Core definitely has next/previous pages on the host/services pages (if that's what you're referring to).

Can you maybe share a screenshot?

**Comment by iFeelUing** [comment]
Hi sir,

"the web page" is the Nagios monitoring web page. And the plugin is powered by Huawei company. I also think that Nagios should support splitting page functional. but we can only see the first 20 LUNs in fact. like this:
![image](https://user-images.githubusercontent.com/15976088/42864618-a79e2cac-8a99-11e8-8254-f471f1e9c6e8.png)

I have 3000+ LUNs, but I only can see the first 20 LUNs.

**Comment by hedenface** [comment]
Can you run the plugin and count the character output please?

```
/path/to/your/plugin | wc -m
```

**Comment by iFeelUing** [comment]
Hello sir,

what kind of character output do you want to? because the command you provide seems incomplete. BTW, the plugin is installed under _/usr/local/nagios_.

**Comment by iFeelUing** [comment]
I don't know why the web page only display 20 LUNs and filesystems, at the detail page of "StorageLUN", it's still display 20 LUNs and can't go to the next page. like this:
![image](https://user-images.githubusercontent.com/15976088/42920047-7990703c-8b47-11e8-9f19-92490efd53da.png)

**Comment by box293** [comment]
> what kind of character output do you want?

Here's a plugin with full output:
```
/usr/local/nagios/libexec/check_ifoperstatus -H 10.25.4.3 -C public -k 1 -v 2 -p 161
OK: Interface tengigabitethernet1/0/1 (index 1) is up.
```

@hedenface wants you to pipe that to `wc -m` so it can count how many characters are in your output, using the example I just gave:
```
/usr/local/nagios/libexec/check_ifoperstatus -H 10.25.4.3 -C public -k 1 -v 2 -p 161 | wc -m
55
```

The number `55` is the amount of characters that was in the output.

We suspect your output for a single service is exceeding some built in limitation, we need to know how many characters are being produced by the plugin.

**Comment by iFeelUing** [comment]
Hello Sir,
the output is below.
```
/usr/local/nagios/libexec/check_ifoperstatus -H 8.44.160.97 -C public -k 1 -v 3 -p 161 | wc -m
309
```

**Comment by box293** [comment]
So the example I gave was just an example, you need to replace everything before `| wc -m` with your plugin and arguments, the one that is generating all the output.

```
/usr/local/nagios/your_plugin with_arguments | wc -m
```

**Comment by iFeelUing** [comment]
Hi Sir,

I run the command using Huawei plugin:
```
[root@localhost huawei]# python checkarray.py checklun -h 8.44.160.97 -c huawei@123 -v v3 -p 10062 |wc -m
1206
```

**Comment by scottwilkerson** [comment]
So if you just run the following what is displayed?

`python checkarray.py checklun -h 8.44.160.97 -c huawei@123 -v v3 -p 10062`
