### ISSUE TITLE
notification count isn't resetting

### ISSUE THREAD

**Issue by cdienger** [NagiosEnterprises/nagioscore#557]
See https://support.nagios.com/forum/viewtopic.php?t=49412#256607 . I've been able to reproduce the behavior on 4.4.1 master and maintenance.

**Comment by scottwilkerson** [comment]
Looks like these lines didn't all get in the refactoring to reset current_notification_number and possibly others:
https://github.com/NagiosEnterprises/nagioscore/blob/nagios-4.3.4/base/checks.c#L740
and 
https://github.com/NagiosEnterprises/nagioscore/blob/nagios-4.3.4/base/checks.c#L3053

**Comment by scottwilkerson** [comment]
I believe this may be related on an XI system
https://support.nagios.com/forum/viewtopic.php?f=16&t=49630

**Comment by scottwilkerson** [comment]
and this
https://support.nagios.com/forum/viewtopic.php?t=49678#258386

**Comment by scottwilkerson** [comment]
I believe this to be currently resolved in the maint branch
https://github.com/NagiosEnterprises/nagioscore/tree/maint

**Comment by a7ger** [comment]
this has been fixed with update 4.4.2
