### ISSUE TITLE
[feature-request] Nagios contacts case-insensitive

### ISSUE THREAD

**Issue by wh1test** [NagiosEnterprises/nagioscore#56]
I use LDAP for authorization in GUI. Users (contacts and their groups) associated with the hosts/services.
When user input for example "Petr" and own ldap password, he loggined but can't see any information.
When user input "petr" (as specidied in contacts.cfg), rhen everything OK - he can see information.

Could you please add possibility to use case-insensitive contacts for user authorization?

More information discribed here: http://support.nagios.com/forum/viewtopic.php?f=34&t=33478

**Comment by jfrickson** [comment]
We discussed this internally, and decided it's potentially too disruptive.
