### ISSUE TITLE
Enable json api to find empty hostgroups etc

### ISSUE THREAD

**Issue by willemdh** [NagiosEnterprises/nagioscore#57]
Hello,
It seems the json api does not find empty hostgroups, which can be very confusing while scripting. For example someone makes a new hostgroup for an application. Automated script are looping through all hostgroups to assign them, but don't find the empty hostgroups. 
Workaround would be to assign a dummy host while creating the hostgroup, but this is 'sloppy' work imho. Enabling the json api to find empty hostgroups would the 'logical' step.
Grtz
Willem

**Comment by estanley375** [comment]
Nagios core optimizes out empty hostgroups (why keep something you'll never use), so by the time the JSON API queries for hostgroups, the empty ones no longer exist.

**Comment by willemdh** [comment]
But you could use them in the future. If you would not need it, you would just delete the hostgroup. 
This is very unlogical to me. If it is not technically possible, you can close this issue.
Thanks and grtz.

**Comment by scottwilkerson** [comment]
It's not technically possible fron the Core json api, this would be something that you would need to get from a configuration DB.

As such I am closing the issue.
