### ISSUE TITLE
nagios 4.4.2 fails to set critical hard

### ISSUE THREAD

**Issue by jenhek** [NagiosEnterprises/nagioscore#576]
we had a no so incident this weekend where Nagios 4.4.2 failed to sent out alarms

the attempt_counter gets incremented but the state does NOT change from
critical-soft to critical-hard

in a second incident some hours later Nagios worked as expected.

Here are the logs from Nagios:

--------------------------------------------------------------------
<pre>
Service Ok[2018-09-02 04:34:38] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;OK;HARD;1;OK: 344
Service Warning[2018-09-02 04:29:38] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;HARD;5;WARNING: 357
Service Critical[2018-09-02 03:39:38] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;HARD;5;CRITICAL: 360
Service Warning[2018-09-02 03:38:38] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;SOFT;4;WARNING: 357
Service Warning[2018-09-02 03:37:38] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;SOFT;3;WARNING: 358
Service Warning[2018-09-02 03:36:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;SOFT;2;WARNING: 354
Service Warning[2018-09-02 03:35:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;SOFT;1;WARNING: 355
Service Ok[2018-09-02 01:55:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;OK;HARD;1;OK: 348
Service Warning[2018-09-02 01:54:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;SOFT;1;WARNING: 358
Service Critical[2018-09-02 01:53:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 364
Service Critical[2018-09-02 01:52:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 368
Service Critical[2018-09-02 01:52:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 368
Service Critical[2018-09-02 01:51:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 376
Service Critical[2018-09-02 01:50:37] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 385
Service Critical[2018-09-02 01:49:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 397
Service Critical[2018-09-02 01:48:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 405
Service Critical[2018-09-02 01:47:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 420
Service Critical[2018-09-02 01:46:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 437
Service Critical[2018-09-02 01:45:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 461
Service Critical[2018-09-02 01:44:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 490
Service Critical[2018-09-02 01:43:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 505
Service Critical[2018-09-02 01:42:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 523
Service Critical[2018-09-02 01:41:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 548
Service Critical[2018-09-02 01:40:36] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 558
Service Critical[2018-09-02 01:39:35] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 563
[...]
Service Critical[2018-09-01 21:22:07] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 375
Service Critical[2018-09-01 21:21:07] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 378
Service Critical[2018-09-01 21:20:07] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 375
Service Critical[2018-09-01 21:19:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 372
Service Critical[2018-09-01 21:18:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 369
Service Critical[2018-09-01 21:17:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 372
Service Critical[2018-09-01 21:16:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 367
Service Critical[2018-09-01 21:15:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 366
Service Critical[2018-09-01 21:14:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;5;CRITICAL: 366
Service Critical[2018-09-01 21:13:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;4;CRITICAL: 361
Service Critical[2018-09-01 21:12:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;CRITICAL;SOFT;3;CRITICAL: 361
Service Warning[2018-09-01 21:11:06] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;SOFT;2;WARNING: 359
Service Warning[2018-09-01 21:10:05] SERVICE ALERT: mes-sw23-kh.env;Temp zwischen S24 und S25;WARNING;SOFT;1;WARNING: 353
</pre>
--------------------------------------------------------------------

The room reached 56.3 degrees Celsius (133 degrees Fahrenheit)

We should have received an alarm at 21:14, but only got one at 03:39

There is something really broken in the code for state transitions
and we went back to Nagios 4.3.4 as we had other not so nice bugs in 4.4.X

Severity: critical

**Comment by jomann09** [comment]
Patch was applied to make this work however it messes with the tests. So there is likely more to change in order to have this fully functional.

**Comment by jomann09** [comment]
Closing this, it seems to be working now in maint, so will be in 4.4.3
