### ISSUE TITLE
RC 4.1.0 - install instructions will need to include installing unzip

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nagioscore#58]
While running 'make all' on a CentOS 6.6 machine I came across this:

```
make[1]: Entering directory `/tmp/nagios-4.1.0rc1/html'
(cd angularjs && unzip angular-1.3.9.zip)
/bin/sh: unzip: command not found
make[1]: *** [all] Error 127
make[1]: Leaving directory `/tmp/nagios-4.1.0rc1/html'
make: *** [all] Error 2
```

Doing:

```
yum -y install unzip
```

Allowed 'make all' to complete successfully.

**Comment by tmcnag** [comment]
To be clear, are you referring to the SourceForge install docs?

http://nagios.sourceforge.net/docs/nagioscore/4/en/quickstart.html

Our `INSTALLING` file just points to the `html/docs/` directory, which in turn points to that link.  Just want to make sure 'were talking about the same install instructions.

Personally, I think the use of a .zip file on a non-Windows machine is gross.  It's a little more work, but converting the .zip files into .tar.gz would help a lot with portability and consistency.

**Comment by box293** [comment]
On this webpage https://www.nagios.org/download/core/thanks/?t=1436160562 it provides a link https://library.nagios.com/library/products/nagioscore/documentation/567-installing-nagios-core-from-source to this installation documentation https://assets.nagios.com/downloads/nagioscore/docs/Installing_Nagios_Core_From_Source.pdf

**Comment by tmcnag** [comment]
Ahh, understood.  That's easier to fix at the moment, I'll see about getting that updated.

We are currently in the middle of reworking our docs, so a lot of what's out there currently is either going to be rewritten from scratch or modified and updated.

**Comment by nook24** [comment]
Maybe you can add a check to the configure, same issue on ubuntu

**Comment by jfrickson** [comment]
I'll add a check for `unzip` to `configure`.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/f61ed03682ad9be213b2e30d69c9cb5297802e11
