### ISSUE TITLE
In 4.4.2 services go directly into HARD state if host is SOFT DOWN

### ISSUE THREAD

**Issue by scottwilkerson** [NagiosEnterprises/nagioscore#584]
From this thread, and reproduced internally
https://support.nagios.com/forum/viewtopic.php?f=7&t=50384

If a host goes down and the service cannot be reached, when the service results are processed after it is determined that the host is not up, the host is going into a SOFT down state while the service goes into a HARD CRITICAL even if it has not reached it's max check attempts.

This triggers the service to prematurely send a notification even though the host is in a SOFT down.

**Comment by ziggimon** [comment]
I'm seeing this same behaviour:

```
[1537427537]HOST ALERT: testhost.server.local;DOWN;SOFT;1;CRITICAL - IP:x.x.x.x: rta nan, lost 100%
[1537427537] GLOBAL HOST EVENT HANDLER: testhost.server.local;DOWN;SOFT;1;eventhandler-host
[1537427600] GLOBAL HOST EVENT HANDLER: testhost.server.local;DOWN;SOFT;2;eventhandler-host
[1537427663] SERVICE ALERT: testhost.server.local;RDP;CRITICAL;HARD;1;CRITICAL - Socket timeout
[1537427663] GLOBAL SERVICE EVENT HANDLER: testhost.server.local;RDP;CRITICAL;HARD;1;eventhandler-service
[1537427664] GLOBAL HOST EVENT HANDLER: testhost.server.local;DOWN;SOFT;3;eventhandler-host
[1537427667] SERVICE ALERT: testhost.server.local;MasterAdmin QuotaHelper;UNKNOWN;HARD;1;ERROR: Process name table : No response from remote host "IP:x.x.x.x".
[1537427667] GLOBAL SERVICE EVENT HANDLER: testhost.server.local;MasterAdmin QuotaHelper;UNKNOWN;HARD;1;eventhandler-service
[1537427726] SERVICE NOTIFICATION: user;testhost.server.local;RDP;CRITICAL;notify-service-by-email;connect to address IP:x.x.x.x and port 3389: No route to host
[1537427726] SERVICE NOTIFICATION: user;testhost.server.local;RDP;CRITICAL;notify-log;connect to address IP:x.x.x.x and port 3389: No route to host
[1537427726] SERVICE NOTIFICATION: user;testhost.server.local;RDP;CRITICAL;notify-service-by-email;connect to address IP:x.x.x.x and port 3389: No route to host
```

Where our service goes HARD;1 on first probe while host is in a soft state.

Service definition:
```
define service{
    service_description RDP
    retry_interval 1 ; Re-check the service every two minutes until a hard state can be determined
    retain_status_information 1 ; Retain status information across program restarts
    retain_nonstatus_information 1 ; Retain non-status information across program restarts
    process_perf_data 1 ; Process performance data
    passive_checks_enabled 1 ; Passive service checks are enabled/accepted
    parallelize_check 1 ; Active service checks should be parallelized (disabling this can lead to major performance problems)
    obsess_over_service 1 ; We should obsess over this service (if necessary)
    notification_period 24x7 ; Notifications can be sent out at any time
    notification_options w,c,r ; Send notifications about warning, unknown, critical, and recovery events
    notification_interval 0 ; Re-notify about service problems every hour
    notifications_enabled 1 ; Service notifications are enabled
    max_check_attempts 5 ; Re-check the service up to 3 times in order to determine its final (hard) state
    is_volatile 0 ; The service is not volatile
    freshness_threshold 3600 ; 1 hour
    flap_detection_enabled 1 ; Flap detection is enabled
    event_handler_enabled 1 ; Service event handler is enabled
    check_period 24x7 ; The service can be checked at any time of the day
    check_interval 5 ; Check the service every 10 minutes under normal conditions
    check_freshness 1 ; Default is to NOT check service 'freshness'
    active_checks_enabled 1 ; Active service checks are enabled
    check_command check_tcp!3389
    host_name testhost.server.local
    hostgroup_name windows
}
```

Host definition:
```
define host{
    retry_interval 1
    retain_status_information 1 ; Retain status information across program restarts
    retain_nonstatus_information 1 ; Retain non-status information across program restarts
    process_perf_data 1 ; Process performance data
    notification_period 24x7
    notification_options d,u,r,f
    notification_interval 0
    notifications_enabled 1 ; Host notifications are enabled
    max_check_attempts 5
    flap_detection_enabled 1 ; Flap detection is enabled
    event_handler_enabled 1 ; Host event handler is enabled
    contact_groups sysadmins,onduty,udvikling
    check_period 24x7
    check_interval 1
    check_command check-host-alive
    host_name testhost.server.local
    alias testhost.server.local
    address x.x.x.x
    hostgroups all,diskusage,windows
}
```

**Comment by ziggimon** [comment]
This bug has been hindering me upgrading to the latest core and patch for the current CVE's. Is there any incoming release that we may see soon that includes a fix for this issue?

**Comment by jomann09** [comment]
I did a little bit of digging on this because I remember talking about what was supposed to happen when a host was in a DOWN state. This document is what was followed in 4.4 https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/statetypes.html

The doc says that a HARD state occurs:
```
When a service check results in a non-OK state and its corresponding host is either DOWN or UNREACHABLE.
```

Now this doesn't actually say if the host needs to be SOFT or HARD down but from testing 4.2 and 4.3 it seems like Core never actually did this. It looks like it goes into a SOFT state and normal service checks would happen but no notification would send.

Reading through the logic, it looks like the notifications are getting triggered for this state change and that is likely a separate bug. I will have to consult with a few people to determine if this should be an intended feature (direct to HARD) or if we should stick with how it's worked. I also need to do a little bit of testing on other past Core systems to see how it handles this and if it follows this logic or not.

**Comment by jomann09** [comment]
I found in the logic where it was automatically sending a notification out from hard state change and it should no longer do that with the patch above. Will test this in maint branch. Service will still go directly into a HARD state if the host is DOWN or UNREACHABLE.

**Comment by jomann09** [comment]
Okay I think this is properly fixed now. States do turn into HARD states after 1 check attempt and they do not notify while host is DOWN. Need to do a bit more testing but this seems like what is intended.

**Comment by ziggimon** [comment]
I really appreciate this. The main pain was the notifications that the entire on call staff got when hosts got rebooted. And the ignoring of the 5 down ticks before services were sending notifications. Looking forward to testing this out soon.

**Comment by jomann09** [comment]
This should be good to go, we're testing it internally and you can test it too if you'd like using the maint branch.
