### ISSUE TITLE
./configure --with-cgibindir and --width-webdir do nothing.

### ISSUE THREAD

**Issue by lawsontyler** [NagiosEnterprises/nagioscore#585]
Testing against the `master` branch, as well as the 4.4.2 release.

According to the `./configure --help`:
```
...
  --with-webdir=DIR       where the website files should be placed
  --with-cgibindir=DIR    where the CGI programs should be placed
...
```
I then do the usual thing:

```
./configure --prefix=/usr/local/nagios \
    --with-webdir=/var/www/html/nagios \
    --with-cgibindir=/var/www/html/nagios/cgi-bin
make all
make install
```

However, I find my HTML in ${prefix}/share and my CGIs in ${prefix}/sbin. 

In all the `Makefile.in` files, it uses `@datarootdir@` and `@sbindir@` for HTMLDIR and CGIDIR, respectively.

This causes installation from source to _always_ place my HTML in ${prefix}/share and my CGIs in ${prefix}/sbin.

I've prepared a fix on my fork and would like to submit a PR for changing these macros to `@webdir@` and `@cgibindir@` across all Makefile.in files.

**Comment by jomann09** [comment]
Thanks for the merge request, I will test it and it should be added into 4.4.3

**Comment by jomann09** [comment]
Merged this into maint.
