### ISSUE TITLE
Creating multiple pages based on service name

### ISSUE THREAD

**Issue by ecnazim** [NagiosEnterprises/nagioscore#588]
HI,

I am not able to separate or create the multiple problem pages in Nagios. Can anyone help me to get this done?

i want to separate the critical scenarios based on the service name!!

![capture](https://user-images.githubusercontent.com/36113198/47634133-57c5ba00-db76-11e8-9c34-270df5ac79de.JPG)

**Comment by ericloyd** [comment]
I'm not sure exactly what you mean, but if you are trying to organize services into groups that you can look at or manage as a unit, then look at service groups.  You can take multiple services (such as all of your Apache processes, for instance, if you have any) and group them into a service group called "Apache Services."  You can then monitor, track, and report on that group (or any other group) as a unit.

Is this what you mean?

**Comment by ericloyd** [comment]
Glad to help.
