### ISSUE TITLE
Nagios core 4.4.2 

### ISSUE THREAD

**Issue by aristech47** [NagiosEnterprises/nagioscore#589]
What I am looking for is the steps I need to take to give my admin staff access to see only the equipment they manage. Right now I have created test account to try and get it working with but for some reason I can only see all devices or just the localhost.

**Comment by ericloyd** [comment]
This is a common issue with Nagios Core.  Basically, if someone authenticates to the web interface with the same email address as a contact's email address within Nagios, then any host/service that that contact gets notifications for will be visible within the interface.

So human -> email -> .htaccess -> contact's email -> notifications -> host/service.
