### ISSUE TITLE
Segmentation fault - RHEL 7 / CENTOS 7

### ISSUE THREAD

**Issue by djgel** [NagiosEnterprises/nagioscore#59]
Hi,  Try start a Nagios 4.1RC or 4.0.8 in Centos7  but after start get error um Message log:

Jun 26 18:17:10 svdf01238 kernel: nagios[48797]: segfault at 0 ip 00007f29d992158c sp 00007fff782cb728 error 4 in libc-2.17.so[7f29d98a1000+1b6000]

In debug:

[1435353430.934346] [2048.2] [pid=48797] Processing macro 155 of 156
[1435353430.934348] [2048.2] [pid=48797] Grabbing value for macro: HOSTANDSERVICESIMPORTANCE
[1435353430.934351] [2048.2] [pid=48797] Adding macro "HOSTANDSERVICESIMPORTANCE" with value "0" to kvvec
[1435353430.934354] [001.2] [pid=48797] add_macrox_environment_vars_r() end
[1435353430.934357] [001.1] [pid=48797] add_argv_macro_environment_vars_r()
[1435353430.934370] [001.1] [pid=48797] add_custom_macro_environment_vars_r()
[1435353430.934379] [001.1] [pid=48797] add_contact_address_environment_vars_r()
[1435353430.934437] [001.0] [pid=48797] clear_volatile_macros_r()

In process started:

Successfully launched command file worker with pid 49466
Segmentation fault

Packs um Centos 7 :+1: 

glibc-headers-2.17-78.el7.x86_64
libcom_err-devel-1.42.9-7.el7.x86_64
glibc-common-2.17-78.el7.x86_64
libcap-2.22-8.el7.x86_64
libcap-ng-0.7.3-5.el7.x86_64
glibc-2.17-78.el7.x86_64
glibc-devel-2.17-78.el7.x86_64
libcom_err-1.42.9-7.el7.x86_64

**Comment by scottwilkerson** [comment]
Is this a vanilla install or do you have custom brokers installed (ie mod_gearman, livestatus,, etc.)?

I ask because we have had 1000s of users using Core 4.0.8 on CentOS 7 and haven't seen this internally, or had any other reports, and 4.0.8 has been out for a year.

**Comment by djgel** [comment]
use NDOUTILS ... but remove this and give same error.

Compile with this command:
./configure --prefix=/usr --exec-prefix=/usr/sbin --bindir=/usr/sbin --sbindir=/usr/lib/nagios/cgi --libexecdir=/usr/lib/nagios/plugins --datadir=/usr/share/nagios --sysconfdir=/etc/nagios --localstatedir=/var/lib/nagios --with-init-dir=/etc/rc.d/init.d --with-cgiurl=/nagios/cgi-bin --with-htmurl=/nagios --with-lockfile=/var/run/nagios.pid --with-nagios-user=nagios --with-nagios-group=nagios --with-file-perfdata --with-command-group=nagcmd

**Comment by scottwilkerson** [comment]
I just tested the following on a fresh minimal CentOS7 system with no segfaults

    yum install gcc glibc glibc-common gd gd-devel make net-snmp openssl-devel unzip httpd php -y

    curl -L -O http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.0.8.tar.gz
    tar xvf nagios-*.tar.gz
    cd nagios-*
    sudo useradd nagios
    sudo groupadd nagcmd
    sudo usermod -a -G nagcmd nagios
    ./configure --prefix=/usr --exec-prefix=/usr/sbin --bindir=/usr/sbin --sbindir=/usr/lib/nagios/cgi --libexecdir=/usr/lib/nagios/plugins --datadir=/usr/share/nagios --sysconfdir=/etc/nagios --localstatedir=/var/lib/nagios --with-init-dir=/etc/rc.d/init.d --with-cgiurl=/nagios/cgi-bin --with-htmurl=/nagios --with-lockfile=/var/run/nagios.pid --with-nagios-user=nagios --with-nagios-group=nagios --with-file-perfdata --with-command-group=nagcmd
    make all
    make install
    make install-commandmode
    make install-init
    make install-config
    make install-webconf
    service nagios start
    service httpd start

**Comment by tmcnag** [comment]
Are you using the standard localhost-only configs or is this a production install?  Can you tar up your configs and post them somewhere?  I am wondering if one of the macros is causing the segfault.

**Comment by djgel** [comment]
is a production facility ... was actually migrating rhel server 6 (because I'm having problems with OS) and taking the opportunity to move to rhel 7. Use the Centreon 2.6 to manage / create settings only. ...

**Comment by scottwilkerson** [comment]
As we cannot recreate this and the OP may have conflicting software, I'm closing the issue.  If it can be re-created on a base install, please open a new issue.

Thanks!

**Comment by djgel** [comment]
Centreon 2.6.0 insert TAG "_CRITICALITY_LEVEL" and "_CRITICALITY_ID" um Services ... make a segfault in nagios

**Comment by tmcnag** [comment]
Do you mean it sets a custom variable?

http://nagios.sourceforge.net/docs/nagioscore/4/en/customobjectvars.html

**Comment by djgel** [comment]
Trevor,

i know, but Nagios not start with this custom variables ... If commented,
this start without Segfault in libc .... This variable is create by
Centreon to change severity server or service.

2015-06-30 16:25 GMT-03:00 Trevor McDonald <notifications@github.com>:

**Comment by scottwilkerson** [comment]
You would need to talk to their developers... We are Nagios, and can only account for Nagios code
