### ISSUE TITLE
Core 4.4.2 last_state_change doesn't update when switching to hard state

### ISSUE THREAD

**Issue by cdienger** [NagiosEnterprises/nagioscore#592]
last_state_change doesn't get updated with the time of the last hard state change.

**Comment by jenhek** [comment]
sounds like issue 576

nagios 4.4.X is pretty unusable here.

**Comment by jomann09** [comment]
I updated maint with a patch for soft state changes but it looks like we will need to do a few more changes and test them/make sure the tests pass also - it seems like some of the logic was causing the hard state not to register properly. Working on trying to get a 4.4.3 out soon.

**Comment by jomann09** [comment]
So the fix for #576 does not necessarily fix this because it looks intentional. Getting more information on this but the test that is ran to validate that everything is working properly specifically tests for the last_state_change not to change when SOFT -> HARD service state changes.

**Comment by jomann09** [comment]
This is fixed and will be in 4.4.3 - this seems to be something that has been in at least Core 4.2 and above so I am not sure when this happened but according to the docs this is considered a state change so we should be setting last_state_change properly for it.
