### ISSUE TITLE
Scheduled downtime bugs

### ISSUE THREAD

**Issue by gzalo** [NagiosEnterprises/nagioscore#595]
Hi. We've found a couple of related bugs regarding scheduled downtimes:

### Downtimes with triggers only react to new events
Steps to reproduce:
* Schedule a fixed downtime for a host (with start time in the past). As expected, the downtime will be "in effect", because the start time is older than the current timestamp.
* Schedule a flexible downtime for another host (any start time) triggered by the previous downtime. 
I was expecting the new downtime to be already activated, but it was inactive. I think it has to do with it not being present when the first downtime was activated. 

I'm not sure if this is expected behavior or a bug, but it's quite annoying and prevents setting up triggered downtimes for hosts that are already down/unreacheable.

### Reload deletes downtime
With the same scheduled downtime configuration mentioned previously, if one restarts the Nagios service the flexible downtime will dissapear!

Before:
![cap1](https://user-images.githubusercontent.com/538127/49091021-c2354d00-f23d-11e8-9138-62bc7c6bc612.PNG)

After:
![cap2](https://user-images.githubusercontent.com/538127/49091032-c6616a80-f23d-11e8-9220-5c56528cb653.PNG)

Log (shows as if the downtime had started and ended in the same time):
```
[1543330972] Nagios 4.4.2 starting... (PID=23479)
[1543330972] Local time is Tue Nov 27 12:02:52 -03 2018
[1543330973] ndomod: NDOMOD 2.1.2 (11-14-2016) Copyright (c) 2009 Nagios Core Development Team and Community Contributors         
[1543330973] ndomod: Successfully connected to data sink.  0 queued items to flush.  
[1543330973] ndomod registered for process data  
...
[1543330973] Event broker module '/usr/local/nagios/bin/ndomod.o' initialized successfully.         
...
[1543330973] HOST DOWNTIME ALERT: Daft;STARTED; Host has entered a period of scheduled downtime
[1543330973] HOST DOWNTIME ALERT: Dummy;STARTED; Host has entered a period of scheduled downtime
[1543330973] HOST DOWNTIME ALERT: Dummy;STOPPED; Host has exited from a period of scheduled downtime
...
```

### Availability reports breaks when a DOWNTIME starts and ends in the same timestamp

Using the same log descripted before, when one attempts to calculate the availability of the host which had the buggy flexible downtime, this happens:

![cap3](https://user-images.githubusercontent.com/538127/49091092-e4c76600-f23d-11e8-92a3-91491b076dae.PNG)

It seems like the downtime start and end events are swapped, so the report supposes that the initial state was in downtime. This causes errors in the calculation of Scheduled and Unscheduled times, as it can be seen here:

![cap4](https://user-images.githubusercontent.com/538127/49091100-e8f38380-f23d-11e8-8641-1eea39b77d10.PNG) 

We are testing using Core 4.4.2 on CentOS 7.5
Thanks, Gonzalo

**Comment by jomann09** [comment]
I believe the availability report works properly now (in the `avail-downtime-fixes` branch) when the host downtime end/start are right after one another. However, I am not sure what the reasoning is for the flexible downtime going away/the end/start times. Will have to test this to find out.

**Comment by tsadpbb** [comment]
Seems there is some weird bug when a downtime is both triggered and flexible, what is the expected behavior here?
