### ISSUE TITLE
Attempt to run "make clean" fails on aarch64 (ARM) architecture.

### ISSUE THREAD

**Issue by garethrandall** [NagiosEnterprises/nagioscore#598]
The contrib/Makefile.in file assumes that the build architecture will be either x86_64 or i686. If an attempt is made to build on aarch64 (ARM) then "make clean" fails.

I previously submitted a pull request to resolve this issue:
https://github.com/NagiosEnterprises/nagioscore/pull/587

Thanks.

**Comment by jomann09** [comment]
Pulled this in, will be in the 4.4.3 release.
