### ISSUE TITLE
log_host_retries parameter is ignored

### ISSUE THREAD

**Issue by gzalo** [NagiosEnterprises/nagioscore#599]
Hi
I've found that in the latest version, the log_host_retries variable is ignored. I think this happened after someone rewrote base/checks.c, which used that variable.

For instance, here is an older version that used this variable:
https://github.com/NagiosEnterprises/nagioscore/blob/0217319ba0011efb0a3fd3837461cb61dba535b4/base/checks.c#L3255

It could be fixed by adding the corresponding lines into base/logging.c, in a way similar to how log_host_event is handled.

Thanks, Gonzalo

**Comment by jomann09** [comment]
This is likely a bug, I will look into it.

**Comment by jomann09** [comment]
This is definitely a bug, working on a fix, should be in 4.4.3
