### ISSUE TITLE
command_line with $ breaks $ARGn$ macros

### ISSUE THREAD

**Issue by ChrisLundquist** [NagiosEnterprises/nagioscore#60]
A basic auth password had a single $ in it. This lead to unexpected breakage of $ARGn$

```
define service {                                                                                      
  service_description example.com-exceptions                                                         
  host example.com                                                                         
  use generic-service                                                                                 
  check_command check_graphite_data!sumSeries(stats.example-com-*.action_controller.status.5*)!1!5!30
}
```
```
define command {                                                                             
    command_name check_graphite_data                                                         
    command_line echo 'http://user:pas$word@example.com/$ARG1$' -w $ARG2$ -c $ARG3$ -s $ARG4$
}
```

The above configuration snippet generated the following:
![screen shot 2015-06-29 at 6 12 54 pm](https://cloud.githubusercontent.com/assets/181256/8422014/fc2aa6fc-1e8a-11e5-800a-07501a3dd3a3.png)

I expected:
```
echo  'http://user:pas$word@example.com/sumSeries(stats.example-com-*.action_controller.status.5*) -w 1 -c 5 -s 30
```

After a deep dive in the docs, the only indication I found that this might be illegal was http://nagios.sourceforge.net/docs/nagioscore/4/en/configmain.html#illegal_macro_output_chars

But I don't think that applies as it pertains to *generated* characters from macros rather than characters that might be interpreted as macros.

I tried escaping `$` to no avail, e.g.

```
define command {                                                                             
    command_name check_graphite_data                                                         
    command_line echo 'http://user:pas\$word@example.com/$ARG1$' -w $ARG2$ -c $ARG3$ -s $ARG4$
}
```

It turns out, to "fix" this is to have `$$`. I can find no documentation on escaping `$` in a command_line and believe this to be a bug as well. To make the initial example "work", you would need:

```
define command {                                                                             
    command_name check_graphite_data                                                         
    command_line echo 'http://user:pas$$word@example.com/$ARG1$' -w $ARG2$ -c $ARG3$ -s $ARG4$
}
```

I fear some future person, probably myself, might attempt to fix this "typo".

```
nagios --version
Nagios Core 4.0.8
```

If this behavior is expected, please show me the relevant doc pages and close this issue.

**Comment by tmcnag** [comment]
http://nagios.sourceforge.net/docs/3_0/objectdefinitions.html#command

"Also, if you want to pass a dollar sign ($) on the command line, you have to escape it with another dollar sign."

**Comment by ChrisLundquist** [comment]
Thank you! I know how frustrating issues like these can be, and apologize. Next time I'm frustrated, I promise to take a break and look at the docs again with a fresh set of eyes.
