### ISSUE TITLE
process_passive_service_check host/service confusion

### ISSUE THREAD

**Issue by gzalo** [NagiosEnterprises/nagioscore#601]
Hi. I've found a small bug when writing logging info about a host that is not found, that might cause confusion:

```
/* we couldn't find the host */
	if(temp_host == NULL) {
		log_debug_info(DEBUGL_CHECKS, 0, 
			"Passive check result was received for service '%s' on host '%s', but the service could not be found!\n", 
			svc_description, host_name);
		logit(NSLOG_RUNTIME_WARNING, TRUE, 
			"Warning:  Passive check result was received for service '%s' on host '%s', but the service could not be found!\n", 
			svc_description, host_name);
		return ERROR;
		}
```

https://github.com/NagiosEnterprises/nagioscore/blob/345fd4e8257085ce7f3806ee4fb04008919f24e5/base/commands.c#L2378

In order to make troubleshooting easier, I think that the message should say **"the host could not be found!"**, as it was in older versions (for instance 4.2.4)

Thanks, Gonzalo

**Comment by jomann09** [comment]
Fixed this for Core 4.4.3 in commit 5e101ca8351213d419ef73a0d199182978289d76
