### ISSUE TITLE
Send alert messages through Followzup, instead of SMS

### ISSUE THREAD

**Issue by RCB2015** [NagiosEnterprises/nagioscore#61]
The purpose of this feature request is to enable sending alert messages through the service followzup, instead of sending with SMS. The service is an open protocol communication service, designed to support alert messages sent to the cell phones.
The process begin with the creation of a channel information (private or public), through which the messages are sent. Once created, the administrator downloads the channel's request function (PHP file) used to assist Nagios requests, which must be "included" by Nagios send-message script.
At last, Nagios calls the request function, with the message's text to be sent. Once requested, the message is redirected to the administrator's cell phone (source: followzup.com).
As the service is a cheap alternative for resources managers, I would like you to please, add this feature to Nagios, showing where the followzup function must be stored and the customized script to send messages through this function.

"Related to the post sent to Nagios Support Forum (Fri Jun 26, 2015 3:38 pm), under the title: Send alert messages through followzup, instead of SMS", and oriented by Nagios Sales Tech.

**Comment by tmcnag** [comment]
This does not need to be implemented in Core itself, as this is exactly what notification commands are for:

http://nagios.sourceforge.net/docs/3_0/notifications.html
http://nagios.sourceforge.net/docs/3_0/objectdefinitions.html#command

To implement this, you would need to write a script that handles all of the followzup logic, then use this script in your notification command.
