### ISSUE TITLE
I want to change the Nagios port from 80 to 8081

### ISSUE THREAD

**Issue by ecnazim** [NagiosEnterprises/nagioscore#615]
Hi,

I am running nginx and Nagios in the same AWS instance. But both needed 80 port number. I want to change the port number of Nagios from 80 to 8081

I tried making changes in /etc/httpd/conf/httpd.conf from LISTEN 80 to LISTEN 8081 but the Nagios status page isn't working.

Please help.

**Comment by mcapra** [comment]
I would suggest posting this to the support forums:
https://support.nagios.com/forum/

**Comment by jomann09** [comment]
Did you end up posting on the forums about this? What is the URL (you can remove ip/hostname) that you're going to for the page that isn't working?
