### ISSUE TITLE
Nagios Start service is failing on CentOS

### ISSUE THREAD

**Issue by waqar-haider-confiz** [NagiosEnterprises/nagioscore#618]
Nagios restart service is failing with the error:

/etc/init.d/nagios: line 153: syntax error near unexpected token `}'

It's only happening on CentOS (6x); For Ubuntu & Redhat this issue does not occur.

Code at line 153: 
printstatus_nagios ()
{
        if status_nagios; then
	status_nagios $1 $2
	RETVAL=$?
	if [ $RETVAL = 0 ]; then
		echo "nagios (pid $NagiosPID) is running..."
	else
		echo "nagios is not running"
	fi
	return $RETVAL
}

There is no **fi** for **if status_nagios; then** statement . 

Please update

**Comment by MHP47** [comment]
What version are you running? How did you upgrade/ install? Through packages or compilation? Did you use a walkthrough? If so, which one?

**Comment by jomann09** [comment]
Looks like the file was a bit corrupt (maybe having been edited, not sure) but that section should look like this https://github.com/NagiosEnterprises/nagioscore/blob/master/startup/default-init.in#L139

Tested and verified it is working in the latest version.
