### ISSUE TITLE
Reloading Nagios 4.4.3 creates defunct processes

### ISSUE THREAD

**Issue by nook24** [NagiosEnterprises/nagioscore#620]
Hi,

when ever I try to reload my Nagios Core 4.4.3 after the `systemctl reload nagios` command my Nagios leave some `[nagios] <defunct>` processes behind.

I have tested this on Debian 9, Ubuntu 16.04 and Ubuntu 18.04. All systems show the same behavior. I also created a script which will deploy a Nagios Core to reproduce the issue.

Most of the time, this happens on the first reload. If not, just reload Nagios again.

Steps to reproduce:

1. Fresh Ubuntu (or Debian) system
2. Deploy Nagios by running
```
curl https://gist.githubusercontent.com/nook24/5324badb989975a4ff8882244f205048/raw/5304b79bd997b0bb65516bc77271916b55aa8ce4/deplay_nagios_core.sh | sudo /bin/bash
```
3. Reload nagios `systemctl reload nagios` 

I also tested this on KVM:
<img width="825" alt="nagios_4 4 3_defunct_kvm" src="https://user-images.githubusercontent.com/9019992/52472789-75061d80-2b94-11e9-8e86-55090b561474.png">

And LXC:
<img width="1043" alt="nagios_4 4 3_defunct_lxc" src="https://user-images.githubusercontent.com/9019992/52472795-7afbfe80-2b94-11e9-9234-33fa780d8cdf.png">

I know there was a bug... May be I am just missing something?
https://github.com/NagiosEnterprises/nagioscore/issues/442#issuecomment-395722593

`/opt/nagios/bin/nagios --version` reports `Nagios Core 4.4.3`

**Comment by nook24** [comment]
Looks like #442 is back in Version 4.4.3. I will check this over the weekend

**Comment by Madlohe** [comment]
This is very similar to #441, see my last comment there for a potential (non-ideal) fix. #442 does look like it could be related, in which case the change I made for #635 is probably not correct either.

**Comment by HarshitaJain09** [comment]
Hi 
We are also facing the same issue on AIX . When we are trying to run Nagios so many defunct process are generating.

**Comment by Madlohe** [comment]
Would either of you be willing to try compiling from https://github.com/Madlohe/nagioscore/tree/bug-441/defunct-processes-on-reload and verify that this fixes the issue for you? It works on my machine but since we've had issues like this before I'd like to check with you before closing.

**Comment by nook24** [comment]
@Madlohe this resolved the issue for me on Ubuntu, thanks.
 
Even if I'm unsure about how reliable `sleep(1);` can resolve this...

**Comment by Madlohe** [comment]
Thanks @nook24!

I agree, we'll keep an eye on this issue internally.
