### ISSUE TITLE
The $SERVICEPROBLEMID$ macro is not set to zero when service is in OK state

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nagioscore#621]
According to the official Nagios Core documentation:

> If the service is currently in an OK state, this macro will be set to zero (0).

[https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/macrolist.html#serviceproblemid](url)

This is not happening. The issue is reported on the Nagios XI support forum here:

https://support.nagios.com/forum/viewtopic.php?f=16&t=52558&p=275367

I was able to recreate the issue on my test XI box, running Nagios Core 4.4.3.

**Comment by Madlohe** [comment]
Patch merged into maint, closing

**Comment by tomsommer** [comment]
Broken by https://github.com/NagiosEnterprises/nagioscore/commit/c2fdf88d09ad47d8bde51a2e903f7159a0afa63e
