### ISSUE TITLE
nagios: job 2 (pid=6481): read() returned error 11

### ISSUE THREAD

**Issue by rosri1992** [NagiosEnterprises/nagioscore#627]
I have Installed Nagios 4.4.3 On RHEL7 AWS Instance and I configured contacts to send email alerts. 
Similarly I have created notify-service-by-sms, and host commands and when I try to trigger custom alerts, we are unable to get the text alerts to our mobiles. I have created contacts with and added commands to the contacts and added my number xxxxx@@txt.att.net. 

Please help me , I went through the similar threads #362, #172  but they are not helpfull to me

**Comment by Madlohe** [comment]
Hi @rosri1992,

I'll need some more information before going forward with this. 

1) What's the relevance of the title for this issue? Does that error reliably show up every time you get a check result?
2) Have you tried using a normal (non-SMS) e-mail address under the same contact? What happens with the e-mail changed?

**Comment by rosri1992** [comment]
@Madlohe  I'm adding the screenshot  when I tried to check the status of Nagios I can see the message "Jul 22 10:48:10 inen2a086.hcqis.org nagios[2417]: job 12153 (pid=31696): read() returned error 11"
I'm adding the screenshot. Let me know if you need more information. I  was able to resolve the issue sending messages to the mobiles in our nagios installation. I'm still  seeing this PID issue. I don't how frequent this comes.
![screen-shot](https://user-images.githubusercontent.com/48814564/61648304-2a2d1d80-ac7d-11e9-9998-4783fb24c309.PNG)

**Comment by Madlohe** [comment]
Okay, if your alerting issue is fixed, I'm going to close this issue. As mentioned in #362 and #172, the log message isn't indicative of an actual problem, and was more a debugging message that was left in by accident.
