### ISSUE TITLE
Nagios check_ntp_time (check_ntp_time: NTP CRITICAL: Offset unknown)

### ISSUE THREAD

**Issue by rosri1992** [NagiosEnterprises/nagioscore#629]
Hello 

I have Nagios running latest version, but I'm having this problem check_ntp_time: NTP CRITICAL: Offset unknown to all my servers. I have found this link open in Nagios-plugins forum (https://github.com/nagios-plugins/nagios-plugins/issues/329) but there is no solution for this problem for RHEL 7 Instance. 

Can you please help me the resolution  for RHEL Instance.

**Comment by EstebanMonge** [comment]
Maybe you need to write to Nagios Plugin repository

**Comment by Madlohe** [comment]
I don't think this is related to Nagios Core - feel free to add to the discussion on the issue you linked
