### ISSUE TITLE
'Checks of this host have been disabled' is triggered by passive only hosts

### ISSUE THREAD

**Issue by 5h4d0ww0lf** [NagiosEnterprises/nagioscore#632]
Strictly passive host with disabled active check fall in `temp_hoststatus->checks_enabled == FALSE` even when passive checks are enabled.

**Comment by Madlohe** [comment]
Hi @5h4d0ww0lf,

Thanks for reporting this and for sending the pull request. I'll make sure to review this before 4.4.4.

**Comment by Madlohe** [comment]
merged pull request into maint, closing
