### ISSUE TITLE
Different behavior for data passed to handle_service_event() if the Host is UP or not UP

### ISSUE THREAD

**Issue by nook24** [NagiosEnterprises/nagioscore#633]
I noticed that the data passed to `handle_service_event()` are changing, depending on the state of the host. This makes it hard to use the data provided by [broker_statechange_data()](https://github.com/NagiosEnterprises/nagioscore/blob/345fd4e8257085ce7f3806ee4fb04008919f24e5/base/sehandlers.c#L166-L178) to calculate availability reports.

### So what happens in detail
When a Service switches from state Ok Hard to Critical Soft(1/3),Critical Soft(2/3)/Critical Hard(3/3) while the Host is in state **Up**
the field `last_hard_state` acts as previous_hard_state (in the state change event). This is quite nice. I use this to build up a state history and track state change events.
I also think it makes total sense, that a state change event can provide me information about the current state, and the previous state.

How ever. If the Host is in a **non Up state** `last_hard_state` behaves as latest_hard_state. This issue is caused by the fact, that a Soft state change will get forced into a hard state change by the system, if the host is in a non Up state.

Would be good if `last_hard_state` would always behave independently from the host state of a service.

![nagios_state_change](https://user-images.githubusercontent.com/9019992/56304295-2188f080-613e-11e9-8973-010366463c00.jpg)

To be clear, I only need this for the state change events. 

Fun fact, in Nagios 3 `last_hard_state` always represents  the previous_hard_state for state change events.

I already fixed this issue in the Naemon Core:
Issue: https://github.com/naemon/naemon-core/issues/287
[Merged] https://github.com/naemon/naemon-core/pull/291

Unfortunately the current Nagios code is looking completely different from the Nagios3 or Naemon Code so I can't just port my solution and send you a pull request.

I will take a closer look into this tomorrow and hopefully find the code which is causing the different behavior.

**Comment by jomann09** [comment]
Thanks for finding this, it looks like this is part of another bug we've found that should be up on here shortly related to how last_hard_state determines the current service state when the host goes from a down to an ok state. Will take a look into this and get it fixed in the next version.

**Comment by nook24** [comment]
Sorry for my late response, I was on on vacation... Sounds good for me,  I will wait for your patch

**Comment by Madlohe** [comment]
Hi @nook24, 

Just to be clear, we're more-or-less of the same opinion as the Naemon maintainers: the immediate transition from OK/HARD to CRITICAL/HARD when the host is DOWN/HARD is an intentional and documented feature ([see bullet 3 under "Hard States" here](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/statetypes.html#)).

We do think it's an issue that last_hard_state moves in lock-step with the current state when the host is DOWN. Going by your images, we're going to patch Core so that the last_hard_state column would show `0, 0, 0, 2` (and 0 again for the next non-OK/SOFT state) when the host is UP, and `?, 0, 2` when the host is DOWN.

**Comment by nook24** [comment]
@Madlohe this looks good
![Bildschirmfoto 2019-05-30 um 12 58 53](https://user-images.githubusercontent.com/9019992/58629047-9c1b6300-82db-11e9-9c91-fbd217d221a5.png)
![Bildschirmfoto 2019-05-30 um 13 03 43](https://user-images.githubusercontent.com/9019992/58629051-9de52680-82db-11e9-8a05-dbb8ac0ed017.png)

Many thanks!

**Comment by Madlohe** [comment]
Glad to hear it! Merging and closing this.
