### ISSUE TITLE
Checks with large check_intervals scheduled outside of short time periods

### ISSUE THREAD

**Issue by Madlohe** [NagiosEnterprises/nagioscore#647]
[See here for context](https://support.nagios.com/forum/viewtopic.php?f=7&t=54064)

In short, when a service has a check_interval much shorter than the total length of the check_period, the check may be scheduled after the end of the time period. When this happens, the check isn't run and the service remains PENDING.

**Comment by Madlohe** [comment]
The issue seems to be from https://github.com/NagiosEnterprises/nagioscore/commit/62af86766d24e73c33edb76ae01ea1ac8dcb6f04, where the previous maintainer was trying to reduce the load caused by scheduling checks from outside their timeperiods. He did this by 'rescheduling' the tests by some random amount of time after the start of the timeperiod. However, this code doesn't ensure that the new time is still in the timeperiod, instead only using the check_interval or retry_interval of the host/service.

**Comment by LoZini** [comment]
Hi @Madlohe, I see in change log:

* Partially reverted changes for #647 due to CPU load issues

We're still with 4.4.3 so we didn't try the previous fix yet. Do we should expect a partial solution?

Thanks,
Antonio
