### ISSUE TITLE
Nagios not restart, nagios.service is not active, cannot reload.

### ISSUE THREAD

**Issue by tariqSahib** [NagiosEnterprises/nagioscore#650]
![1](https://user-images.githubusercontent.com/51790147/59437658-6ada8100-8e0b-11e9-9e2a-b77a69a1dc5d.PNG)
![2](https://user-images.githubusercontent.com/51790147/59437666-7037cb80-8e0b-11e9-8a25-af46ce095ccb.PNG)
![3](https://user-images.githubusercontent.com/51790147/59437674-7463e900-8e0b-11e9-8a78-5d943101205a.PNG)
I face error when I try to restart the Nagios.
1-Error: Service notification command 'notify-by-email' specified for contact 'Nam' is not defined anywhere!
2-Error: Host notification command 'host-notify-by-email' specified for contact 'Nam' is not defined anywhere!
3- Error:"Failed to start LSB: Starts and stops the Nagios monitoring server.
4-nagios.service is not active, cannot reload

**Comment by Madlohe** [comment]
Hi @tariqSahib,

Can you post the configuration files where you defined notify-by-email and host-notify-by-email?

**Comment by tariqSahib** [comment]
![contect 1](https://user-images.githubusercontent.com/51790147/59439841-66b06280-8e0f-11e9-8b48-50725371abe8.PNG)
[commands.cfg.txt](https://github.com/NagiosEnterprises/nagioscore/files/3286576/commands.cfg.txt)
[contacts.cfg.txt](https://github.com/NagiosEnterprises/nagioscore/files/3286577/contacts.cfg.txt)


![contact file](https://user-images.githubusercontent.com/51790147/59439831-61531800-8e0f-11e9-9b4b-57f027a3349a.PNG)

**Comment by tariqSahib** [comment]
> Hi @tariqSahib,
> 
> Can you post the configuration files where you defined notify-by-email and host-notify-by-email?

i Attached contacts.cfg and commands.cfg kindly check

**Comment by tariqSahib** [comment]
![command 2](https://user-images.githubusercontent.com/51790147/59441574-3cac6f80-8e12-11e9-96cd-07b3ff35025c.PNG)

**Comment by tariqSahib** [comment]
> Hi @tariqSahib,
> 
> Can you post the configuration files where you defined notify-by-email and host-notify-by-email?

please check contacts.cfg and command.cfg file

**Comment by Madlohe** [comment]
The commands.cfg.txt that you attached didn't have the notification commands that you're showing in your last screenshot. Once you've added them, the service should start.

**Comment by tariqSahib** [comment]
[commands.cfg (complete).txt](https://github.com/NagiosEnterprises/nagioscore/files/3289028/commands.cfg.complete.txt)
Now i fully copy paist the command.cfg file. please check

**Comment by tariqSahib** [comment]
> The commands.cfg.txt that you attached didn't have the notification commands that you're showing in your last screenshot. Once you've added them, the service should start.
HI Madlohe 
the notification command  are already added as mention below 
# 'notify-host-by-email' command definition
define command{
        command_name    notify-host-by-email
        command_line    /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: $NOTIFICATIONTYPE$\nHost: $HOSTNAME$\nState: $HOSTSTATE$\nAddress: $HOSTADDRESS$\nInfo: $HOSTOUTPUT$\n\nDate/Time: $LONGDATETIME$\n" | /bin/mail -s "** $NOTIFICATIONTYPE$ Host Alert: $HOSTNAME$ is $HOSTSTATE$ **" $CONTACTEMAIL$
        }

# 'notify-service-by-email' command definition
define command{
        command_name    notify-service-by-email
        command_line    /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: $NOTIFICATIONTYPE$\n\nService: $SERVICEDESC$\nHost: $HOSTALIAS$\nAddress: $HOSTADDRESS$\nState: $SERVICESTATE$\n\nDate/Time: $LONGDATETIME$\n\nAdditional Info:\n\n$SERVICEOUTPUT$\n" | /bin/mail -s "** $NOTIFICATIONTYPE$ Service Alert: $HOSTALIAS$/$SERVICEDESC$ is $SERVICESTATE$ **" $CONTACTEMAIL$
        }

**Comment by Madlohe** [comment]
Please run the following command again and post the output
`/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg`

Also, please upload your nagios.cfg file

**Comment by tariqSahib** [comment]
Hi Madlohe 
i used this command but error not solve 
/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg

![error1](https://user-images.githubusercontent.com/51790147/59547367-44c1f780-8f57-11e9-9daf-2e8bc2d05181.PNG)
nagios.cfg file[nagios .cfg.txt](https://github.com/NagiosEnterprises/nagioscore/files/3292745/nagios.cfg.txt)

**Comment by Madlohe** [comment]
Where are you defining 'Nam'? The contact isn't listed in your contacts.cfg.

You will want to remove its notification_commands and make sure 'use' is set to 'generic-contact'

**Comment by tariqSahib** [comment]
> Where are you defining 'Nam'? The contact isn't listed in your contacts.cfg.
Answer: Actually, Mr. Nam works on Nagios. I try to resolve this issue.
> You will want to remove its notification_commands and make sure 'use' is set to 'generic-contact'
Answer: you mean to say that notification command which is added in the "commands.cfg" i remove these command?  and past it into contacts.cfg at place in the generic-contact'. please reply
![Notification command](https://user-images.githubusercontent.com/51790147/59584914-b5544a00-90f8-11e9-9cc2-5d2e57cd83d9.PNG)
![contact](https://user-images.githubusercontent.com/51790147/59584925-b8e7d100-90f8-11e9-8b94-9fc761098ba2.PNG)


# 'notify-host-by-email' command definition
define command{
        command_name    notify-host-by-email
        command_line    /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: $NOTIFICATIONTYPE$\nHost: $HOSTNAME$\nState: $HOSTSTATE$\nAddress: $HOSTADDRESS$\nInfo: $HOSTOUTPUT$\n\nDate/Time: $LONGDATETIME$\n" | /bin/mail -s "** $NOTIFICATIONTYPE$ Host Alert: $HOSTNAME$ is $HOSTSTATE$ **" $CONTACTEMAIL$
        }

# 'notify-service-by-email' command definition
define command{
        command_name    notify-service-by-email
        command_line    /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: $NOTIFICATIONTYPE$\n\nService: $SERVICEDESC$\nHost: $HOSTALIAS$\nAddress: $HOSTADDRESS$\nState: $SERVICESTATE$\n\nDate/Time: $LONGDATETIME$\n\nAdditional Info:\n\n$SERVICEOUTPUT$\n" | /bin/mail -s "** $NOTIFICATIONTYPE$ Service Alert: $HOSTALIAS$/$SERVICEDESC$ is $SERVICESTATE$ **" $CONTACTEMAIL$
        }

**Comment by tariqSahib** [comment]
Hi ,
i add NAM in the contacts.cfj  and run this command  /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg. please see snapshot
![5- i add the NAM in contact](https://user-images.githubusercontent.com/51790147/59605436-3bd45000-9128-11e9-8611-94687da57c40.PNG)
![4-NAM duplicate](https://user-images.githubusercontent.com/51790147/59605445-41319a80-9128-11e9-8432-7295fb531591.PNG)

**Comment by Madlohe** [comment]
Who is chotoixinchuky@gmail.com? If they still work at your organization, you should probably change the contact in switch.cfg to set `service_notification_commands` to `notify-service-by-email` and `host_notification_commands` to `notify-service-by-email`, then remove the contact you added in contacts.cfg.

If they don't work at your organization any more, then you should be able to remove that contact from switch.cfg and keep the one in contacts.cfg

**Comment by tariqSahib** [comment]
> If they don't work at your organization any more, then you should be able to remove that contact from switch.cfg and keep the one in contacts.cfg
**Special Thanks to Mr.Madlohe**
All errors are solved just repeat the above comments 
![7-problem solve](https://user-images.githubusercontent.com/51790147/59654799-3ec75300-91b1-11e9-8495-24a5d8cd381a.PNG)
Good news Nagios Error solve 
1-Error: Service notification command 'notify-by-email' specified for contact 'Nam' is not defined anywhere!
2-Error: Host notification command 'host-notify-by-email' specified for contact 'Nam' is not defined anywhere!
3- Error:"Failed to start LSB: Starts and stops the Nagios monitoring server.
4-nagios.service is not active, cannot reload

**Comment by Madlohe** [comment]
Glad to hear it! I'll close the issue now.
