### ISSUE TITLE
Attention :Found a swap file

### ISSUE THREAD

**Issue by tariqSahib** [NagiosEnterprises/nagioscore#654]
Hi Guys:
please help me I found the following confusion option.
Found a swap file by the name ".phoenix.cfg.swp"
          owned by: root   dated: Wed Jun 19 00:04:01 2019
         file name: /usr/local/nagios/etc/servers/phoenix.cfg
          modified: YES
         user name: root   host name: nagios-01
        process ID: 18513
While opening file "phoenix.cfg"
             dated: Wed Jun 19 01:07:05 2019
      NEWER than swap file!

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r phoenix.cfg"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file ".phoenix.cfg.swp"
    to avoid this message.
![1](https://user-images.githubusercontent.com/51790147/60249244-e34a4300-98dd-11e9-93f5-62e5091c821b.PNG)

**Comment by ericloyd** [comment]
Someone used vi to edit phoenix.cfg and didn't terminate the edit session properly.

**Comment by EstebanMonge** [comment]
You can resolve this errasing the file .phoenix.cfg.swp

It is offtopic... non related to Nagios

**Comment by tariqSahib** [comment]
HI EstebanMonge : 
  How I erase the file..phoenix.cfg.swp. please guide me

**Comment by ericloyd** [comment]
rm phoenix.cfg.swp

I have to say, this is very basic Unix systems administration tasks.  If you are unfamiliar with how to do these things, then running Nagios may be a challenge for you.
