### ISSUE TITLE
CHECK_NRPE: Socket timeout after 30 seconds

### ISSUE THREAD

**Issue by tariqSahib** [NagiosEnterprises/nagioscore#655]
Hi Guys
Can you please help with the issue related to check_nrpe socket timeout
root@nagios-01:~# ps -aef | grep nrpe
root     16861 16842  0 02:51 pts/8    00:00:00 grep --color=auto nrpe
root@nagios-01:~# cd /usr/local/nagios
root@nagios-01:/usr/local/nagios# ls
bin  etc  libexec  sbin  share  var
root@nagios-01:/usr/local/nagios# cd etc
root@nagios-01:/usr/local/nagios/etc# ls
cgi.cfg       htpasswd.users  objects   resource.cfg  servers
contacts.cfg  nagios.cfg      printers  routers       switches
root@nagios-01:/usr/local/nagios/etc# cd
root@nagios-01:~# service xinetd status
● xinetd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
root@nagios-01:~# cd /usr/local/nagios
root@nagios-01:/usr/local/nagios# ls
bin  etc  libexec  sbin  share  var
root@nagios-01:/usr/local/nagios# cd libexec
root@nagios-01:/usr/local/nagios/libexec# ls
check_apt       check_ftp           check_mrtg      check_pop      check_time
check_breeze    check_hpjd          check_mrtgtraf  check_procs    check_udp
check_by_ssh    check_http          check_nagios    check_real     check_ups
check_clamd     check_icmp          check_nntp      check_rpc      check_uptime
check_cluster   check_ide_smart     check_nntps     check_sensors  check_users
check_dhcp      check_ifoperstatus  check_nt        check_simap    check_wave
check_dig       check_ifstatus      check_ntp       check_smtp     negate
check_disk      check_imap          check_ntp_peer  check_snmp     urlize
check_disk_smb  check_ircd          check_ntp_time  check_spop     utils.pm
check_dns       check_jabber        check_nwstat    check_ssh      utils.sh
check_dummy     check_load          check_oracle    check_ssmtp
check_file_age  check_log           check_overcr    check_swap
check_flexlm    check_mailq         check_ping      check_tcp

**Comment by ericloyd** [comment]
There is a huge amount of information about this topic in the Nagios support forums.  That should be the first place you look, and if you search for "30 second nrpe timeout," any search engine will take you there.

**Comment by Madlohe** [comment]
Hi @tariqSahib,

I'm going to request that you go to [our support forums](https://support.nagios.com/forum/index.php) for any more usage-related issues. We have dedicated technicians there that will be able to assist you. 

If you're only using open-source components, then you'll want to post in General Support -> Nagios Core. Thanks!
