### ISSUE TITLE
connect to address 172.16.0.x and port 80: No route to host 

### ISSUE THREAD

**Issue by tariqSahib** [NagiosEnterprises/nagioscore#656]

**Comment by ericloyd** [comment]
@tariqSahib, you really need to take these to the Nagios support forum (https://support.nagios.com/forum).  You will get more answers there.

Also, your message has no real question in it.  We don't know what you're really asking.  Please ask on the forums instead, where Nagios support lives, and where people like me who help others respond as well.

**Comment by tariqSahib** [comment]
![http ssh](https://user-images.githubusercontent.com/51790147/60482993-13faf580-9cad-11e9-921c-f87f9356560e.PNG)
![alarm](https://user-images.githubusercontent.com/51790147/60483000-1e1cf400-9cad-11e9-97fb-03ab526e6eef.PNG)
i used Nagios Core 4.3.4. 
i define host in etc/servers, i am face critical alarm on the dashbord alarm info is mention in the snaps

**Comment by ericloyd** [comment]
@tariqSahib, you really need to take these to the Nagios support forum (https://support.nagios.com/forum). You will get more answers there.

**Comment by Madlohe** [comment]
Hi @tariqSahib,

I think @ericloyd has the right of it. This issues page is used mostly for tracking bugs and feature requests. If you're still learning to use the software, [the support forums](https://support.nagios.com/forum) are your best bet.
