### ISSUE TITLE
New map not working for RU locale

### ISSUE THREAD

**Issue by Metori** [NagiosEnterprises/nagioscore#67]
I have Firefox with RU default locale. When I try to open the new Nagios Map (legacy map work fine) it is not shown (only button with three lines and loading circle for some seconds) and i see JSON.parser error in developer console.
When I change intl.accept_languages to "en-US, en" in my Firefox then map work fine.

**Comment by Metori** [comment]
Maybe this actual for all locales other than EN.

**Comment by jfrickson** [comment]
Open `Tools / Web Developer / Network` then try loading the map. See if anything shows an error.

**Comment by scottwilkerson** [comment]
Additional information in this thread
 https://support.nagios.com/forum/viewtopic.php?f=7&t=34307&start=60

**Comment by jfrickson** [comment]
Fix has been implemented. It is in place in the master branch (4.1.1) at https://github.com/NagiosEnterprises/nagioscore and the 4.1.2-beta branch at https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-beta
