### ISSUE TITLE
Nagios creates zombie processes

### ISSUE THREAD

**Issue by hydrapolic** [NagiosEnterprises/nagioscore#683]
Zombies started to appear after upgrading Nagios from 4.4.3 to 4.4.4. 

````
# ps auxw | grep defunct
nagios   25997  0.2  0.0      0     0 ?        Z    19:48   0:00 [check_nrpe] <defunct>
nagios   26048  0.0  0.0      0     0 ?        Z    19:48   0:00 [check_ping] <defunct>
nagios   26095  1.0  0.0      0     0 ?        Z    19:48   0:00 [check_nrpe] <defunct>
nagios   26099  1.0  0.0      0     0 ?        Z    19:48   0:00 [check_nrpe] <defunct>
````

After a half day, there were almost 100 zombie processes. A nagios restart cleaned them up.

**Comment by hydrapolic** [comment]
![Screenshot from 2019-08-15 21-49-18](https://user-images.githubusercontent.com/3277373/63122605-74b56780-bfa7-11e9-89ed-b5aad0cd8437.png)

**Comment by Madlohe** [comment]
Hi @hydrapolic,

can you try compiling from maint? I believe I've reverted the change that caused this for 4.4.5.

**Comment by hydrapolic** [comment]
> Hi @hydrapolic,
> 
> can you try compiling from maint? I believe I've reverted the change that caused this for 4.4.5.

Hello @Madlohe, yes, that seems to work, thanks!

**Comment by Madlohe** [comment]
Glad to hear it!
