### ISSUE TITLE
Fixing spec file for 4.4.5 for EPEL replease

### ISSUE THREAD

**Issue by tjyang** [NagiosEnterprises/nagioscore#684]
Hi 
I am opening this issue to track R1 bug.

* R1: https://bugzilla.redhat.com/show_bug.cgi?id=1742383#c1

**Comment by Madlohe** [comment]
Hi,

I don't really understand that page (I'm not familiar with the EPEL release process), but if I've broken anything for you guys please let me know.

BTW, I would recommend skipping the 4.4.4 release. We'll be putting out 4.4.5 sometime this week (most likely tomorrow), which fixes a couple of major issues in 4.4.4.

**Comment by tjyang** [comment]
@Madlohe , thanks for the response.

I created this issue hoping to figure out what is the release work-flow from release tar ball to RPMs on EPEL repository. 

One thing I found so far is that sourceforge is hosting released tar ball and  .spec file is still referring to sourceforge.  Is sourceforge still needed in this work-flow ?

**Comment by Madlohe** [comment]
To be honest, I don't have very much communication with the EPEL maintainers. I know the assignee on that ticket is @smooge, so possibly you can ask him.

On our side, the sourceforge repo is something that's updated after the github release, using some automation on our internal servers. Sourceforge used to be the "main" repository, so you will probably find references to it in a lot of places.

I'm also not sure about Core specifically, but EPEL has previously added fairly substantial patches to nagios-plugins which stayed downstream. I wouldn't be surprised if they did the same for this project. It may be worth trying to find what repository they use for their build server, and merging the new commits into there.

**Comment by smooge** [comment]
There are 2 different spec files in the package. There is the Fedora spec file which passed some sort of review a long time ago so I still use it. This one points its sources at the github. Then there is the one that is shipped by Nagios which I believe is meant to work on SuSE, Mandrake and for a user to build their own. That one I think points to sourceforge.

Normally I pull whatever tar.gz release is listed in github as it is the true upstream and sourceforge was weird for a while. I normally wait 2-3 weeks after a release as there are either followup releases or a set of git pulls I need to patch items. Most of the additional source listed in that ticket are items which are Fedora specific like an selinux policy and some other items.

For the nagios-plugins Fedora does have a lot of patches as the upstream was very quiescent and I had to use the maintenance git with other fixes as needed.

**Comment by tjyang** [comment]
@Madlohe , Thanks for your information. 
@smooge, I am using nagioscore/nagios.spec to build for CentOS 7 for testing but using EPEL one for production install.  This is causing problem  on  .spec variation issue. 
Is it possible for you to contribute your .spec file for Fedora back as nagioscore/nagios.fedora.spec on github ?
I like to build my own rpm that can just upgrade my existing rpm from EPEL repo.

**Comment by tjyang** [comment]
Hi @smooge  and @Madlohe 

Please review PR: https://github.com/NagiosEnterprises/nagioscore/pull/686.

- WHAT: 

 I submitted a[ PR](https://github.com/NagiosEnterprises/nagioscore/commit/40e75946e2e549007b9f204c9708a72b98d1d7b7#diff-bece0af4b7d939c7a73943d704d970c7) a while back to enable "./configure && cd contrib && make rpm" to create RPMs using nagios.spec file. But RPMs created are not really what I want.

- WHY:

1. I am using RPMs in production/testing from Fedora EPEL repo. so The changes in this PR is to allow one to create EPEL compatible RPMs before official EPEL release 
1.  Hopefully, this will enable more people to participate  on Fedora EPEL side of RPM creation workflow.

- Debug,change local git src files and then create RPMs for testing.
1. ./configure&& cd contrib
1.  make localsrc-rpm
- OR using [release tarballs](https://github.com/NagiosEnterprises/nagioscore/releases/) from  github repo.
1. ./configure&& cd contrib
1.  make rpm
