### ISSUE TITLE
Followup to Issue #621

### ISSUE THREAD

**Issue by alamp1360** [NagiosEnterprises/nagioscore#688]
Hi!

The fix for issue #621 (Macro PROBLEMID not set to 0 when service changes to OK state) is, in my opinion, too too late in function handle_async_service_check_result.
The two variables current_problem_id and last_problem_id are currently set after notifications are run, so any notification script gets the "old" values.

My proposal to solve the issue would be to move the two lines (Lines 1624/1625)

                svc->last_problem_id = svc->current_problem_id;
                svc->current_problem_id = 0L;

somewhere above line 1579 and enclose it with a

                 if (svc->current_state == STATE_OK && state_change == TRUE) {
                 
Maybe it would also be ok to move the whole block (Lines 1621-1639)?

Greetings!

**Comment by Madlohe** [comment]
Hi @alamp1360,

Thanks for letting us know about this! That change looks reasonable to me. It seems like nothing uses or sets the problem_id struct members, so this should be okay to put in the next version.

**Comment by sawolf** [comment]
Merged into maint, closing
