### ISSUE TITLE
[Bug] Empty variable macro leads to broken CGI

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#69]
(Filing on behalf of a user, have yet to confirm)

https://support.nagios.com/forum/viewtopic.php?f=7&t=33707

Setting a blank custom variable on a host appears to break the cmd.cgi when enable_environment_macros=1.  This was reported against 4.0.8.

**Comment by jfrickson** [comment]
Aha! I looked at http://tracker.nagios.org/view.php?id=622 and couldn't get it to fail. That is, until now when I know the culprit was enable_environment_macros=1

I'll be looking into this issue again now.

**Comment by jfrickson** [comment]
The fix is now in https://github.com/NagiosEnterprises/nagioscore/tree/nagios-maint and will most likely be merged onto TRUNK after the release of 4.1.0.

**Comment by jfrickson** [comment]
Change of plans. Will go in with the 4.1.0 release
