### ISSUE TITLE
Contact Macros not expanding into env properly

### ISSUE THREAD

**Issue by jrdalrymple** [NagiosEnterprises/nagioscore#70]
Cross-linking old tracker bug:
https://tracker.nagios.org/view.php?id=575

**Comment by jfrickson** [comment]
The fix is in https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.0rc3
Let me know how it works.

**Comment by jfrickson** [comment]
The fix was moved into production with release 4.1.0
