### ISSUE TITLE
Ability to query with API for 'Unhandled' alerts only

### ISSUE THREAD

**Issue by hales8181** [NagiosEnterprises/nagioscore#700]
Add the ability to pull back using the API the number of unhandled alerts.

**Comment by ericloyd** [comment]
Great idea.  This could then be added to the "nagiostats" command and eventually migrate into the Naigos Stats Wizard in XI as well.  Great idea!

**Comment by hedenface** [comment]
Which API are you referring to @hales8181 ?

**Comment by hales8181** [comment]
The inbuilt API: 
https://monitoringsystem/nagiosxi/api/v1/

**Comment by sawolf** [comment]
In that case, I'm going to close this issue, since it's for a different product. I'll file an internal feature request for this, but in the future I would recommend using [our support forums](https://support.nagios.com/forum/) to make feature requests for our paid products.
