### ISSUE TITLE
Nagiosxi : Feature request to provide performance metrics in data format

### ISSUE THREAD

**Issue by ranjithkodumbu** [NagiosEnterprises/nagioscore#702]
Feature request to provide performance metrics in data format. Currently it is possible to view it as Graph format(pnp4nagios), it would be great if we can pull it as data format. This will help to perform some analytics using this data.

**Comment by sawolf** [comment]
Can you be more specific about what you mean? The data for the graphs are stored in .rrd files. You should be able to [export these as XML from the terminal](https://linux.die.net/man/1/rrdxport) already. Is this what you needed or are you looking for something else?

**Comment by ericloyd** [comment]
I'm guessing rrdxport is what they wanted, but didn't know of its existence.  And before anyone asks, here's a script we found that we use to convert to XLS format:

https://monjurulhasan.blogspot.com/2009/11/export-rrd-values-to-ms-excel.html

**Comment by ranjithkodumbu** [comment]
Hi Eric, you are right, but we need to integrate this feature in Nagios console as performance data report, Daily/weekly/Monthly/Yearly/custom date something like availability Report.

**Comment by ericloyd** [comment]
That is not likely going to happen with Nagios Core.  The information is available in RRD files, and you can write your own export to XML data or CSV or XLS format via automated scripts.  Nagios XI offers the functionality you're looking for with performance reports and graphs, as well as scheduled reporting (and significantly increased numbers of reports) so I can't imaging that this feature will be included in the Nagios Core code.

**Comment by sawolf** [comment]
Okay, in that case I don't think there's anything to be done in the Nagios Core codebase. I'll pass this along, but in the future, I'd recommend that you post XI feature requests to the support forums.

**Comment by sawolf** [comment]
One last point: the capacity planning report will produce something very similar to what you're looking for. Just thought I'd point that our in case you hadn't looked into it

**Comment by ericloyd** [comment]
Capacity planning report is an XI Enterprise feature, don't forget.

**Comment by box293** [comment]
You could also use Grafana to view the rrd data in a different interface:

https://support.nagios.com/kb/article/nagios-core-using-grafana-with-pnp4nagios-803.html

https://support.nagios.com/kb/article/nagios-xi-using-grafana-with-existing-performance-data-805.html
