### ISSUE TITLE
RFE: support negative (subtractive) inheritance

### ISSUE THREAD

**Issue by ensc** [NagiosEnterprises/nagioscore#704]
nagios support additive inheritance to add new items to inherited configuration options; e.g.

```
define host {
    name linux-host
    register 0
    hostgroups +ssh-server, diskcheck-server
}

define host {
    name host-a
    use linux-host
    hostgroups +loadcheck-server, http-server
}
```

When there is some other host, which does not provide e.g. SSH services, the whole `hostgroups` statement must be replicated atm:

```
define host {
    name host-b
    use linux-host
    hostgroups diskcheck-server, loadcheck-server, http-server
}
```

When there are inheritance chains (like in "Precedence With Multiple Inheritance Sources" at https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/objectinheritance.html), this becomes very difficulty to maintain.

It would be nice when single items can be removed from the list, e.g. like

```
define host {
    name host-b
    use linux-host
    hostgroups -ssh-server
}
```

**Comment by ericloyd** [comment]
Use ! to remove things.,

**Comment by sawolf** [comment]
I agree with Eric. For your last example, you should be able to do 
```
define host {
    name host-b
    use linux-host
    hostgroups *,!ssh-server
}
```
though I haven't tried that myself.
I'd also recommend that you read [this documentation](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/objecttricks.html) for more information on how this works.

**Comment by ensc** [comment]
thanks; this seems to solve my use cases. Although it does not seem to be possible to readd items. E.g.

```
define host {
    name template-a
    hostgroups grp-a, !grp-b
}
```

will permanently remove `grp-b` so that with

```
define host {
    name host-a
    use template-a
    hostgroups +grp-b
}
```

the `host-a` will **not** be member of `grp-b`
