### ISSUE TITLE
Name conflict between "lib/pqueue.h" and "openssl/pqueue.h" when compiling NDOUtils with "--enable-ssl" configuration option

### ISSUE THREAD

**Issue by kaiwetlesen** [NagiosEnterprises/nagioscore#706]
This is a build time issue that primarily affects NDOUtils' use of OpenSSL. When setting the `--enable-ssl` flag, the OpenSSL libraries pull in a pqueue library which contains conflicting function signatures in OpenSSL v1.0.2k as installed on RHEL7. I would open this in the NDOUtils but it looks like `pqueue.h` is a core library of Nagios Core.

Steps to reproduce:
- Configure NDOUtils add-on with `--enable-ssl` omitted
- Attempt to build
- Install OpenSSL 1.0.2k development libraries and headers
- Configure NDOUtils add-on with `--enable-ssl` set
- Attempt to build

Expected Behavior:
NDOUtils builds successfully under both conditions with no type conflicts

Actual Behavior:
NDOUtils builds successfully with no SSL, but build aborts when SSL enabled due to type conflicts

Build log is included below.
[build-log-no-ssl.txt](https://github.com/NagiosEnterprises/nagioscore/files/3741619/build-log-no-ssl.txt)
[build-log-ssl-enabled.txt](https://github.com/NagiosEnterprises/nagioscore/files/3741620/build-log-ssl-enabled.txt)

**Comment by sawolf** [comment]
I've made a new issue for you in https://github.com/NagiosEnterprises/ndoutils/issues/58. Closing this
