### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by sawolf** [NagiosEnterprises/nagioscore#709]
Similar to https://github.com/NagiosEnterprises/ncpa/issues/592, Nagios Core uses jQuery [1.12.4](https://github.com/NagiosEnterprises/nagioscore/blob/master/html/js/jquery-1.12.4.min.js), which is out of date. For some security scanners, this will show up as an XSS vulnerability.

Solution is to upgrade to jQuery >=3.4.0 (while making certain that the rest of the existing JS code works).

**Comment by dylan-at-nagios** [comment]
This was resolved in 4.5.3
