### ISSUE TITLE
nagios-4.1.0:CGI Could not read object configuration data

### ISSUE THREAD

**Issue by alex2grad** [NagiosEnterprises/nagioscore#71]
All CGI script not working because can not parse dependency_type in files objects.cache/objects.precache.
If I manually remove dependency_type from objects.cache/objects.precache all cgi scripts are working.
The commit 6cdc8f6247d82d7b2cd7999e5ae319fb92200139 added dependency_type.

**Comment by jfrickson** [comment]
Fixed in release 4.1.1
