### ISSUE TITLE
Host and Services Notes

### ISSUE THREAD

**Issue by 4gemenot** [NagiosEnterprises/nagioscore#712]
Dear Gents,

how to create a multi-line note in host and service objects?

Nagios Core version 4.4.5

Thanks,

Ronald

**Comment by sawolf** [comment]
Hi @4gemenot,

I don't think this is currently possible using the `notes` directive for hosts/services. As a workaround, if you need more detailed notes, I would recommend using the `notes_url` directive and creating a webpage for that specific host or service.

**Comment by 4gemenot** [comment]
Hello @sawolf,

Thank you for the update, I'll try to use the notes_url.

Again thank you :-)

**Comment by sawolf** [comment]
No problem!

I'm going to close this issue for now. If you have more questions related to this, feel free to comment again and I'll re-open it.
