### ISSUE TITLE
nagios-4.1.0: exclude (!) not working

### ISSUE THREAD

**Issue by alex2grad** [NagiosEnterprises/nagioscore#72]
in nagios 4.0.8 this part of config working
define servicedependency {
    host_name                      sw
    service_description                 PING
    dependent_service_description       Uptime
    inherits_parent                     1
    execution_failure_criteria          c,p
    notification_failure_criteria       c,p
}
define servicedependency {
    host_name                      sw
    service_description                 Uptime
    dependent_service_description       *,!PING,!Uptime
    inherits_parent                     1
    execution_failure_criteria          c,p
    notification_failure_criteria       c,p
}

In 4.1.0 configtest returns
Error: Circular notification dependency detected for services 'sw;PING' and 'sw;Uptime'
Error: Circular execution dependency detected for services 'sw;PING' and 'sw;Uptime'

**Comment by jfrickson** [comment]
Fixed in release 4.1.1
