### ISSUE TITLE
Nagios 4 query handler : nerd

### ISSUE THREAD

**Issue by dbaid** [NagiosEnterprises/nagioscore#723]
Hello, 
when I submitted the following commands to test query handler
echo -e '@nerd list\0'|nc -U /usr/local/nagios/var/rw/nagios.qh
I got a response :
404: nerd: No such handler
Install nagios 4 according to your [quickstart documents:
https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu
Any suggestions ???
Regards,
dbaid

**Comment by sawolf** [comment]
When you ran `./configure`, did you use `--enable-nerd`? If you follow the quickstart documentation directly, it will be disabled.

**Comment by dbaid** [comment]
yes

I checked it this morning here. Thank  you.

https://support.nagios.com/forum/viewtopic.php?f=7&t=55660&p=292812&hilit=nerd#p292812

Sebastian Wolf <notifications@github.com> 於 2020年1月29日 週三 23:32 寫道：

**Comment by dbaid** [comment]
Hello,

   ./configure --enable-nerd 
    and make all
   I got errors

gcc -Wall -g -O2 -DHAVE_CONFIG_H -c skiplist.c -o skiplist.o
gcc -Wall -g -O2 -DHAVE_CONFIG_H -c nsock.c -o nsock.o
gcc -Wall -g -O2 -DHAVE_CONFIG_H -c nspath.c -o nspath.o
ar cr libnagios.a squeue.o kvvec.o iocache.o iobroker.o bitmap.o dkhash.o runcmd.o nsutils.o fanout.o pqueue.o worker.o skiplist.o nsock.o nspath.o
make[2]: Leaving directory '/tmp/nagioscore-nagios-4.4.5/lib'
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCORE -o nagios nagios.o broker.o nebmods.o ../common/shared.o nerd.o query-handler.o workers.o checks.o config.o commands.o events.o flapping.o logging.o macros-base.o netutils.o notifications.o sehandlers.o utils.o retention-base.o xretention-base.o comments-base.o xcomments-base.o objects-base.o xobjects-base.o statusdata-base.o xstatusdata-base.o perfdata-base.o xperfdata-base.o downtime-base.o  -Wl,-export-dynamic   -lm  -ldl  ../lib/libnagios.a
nagios.o: In function `main':
/tmp/nagioscore-nagios-4.4.5/base/nagios.c:688: undefined reference to `nerd_init'
collect2: error: ld returned 1 exit status
Makefile:157: recipe for target 'nagios' failed
make[1]: *** [nagios] Error 1
make[1]: Leaving directory '/tmp/nagioscore-nagios-4.4.5/base'
Makefile:88: recipe for target 'all' failed

**Comment by dbaid** [comment]
when test with 4.3.3
compiling success and then perform a test against nerd handler.
It seems ok.
 
root@ng4:/tmp/nagioscore-nagios-4.3.3# echo -e '@nerd list\0'|nc -U /usr/local/nagios/var/rw/nagios.qh
hostchecks      Host check results
servicechecks   Service check results
opathchecks     Host and service checks in gource's log format

**Comment by sawolf** [comment]
OK, I can confirm that building with NERD is broken for Ubuntu 18.04.

**Comment by sawolf** [comment]
The pull request directly above resolved the issue on my test system. Are you able to confirm that it's working for you as well?

**Comment by dbaid** [comment]
Hello sawolf,

    I tried to download your source from https://github.com/NagiosEnterprises/nagioscore/tree/3166cedc6e06938b31fd793985fde97668d4d317
   and built it. Configure with --enable-nerd and Compiling is ok.
   My test version :
root@ng4:/usr/local/nagios/libexec#  /usr/local/nagios/bin/nagios -v

Nagios Core 4.4.5
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2019-08-20
License: GPL

And perform a nerd list test:
root@ng4:/usr/local/nagios/libexec# echo -e '@nerd list\0'|nc -U /usr/local/nagios/var/rw/nagios.qh
hostchecks      Host check results
servicechecks   Service check results
opathchecks     Host and service checks in gource's log format
The issue I posted yesterday is solved in 4.4.5.

**Comment by dbaid** [comment]
Thank you~~
