### ISSUE TITLE
Once you "set flap_detection_enabled 0" on a host/service it should remove the flapping state from the host/services page

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#74]
When you have a host/service that enters a flapping state then you go in and "set flap_detection_enabled 0" on the host/service, restart nagios, and it will leave the host/service as flapping on the hosts/services page.  It should remove the flapping state, you can't get rid of it unless you enable flap detection again and submit enough results for it to come out of flapping, then you can disable flapping.

**Comment by jfrickson** [comment]
Should we log/broker a flapping stopped notice and send notifications, or just clear the "is flapping" flag?

**Comment by ssaxnagios** [comment]
I would just remove the "is flapping" flag since you've just disabled flap detection, the assumption is you don't want any flapping emails.

**Comment by tmcnag** [comment]
Definitely log+broker it, that way we have it in nagios.log and (possibly) in ndo for historical purposes.  I would not send a notification, as @ssaxnagios pointed out.

**Comment by ssaxnagios** [comment]
Yeah, that sounds good, log+broker but no notfiy.

**Comment by jfrickson** [comment]
Fix in commit https://github.com/NagiosEnterprises/nagioscore/commit/c7a9212dadaa7ab1e04ebbc1a7db7317464fff75 in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-beta

**Comment by jfrickson** [comment]
Missed @tmcnag and @ssaxnagios last two comments. New commit https://github.com/NagiosEnterprises/nagioscore/commit/4ed1222bb2328d08a9a1d1f07ad79c28b854eb35 pushed onto the nagios-4.1.2-beta branch.
