### ISSUE TITLE
ping Monitoring

### ISSUE THREAD

**Issue by rguptarg** [NagiosEnterprises/nagioscore#741]
Hi Team,

I am new in Nagios, I am looking ping Monitoring configuration in nagios.

I have 1000+ IP List, so how can I configure all IP's for Ping/ICMP monitorng.

**Comment by sawolf** [comment]
Hi @rguptarg,

If you install the default configuration, the host shows an example of how to do ping monitoring. You should be able to simply remove the services from that configuration and copy the host configuration for each IP address you want to monitor.

**Comment by ericloyd** [comment]
This is also a better question to ask in the Nagios support forum (https://support.nagios.com/forum/) than here, as this tends to be code related questions, not usage questions.  LOTS more people will see your note and reply to you in the forums with helpful advice.
