### ISSUE TITLE
PHP Notice:  Trying to access array offset on value of type bool on home page

### ISSUE THREAD

**Issue by YanDatsiuk** [NagiosEnterprises/nagioscore#745]
After installing nagios at home page you get an few errors: `PHP Notice:  Trying to access array offset on value of type bool`

When: right after project installation.
Version: 4.4.5
OS: Linux homestead 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Expected behavior: to see home page without errors.

Steps to reproduce:
1. Install Vagrant's [homestead virtual box](https://app.vagrantup.com/laravel/boxes/homestead).  (optional step - (could probably be any Debian based OS))
2. Install nagios core due to the [instructions](https://www.booleanworld.com/guide-monitoring-servers-nagios/): 
3. Open nagios home page.

Screenshot with error screen will be attached.
![nagios-err-1](https://user-images.githubusercontent.com/3888040/76617190-712e9280-652e-11ea-8d28-680ef67d99e7.PNG)

List of all errors on a home page:

- Trying to access array offset on value of type bool in /usr/local/nagios/share/includes/utils.inc.php on line 220

- Trying to access array offset on value of type bool in /usr/local/nagios/share/includes/utils.inc.php on line 154

P.S. Also I've already found a fix to this. Problem is in parsing settings file by utils.inc.php

**Comment by sawolf** [comment]
Thanks for reporting this. Since you said you had a fix, would you mind sending in a pull request?

**Comment by YanDatsiuk** [comment]
@sawolf Hi! I've just made the pull request. #747 If something is wrong or should be improved - please let me know.

**Comment by iwhite-nagios** [comment]
I took a bit of a deeper look at this bug and noticed that it is in a few more places. The issue has to do with running a bunch of checks on code before checking for the end of the file. This is because fgets() moves the pointer and grabs the _next_ line of the file while feof() checks the _current_ line of the file. Unless the file is empty, fgets() always hits the EOF before feof() and error prone code is run.

**Comment by YanDatsiuk** [comment]
Thanks for the fix! Great job! I've closed the issue.
