### ISSUE TITLE
Missing Image for Host and Service State Trends in Availability Report

### ISSUE THREAD

**Issue by fabianwagner** [NagiosEnterprises/nagioscore#75]
The Host Availability Report and the Service Availability Report do not include the small image for state trends at the top of the page. They just show the broken image icon. Tested on CentOS 7.1 and 6.7 with Nagios Core 4.1.0 and 4.1.1. No errors in the event logs of nagios or httpd to narrow down the problem. State Trends Report instead is working fine.

![host](https://cloud.githubusercontent.com/assets/13900716/9404794/a0de9fe2-47f2-11e5-80b0-293743bc6ada.PNG)
![service](https://cloud.githubusercontent.com/assets/13900716/9404805/c1efcfc6-47f2-11e5-8b5a-d0b79988186d.PNG)

**Comment by jakepaulus** [comment]
The HTML for the page shows the broken image source is:

    src='../trends.html?createimage&smallimage&host=host1&t1=1441719014&t2=1441805414&includesoftstates=no&assumestateretention=yes&assumeinitialstates=yes&assumestatesduringnotrunning=yes&initialassumedhoststate=0&backtrack=4'

The request for this object from avail.cgi sets the HTTP header `Accept:image/webp,image/*,*/*;q=0.8`, but when I visit this URL directly, trends.html delivers HTML.

**Comment by nichokap** [comment]
Hello fabianwagner.

The problem is that the link created is 

`src='../trends.html?createimage&smallimage&host=host1&t1=14417`

instead of 

`src='../cgi-bin/trends.cgi.html?createimage&smallimage&host=host1&t1=14417`

In order to fix this you need to change the source code, ie the file nagios-4.2.0/include/cgiutils.h and change the following line:

`#define TRENDS_CGI		"../trends.html"`

with 

`#define TRENDS_CGI		"trends.cgi"`

**Comment by jfrickson** [comment]
The fix is now in the 'maint' branch via commit https://github.com/NagiosEnterprises/nagioscore/commit/bd029600fbfa5034f905752ddab22bfed70365eb.

Please verify, I'm planning a bug-fix release for around September 1.

**Comment by fabianwagner** [comment]
I can confirm that the suggestion of nichokap did fix the issue for my installation of Nagios 4.1.1. Thank you very much for the solution!

I am looking forward to testing the announced bug-fix release.

**Comment by jfrickson** [comment]
@fabianwagner If you're interested, you can test it now by downloading https://github.com/NagiosEnterprises/nagioscore/archive/maint.zip. Run your normal `./configure`, `make all`, `make install`.
