### ISSUE TITLE
Nagios not sending log message if the host is UP ?

### ISSUE THREAD

**Issue by kopilim96** [NagiosEnterprises/nagioscore#750]
As the tittle above, 
**the question is Nagios will not sending the log message while the Host and service is currently Up?** 

here is my screenshot.

![image](https://user-images.githubusercontent.com/33795389/77131798-f3bbd280-6a97-11ea-9329-31b860099ae4.png)

**Comment by sawolf** [comment]
Hi @kopilim96,

I'm afraid I don't understand your question. Based on your screenshot, it looks to me like the host and service both create a log message when they recover to an OK state, which is the default behavior. What behavior are you looking for?

**Comment by kopilim96** [comment]
I want to know will Nagios send notification to notify user that host are ok. Since the log u seen is on 12am.

**Comment by sawolf** [comment]
If the user gets a notification for a non-OK host or service, they should also receive a recovery notification when it goes back to OK. If you don't want people to receive notifications during off hours, you can set a `notification_period` on the host or service (or on the contact) that's equal to their working/on-call time.

If you don't care at all about certain devices going down during off hours, you can also set a `check_period` on the host/service to prevent checks outside of a certain time.
