### ISSUE TITLE
HARD OK state on recovery

### ISSUE THREAD

**Issue by cdienger** [NagiosEnterprises/nagioscore#757]
Using core 4.4.5 in in XI 5.6.14

prompted by https://support.nagios.com/forum/viewtopic.php?t=58285#308158.

It appears that a service will go into a HARD OK state if it recovers on the max check attempt. It will go into a SOFT OK prior to the max check attempt.

Examples below. The max check attempts is set to 5 for both. With the first example the OK occurs on the 4th attempt and with the second example the OK occurs on the 5th attempt.

The service has changed state at Thu Apr 23 16:27:51 CDT 2020: CRITICAL SOFT 1
The service has changed state at Thu Apr 23 16:27:55 CDT 2020: CRITICAL SOFT 2
The service has changed state at Thu Apr 23 16:27:59 CDT 2020: CRITICAL SOFT 3
The service has changed state at Thu Apr 23 16:28:07 CDT 2020: OK SOFT 4

The service has changed state at Thu Apr 23 16:28:26 CDT 2020: CRITICAL SOFT 1
The service has changed state at Thu Apr 23 16:28:30 CDT 2020: CRITICAL SOFT 2
The service has changed state at Thu Apr 23 16:28:34 CDT 2020: CRITICAL SOFT 3
The service has changed state at Thu Apr 23 16:28:40 CDT 2020: CRITICAL SOFT 4
The service has changed state at Thu Apr 23 16:28:46 CDT 2020: OK HARD 5

**Comment by sawolf** [comment]
related #575

**Comment by cdienger** [comment]
Looks like this may still be an issue. Tested 4.4.6 on a XI 5.7.2 machine and still seeing HARD OK's when a service recovers after reaching its max check attempts, but SOFT OK's if it recovers before reaching its max check attempts.
