### ISSUE TITLE
Even though host is in downtime it sometimes sends problem notification after nagios restart/apply config

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#764]
I was unable to reproduce this (and the customer isn't able to reliably reproduce it either) but the logs on the customer's system are showing that it's currently in downtime but sometimes on the nagios restart a notification is sent, see here for logs/details:

https://support.nagios.com/tickets/scp/tickets.php?id=9344

Looks like a bug based on the nagios.log info from the ticket.

Would be an edge-case.

**Comment by wisgb** [comment]
Hi
I'm seeing the same issue on Nagios XI 5.6.6. Set up a scheduled downtime window lasting 3 days but received a host notification 8 hours after the start of the scheduled downtime. Happy to provide further info. This was logged as a Nagios support call initially and Sean advised I update this github bug report.

Steve
