### ISSUE TITLE
NRPE: Unable to read output 

### ISSUE THREAD

**Issue by rosri1992** [NagiosEnterprises/nagioscore#766]
Hello Team,

I'm trying to set up monitoring of Kubectl cluster using this article https://github.com/colebrooke/kubernetes-nagios 

I came a weird Issues. I have the Kubectl cluster running on Remote RHEL server. When I try to run the scripts locally using NRPE it works.
From Remote server locally.
 /usr/local/nagios/libexec/check_pods.sh -k <Kubectl-config-file> -n <name-space> -w 500 -C 800
**OK -  pods are all OK, found 2 in  state.** 

Same command using nrpe plugin on remote server too 
/usr/local/nagios/libexec/check_nrpe -H localhost -c check_pod_cjoc
**NRPE: Unable to read output**

So I have defined a command definition in nrpe.cfg & restarted NRPE agent on the Remote server.

When I try to invoke this script from Nagios server. I'm getting "NRPE: Unable to read output" error. 

From Nagios Server
 /usr/local/nagios/libexec/check_nrpe -H <Remote-IP> -c check_pod_cjoc
**NRPE: Unable to read output**

I have tested with two versions of NRPE agent i.e 3.2.1 & 4.0.3, I didn't try with other versions, but getting same error message

Note: Nagios user has admin(sudo) rights to run these scripts on Remote server.

Nagios running is running on v4.4.5 on RHEL server.

Let me know if you need more information. Can you guys please look at it. @ericloyd  @sawolf 
######Stay Home#######Stay Safe#########
Thanks,
Srikanth

**Comment by rosri1992** [comment]
I found this in NRPE log file

[1589291681] Host X.X.X.X is asking for command 'check_pod_cjoc' to be run...
[1589291681] Running command: /usr/local/nagios/libexec/check_pods.sh -k config -n cloudbees-core -w 500 -C 800
[1589291681] WARNING: my_system() seteuid(0): Operation not permitted
[1589291681] Command completed with return code 3 and output:
[1589291681] Return Code: 3, Output: NRPE: Unable to read output
[1589291681] Connection from X.X.X.X closed.

Let me know if you need more information

**Comment by rosri1992** [comment]
The Issue which I have mentioned above is seen only from Nagios server.

The Command works fine on Remote server and gives expected output from Kubectl cluser.

When Nagios server tries to run this script on Remote server using check_nrpe plugin, it fails and give me NRPE Unable to read output error

**Comment by sawolf** [comment]
Closing this since it's not core-related (command fails when check_nrpe is invoked manually)
