### ISSUE TITLE
passive host check not executing check_command when freshness expires

### ISSUE THREAD

**Issue by cdienger** [NagiosEnterprises/nagioscore#768]
Core 4.4.5. Using the definition:

define host {
        host_name       192.168.55.5
        alias   192.168.55.5
        address 192.168.55.5
        check_period    xi_timeperiod_24x7
        check_command   check_dummy!2!!!!!!!
        contacts        nagiosadmin
        notification_period     xi_timeperiod_24x7
        initial_state   o
        importance      0
        check_interval  1.000000
        retry_interval  1.000000
        max_check_attempts      1
        active_checks_enabled   0
        passive_checks_enabled  1
        obsess  1
        event_handler_enabled   1
        low_flap_threshold      0.000000
        high_flap_threshold     0.000000
        flap_detection_enabled  0
        flap_detection_options  a
        freshness_threshold     60
        check_freshness 1
        notification_options    a
        notifications_enabled   1
        notification_interval   60.000000
        first_notification_delay        0.000000
        stalking_options        n
        process_perf_data       1
        icon_image      network_node.png
        statusmap_image network_node.png
        retain_status_information       1
        retain_nonstatus_information    1
        _XIWIZARD       genericnetdevice
        }

It will accept passive checks, but will not run the check_dummy command when the freshness threshold is crossed unless active_checks_enabled is 1.

**Comment by ericloyd** [comment]
That sounds right.  The passive check freshness failure triggers an active check which doesn't run unless active checks are enabled.

**Comment by arthurkay** [comment]
Is this really a bug?
To me this sounds like normal operation. Or maybe this is a feature request wrongly tagged as a bug

**Comment by HunnyPuns** [comment]
Definitely a bug.
> Tip: An active check is executed even if active checks are disabled on a program-wide or host- or service-specific basis. 

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/freshness.html

**Comment by scottwilkerson** [comment]
Are you sure 
`check_host_freshness=1`
 in the nagios.cfg?

**Comment by cdienger** [comment]
That could very well be the issue. I wasn't aware of that setting and it looks like it is set to 0 by default.
