### ISSUE TITLE
Nagiosql - Restart Getting Stuck

### ISSUE THREAD

**Issue by pradeepspa** [NagiosEnterprises/nagioscore#769]
Hello Folks,

I am running Nagios-core-4.2.4 on a centos7 machine integrated with Nagiosql (3.4.0). I am recently noticing an issue with "Restart Nagios" functionality in Nagiosql which eventually sends "Restart_Program" external command. Looks like whenever the command was passed, its not working as it should be. Below is the log. Any idea why it stopped working?

> May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: Nagios 4.2.4 starting... (PID=19761)
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: Local time is Thu May 14 15:40:01 UTC 2020
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: LOG VERSION: 2.0
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: qh: Socket '/usr/local/nagios/var/rw/nagios.qh' successfully initialized
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: qh: core query handler registered
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: nerd: Channel hostchecks registered successfully
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: nerd: Channel servicechecks registered successfully
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: nerd: Channel opathchecks registered successfully
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: nerd: Fully initialized and ready to rock!
May 14 15:40:01 nagios-core.bxi.lan nagios[19761]: wproc: Successfully registered manager as @wproc with query handler

>

**Comment by sawolf** [comment]
Hi @pradeepspa, thanks for reporting this.

What output are you expecting to see here? From your log, It looks to me like nagios started (that is, restarted) at 3:40pm on May 14th

**Comment by pradeepspa** [comment]
It looks like it but its not doing any check after that. Accessing Nagios GUI, it says "Internal server error". Only work around is to do a clean restart pf the daemon.

**Comment by sawolf** [comment]
That sounds somewhat familiar to me - there were some issues related to restarting/reloading the nagios daemon in nagios 4.3.x. I wouldn't be surprised if they were an issue before then as well.

If you create a test system with the latest nagios (4.4.6) and copy your configuration/nagiosql code, do you still have the same issue?
