### ISSUE TITLE
Check return codes everywhere

### ISSUE THREAD

**Issue by elfring** [NagiosEnterprises/nagioscore#78]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html) ⇒ [test_configured_paths](https://github.com/gree/flare/blob/492e6d62c57d43f98d71d6ef8bf5fdd71a4ff84c/src/lib/thread_pool.cc#L16)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [broker_event_handler](https://github.com/NagiosEnterprises/nagioscore/blob/ef348ff694d1e8cedac649cb398fefaa3390b35a/base/broker.c#L149)
- [write](http://pubs.opengroup.org/onlinepubs/9699919799/functions/write.html) ⇒ [qh_echo](https://github.com/NagiosEnterprises/nagioscore/blob/eb8e83d5d05e572eb8c0d4d4764885c5427b4b69/base/query-handler.c#L24)

**Comment by tmcnag** [comment]
Your link to [test_configured_paths](https://github.com/gree/flare/blob/492e6d62c57d43f98d71d6ef8bf5fdd71a4ff84c/src/lib/thread_pool.cc#L16) is pointing to a project that is not ours.  The other two are fine.

As usual, I will defer to @jfrickson for any final decisions.  I am but a humble adviser.

**Comment by jfrickson** [comment]
This will go along with (or rather supersede) http://tracker.nagios.org/view.php?id=410 and yes it probably should be done.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by tmcnag** [comment]
We'll take this all into consideration, thanks!  For now since this is not a pressing issue and is already on our Tracker, do you have anything else to add or can we close this?

**Comment by elfring** [comment]
I would appreciate if this issue will be kept open until all affected implementation details will be fixed.

Would you like to detect every error situation as early as possible?

**Comment by tmcnag** [comment]
We'll keep it open, though your last question seems a bit rhetorical  :)

**Comment by jfrickson** [comment]
This is an ongoing concern that won't be corrected all at once, and is on my list of code improvements. So I'm closing this issue.
