### ISSUE TITLE
Availability report not honoring Report Time Period when using it to exclude

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#782]
Nagios Core 4.4.6

If you setup a time period that only has:

july 31 00:00-15:00
july 31 16:00-23:59

That 15:00 to 16:00 gap is where some CRITICAL events occur and the time period above is set to exclude them. (I also tested with adding an exclusion to a standard timeperiod and that didn't work either)

If you run the availability (legacy and XI) report/SLA report and for the Period to include july 31 then select your new time period exclude from the Report Time Period dropdown it does not exclude them.

See here as well:

https://support.nagios.com/tickets/scp/tickets.php?id=10068

I replicated this on the customers system and on my own fresh install.

**Comment by aaronagios** [comment]
Fixed in 4.5.2.
