### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [NagiosEnterprises/nagioscore#79]
The function "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html)" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[sighandler](https://github.com/NagiosEnterprises/nagioscore/blob/4046e1c0fb222c820416be8ebc93cde9137c60f0/base/utils.c#L1618)".

**Comment by tmcnag** [comment]
Not too sure on this one, but it seems to me that if a segfault is occurring (which is the case in which exit() would be triggered) then maintaining async-safety does not seem like a high priority.  This is an incredibly freshman view of things I am sure, so please if I am wrong enlighten me.

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by jfrickson** [comment]
I did a first pass at this by changing calls to `signal` to `sigaction` and having it block all other signals as in `sigfillset(&sig_action.sa_mask);`. I will be looking into this further as time permits.

**Comment by jfrickson** [comment]
This is an ongoing concern that is on my list of code improvements. So I'm closing this issue.
