### ISSUE TITLE
Object inheritance and the web interface

### ISSUE THREAD

**Issue by surpadisfa** [NagiosEnterprises/nagioscore#790]
I'm running Nagios Core 4.4.3.

I have many hosts and their related services: every host has a "contact_groups" property declared (and not a "contacts" one), almost every related service doesn't have its own "contacts" or "contact_groups" because it's ok to inherit them from the host object.

There are some specific service objects that define their own "contacts" and "contact_groups" because I need a different behavior: I need that these services are notified and displayed on the web interface to different users than all the other host's services.

The problem I'm facing is that, while the notification part works properly, on the web interface I get mixed results.

Using the example snippet i posted below this is what I'm getting:
- Contact "all_notifications" gets notifications for all services "check 1", "check 2" and "check 3" and also sees them on the web interface as expected.
- Contact "check3_notifications" gets notifications for service "check 3" and sees only "check3" on the web interface as expected.
- Contact "web_user" gets notifications for services "check 1" and "check 2" but sees all of them on the web interface and that's where I'm failing to understand what's going on.

This is of course a simplified configuration snippet, I think (hope) I kept all the relevant parts.

```
define host {
        host_name       host1
        address               host1.mydomain.loc
        contact_groups        cg-host-monitoring
      ...
}

define service {
        host_name       host1
        service_description   check 1
      ...
}

define service {
        host_name       host1
        service_description   check 2
      ...
}

define service {
        host_name       host1
        service_description   check 3
        contacts        check3_notifications
        contact_groups        cg-check3
      ...
}

define contactgroup {
      contactgroup_name cg-host-monitoring
      members                 all_notifications,web_user
}     

define contactgroup {
      contactgroup_name cg-check3
      members                 all_notifications
}

define contact {
        contact_name            all_notifications
      ...
}

define contact {
        contact_name            web_user
      ...
}

define contact {
        contact_name            check3_notifications
      ...
}
```

**Comment by klaernie** [comment]
The documentation explains it clearly:
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/cgiauth.html
> Authenticated contacts[*](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/cgiauth.html#definitions) are granted the following permissions for each host for which they are contacts (but not for hosts for which they are not contacts)...
> …
> - Authorization to view status information for all services on the host
> …

**Comment by ericloyd** [comment]
Simply, Nagios shows you anything for which you are configured to receive notifications.

**Comment by surpadisfa** [comment]
Thanks for the replies. I changed my configuration to suit my needs. From my point of view this issue is no more regardless of whether it works as intended or is a problem.
