### ISSUE TITLE
Queries in Nagios Core Availability Report

### ISSUE THREAD

**Issue by nishithvyas** [NagiosEnterprises/nagioscore#791]
While fetching "Nagios Availability Report", I've observed that sometimes Nagios shows below listed statistics. 

06-05-2020 11:30:55 | 06-05-2020 11:30:56 | 0d 0h 0m 1s | PROGRAM END | Normal program termination
06-05-2020 11:30:56 | 06-05-2020 11:33:20 | 0d 0h 2m 24s | PROGRAM (RE)START | Program start
06-05-2020 11:33:20 | 06-05-2020 11:33:21 | 0d 0h 0m 1s | PROGRAM END | Normal program termination
06-05-2020 11:33:21 | 06-06-2020 00:00:00 | 0d 12h 26m 39s | PROGRAM (RE)START | Program start

So, I'd like to know what exactly the mean of "Normal Program Termination" & "Program Start".

Thanks,
**Nishith N. Vyas**

![Nagios_Availabiliy_Report_Query](https://user-images.githubusercontent.com/19428787/94006712-e15f8000-fdbd-11ea-8fed-9d4972f9cf25.jpg)

**Comment by ericloyd** [comment]
Nagios core reloads (which are actually stops and starts).

**Comment by nishithvyas** [comment]
In that situation, nagios should show that respective services should show OK status in availability report. Isn't that true?

**Comment by ericloyd** [comment]
Nagios itself is not a service.  It is the program itself.  So having it in an availability report allows you to see the availability of Nagios itself.

Maybe I am not understanding what you're asking.

**Comment by nishithvyas** [comment]
Hello,

I understand the concern. In other way, I was trying to get remote host service availability report where it is showing the first error message.

Here, if client ask us to provide availability report, we can't give the report because it doesn't show full 24 hour report. See the first snapshot.

**Comment by nishithvyas** [comment]
On technical ground & as per the attached snap shot, Nagios should show 100% availability report as the remote server/service was UP & Running. Rather than it is showing below status.

06-05-2020 11:30:55 | 06-05-2020 11:30:56 | 0d 0h 0m 1s | PROGRAM END | Normal program termination
06-05-2020 11:30:56 | 06-05-2020 11:33:20 | 0d 0h 2m 24s | PROGRAM (RE)START | Program start
06-05-2020 11:33:20 | 06-05-2020 11:33:21 | 0d 0h 0m 1s | PROGRAM END | Normal program termination
06-05-2020 11:33:21 | 06-06-2020 00:00:00 | 0d 12h 26m 39s | PROGRAM (RE)START | Program start

I think, we should get SERVICE OK Message only.
