### ISSUE TITLE
servicedependency: dependent_service_description requirement when dependent_servicegroup_name is used?

### ISSUE THREAD

**Issue by cdienger** [NagiosEnterprises/nagioscore#796]
Say I created a servicedependency and wanted to use dependent_servicegroup_name, should I still have to define dependent_service_description ?

dependent_service_description appears to be a requirement, but does that make sense?

**Comment by sawolf** [comment]
refer to https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/objecttricks.html#servicedependency for this - if you do configuration directly in the files, it should work to just specify servicegroups. If you do configuration through another interface (like NagioSQL or the Nagios XI CCM), it's a pretty niche combination and those interfaces might not allow it.
