### ISSUE TITLE
SSO Authentication integration in Nagios XI

### ISSUE THREAD

**Issue by bindybandy** [NagiosEnterprises/nagioscore#798]
Considering purchasing Nagios XI licences for datacentre but it appears you do not offer and SSO options - SAML is something we use as standard to meet security policies so have you any plans to introduce this in the very near future? I see you release frequent NagiosXI updates each year so maybe one is imminent for 2020?

**Comment by sawolf** [comment]
Hi @bindybandy, thanks for reaching out - I recommend you refer this kind of question to sales@nagios.com. This issue list is for code issues in Nagios Core, not for product questions in Nagios XI.
