### ISSUE TITLE
Need to stop sound alert on every refresh

### ISSUE THREAD

**Issue by hbtechnologia** [NagiosEnterprises/nagioscore#799]
Hi folks, i have followed this guide to enable sound alert in nagios but it speaks on every refresh and i want that it plays the file only once is it possible ?

https://www.pearlsit.com/configure-audio-alerts-in-nagios-core/

**Comment by hbtechnologia** [comment]
anyone there ?

**Comment by ericloyd** [comment]
You'd have better luck asking for general support in the Support Forums.  This is more for code issues.

https://support.nagios.com/forum/

**Comment by hbtechnologia** [comment]
Got it.
