### ISSUE TITLE
configuring with empty --with-htmurl= leads to images loading problem

### ISSUE THREAD

**Issue by slawomir-sikora** [NagiosEnterprises/nagioscore#8]
I want run my nagios without /nagios context. 
My configuration options are:
./configure --with-nagios-user=nagios --with-command-group=nagioscmd --with-htmurl='' --with-cgiurl='/cgi-bin'

At the end of configuration there is ..

 Web Interface Options:
 ------------------------
                 HTML URL:  http://localhost/
                  CGI URL:  http://localhost/cgi-bin/

Looks GOOD!

Next make all, make install, make install-commandmode, make install-config etc

Virtual Host configuration:

<VirtualHost *:80>
	ServerAdmin admin@MY_DOMAIN
	ServerName nagios.MY_DOMAIN

	DocumentRoot /usr/local/nagios/share
	<Directory />
		Options FollowSymLinks
		AllowOverride None
	</Directory>

	ScriptAlias /cgi-bin "/usr/local/nagios/sbin"

	<Directory "/usr/local/nagios/sbin">
		Options ExecCGI
		AllowOverride None
		Order allow,deny
		Allow from all
		AuthName "Nagios Access"
		AuthType Basic
		AuthUserFile /usr/local/nagios/etc/htpasswd.users
		Require valid-user
	</Directory>
	<Directory "/usr/local/nagios/share">
		Options None
		AllowOverride None
		Order allow,deny
		Allow from all
		AuthName "Nagios Access"
		AuthType Basic
		AuthUserFile /usr/local/nagios/etc/htpasswd.users
		Require valid-user
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/nagios/error.log

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/nagios/access.log combined

</VirtualHost>

All above leads to nagios looks like this:

![nagios](https://cloud.githubusercontent.com/assets/8234094/3657232/27e1014e-1192-11e4-8df0-fa7cfcabb113.png)

SOLITION:
Edit etc/cgi.cnf and set url_html_path to "/"

url_html_path=/

Instalation script leaves it blank which is not correct.

**Comment by tmcnag** [comment]
Should probably be closed.
