### ISSUE TITLE
Setup Nagios users to view specific host is not working in the new network map.

### ISSUE THREAD

**Issue by dbareiro** [NagiosEnterprises/nagioscore#80]
Hi all!!

When I create a user who has permissions to view a subset of hosts, the "legacy map" shows this subset for this user but the new network map shows only the Nagios process. This happens in Nagios 4.1.1.

Please let me know if you need more information.

Thanks!

Best regards,
Daniel

**Comment by dbareiro** [comment]
Hi!

I would like to know if you were able to see something about this issue, because unlike others, this was not labeled as "bug". I would appreciate if you have any update on this issue.

I have some installations where we use the feature mentioned in the issue and I would like to upgrade to the new version of Nagios Core, but I could not do it because of the described problem. If there is something else on I can help, please let me know.

Thanks.

Best regards,
Daniel

**Comment by jfrickson** [comment]
Hi Daniel, this is on my list of things to do, and I hope to get to it fairly soon. I'll post more here as soon as I know more.

**Comment by dbareiro** [comment]
Hi, John.

Thank you for your reply. I hope your comments.

Best regards,
Daniel

**Comment by jfrickson** [comment]
Hi Daniel, Sorry it took so long to get back on this issue.

Currently, for all hosts you want them to view, they need permissions for the parent(s) as well. Also, they must have permission to all children of that parent. For example, host1, host2 and host3 all have switch1 as their parent. To view host1, they must be able to view switch1 and also host2 and host3. If switch1 has a parent, they must be able to view its parent also.

The place where these checks happen is very complex, so I don't have a fix yet. For now, my description should give you a work-around.

**Comment by jfrickson** [comment]
Fixed with commit https://github.com/NagiosEnterprises/nagioscore/commit/90c6ae6f696d5d1cfdb7a1b1c2a6848145bdbbfe
in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1

**Comment by dbareiro** [comment]
Hi, John.

Glad to read you. I hope you are well.

Thanks for your reply.

I read you were talking about a workaround. But then you published a patch. By applying this patch the workaround no longer needed?

Thanks again.

Best regards,
Daniel

**Comment by jfrickson** [comment]
Yes, with the patch, you shouldn't need a workaround.

**Comment by dbareiro** [comment]
Hi, John.

Thanks for confirm.

I applied the patch to the ```html/js/map-directive.js``` of core Nagios 4.1.1 and then I've recompiled it. But this has not worked for me.

I created a ```customer1``` user with permission to view the ```ws2``` host. I can see the host and services, but the host does not appear in the network map. Attached screenshots.

![restricteduser1](https://cloud.githubusercontent.com/assets/7597354/11278595/88f4e264-8eca-11e5-94c7-3544096899cf.png)
![restricteduser2](https://cloud.githubusercontent.com/assets/7597354/11278594/88ec73a4-8eca-11e5-95f4-078b1ffab544.png)
![restricteduser3](https://cloud.githubusercontent.com/assets/7597354/11278596/88fb8592-8eca-11e5-9923-552fa96ba09a.png)

I think I have applied the patch correctly. Attached patched file. I think that after compilation and installation it is ```/usr/local/nagios/share/js/map-directive.js```.

[map-directive.js.txt](https://github.com/NagiosEnterprises/nagioscore/files/39272/map-directive.js.txt)

Thanks for your time.

Best regards,
Daniel

**Comment by jfrickson** [comment]
Hi Daniel,

Sorry for the delay.

If `ws2` has a parent, that parent must be visible. If the parent has a parent, that must be visible also, and so on. The map can not be displayed unless view permissions are on all objects between the nagios process and the final object.

**Comment by dbareiro** [comment]
Hi, John.

> Sorry for the delay.

No problem :-)

> If ws2 has a parent, that parent must be visible. If the parent has a parent, that must be visible also, 
> and so on. The map can not be displayed unless view permissions are on all objects between the 
> nagios process and the final object.

Thanks for the reply. I see here that what you say has to do with the workaround you mentioned a few days ago. I thought that since you told me that with this patch then the workaround was not necessary, then there was no need to give permission to all hosts parents. Perhaps we misunderstand. It seems that the patch consists of implementing the workaround you mentioned.

Based on the following direct relationship:

```
ws2 -> ss01 -> Alderamin -> Router1 -> Nagios Process
```
Now I've given permission to the group to which the user belongs on SS01, Alderamin and Router1. I did this only in the host definition for each one of them. But it has a side effect: the user sees (and will receive notifications) the services of the intermediate hosts. How I can prevent it so that the user only sees the services of ws2?

Moreover, all hosts are superimposed on the network map:

![restricteduser4](https://cloud.githubusercontent.com/assets/7597354/11286779/b3ed749c-8ef5-11e5-9b90-95886d497872.png)

Thanks for your time.

Best regards,
Daniel

**Comment by jfrickson** [comment]
I don't know what I can do about the hosts overlapping, but I'll look into it. I'll also check if there is any way to display a host without its parents, but I doubt it. I'll leave the issue open for a while as I do more research.

**Comment by dbareiro** [comment]
Hi, John.

Thanks for reopen the issue.

I wonder if before publishing the patch and close the ticket, in your test environment, you has noticed this overlapping problem on the map. Just to know if this could be something on my installation because maybe your tests were with the code of Nagios Core 4.1.2 and my environment is Nagios Core 4.1.1

Thanks again.

Best regards,
Daniel

**Comment by jfrickson** [comment]
Fixed with commit https://github.com/NagiosEnterprises/nagioscore/commit/44d5ea45ecbe7f49aa66b655a9dfe82879c93b43
on branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1

**Comment by dbareiro** [comment]
Hi, John.

Thank you very much for your time to publish this new commit.

I think to have some differences in my file ```html/js/map-directive.js``` for Nagios Core 4.1.1. After  applying the patch related to the commit 90c6ae6, it was as follows:

```
1183                                                         $scope.hostList[host].name = host;
1184                                                         $scope.hostList[host].serviceCount = 0;
1185                                                 }
1186                                                 // Update the information returned
1187                                                 $scope.hostList[host].objectJSON =
1188                                                                 json.data.hostlist[host];
1189                                         }
```
We seem to have an offset of three lines. Is it posible?

Best regards,
Daniel

**Comment by jfrickson** [comment]
My guess is you're missing https://github.com/NagiosEnterprises/nagioscore/commit/7ca4de0c8dc20d8d4e93c7918433f1428d243b04#diff-a60f950fb4a56c5a3740a530cf705552

**Comment by dbareiro** [comment]
Hi, John.

> My guess is you're missing 7ca4de0#diff-a60f950fb4a56c5a3740a530cf705552

Yes, I can see that doing a ```diff``` between the file on my local server and the one on the git repository. Thanks!

After adding the lines introduced by the commit 7ca4de0 I was able to apply without problems the commit 44d5ea4.

I have a feeling that after applying 7ca4de0, the hosts icons get better organized following a bouquet form based on the father of each hosts. Before I think this did not happen and the hosts appeared with crisscrossing lines.

After applying 44d5ea4, I did a test only giving permission to the user on ```ws2```. The result is that the host is shown although it is superimposed with the Nagios process.

![restricteduser5](https://cloud.githubusercontent.com/assets/7597354/11409975/8096d406-93a2-11e5-9019-52df6498d108.png)
**Note**: doing a zoom out not change the situation.

But if after I give permission to all parents until reach the Nagios process, several hosts are repeated:

![restricteduser6](https://cloud.githubusercontent.com/assets/7597354/11410250/a63d924c-93a4-11e5-8787-ea69c194ccce.png)

**Note**: the relationship is ```ws2 -> ss01 -> Alderamin -> Router1 -> Nagios Process```

It seems that this has become more complicated than we thought :-(
I appreciate your effort and your time.

Best regards,
Daniel

**Comment by dbareiro** [comment]
Hi, John.

> But if after I give permission to all parents until reach the Nagios process, several hosts are repeated

Oh, now I observe more closely the initial view of the map with all hosts, unrestricted, I see that many are also repeated. Maybe it has to do with what someone said in the forum:

https://support.nagios.com/forum/viewtopic.php?f=7&t=34307&start=70#p152920

Although I'm not sure if this is already fixed in the beta.

Best regards,
Daniel

**Comment by dbareiro** [comment]
Hi, John.

I hope you are well.

When you can, please let me know what I commented in the last two messages.

Thanks in advance for your time.

Best regards,
Daniel

**Comment by jfrickson** [comment]
Getting too many comments here. I opened another issue:
https://github.com/NagiosEnterprises/nagioscore/issues/97

**Comment by aristech47** [comment]
I am running Nagios 4.4.2 and I want to setup my admins with access to only the locations they are in charge of. Is there any documentation or how too?
