### ISSUE TITLE
Active Directory integration not working

### ISSUE THREAD

**Issue by surajsah2053** [NagiosEnterprises/nagioscore#802]
I tried to use Nagios XI for the testing environment to integrate Active Directory Microsoft server instance from the AWS. 
The Active Directory successfully integrated and also working well. But when I integrate the Active Directory as your document "https://assets.nagios.com/downloads/nagiosxi/docs/Authenticating-and-Importing-Users-with-Active-Directory-in-Nagios-XI.pdf" say  there is no any kinds of errors or not even a successful windows of active directory open after the authentication in Add Users from LDAP/AD .

**Comment by sawolf** [comment]
Hopefully you've had your concern answered somewhere else, but in the future I would recommend contacting Nagios XI support for this kind of issue.
