### ISSUE TITLE
Invalid Logins are not sent to syslog, because of this it is not possible to create a fail2ban jail.

### ISSUE THREAD

**Issue by xekon** [NagiosEnterprises/nagioscore#806]
I was going to create a fail2ban jail filter to ban invalid login attempts.

but unfortunately it seems invalid login attempts with IP address are not sent to the log file.

If the invalid login attempt were output to the log then I could create the fail2ban filter myself, that is not a problem.

I will also share the jail config here if somebody could please just send invalid login attempt to the log with ip address, I would really appreciate this fix.

**Comment by ericloyd** [comment]
I believe invalid logins are logged to the HTTP error log, which you could have fail2ban monitor directly.

**Comment by xekon** [comment]
You are correct! thank you so much, appreciate the response.

**Comment by ericloyd** [comment]
Glad to help!

**Comment by xekon** [comment]
Here is a fail2ban filter and jail that works for me.

`sudo nano /etc/fail2ban/filter.d/nagios-web.conf`
```
[Definition]
failregex = .*client <HOST>:\d+.*authentication failure for.*
ignoreregex =
```

`sudo nano /etc/fail2ban/jail.local`
```
[nagios-web]
enabled = true
filter = nagios-web
action = iptables-allports[name=nagios-web, port="http,https", protocol=tcp]
logpath = /var/log/apache2/error.log
maxretry = 1
bantime = -1
```
