### ISSUE TITLE
Service & host problems cannot be acknowledged without comment (when set to not required)

### ISSUE THREAD

**Issue by mulroony** [NagiosEnterprises/nagioscore#808]
We made comments optional when acknowledging a service / host issue by setting the following settings in 'cgi.cfg'.

CMT_ACKNOWLEDGE_HOST_PROBLEM=1
CMT_ACKNOWLEDGE_SVC_PROBLEM=1

The setting works in that the comment box becomes optional as expected in the web interface. When an acknowledgement is submitted without a comment an error is thrown and the acknowledgement does not go through. If you completely disable comments I believe no acknowledgements are recognized. 

If I am reading the code correctly it looks like lines [2579-2582 in commands.c](https://github.com/NagiosEnterprises/nagioscore/blob/master/base/commands.c#L2578) are hard coded to require a comment.

Thanks! Let me know if there is anything else I can provide or test.

To test:

1. Add 'CMT_ACKNOWLEDGE_SVC_PROBLEM=1' to 'cgi.cfg' file
2. Trigger a service problem
3. Attempt to submit problem acknowledgement leaving the comment blank.
4. Error will appear in log.

$ uname -a
Linux ... 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release 
CentOS Linux release 8.3.2011

$ rpm -qa|grep nagios
nagios-common-4.4.5-1.el8.x86_64
nagios-4.4.5-1.el8.x86_64

**Comment by TomTheGeek** [comment]
Also experiencing this issue with nagios4-core 4.4.6-4 on Debian. 

Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

Please fix!
