### ISSUE TITLE
Using host macros in static service definition

### ISSUE THREAD

**Issue by ericloyd** [NagiosEnterprises/nagioscore#81]
Originally from forum post:  https://support.nagios.com/forum/viewtopic.php?f=7&t=28674:

My browse through common/macros.c indicates that _SERVICE and _HOST and _CONTACT variables are all included at the same time, but only in service, host, and contact configurations.

So you're trying to use a $_HOST macro in a service definition and I think it should work. So I'm guessing you're either not doing it right (doubtful) or it's a bug.

**Comment by tmcnag** [comment]
Labeling this as an enhancement for now unless someone can find any documentation saying it should work as you described.

**Comment by giteric** [comment]
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/customobjectvars.html
It is not clear if SERVICE_ variables should be available in a host definition and vice versa, but it does say this:
"Custom variables allow users to define additional properties in their host, service, and contact definitions, and use their values in notifications, event handlers, and host and service checks."
Nothing about those variables ONLY being available in the type of config block that matches their type.
:-)

**Comment by tmcnag** [comment]
Custom variables and the macros used to reference them are different.  When it says "and user their values in notifications, event handlers, and host and service checks" that is referring to the macros, not the custom variables themselves.

**Comment by giteric** [comment]
Go back and look at the original post in the forum page.  I think OP should be able to do what they want to do.  Even abrist said so in reply #10.  :-)

**Comment by jfrickson** [comment]
I just took a closer look at this. It would open one _**HUGE**_ can'o'worms. If someone really wants this, we can discuss it below, and maybe that someone can appeal to a higher authority. But I'm going to say "nope".

**Comment by ericloyd** [comment]
Wow.  2 years to debate, 18 minutes to close.  :-)  Would love to discuss with you sometime offline.
