### ISSUE TITLE
Nrpe can't read files on Remote hosts (Permission is correct)

### ISSUE THREAD

**Issue by rathodloki** [NagiosEnterprises/nagioscore#811]
These are the two commands I have tried which will access files on remote files

```
 $ ./check_nrpe -H 172.31.35.55 -c check_logs
 $ ./check_nrpe -H 172.31.35.55 -c check_file_age
```
 config on remote server-> _**/etc/nrpe.cfg**_
 
```

1. command[check_log]=/usr/lib64/nagios/plugins/check_log -F /home/ec2-user/shaft2/logs/access.log -O /tmp/access.log -q '404'
2. command[check_file_age]=/usr/lib64/nagios/plugins/check_file_age -f "/home/ec2-user/shaft2/logs/access.log"

```
Yet I have also tried changing permission on files but still not get solved.
Can anyone please help me on that.

**Comment by sawolf** [comment]
Honestly, if you're setting up new monitoring, I would try to install NCPA rather than NRPE. It has far fewer footguns and it's not deprecated. That said, this issue list is for Nagios Core, so I'm closing this issue.
