### ISSUE TITLE
A '^' character in service output being replaced by incomplete entity code by status.cgi

### ISSUE THREAD

**Issue by ftruscot** [NagiosEnterprises/nagioscore#813]
I have a custom plugin that produces output which contains the ^ character extensively. 

When using it in a Nagios Core 4.3.1 instance, the output is correctly displayed by status.cgi.

When using it on a Nagios Core 4.4.5 instance, the output gets mangled by the status.cgi program. Specifically, the '^' character is replaced by `&#94`. Note that it does not include the ; required to terminate the entity. This has the effect of rending ^1 on the service status page as 'έ' which is the character one would expect for the entity `&#941;` and a '^2' gets rendered as a 'ή' which is the character expected by the entity `&#942;`. So, the browser is trying to figure out the end of the entity encoding itself. If the next character after the '^' in the output is not a number, the browser figures out that the intended entity was `&#94;` and it renders the '^'.

The instance exhibiting the bug (4.4.5) is running on `Linux hostname 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

This is what I see in the GUI (rendered by status.cgi):
![image](https://user-images.githubusercontent.com/78814295/107403447-1e10e700-6ad3-11eb-8ab7-202cafa23c7d.png)

This is the HTML source for the service output shown above:

    `<TR><TD CLASS='dataVar' VALIGN='top'>Status Information:</TD><TD CLASS='dataVal'>[WARNING] There are 1 differences in configurations<BR>CacheConfigSecurityServices Differences<BR>NAME&#94Enabled&#94Description&#94AutheEnabled&#94AutheEnabledCapabilities&#94Capabilities&#94ClientSystems<BR>**********<BR>10.10.41.197: %Service_DataCheck&#941&#94Controls this system as a DataCheck source&#941024&#941024&#94905&#9410.10.41.198<BR>10.10.41.198: %Service_DataCheck&#941&#94Controls this system as a DataCheck source&#941024&#941024&#94905&#9410.10.41.197<BR>**********<BR></TD></TR>`

Notice that there are no semicolons to close the '&#94;' entities.

Here is the output as it sits in the status.dat file:
`        plugin_output=[WARNING] There are 1 differences in configurations`

`        long_plugin_output=CacheConfigSecurityServices Differences\nNAME^Enabled^Description^AutheEnabled^AutheEnabledCapabilities^Capabilities^ClientSystems\n**********\n10.10.41.197: %Service_DataCheck^1^Controls this system as a DataC
heck source^1024^1024^905^10.10.41.198\n10.10.41.198: %Service_DataCheck^1^Controls this system as a DataCheck source^1024^1024^905^10.10.41.197\n**********\n
`

So what is going into status.cgi as '^' comes out as `&#94` (without a closing semicolon) and thus gets rendered by the browser in unreliable ways.

I do not have control over the nagios server, but I will try to influence its upgrade to the latest 4.4.6. I have looked through the changelog and the other reported bugs and I do not see anything that seems to address this character encoding issue.

**Comment by ftruscot** [comment]
I'm not a C coder, but I believe the issue is in cgi/cgiutils.c

The html_encode function (starting on line 1145) incudes the ^ in the characters to be encoded, by excluding it from the list of characters not encoded around line 1165-66:

		/* Most ASCII characters don't get encoded */
		if (*incp >= 0x20 && *incp <= 0x7e && !strchr("'\"&^<>", *incp)) {

After a series of elseif statements dealing with special cases among the characters listed above for encoding, the '^' character is not handled so falls to the final else statement on lines 1339-40:

		else
			outcp = encode_character(*incp, outcp, output_max);

In the encode_character() function starting on line 1099, there is a switch statement (styarting on line 11:04) that sets the entitiy string to use for most the characters that should be encoded, but the '^' character is not included. That leaves the encoding to be done by the code on line 1124:

	sprintf(outcp, "&#%u", (unsigned int)in);

This code does not include the required ';' character after the entity number represented by %u. Thus we see that all the other intended characters get encoded properly except this '^' character which is renderd as '&#94'

Regardless if this is fixed in html_encode() by not specifying it for encoding, or in encode_character() by inclduing it on the switch statement, the sprintf() call on line 1124 should have the ';' included in the replacement string so that this problem doesn't happen with any other future 'unhandled' characters set to be encoded.

**Comment by sawolf** [comment]
Hi @ftruscot, thanks for reaching out.

I agree that the current behavior isn't correct. I think that, rather than adding another exception to the html entity encoding, I just need to find a way to write the html entities correctly. The bug you're describing could in principle affect anything that gets encoded as an entity, not just the '^' character.
