### ISSUE TITLE
Command definitions that end in a \\ will cause the objects.cache file to only have a single \ breaking the CGIs (at least for statusjson)

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#819]
Command definitions that end in a `\\` will cause the objects.cache file to only have a single `\` breaking the CGIs (at least for statusjson).

Add this as a command definition and apply config/restart nagios:

```
define command {
        command_name    check_whatever
        command_line    $USER1$/check_dummy 0 K:\\
        }
```

Validate through the CLI and see the error messages:

```
[root@xid var]# /bin/sh -c 'export QUERY_STRING="query=programstatus" && REQUEST_METHOD=GET /usr/local/nagios/sbin/statusjson.cgi' apache | head -20
Cache-Control: no-store
Pragma: no-cache
Last-Modified: Wed, 10 Mar 2021 18:16:51 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-type: application/json; charset=utf-8

{
  "format_version": 0,
  "result": {
    "query_time": 1615400211000,
    "cgi": "statusjson.cgi",
    "query": "programstatus",
    "query_status": "released",
    "program_start": 0,
    "type_code": 2,
    "type_text": "Unable to Open File for Reading",
    "message": "Error: Could not read some or all object configuration data!"
```

**The workaround:**

Now edit the command definition and add a literal space after the `K:\\ ` and apply config/restart nagios and it will work:

```
[root@xid var]# /bin/sh -c 'export QUERY_STRING="query=programstatus" && REQUEST_METHOD=GET /usr/local/nagios/sbin/statusjson.cgi' apache | head -20
Cache-Control: no-store
Pragma: no-cache
Last-Modified: Wed, 10 Mar 2021 18:22:18 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-type: application/json; charset=utf-8

{
  "format_version": 0,
  "result": {
    "query_time": 1615400538000,
    "cgi": "statusjson.cgi",
    "user": "",
    "query": "programstatus",
    "query_status": "released",
    "program_start": 1615400180000,
    "last_data_update": 1615400530000,
    "type_code": 0,
    "type_text": "Success",
    "message": ""
  },

```

EDIT: While you're in there, how can we get the config errors (it reads the objects.cache for the cgis only) to show what the issue is in this case? I had to modify the xodtemplate.c and write the errors to a file to even get it to show anywhere WHY and WHAT it was failing on.

**Comment by sawolf** [comment]
This is unintuitive, but I think it's the intended behavior - a backslash right before a newline indicated that the newline should be ignored, and the next line should be treated as though it's on the same line, similar to Makefiles.
