### ISSUE TITLE
Optional/default comments in Acknowledgments

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#82]
Comments should either be optional, or be set to a (configurable?) default if left blank.

https://support.nagios.com/forum/viewtopic.php?t=35154#156301

**Comment by giteric** [comment]
I agree that comments should be optional.  This would alleviate the "middleware piece of PHP" that has to be used to automatically add a comment and drop things in the command file when using URLs to auto-acknowledge things.

**Comment by jfrickson** [comment]
Note: related to http://tracker.nagios.org/view.php?id=52

**Comment by jfrickson** [comment]
This is in branch `cmd_comments`. Not sure when or if it will be released.

**Comment by jfrickson** [comment]
Fixed in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.4.0-alpha1 via commit f885e90
