### ISSUE TITLE
Nagios 4.4.5+ SIGBUS, SIGABRT coredump

### ISSUE THREAD

**Issue by Kilvador** [NagiosEnterprises/nagioscore#825]
Hello!

My system is: RedHat 7, 3.10.0-1160.24.1.el7.x86_64, glibc-2.17.323
Nagios version: 4.4.5, 4.4.6

Got SIGBUS, SIGABRT on glibc-2.17:

journalctl:
Jun 01 18:36:34 NewNagios2 kernel: traps: nagios[20366] trap stack segment ip:7f0022f29df2 sp:7ffcce68b9c0 error:0 in libc-2.17.so[7f0022ea4000+1c4000]
Jun 01 18:36:34 NewNagios2 abrt-hook-ccpp[8849]: Process 20366 (nagios) of user 501 killed by SIGBUS - dumping core
Jun 01 18:36:35 NewNagios2 systemd[1]: nagios.service: main process exited, code=dumped, status=7/BUS

core:
(gdb) bt
#0  0x00007f0022f29df2 in realloc () from /lib64/libc.so.6
#1  0x0000000000474ea4 in iocache_resize (ioc=0x23626d0, new_size=2097152) at iocache.c:63
#2  0x0000000000474f4e in iocache_grow (ioc=0x23626d0, increment=1048576) at iocache.c:73
#3  0x00000000004756d8 in iocache_read (ioc=0x23626d0, fd=20) at iocache.c:203
#4  0x000000000041941f in handle_worker_result (sd=20, events=<optimized out>, arg=0x2361730) at workers.c:733
#5  0x000000000047680d in iobroker_poll (iobs=0x2342140, timeout=0) at iobroker.c:353
#6  0x0000000000433661 in event_execution_loop () at events.c:1135
#7  0x0000000000413d59 in main (argc=<optimized out>, argv=<optimized out>) at nagios.c:846
(gdb)

journalctl:
Jun  1 20:03:11 NewNagios2 systemd: nagios.service: main process exited, code=dumped, status=6/ABRT
Jun  1 20:03:11 NewNagios2 abrt-hook-ccpp: Process 22631 (nagios) of user 501 killed by SIGABRT - dumping core
Jun  1 20:03:13 NewNagios2 systemd: Configuration file /usr/lib/systemd/system/nagios.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jun  1 20:03:13 NewNagios2 systemd: Unit nagios.service entered failed state.
Jun  1 20:03:13 NewNagios2 systemd: nagios.service failed.
Jun  1 20:03:54 NewNagios2 abrt-server: Generating core_backtrace

core_debug:
(gdb) bt
#0  0x00007f0f33a093d7 in raise () from /lib64/libc.so.6
#1  0x00007f0f33a0aac8 in abort () from /lib64/libc.so.6
#2  0x00007f0f33a4bf67 in __libc_message () from /lib64/libc.so.6
#3  0x00007f0f33a52474 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f0f33a57861 in _int_realloc () from /lib64/libc.so.6
#5  0x00007f0f33a58e12 in realloc () from /lib64/libc.so.6
#6  0x00000000004dc174 in iocache_resize (ioc=0x14ce020, new_size=4194304) at iocache.c:63
#7  0x00000000004dc21e in iocache_grow (ioc=0x14ce020, increment=2097152) at iocache.c:73
#8  0x00000000004dc9fe in iocache_read (ioc=0x14ce020, fd=36) at iocache.c:207
#9  0x0000000000420890 in handle_worker_result (sd=36, events=1, arg=0x13f3920) at workers.c:733
#10 0x00000000004ddb33 in bitmap_clear (bm=0x0) at bitmap.c:25
#11 0x0000000000450d0e in event_execution_loop () at events.c:1135
#12 0x0000000000416094 in main (argc=3, argv=0x7fff484d8d78) at nagios.c:846
(gdb) frame 5
#5  0x00007f0f33a58e12 in realloc () from /lib64/libc.so.6
(gdb) frame 6
#6  0x00000000004dc174 in iocache_resize (ioc=0x14ce020, new_size=4194304) at iocache.c:63
63              buf = realloc(ioc->ioc_buf, new_size);

Made this patch on 4.4.6 version, tested one day - no coredumps:

[iocache.c.patch.zip](https://github.com/NagiosEnterprises/nagioscore/files/6591295/iocache.c.patch.zip)

```
diff -ur nagios-4.4.6/lib/iocache.c nagios-4.4.6-fixed/lib/iocache.c
--- nagios-4.4.6/lib/iocache.c	2020-04-28 23:48:29.000000000 +0300
+++ nagios-4.4.6-fixed/lib/iocache.c	2021-06-02 13:33:45.055036247 +0300
@@ -188,7 +188,7 @@
 
 int iocache_read(iocache *ioc, int fd)
 {
-	int to_read, bytes_read, ret;
+	int to_read, bytes_read;
 
 	if (!ioc || !ioc->ioc_buf || fd < 0)
 		return -1;
@@ -198,18 +198,9 @@
 
 	/* if we've maxed out our buflen, grow by 2x to be safe */
 	if (ioc->ioc_buflen >= ioc->ioc_bufsize) {
-
-		to_read = ioc->ioc_buflen + ioc->ioc_bufsize;
-		ret = iocache_grow(ioc, ioc->ioc_bufsize);
-		if (ret == -1) {
-			to_read = ioc->ioc_buflen;
-		}
-
-	} else {
-
-		/* calculate the size we should read */
-		to_read = ioc->ioc_bufsize - ioc->ioc_buflen;
+		iocache_grow(ioc, ioc->ioc_bufsize);
 	}
+	to_read = ioc->ioc_bufsize - ioc->ioc_buflen;
 
 	bytes_read = read(fd, ioc->ioc_buf + ioc->ioc_buflen, to_read);
 	if (bytes_read > 0) {

```

**Comment by sawolf** [comment]
Should be resolved by #828
