### ISSUE TITLE
installing nagioscore 4.4.5 on fedora 34  giving below error. 

### ISSUE THREAD

**Issue by vidhya199** [NagiosEnterprises/nagioscore#829]
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCGI -c -o statusdata-cgi.o ../common/statusdata.c
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCGI -c -o xstatusdata-cgi.o ../xdata/xsddefault.c
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCGI -c -o comments-cgi.o ../common/comments.c
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCGI -c -o downtime-cgi.o ../common/downtime.c
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCGI -DJSON_NAGIOS_4X -c -o archiveutils.o archiveutils.c
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCGI -DJSON_NAGIOS_4X -c -o jsonutils.o jsonutils.c
gcc -Wall -I.. -g -O2 -DHAVE_CONFIG_H -DNSCGI -DJSON_NAGIOS_4X  -o archivejson.cgi archivejson.c ../common/shared.o getcgi.o cgiutils.o cgiauth.o macros-cgi.o  objects-cgi.o xobjects-cgi.o statusdata-cgi.o xstatusdata-cgi.o comments-cgi.o downtime-cgi.o ../lib/libnagios.a archiveutils.o jsonutils.o 
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:55: multiple definition of `process_performance_data'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:21: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:54: multiple definition of `enable_flap_detection'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:33: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:51: multiple definition of `obsess_over_hosts'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:41: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:50: multiple definition of `obsess_over_services'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:40: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:49: multiple definition of `enable_event_handlers'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:39: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:48: multiple definition of `accept_passive_host_checks'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:38: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:47: multiple definition of `execute_host_checks'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:37: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:46: multiple definition of `accept_passive_service_checks'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:36: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:45: multiple definition of `execute_service_checks'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:35: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:44: multiple definition of `enable_notifications'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:34: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:43: multiple definition of `last_log_rotation'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:27: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:41: multiple definition of `program_start'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:14: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:42: multiple definition of `daemon_mode'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:25: first defined here
/usr/bin/ld: xstatusdata-cgi.o:/tmp/nagioscore-nagios-4.4.5/cgi/../xdata/xsddefault.c:56: multiple definition of `nagios_pid'; ../common/shared.o:/tmp/nagioscore-nagios-4.4.5/base/../common/shared.c:24: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:177: archivejson.cgi] Error 1
make[1]: Leaving directory '/tmp/nagioscore-nagios-4.4.5/cgi'
make: *** [Makefile:89: all] Error 2
[root@fedora nagioscore-nagios-4.4.5]# make install 
cd ./base && make install
make[1]: Entering directory '/tmp/nagioscore-nagios-4.4.5/base'
/usr/bin/install -c -m 775 -o nagios -g nagios -d /usr/local/nagios/bin
/usr/bin/install -c -s -m 774 -o nagios -g nagios nagios /usr/local/nagios/bin
/usr/bin/install -c -s -m 774 -o nagios -g nagios nagiostats /usr/local/nagios/bin
make[1]: Leaving directory '/tmp/nagioscore-nagios-4.4.5/base'
cd ./cgi && make install
make[1]: Entering directory '/tmp/nagioscore-nagios-4.4.5/cgi'
make install-basic
make[2]: Entering directory '/tmp/nagioscore-nagios-4.4.5/cgi'
/usr/bin/install -c -m 775 -o nagios -g nagios -d /usr/local/nagios/sbin
for file in *.cgi; do \
	/usr/bin/install -c -s -m 775 -o nagios -g nagios $file /usr/local/nagios/sbin; \
done
/usr/bin/install: cannot stat '*.cgi': No such file or directory
make[2]: *** [Makefile:207: install-basic] Error 1
make[2]: Leaving directory '/tmp/nagioscore-nagios-4.4.5/cgi'
make[1]: *** [Makefile:197: install] Error 2
make[1]: Leaving directory '/tmp/nagioscore-nagios-4.4.5/cgi'
make: *** [Makefile:277: install] Error 2

**Comment by Kilvador** [comment]
Hello!

May be you have precompiled package of Nagios for your distributive?

**Comment by sawolf** [comment]
I don't have a Fedora machine on hand right now, will try to reproduce this later.

If you're having issues, though, EPEL does package for nagios core, so you can always try to install via `dnf`
