### ISSUE TITLE
REST API - objects/sla problem with dont_count_warning

### ISSUE THREAD

**Issue by Cesaaar** [NagiosEnterprises/nagioscore#830]
Good evening,

I am using the rest api to download a SLA report from Nagios.
I followed the guide below: https://[NAGIOS-URL]/nagiosxi/help/?xiwindow=api-object-reference.php

Es. https://[NAGIOS-URL]/nagiosxi/api/v1/objects/sla/?apikey=[API-KEY]&pretty=1&host=APPLICAZIONI_BUSINESS&dont_count_downtime=on&dont_count_warning=1

However, the report does not suppress the warning states, despite using the parameter dont_count_warning=1

What could be the problem?

Many thanks for any support

**Comment by sawolf** [comment]
Hi @Cesaaar, hopefully you found a resolution to your issue already, but if you didn't: you'll want to contact the Nagios XI support team to resolve Nagios XI issues. This issue list is only for Nagios Core.
