### ISSUE TITLE
Nagios parent / child issues

### ISSUE THREAD

**Issue by AgastyaTanuj** [NagiosEnterprises/nagioscore#835]
Nagios parent / child issues: Even if Nagios parent host/s come online but children go into Down state and stays in same state, after Unreachable state. Any suggestions on this, please.

Best!

**Comment by ericloyd** [comment]
Down is down.  Unreachable is unreachable.  They are not the same thing and trigger for different reasons.  Without additional information though, we cannot help.

You might be better submitting this to the Nagios support forum, though.  

https://support.nagios.com/forum/

**Comment by AgastyaTanuj** [comment]
Thanks Eric for response. Issue is: In case a parent host comes online after some activity or issue, it's children are still shown in down state. If there is any solution or fix for this issue; help is much appreciated.
Best!

**Comment by ericloyd** [comment]
Nagios Enterprises has an entire online support forum for asking questions just like this.  You can find it at https://support.nagios.com/forum/viewforum.php?f=7

This forum (Github) is not for product support, it is for discussing code issues.  I strongly suggest you search the forum to see if there are any people with problems similar to yours, and if not, then open a new support issue there.  Thousands of people from the community and from Nagios will see it, including me, and you will receive much more support there than you will here.

**Comment by AgastyaTanuj** [comment]
Ok. Thanks.
