### ISSUE TITLE
OK HARD state with current attempt = max_check_attempts (should be 1), on host in DOWN state

### ISSUE THREAD

**Issue by Ysincit** [NagiosEnterprises/nagioscore#837]
Nagios Core Release: 4.4.6
Actual behavior: When a service becomes OK while its host is still DOWN (that is allowed and possible by concept), the service current attempt stays on max attempts. That a service in a problem state gets immediately current attempt = max_check_attempts while a host is DOWN, is described behavior in the documentation, but HARD OK state with current attempt > 1 is not expected/consistent (as I interpret it and could maybe confuse interfaces to other applications).
Expected behavior: current attempt = 1 on a HARD OK state service, independent of the hosts state.
Steps to reproduce (works always): 1. create a host alive check, which you can control e.g. by a existing/non existing file.
2. create a service check with max_check_attempts > 1 (e.g. 5), which you can control e.g. by a existing/non existing file.
3. let service become HARD CRITICAL, then let host become DOWN, then let service become OK and have a look to the  current attempt.

I have already mentioned this bug, and proposed a solution, in a comment to issue #759 . 
But because its good practice that every bug should have its own issue number, I am opening this one.

My proposed solution to solve this problem and #759 was:
in source file base/checks.c (based on source of 4.4.6)
introduce a new flag variable in function handle_async_service_check_result.
int forced_hard = FALSE;
and change the following lines to this new versions:
1354: if (svc->current_state == STATE_OK) { svc->current_attempt = 1; } else { svc->current_attempt = svc->max_attempts; forced_hard = TRUE; }
1392: if (! forced_hard) svc->current_attempt = 1;

Best regards!

**Comment by sawolf** [comment]
Hi @Ysincit, thanks for reaching out. I decided to fix this slightly differently - you can see the commit for more info. If you find a problem with this change, let me know. We're aiming to do a maintenance release in about two weeks.
