### ISSUE TITLE
YouTube on main page

### ISSUE THREAD

**Issue by Benger85** [NagiosEnterprises/nagioscore#840]
Hi all

I was surprised to find a YouTube Frame on the main page of Nagios Core.

Please, for privacy sake, remove the YouTube frame from the main page or just place a link without tracker or at least use youtube-nocookie.com instead.

Thank you.

Regards
Ben

**Comment by sawolf** [comment]
If you're not comfortable/happy with the php portion of the Nagios Core interface, I would recommend customizing that code a little (maybe just remove the links?) and adding those changes to your upgrade process. The marketing for other Nagios products justifies and funds future Core development, so I don't think it's going anywhere.
