### ISSUE TITLE
Timeperiods with slash days (for every X days) with overlapping period not honoring notification period

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#841]
When you have a timeperiod that uses the slash day to occur every X days with an overlapping timeperiod is not honoring the timeperiod.

```
define timeperiod {
        timeperiod_name 1-TimeOff-Sean
        alias   test
        }

define timeperiod {
        timeperiod_name phil.oncall_notification_times
        alias   Notification Times for sean.oncall
        exclude 1-TimeOff-Sean
        2020-01-03 / 21 09:00-24:00
        2020-01-04 - 2020-01-09 / 21    00:00-24:00
        2020-01-10 / 21 00:00-24:00
        2021-09-28      12:00-24:00
        2020-01-17 / 21 00:00-24:00
        2020-01-17 / 24 00:00-24:00
        }
```

I added the "2021-09-28      12:00-24:00" one to send for today and even though I'm in that timeperiod the notifications are not sending. There must be an overlap bug with the slash day thing.

Stemmed from this:

https://support.nagios.com/tickets/scp/tickets.php?id=15715

**Comment by sawolf** [comment]
Had some time to look into this, and as far as I can tell, it's unintuitive, but not a bug. Note that the timeperiod shown above doesn't quite match what the customer was dealing with.

Per the [documentation](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/timeperiods.html), we expect that any "calendar date" directive will be at the same level of precedence as any other. This means that, regardless of whether there's a slash or what exact times are shown, they can be overridden by each other depending on the order of the lines.

From the testing I've done, it looks like the earliest lines take priority over the later lines, within a certain precedence level. This is roughly the opposite of what most users expect (i.e. most users will put a single-day exception at the end of a timeperiod), but changing it is also a backward-compatibility issue. If anyone runs into this again, try putting the single day that's weird at the top of the timeperiod definition.
