### ISSUE TITLE
Broken link to the Nagios Core Development forum in README.md

### ISSUE THREAD

**Issue by hablutzel1** [NagiosEnterprises/nagioscore#845]
In https://github.com/NagiosEnterprises/nagioscore/blob/master/README.md#contributing:

> Do you have an idea or feature request to make Nagios better? Join or start a discussion on the [Nagios Core Development forum](https://support.nagios.com/forum/viewforum.php?f=34).

The previous link is broken. Visiting the page produces:

> https://support.nagios.com/forum/viewforum.php?f=34

**Comment by sawolf** [comment]
Thanks for letting me know - will fix soon

**Comment by fenrus** [comment]
This issue can be closed, it's fixed.
