### ISSUE TITLE
Nagios is sending sometime recoveries notifications and sometimes not!?!

### ISSUE THREAD

**Issue by Rostivar** [NagiosEnterprises/nagioscore#847]
Hello together,
I've the problem that Nagios is sending sometime recoveries notifications and sometimes not.
On each item (where it is needed) the time period is 24x7 and service_notification_options has w,u,c,r 
See an picture as example where the first issue has initiated a recovery notification and the second not.

Nagios® Core™
Version 4.4.6

![nagios_no_ok](https://user-images.githubusercontent.com/6270289/142596774-7214916d-92eb-4061-83e5-c18c5101c9e7.png)

`define service{
        use                             generic-service
        host_name                       srvxxxx,...
        service_description             DNS ns1-yyy
        is_volatile                     0
        check_period                    24x7
        max_check_attempts              1
        check_interval                  5
        retry_interval                  1
        contact_groups                  dl,...
        notification_interval           60
        notification_period             24x7
        notification_options            w,u,c,r
        check_command                   check_nrpe!check_dns_5
}

define timeperiod{
        timeperiod_name 24x7
        alias           24 Hours A Day, 7 Days A Week
        monday          00:00-24:00
        tuesday         00:00-24:00
        wednesday       00:00-24:00
        thursday        00:00-24:00
        friday          00:00-24:00
        saturday        00:00-24:00
        sunday          00:00-24:00
}

define contactgroup{
        contactgroup_name       dl
        alias                   Delivery Leads
        members                 xxx_mail,...
}

define contact{
        contact_name                    xxx_mail
        alias                           Haaa Kbbbb DL
        service_notification_period     24x7
        host_notification_period        24x7
        service_notification_options    w,u,c,r
        host_notification_options       d,u,r
        service_notification_commands   notify-by-email
        host_notification_commands      host-notify-by-email
        email                           e-amil@address.com
}
`

Please can you help me?
BR Rostivar.

**Comment by Rostivar** [comment]
It seems it was an issue with the "flapping service". Will watch it and update this thread.

**Comment by sawolf** [comment]
I agree that the behavior isn't correct - recoveries and flapping behavior don't currently interact properly. I should be able to look into this soon-ish

**Comment by acrewdson** [comment]
> I agree that the behavior isn't correct - recoveries and flapping behavior don't currently interact properly. I should be able to look into this soon-ish

Hi @sawolf 👋 Wanted to check in on this issue. The problem with flap detection where a final RECOVERY alert is never sent once flapping is over has been a problem for as long as I can remember. 

From my perspective, and I assume from many other Nagiosu users' perspectives, addressing this would be a great improvement, and would be hugely appreciated. If there is any possibility of prioritizing this soon, it would be awesome.

Thank you!

**Comment by ranjithkodumbu** [comment]
I am also facing this issue, when Nagios will release the fix for this?

**Comment by sawolf** [comment]
> From my perspective, and I assume from many other Nagiosu users' perspectives, addressing this would be a great improvement, and would be hugely appreciated. If there is any possibility of prioritizing this soon, it would be awesome.

I agree with your perspective - I did spend some time on this closer to my last response, but I don't have the context anymore. I'll see what I can do.

> when Nagios will release the fix for this?

I can't commit to a timeline, but if you think you know the solution, I'm more than happy to review a pull request for the next release.

**Comment by acrewdson** [comment]
@sawolf Thanks for the response. I don't have a solution, but if I come up with one I'll let you know. Thanks for being open to a PR.
