### ISSUE TITLE
Commands not showing on the list

### ISSUE THREAD

**Issue by devopski** [NagiosEnterprises/nagioscore#848]
Hello,
I have defined 160 commands:
![image](https://user-images.githubusercontent.com/77720864/144851650-00662bec-d949-412e-9634-1cae4abdd8bc.png)

When I am trying to add command to the contact I see only part of this list:
![image](https://user-images.githubusercontent.com/77720864/144851777-23f73ad9-debc-42f9-870b-1b83706170a7.png)

Do you know what might be the reason?

**Comment by sawolf** [comment]
Hi @devopski, thanks for reaching out. It looks to me like you're using Nagios XI - this issue list is for Nagios Core. I would recommend reaching out to the Nagios XI support team if you need help with the CCM interface, and they'll be able to help you a lot faster than anyone here.
