### ISSUE TITLE
Timeperiods are corrupted by external command CHANGE_SVC_CHECK_TIMEPERIOD

### ISSUE THREAD

**Issue by xoubih** [NagiosEnterprises/nagioscore#85]
Hi all,
My nagios 4.1.1 installation sometime start after being stopped but stay in an indeterminate state and don't create the nagios.cmd external command file.
After investigations, i note that this is due to bad check_period entries in the retention.dat file : there is random characters instead of the name of the timeperiod that should be there.
A few more testing lead me to this finding :
The use of CHANGE_SVC_CHECK_TIMEPERIOD on the external command file nagios.cmd implie that 
, in the status.dat file, the check_period entry of the service for wich the command was submitted is corrupted (random characters), but ALSO for all entries using the same timeperiod (same random character string for all entries).
This is alway reproductible.
Greetings,

**Comment by tmcnag** [comment]
Can you please provide some architecture information?  OS, version, 32- vs 64-bit, etc.

**Comment by xoubih** [comment]
Thank you for reading.
This occur on : 
        + OS = Red Hat Enterprise Linux Server release 6.1 (Santiago)
        + Kernel = 2.6.32-220.4.2.el6.x86_64
        + Memory = 8054344 kB
Compiled from nagios source.

**Comment by xoubih** [comment]
Tracing the problem, it appear that it occur in those 4 lines :

my_free(temp_service->check_period);
temp_service->check_period = temp_ptr;  
temp_service->check_period_ptr = temp_timeperiod;
attr = MODATTR_CHECK_TIMEPERIOD;

Seem that there's no syntax or logic problem at this point. Conception error ?
It seem that check_period names and notification_period names are shared by all instances.

in objects.c , 
new_service->check_period = cp ? cp->name : NULL;
new_service->notification_period = np ? np->name : NULL;

should be replaced by : 

new_service->check_period = cp ? (char *)strdup(cp->name) : NULL;
new_service->notification_period = np ? (char *)strdup(np->name) : NULL;

to avoid the problem.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' by pulling in @xoubih's commit https://github.com/xoubih/nagioscore/commit/17ebd6760ee46e7e3f4ca970995da744196f8414
via my commit https://github.com/NagiosEnterprises/nagioscore/commit/df2256cce0ec141e81be003553eed7d49a5965d7
