### ISSUE TITLE
Nagios core showing checks that never been added to the host 

### ISSUE THREAD

**Issue by jithinjacob47** [NagiosEnterprises/nagioscore#851]
Hi,

I'm facing an issue with the latest Nagios, it happened 2 days back.
My Nagios is showing some kind of checks that is not relevant or not been added to the specific host.
Is there any way it can be cleared?  
The Nagios has more than 700 hosts, I don't know what exactly happened.. Its showing more than 300 critical alerts..
Can anyone please help?

**Comment by ericloyd** [comment]
You'd be better of submitting this on the Nagios support forum  (https://support.nagios.com/forum) where people can help you with specific examples and configuration information.  This is likely a hostgroup that a service has been attached to and now it's appearing on many hosts, but it will be much easier to help you in the support forums than in the code repository.

**Comment by jithinjacob47** [comment]
Hi,

Thank you for the reply.
I have managed to clear most of the critical alerts, it was due to some messed up settings on a host.
Now, the problem is, there is one Check Site error for some website that I never added. Also, I checked on DB for the specific hosts but no luck, I couldn't see any check or description as named Check Site error.
Do you have any idea where to look?

**Comment by ericloyd** [comment]
You'll get faster responses if you ask this on the Nagios support forum (https://support.nagios.com/forum) where people can help you with specific examples and configuration information. This is not a code problem, it is a configuration problem.

**Comment by sawolf** [comment]
Nagios Core doesn't come with any sort of database integration - if you're using Nagios XI, I recommend that you use official support resources.

If you are using Nagios Core on its own:
Currently, Nagios Core only reads monitoring configuration from the directories specified in nagios.cfg (or whatever configuration file you're reading from. I recommend 1) confirming what file you use for configuration using `ps | grep nagios`, 2) reading that configuration file to determine what directories/files you're using to read configuration info, and 3) grepping those files for your rogue service name. As a side note, if you're finding that you have services that you didn't configure, I would change the SSH keys for the server and make sure no one gets access to them.
