### ISSUE TITLE
Reload Breaks Livestatus

### ISSUE THREAD

**Issue by hs-hub-world** [NagiosEnterprises/nagioscore#852]
Hello, 
We are using Nagios 4.4.6 (The latest version from Github) with Thruk and we are noticing unusual behavior with the service Reload.  If I execute the reload manually directly from the shell that works fine. But when the reload is executed through a schedule task (i.e. Ansible or Rundeck) it breaks the Livestatus.  So we are back to doing service restart.  

we have tried both reload options.
systemctl reload nagios  
OR
/etc/init.d/nagios reload

![image](https://user-images.githubusercontent.com/20629911/147896822-83cb6950-baa3-4b02-8d4b-b7dcd1236a43.png)

At this point, I have not been able to pinpoint the root cause. Any insight is greatly be appreciated!

Thank you
HS

**Comment by ericloyd** [comment]
Sounds like a user mismatch as far as who's doing the reload.

**Comment by hs-hub-world** [comment]
@ericloyd  thanks for the quick reply. Ok, I have confirmed it has nothing to do with the user, every time we restart or reload Nagios the process exits/crashes after 1~2hrs. I have not been able to pinpoint/track in the logs. It has something to do with the new version 4.4.6 for some reason can't handle the host/service load we have. So I downgraded back to 4.4.3 (the previous working version we had) and it's no longer crashing.

![image](https://user-images.githubusercontent.com/20629911/148096238-95c78a6c-5d70-4237-8f22-721d11015da4.png)

**Comment by ericloyd** [comment]
Nagios doesn't really scale well above a few tens of thousands of checks on its own.  Its schedule ends up tripping over itself to get stuff done.  I'm surprised you lasted this long!  You're running about 65,000 checks with more than 88,000 service dependencies, and it really sounds like you're taxing Nagios beyond its limits.  I'd strongly suggest splitting it into two or more separate Nagios servers and/or making use of mod_gearman to lighten the load on the primary server.

**Comment by hs-hub-world** [comment]
Thanks for gearman info- it looks promising. But for now, I have rolled back to 4.4.3 with our current size/load and it works without crashing - just FYI.  I'll close the issue for now.  Thx again!

**Comment by ericloyd** [comment]
Interesting.  It would be worthwhile knowing what's different about the two versions to cause this.  I'm not sure it should be closed.
