### ISSUE TITLE
Nagios Uninstaller

### ISSUE THREAD

**Issue by saumasan** [NagiosEnterprises/nagioscore#853]
Any playbook for Nagios uninstaller?
If not, can someone share the silent command line syntax (or steps) for uninstalling Nagios ?

**Comment by ericloyd** [comment]
service nagios stop
userdel nagios
rm -Rf /usr/local/nagios /home/nagios
Have a beer.  You worked hard.

Other than the start/stop scripts in /etc/init.d or /etc/systemd (or similar things based on your Linux flavor) there really isn't anything else left lying around.  A normal install of Nagios Core puts everything useful in /usr/local/nagios and the home directory for the nagios user has some random stuff in it, but that's about it.

**Comment by saumasan** [comment]
This is for Linux uninstallation. For Windows, i need silent uninstall command.. Is there any ?

**Comment by ericloyd** [comment]
Since you cannot install Nagios on Windows, you must be referring to something else.  Perhaps an agent?  If that's the case, what agent are you looking to uninstall?

**Comment by usabari** [comment]
Suppose, I am going to have anohter monitoring tool instead of Nagios, i would like to do bulk uninstallatoin of the nagios agent from all the servers. and disconnect them from Nagios Relay servers / portal.

**Comment by ericloyd** [comment]
I'm sorry to keep asking, but what agent?  Nagios can use a lot of them.  NCPA?  NSclient?  NRDP?  These are just three of them.  Nagios core itself does not install anything on Windows, so perhaps if you could be more specific, we can be more helpful.  What, exactly, are you wanting to uninstall,l?

**Comment by usabari** [comment]
I am trying to uninstall NCPA client agent that is running on a VM
Regards, Sabari 

    On Sunday, 16 January, 2022, 10:51:21 pm IST, Eric Loyd ***@***.***> wrote:  
 
 


I'm sorry to keep asking, but what agent? Nagios can use a lot of them. NCPA? NSclient? NRDP? These are just three of them. Nagios core itself does not install anything on Windows, so perhaps if you could be more specific, we can be more helpful. What, exactly, are you wanting to uninstall,l?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by usabari** [comment]
i would like to uninstall nagios NCPA client that is installed. I want uninstallation steps (silent commands syntax) for uninstalling NCPA Client for each agent..

**Comment by ericloyd** [comment]
Like most Windows programs, NCPA is installed using the Windows installer.  You can uninstall it using the Windows Add/Remove Programs control panel applet.  I do not believe there is a "silent uninstall" option.  If you need additional help, you should ask on the Nagios support forum, as this is the code repository for Nagios Core, not a support channel for Nagios agents.  Good luck!

https://support.nagios.com/forum

**Comment by usabari** [comment]
Hi, I have 2K servers on which Nagios NCPA Agent is running. We need to uninstall them. I am looking for a playbook to do that job (all are windows servers). Not sure if we have one already.. and that is why I was looking for a command line syntax which can be put in a playbook and I can apply it on all hosts.

**Comment by ericloyd** [comment]
NCPA is installed just like any other Windows program - it uses the Windows installer.  So to uninstall it, you would uninstall it just like any other Windows program - you use the Windows Add/Remove programs applet.  

You can use Google or Duckduckgo to find articles that may help you with uninstalling Windows programs from the command line.  Here is one example:  https://lmgtfy.app/?q=how+to+uninstall+windows+software+from+command+line

Good luck!

**Comment by usabari** [comment]
Hi, BTW, u have an playbook to uninstall NSclient++ silently (without reboot) ?
(0.4.4.19 version)

**Comment by ericloyd** [comment]
NSClient++ is a 3rd party application, not a Nagios produced software product.  You might want to ask on their web site.

**Comment by sawolf** [comment]
Thanks for answering these, @ericloyd.

As Eric pointed out, we don't support installing directly on Windows. Nagios Core doesn't have an uninstaller - for this reason, we usually recommend installing in a virtual environment, so that you can just throw away the VM when you're done with it.

**Comment by usabari** [comment]
Never mind Guys,I wrote one for my self and made it work :)
Regards, Sabari 

    On Wednesday, 6 April, 2022, 12:56:13 am IST, Sebastian Wolf ***@***.***> wrote:  
 
 


Thanks for answering these, @ericloyd.

As Eric pointed out, we don't support installing directly on Windows. Nagios Core doesn't have an uninstaller - for this reason, we usually recommend installing in a virtual environment, so that you can just throw away the VM when you're done with it.
