### ISSUE TITLE
Is Nagios Core still alive?

### ISSUE THREAD

**Issue by nook24** [NagiosEnterprises/nagioscore#854]
I'm asking because the last release was almost two years ago. I also did not find any code changes and it looks like PRs are not getting handled anymore.

**Comment by zigford** [comment]
Not sure either. But it's still functioning perfectly well for me on the latest distro of SLES.

**Comment by ericloyd** [comment]
I've asked Nagios Enterprises to address this question directly, as anything else would be pure speculation.

**Comment by ibering** [comment]
@ericloyd Any news on this issue?

**Comment by ericloyd** [comment]
On February 2, I was told:

> Hey Eric – <TEAM LEAD> mentioned that <THEIR> team was going to check out the question, and answer the question on github, I am not sure if they’ve posted. I suppose the short answer is, Nagios core is still alive.

**Comment by jomann09** [comment]
Sorry for the late response on this. As Eric has mentioned, Nagios Core is not dead. We have no plans to discontinue it.

The last year we've been focusing on other pieces of the monitoring puzzle. We will be circling back to Nagios Core soon to continue development, including updating the pull requests. We are also in the planning stages for Nagios Core 5, which will include a lot of features that I think are going to make it a lot easier to configure and maintain. We will be posting here on GitHub more information about that as we start that process.

As a side note, we also plan on updating the build and testing processes to use more of GitHub's functionality.

**Comment by nook24** [comment]
Thanks @jomann09 for your statement and clarification on this.
I'm looking forward for Nagios Core 5 :)
