### ISSUE TITLE
Ping started throwing this error after yum update on Centos 8   	CRITICAL - Could not interpret output from ping command

### ISSUE THREAD

**Issue by gregg56** [NagiosEnterprises/nagioscore#855]
The ping service and check host alive both worked until this update.
Now the check_ping command, if run from the command line returns a good ping.

Since my first test of the check_ping command worked, I am a bit baffled about what the origin of this message is and how to fix the problem.

Any help will be appreciated.

**Comment by sawolf** [comment]
This is probably an issue for nagios-plugins - I opened an issue over here, so I'm closing this one. If you want notifications for when it gets fixed, feel free to leave a comment on that issue.
