### ISSUE TITLE
Error: Could not read host and service status information!

### ISSUE THREAD

**Issue by Jrb62** [NagiosEnterprises/nagioscore#856]
Hello, currently in training my tutor ask me to put his PC in HOST on his Windows PC. I followed a tutorial that told me to use NSClient ++ and also that I had to modify the folder "windows.cfg" "commands.cfg" and "nagios.cfg", so I restarted my server afterwards to validate my changes. Except that when I restarted the Nagios GUI, I got the error message "Error: Could not read host and service status information!

**Comment by ericloyd** [comment]
You should ask this on the Nagios support forum at https://support.nagios.com/forum.

**Comment by Jrb62** [comment]
Okay thanks!
