### ISSUE TITLE
$SERVICEPROBLEMID$ and $LASTSERVICEPROBLEMID$ do not increment when service changes from CRITICAL to OK

### ISSUE THREAD

**Issue by dgersic** [NagiosEnterprises/nagioscore#859]
Nagios Core 4.4.6 - Claims to be the latest available with no updates available. I created a simple event handler script. Called with command:

`command_line    /usr/local/nagios/libexec/eventhandlers/ticket.sh --hostgroup $HOSTGROUPNAME$ --hostname $HOSTNAME$ --hoststate $HOSTSTATE$ --hostprobid $HOSTPROBLEMID$ --hostlastprobid $LASTHOSTPROBLEMID$ --servicename $SERVICEDESC$ --servicestate $SERVICESTATE$ --serviceprobid $SERVICEPROBLEMID$ --servicelastprobid $LASTSERVICEPROBLEMID$`

When the service changes from OK to CRITICAL, event handler gets:

`Command line  --hostgroup cis-lab --hostname test2.lab.cisus.com --hoststate UP --hostprobid 0 --hostlastprobid 18055 --servicename Test Process --servicestate CRITICAL --serviceprobid 18270 --servicelastprobid 18265`

That looks good. But when the service changes from CRITICAL to OK, event handler gets:

`Command line  --hostgroup cis-lab --hostname test2.lab.cisus.com --hoststate UP --hostprobid 0 --hostlastprobid 18055 --servicename Test Process --servicestate OK --serviceprobid 18270 --servicelastprobid 18265`

Note that the $SERVICEPROBLEMID$ and $LASTSERVICEPROBLEMID$ values are the same.  That's not good.

According to the documentation (https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/macrolist.html#serviceproblemid), the "OK" state should have set SERVICEPROBLEMID to 0 and LASTSERVICEPROBLEMID to 18270.

$SERVICEPROBLEMID$ | A globally unique number associated with  the service's current problem state.  Every time a service (or host)  transitions from an OK or UP state to a problem state, a global problem  ID number is incremented by one (1).  This macro will be non-zero if the  service is currently a non-OK state.  State transitions between non-OK  states (e.g. WARNING to CRITICAL) do not cause this problem id to  increase.  If the service is currently in an OK state, this macro will  be set to zero (0).  Combined with event handlers, this macro could be  used to automatically open trouble tickets when services first enter a  problem state.

$LASTSERVICEPROBLEMID$ | The previous (globally unique) problem  number that was given to the service.  Combined with event handlers,  this macro could be used for automatically closing trouble tickets, etc.  when a service recovers to an OK state.

**Comment by sawolf** [comment]
Hi @dgersic, thanks for reaching out.
There have been a couple of people that mentioned this, and it looks like I added a patch awhile ago to the `maint` branch. I've taken that commit and put it into `master` now.

Would you be able to rebuild Nagios Core from `master` and verify that this issue is fixed for you?

**Comment by dgersic** [comment]
Thanks Sebastian. I don't have the ability to build from source and test this right now. Sorry. I hope the patch works.

**Comment by dgersic** [comment]
Confirmed that this bug is fixed in Nagios Core 4.4.7.
