### ISSUE TITLE
Nsclient++ return code 1 or 2 but GUI shows OK

### ISSUE THREAD

**Issue by thierry-dosseto** [NagiosEnterprises/nagioscore#860]
Hello
After being advised by the manufacturer of our RIS/PACS that one of the server disk was nearly full, I wondered why I was not warned by Nagios (Core latest release on Debian 11).
Well, because the disk (99% full ...) show as ... OK !
And upon verification so do bunch of others with nearly full disks !
check_nt command uses W at 80 and C at 90, it works fine for 90% of my 100+ servers, but fails for 10%
check_nt returns proper 2 return code for this server, as well as 1 for a server with disk full at 85%, so it is definitely Nagios that wrongfuly interprets the correct return code

I've ben using nagios for 15 years on many companies, and I never ever saw such a behaviour.

Any hint ?

**Comment by ericloyd** [comment]
You closed with no notes. What was your solution?

**Comment by thierry-dosseto** [comment]
Hello
my apologies, I left a message but must have messed up since it did not show.
The solution is that I'm an idiot but that check_nt is bugged :-)
Let me explain....
Since I have like 10 disks monitored, like C D E F G H I K L M S, I obviously copied/pasted the service definition.
After the -l you must put the disk reference, hence d e f and so on
I completely forgot to remove the c character, leaving the -l option with both d and c, which caused the bug since d was in warning state but not c disk.
I reckon check_nt or nagios should have thrown an error, since it makes no sense to check 2 disks within the same service.
One again my apologies.

**Comment by ericloyd** [comment]
Thank you.  As for throwing an error while checking more than one disk at once, this is a long-time feature.  The design is so that you do not have to make multiple checks that are the same except for drive letter.  If you group them all together, you can just get one notice that there is a problem on at least one of the drives, and the human who gets the alert is supposed to know to look at figure it out.

Glad it worked out for you.

**Comment by thierry-dosseto** [comment]
Allow me to retort that it does not work, what I posted is the living example.
D was critical whereas C was fine, and both C and D showed green and OK in Nagios.
