### ISSUE TITLE
Services are stuck on pending

### ISSUE THREAD

**Issue by AshleyJ7** [NagiosEnterprises/nagioscore#869]
I just configured the latest version of Nagios Core on Centos. I add all of our servers, added services and it has been stuck in a pending status for a few days. We have restarted services and rebooted the server without any luck. Please assist.

![error](https://user-images.githubusercontent.com/36677968/177339208-a0b33517-4b22-4102-b42b-042e27df6a74.PNG)

**Comment by aaronagios** [comment]
this sort of question would be a better fit on https://support.nagios.com/forum/viewforum.php?f=7
