### ISSUE TITLE
Nagios Core runs for about a day and then just stops.

### ISSUE THREAD

**Issue by darkwaylander** [NagiosEnterprises/nagioscore#870]
Nagios is broken. My Network Engineer upgraded the server from Centos 7 to Centos 8 Stream and updated Nagios. It runs for awhile, then ABENDS (abnormally ends). I am a very junior Network Admin and Cybersecurity Analyst, who has only done minimal classroom based tasks in any Linux Distro. I tried a fix I found on Reddit, and it seemed to work for a while, but even that was not a permanent fix. that fix was found here: https://www.reddit.com/r/nagios/comments/uz4isj/weird_issue_after_updating_from_443_to_447/

Any help with this would be fantastic.

**Comment by sawolf** [comment]
Hi @darkwaylander, thanks for reaching out. Core 4.4.7 did have an issue that would cause periodic crashes. Can you confirm that your issue still exists on version 4.4.8?

**Comment by sawolf** [comment]
I'm going to assume this was related to the segfault when update-checking in 4.4.7 - if you or your network engineer still has issues with this, feel free to open a new issue.
