### ISSUE TITLE
nagios4[2954236] general protection fault ip:7f0d85d91846 sp:7fff0d98dcf8 error:0 in libc-2.31.so[7f0d85d19000+14b000]

### ISSUE THREAD

**Issue by pschonmann** [NagiosEnterprises/nagioscore#871]
Hi, we have problem on relatively fresh installation Nagios 4 on Deb11
Nagios 4 crashes randomly. Tried to update latest kernel and libc but not works.

```
Jul 27 04:15:56 mon kernel: [378516.055884] traps: nagios4[2954236] general protection fault ip:7f0d85d91846 sp:7fff0d98dcf8 error:0 in libc-2.31.so[7f0d85d19000+14b000]

Linux mon 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
ii  linux-image-amd64                       5.10.127-1                                                 amd64        Linux for 64-bit PCs (meta-package)
ii  libc6:amd64                             2.31-13+deb11u3                                            amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                         2.31-13+deb11u3                                            amd64        GNU C Library: Development Libraries and Header Files
```

One thing thats different from repo is that i downloaded source for nagios-nrpe-server and recompiled with –enable-command-args

**Comment by sawolf** [comment]
Hi @pschonmann, thanks for reaching out. In Nagios Core 4.4.7 there was an issue with the update-checking routines causing a crash, which should be fixed in the latest version.
Do you still experience this issue when either compiling from `master` or running on version 4.4.8?

**Comment by sawolf** [comment]
I'm going to close this issue for now - if you find that you're still having this problem on version 4.4.8 or higher, please feel free to create another issue.
