### ISSUE TITLE
Nrpe not working with external ip

### ISSUE THREAD

**Issue by 605adi** [NagiosEnterprises/nagioscore#874]
**Nagios core :** nagios-4.4.6
**nagios-plugins :** release-2.3.3
**Nrpe :** nrpe-4.0.3

I have installed nagios core and nrpe plugin to monitor my system disk cpu and memory usage.
Nagios core and nrpe all working fine with internal ip but when i am using external ip its not working.
**Nagios core and nrpe :-** Nagios server
**Nrpe :-** remote host
**Error:-**
CHECK_NRPE: Error - Could not connect to external ip. Check system logs on external ip.

Is there any configuration in Nagios core or nrpe that i need to change in order to use external ip.

**Comment by sawolf** [comment]
Hi @605adi, thanks for reaching out. This looks like a question related to networking issues with the NRPE project. I would maybe check your allowed_hosts entry in nrpe.cfg. Otherwise, this issue list is for Nagios Core, so I'm going to close this issue.
