### ISSUE TITLE
Caught SIGSEGV

### ISSUE THREAD

**Issue by mauricev** [NagiosEnterprises/nagioscore#875]
I’m trying to get Nagios running under 64-bit Gentoo. It installed fine from source. Log as follows
`
Aug 22 11:45:33 [nagios] Nagios 4.4.7 starting... (PID=32293)
Aug 22 11:45:33 [nagios] Local time is Mon Aug 22 11:45:33 EDT 2022
Aug 22 11:45:33 [nagios] LOG VERSION: 2.0_
Aug 22 11:45:33 [nagios] qh: Socket '/var/lib/nagios/rw/nagios.qh' successfully initialized
Aug 22 11:45:33 [nagios] qh: core query handler registered
Aug 22 11:45:33 [nagios] qh: echo service query handler registered
Aug 22 11:45:33 [nagios] qh: help for the query handler registered
Aug 22 11:45:33 [nagios] wproc: Successfully registered manager as @wproc with query handler
Aug 22 11:45:33 [nagios] wproc: Registry request: name=Core Worker 32295;pid=32295
Aug 22 11:45:33 [nagios] wproc: Registry request: name=Core Worker 32296;pid=32296
Aug 22 11:45:33 [nagios] wproc: Registry request: name=Core Worker 32297;pid=32297
Aug 22 11:45:33 [nagios] wproc: Registry request: name=Core Worker 32294;pid=32294
Aug 22 11:45:33 [sudo] pam_unix(sudo:session): session closed for user root
Aug 22 11:45:33 [nagios] Caught SIGSEGV, shutting down...
`

This is 100% reproducible. It can’t launch at all.

**Comment by sawolf** [comment]
Hi @mauricev, thanks for reaching out. In Nagios Core 4.4.7 there was an issue with the update-checking routines, which should be fixed in the latest version.
Do you still experience this issue when either compiling from `master` or running on version 4.4.8?
