### ISSUE TITLE
Nagios timeout issues 

### ISSUE THREAD

**Issue by SamikshaShukla05** [NagiosEnterprises/nagioscore#879]
Hi all, 
I am facing issue changing the default nagios timeout from 30 sec to 60 sec in the Nagios client systems
------------------------------------------------------------------------------------------------------------------
NSClient.ini 
[/settings/default]

; ALLOWED HOSTS - A comma separated list of allowed hosts. You can use netmasks (/ syntax) or * to create ranges.
<% if @nrpe_servers -%>
allowed hosts = <%= @nrpe_servers.sort.join(',') %>

; Undocumented section
[/settings/NRPE/server]
verify mode = none
insecure = true
allow arguments = true
allow nasty characters = true

[/includes]
**custom = ini://custom.ini
wfm = ini://wfm.ini
eem = ini://eem.ini**

; Undocumented section
[/modules]

; CheckExternalScripts - Execute external scripts
CheckExternalScripts = 1

; CheckHelpers - Various helper function to extend other checks.
CheckHelpers = 1

; CheckEventLog - Check for errors and warnings in the event log.
CheckEventLog = 1

; CheckNSCP - Use this module to check the health and status of NSClient++ itself
CheckNSCP = 1

; CheckDisk - CheckDisk can check various file and disk related things.
CheckDisk = 1

; CheckSystem - Various system related checks, such as CPU load, process state, service state memory usage and PDH counters.
CheckSystem = 1

; NSClientServer - A server that listens for incoming check_nt connection and processes incoming requests.
NSClientServer = 1

; NRPEServer - A server that listens for incoming NRPE connection and processes incoming requests.
NRPEServer = 1

; Section for external scripts configuration options (CheckExternalScripts).
[/settings/external scripts]

; COMMAND ARGUMENT PROCESSING - This option determines whether or not the we will allow clients to specify arguments to commands that are executed.
allow arguments=true

; A list of scripts available to run from the CheckExternalScripts module. Syntax is: <command>=<script> <arguments>
--------------------------------------------------------------------------------------------------
**I tried adding timeout to eem.ini file 
timeout=60
but it did not make any changes to the timeout**
Instead of adding the timeout to the main Nsclient file in the client system I want to add timeout to sub file **eem.in**i mentioned in the includes section of the file

How this can be done 

Thanks,
Samiksha

**Comment by sawolf** [comment]
Hi @SamikshaShukla05, thanks for reaching out. Unfortunately, NSClient isn't actually our project - we support and recommend [NCPA](https://github.com/NagiosEnterprises/ncpa) for Windows monitoring. If you want to continue with NSClient, you'll need to reach out to the maintainers of that project.
