### ISSUE TITLE
4.1.1: "systemctl reload nagios" function is missed

### ISSUE THREAD

**Issue by tjyang** [NagiosEnterprises/nagioscore#88]
I missed "/etc/init.d/nagios reload" feature. I understand we can do "systemctl restart nagios" but it will create new pid for nagios daemon.

**Comment by jfrickson** [comment]
It works on my test box. What OS/Version/Architecture? What version of core?

**Comment by tjyang** [comment]
Hi John
1. Turns out the nagios 4.x rpm I was refering to is from Fedora 21 project. See below
<pre>
[rapi@f21rapi01 .ssh]$ rpm -qif /usr/lib/systemd/system/nagios.service
Name        : nagios
Version     : 4.0.8
Release     : 1.fc21
Architecture: armv7hl
Install Date: Mon 09 Nov 2015 08:54:41 AM CST
Group       : Applications/System
Size        : 7127517
License     : GPLv2
Signature   : RSA/SHA256, Sun 20 Sep 2015 10:04:45 AM CDT, Key ID 89ad4e8795a43f54
Source RPM  : nagios-4.0.8-1.fc21.src.rpm
Build Date  : Sat 19 Sep 2015 07:41:05 PM CDT
Build Host  : arm04-builder05.arm.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
<snipped>
files for Nagios. Development files are built as a separate package.
[rapi@f21rapi01 .ssh]$ sudo systemctl reload nagios
Failed to reload nagios.service: Job type reload is not applicable for unit nagios.service.
[rapi@f21rapi01 .ssh]$ sudo systemctl restart   nagios
[rapi@f21rapi01 .ssh]$ rpm -qil nagios |grep systemd
/usr/lib/systemd/system/nagios.service
[rapi@f21rapi01 .ssh]$


</pre>

2. I try to build 4.1.1 rpm from nagioscore git src by "./configure;cd contrib;make rpm".

systemd/system/nagios.service is not built from our nagios.spec file.
<pre>
[pi@centos71t01 contrib]$ rpm -qilp nagios-4.1.1-2.el7.centos.x86_64.rpm | egrep 'init.d|systemd'
/etc/rc.d/init.d/nagios
[pi@centos71t01 contrib]$
</pre>

Looks like our 4.1.1 nagios.spec doesn't support systemd service at all.

**Comment by tjyang** [comment]
I need some time to recreate the test  case, my test VM got wiped out.

**Comment by tjyang** [comment]
Hi John
I am able to  create a centos 7 VM and " sudo systemctl reload  nagios.service" was able to reload the conf file without using new pid. Sorry for the false alarm.

**Comment by jfrickson** [comment]
No problem. Glad it's working for you!

**Comment by saydulk** [comment]
![screenshot from 2017-11-02 05 08 06](https://user-images.githubusercontent.com/1058663/32302245-dab1e13a-bf8b-11e7-8c29-554526ed4274.png)
![screenshot from 2017-11-02 05 09 51](https://user-images.githubusercontent.com/1058663/32302285-16e6d23c-bf8c-11e7-83eb-774126f97d0b.png)

I am using Ubuntu 16.04 box and having attached problem when i try to start nagios using terminal
