### ISSUE TITLE
Nagios 4.4.7 on AIX: 

### ISSUE THREAD

**Issue by ewwolz** [NagiosEnterprises/nagioscore#882]
I'm trying to run the Nagios 4.4.7 downloaded from the AIX Open Source Toolbox (https://www.ibm.com/support/pages/aix-toolbox-open-source-software-downloads-alpha#N):
```
# rpm -qa | grep nagios |sort 
nagios-4.4.7-1.ppc
nagios-gui-4.4.7-1.ppc
nagios-nrpe-4.0.3-1.ppc
nagios-plugins-2.3.3-1.ppc
```
but I am seeing a bunch of "wproc: Registry request: name=Core Worker" statements in nagios.log followed almost immediately by an equal number of "wproc: Socket to worker Core Worker broken, removing" statements.  There are also a bunch of "Unable to run scheduled host check at this time" and "failed because job was null" messages in the nagios.debug.  

If starting Nagios *not* as a daemon but in the current command window, I also see an equal number of "Worker failed to create io broker socket set: No such file or directory" statements.  The googles tell me that this problem can occur when operating system limits restrict the max number of processes that can be executed... but I'm pretty sure that's not the case here:
```
# ulimit -a
time(seconds)        unlimited
file(blocks)         2097151
data(kbytes)         131072
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     2097151
nofiles(descriptors) 20000
threads(per process) unlimited
processes(per user)  unlimited
```
This is on a POWER8 LPAR with 4 virtual processors and 8 GB of RAM.  AIX oslevel is 7200-05-03-2135.  Any ideas?

**Comment by sawolf** [comment]
Hi @ewwolz, thanks for reaching out. Unfortunately, we don't have any AIX machines available in-house at the moment, so I'm not able to reproduce/debug this (and I haven't seen this issue in any other contexts). If I were you, I'd try reaching out to an AIX-specific support forum or users' group to see if anyone else has run into this.

**Comment by ericloyd** [comment]
It's been a while, but every time we've installed Nagios Core on AIX, we've compiled it from source.  If that's an option for you, I'd go that route rather than rpms.

However, you definitely need to increase the ulimit for root or else you will see problems that are not unlike these.

**Comment by ewwolz** [comment]
I increased nofiles to unlimited but that didn't help.  As long as nofiles is an actual number (doesn't matter which one) I get the messages reported at the top of this thread.

```
# ulimit -a
time(seconds) unlimited
file(blocks) 2097151
data(kbytes) 131072
stack(kbytes) 32768
memory(kbytes) 32768
coredump(blocks) 2097151
nofiles(descriptors) unlimited
threads(per process) unlimited
processes(per user) unlimited

#/opt/freeware/bin/nagios /etc/nagios/nagios.cfg

Nagios Core 4.4.7
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2022-04-14
License: GPL

Website: https://www.nagios.org/
Error: Failed to create IO broker set: Error 0
```

**Comment by ericloyd** [comment]
Sorry - my last suggestion would be to compile from source.  The last time my fingers used Nagios on AIX was 10 years and one week ago, to the day.  :-)
