### ISSUE TITLE
The behavior for last_state_change date between host and service is different

### ISSUE THREAD

**Issue by klnjmm** [NagiosEnterprises/nagioscore#891]
Hi,

I have a different behavior between the value of last_state_change date between host and service when having retry (soft and hard state)

Environment : Ubuntu 20.04

### Nagios 4.2.3

* For host, the value is the date at the last try (when passing from soft to hard status)
<img width="460" alt="host-nagios-4 2 3-01" src="https://user-images.githubusercontent.com/15214050/209554988-40d4dbb5-fa10-41cb-b674-c9d30f55886c.png">
<img width="455" alt="host-nagios-4 2 3-02" src="https://user-images.githubusercontent.com/15214050/209554986-f916084c-d38e-4b14-99de-c5b3e4ad46f6.png">

* For service, the value is the date at the first try (1/X soft state)
<img width="491" alt="service-nagios-4 2 3-01" src="https://user-images.githubusercontent.com/15214050/209554044-a2b4ce48-b9ee-4194-bcc6-9261cbb8836f.png">
<img width="469" alt="service-nagios-4 2 3-04" src="https://user-images.githubusercontent.com/15214050/209554041-535de577-bb6d-48b6-8d4f-aa514dd22c14.png">

### Nagios 4.4.3
This change has fixed this bug for service :
* Fixed last_state_change to update when a state goes from soft -> hard state (#592) (Jake Omann)

But the value for host has changed : it's now the date at the first try ...
<img width="495" alt="host-nagios-4 4 3-01" src="https://user-images.githubusercontent.com/15214050/209554079-5d617dec-5e5a-4529-a3ac-249be41b6846.png">
<img width="502" alt="host-nagios-4 4 3-04" src="https://user-images.githubusercontent.com/15214050/209554077-bfc98b8e-6929-4c09-89a6-afc260be7a63.png">

### Nagios 4.4.9
Same behavior than nagios 4.4.3
<img width="448" alt="host-nagios-4 4 9-01" src="https://user-images.githubusercontent.com/15214050/209554127-e6aedbca-67be-4e7f-8904-1fbb9815711e.png">
<img width="453" alt="host-nagios-4 4 9-03" src="https://user-images.githubusercontent.com/15214050/209554123-13118098-45ed-4481-a02c-19e170589a1a.png">

### Expected behavior :
The value of last_state_change is the value of the last try, when passing in hard state, for host and for service.

Do you encounter the same problem ?

**Comment by sawolf** [comment]
Hi Jim - thanks for reaching out. I haven't gotten into this one yet but the information you've given is clear. I'll commit to at least looking into this for 4.4.11.

**Comment by sawolf** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/commit/ade7c47207130926cb4d120bd604eced2b59fc6a

I wasn't able to find the change that made host state changes regress, but based on the discussion around #592 it seems like people expect "Last State Change" to reflect changes from SOFT to HARD state.
