### ISSUE TITLE
Improve Nagios Alerts

### ISSUE THREAD

**Issue by notanavailableusername** [NagiosEnterprises/nagioscore#894]
Good Morning, All.

I'm not sure if this is the right place for Core 4.3.4 topics, but I couldn't find anywhere specific for Core.

We currently have Nag Core 4.3.4 monitoring our infrastructure and it's running great. We currently monitor a few folder checks i.e. if this file has been here this long in this location, send a warning. What I want to do is add a UNC path to the alert that way we can easily navigate too the folder location. I've searched and have gotten some info, but they are web links and I'm not sure if that will give me the same result.

Thanks, and any help is appreciated!

**Comment by ericloyd** [comment]
What you're asking about is more of a support issue than a technical or code-related issue.  My suggestion would be to ask in the Nagios Community Support Forums at https://support.nagios.com/forum.  In fact, it's entirely possible that I (or one of our staff) would be helping you out over there!

Better to keep GitHub for code-related things, not general support.
