### ISSUE TITLE
Check For Updates Info Incorrect

### ISSUE THREAD

**Issue by TotalGriffLock** [NagiosEnterprises/nagioscore#895]
Having upgraded from nagios core 4.4.9 to 4.4.10 last week, the file main.php indicates that there is a new version available - 4.4.7. This is obviously not a newer version. It seems that in my install the variable last_version (in the status file and so on) is set to 4.4.6 so the API call to api.nagios.org informs that there is an update available. This behaviour was not seen when running 4.4.9.

From /usr/local/nagios/var/status.dat
```
info {
        created=1674756823
        version=4.4.10
        last_update_check=1651142922
        update_available=1
        last_version=4.4.6
        new_version=4.4.7
        }
```
This installation was originally 4.4.6 and has been in place upgraded incrementally (following the documented procedure) to 4.4.10 via each point release.

**Comment by sawolf** [comment]
Just happened to see this issue again and there's a chance there isn't a bug. In 4.4.7, there was a fairly nasty bug where the update check would cause a crash when it ran, and the recommended fix for most people was to set `check_for_updates=0`. Can you confirm that `check_for_updates` is set to `1` in your nagios.cfg file?
