### ISSUE TITLE
nagios and nagiostats permissions

### ISSUE THREAD

**Issue by tartina** [NagiosEnterprises/nagioscore#897]
nagios and nagiostats are installed with 774 permissions.
Is that a mistake?
Shouldn't the permissions be 775 or 755?

**Comment by sawolf** [comment]
Hi @tartina, thanks for reaching out.

I'm not 100% confident, but the permissions seem fine to me. I'm not sure when a legitimate user would want to run either of those programs without being the `nagios` user/in the `nagios` group
