### ISSUE TITLE
NagiosXI on Debian

### ISSUE THREAD

**Issue by nave0010** [NagiosEnterprises/nagioscore#900]
Getting this message while installing NagioXI on Debian Distro, I think I missing some packages as I tried updating pip and tools, they are updated to 44.1.1. Anyone has any ideas how to proceed further on this?

Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  systemctl restart apache2
Enabling module rewrite.
To activate the new configuration, you need to run:
  systemctl restart apache2
Enabling site default-ssl.
To activate the new configuration, you need to run:
  systemctl reload apache2
Collecting pymssql<3
  Downloading https://files.pythonhosted.org/packages/64/68/c1ba0fabf98ebe9d22afc23c6b6803553b28911ed36bb53b8be93feb2446/pymssql-2.2.7.tar.gz (170kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-x1BibJ/pymssql/setup.py", line 54
        raise Exception(f"Unsupported environment value {env_name}={val}")
                                                                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-x1BibJ/pymssql/
RESULT=1

**Comment by dougnazar** [comment]
This doesn't seem to be a `Nagios` issue. It looks like it's failing to install `pymssql`. You don't mention which version of `Debian` or `Python` you are running. Best guess is it's with a version of `Python` less than `3.6` as that was when [f-strings](https://peps.python.org/pep-0498/) were introduced.

From https://wiki.debian.org/Python:

* Debian [Bookworm](https://wiki.debian.org/DebianBookworm) currently contains 3.10, and will likely not ship Python 2, see also [Python/FAQ#Python_2_support](https://wiki.debian.org/Python/FAQ#Python_2_support).
* Debian [Bullseye](https://wiki.debian.org/DebianBullseye) contains 3.9, minimal support for 2.7
* Debian [Buster](https://wiki.debian.org/DebianBuster) contains Python 2.7, 3.7
* Debian [Stretch](https://wiki.debian.org/DebianStretch) contains Python 2.7, 3.5
* Debian [Jessie](https://wiki.debian.org/DebianJessie) contains Python 2.7, 3.4
* Debian [Wheezy](https://wiki.debian.org/DebianWheezy) contains Python 2.7, 3.2
* Debian [Squeeze](https://wiki.debian.org/DebianSqueeze) contains Python 2.5, 2.6 (the default), 3.1.
* Debian [Lenny](https://wiki.debian.org/DebianLenny) contains Python 2.4 and 2.5 (the default).

**Comment by sawolf** [comment]
Hi @nave0010, thanks for reaching out (and thanks Doug for the assist!). If you need help with our paid products, I would recommend creating an account at https://support.nagios.com/forum/ for community support or utilizing your support plan. This issue list is specifically for handling bugs in Nagios Core, which is only a small part of Nagios XI.
