### ISSUE TITLE
Bug in service name - 4.4.11

### ISSUE THREAD

**Issue by nscblauensteiner** [NagiosEnterprises/nagioscore#907]
Hello team,

after updating from 4.4.10 to 4.4.11 the service name for a re-scheduled check appears wrong.
It seems that the "/" becomes a "&".

Service check:

define service{
...
service_description    Space /
is_volatile                   0
check_period             24x7
max_check_attempts 3
check_interval            60
retry_interval              1
...
}

If I now reschudele this check on the web it looks like this:

![image](https://user-images.githubusercontent.com/54094754/233571297-ebeef065-de19-455a-9323-1eb246af97dd.png)

BR, Lukas

**Comment by sawolf** [comment]
Hi Lukas, thanks for reporting this - I was able to reproduce the issue, and I'll make sure this is fixed for 4.4.12.

**Comment by nscblauensteiner** [comment]
> Hi Lukas, thanks for reporting this - I was able to reproduce the issue, and I'll make sure this is fixed for 4.4.12.

Hy Sebastian, thanks so far!
