### ISSUE TITLE
Downtime Comment Wrong Entry time

### ISSUE THREAD

**Issue by blevans33** [NagiosEnterprises/nagioscore#910]
After putting a service in Fixed Downtime with any old Comment,
Go to the Service's Detail page. The Entry Time should look correct for the comment associated with the downtime entry.
Now restart Nagios.
Go to the Service's Detail page again. This time the Entry Time is different!

Apparently, the Entry Time gets updated to current time every time Nagios Core is restarted.
Im guessing that Core, upon startup, is going through its retention.dat data and putting in place the downtime entries it finds there as if they were fresh, at which point they get a timestamp/Entry Time of now.

Bug?

**Comment by sawolf** [comment]
Possibly a bug - I will try to look into this when I can

**Comment by sawolf** [comment]
I looked into this awhile back and forgot to update you on it.

Here's what happens internally:
1) When you "register" a downtime, Nagios Core also creates a comment at the same time.
2) The comment isn't set as a persistent comment, so it gets deleted on restart.
3) The downtime does not get deleted, but is instead passed through that same "register" routine again.

It looks like fixing this is going to require a change to the project headers (which are technically a public API), so I'm going to defer the fix to 4.5.0.

**Comment by sawolf** [comment]
This is fixed in 4.5.2 - closing
