### ISSUE TITLE
Feature Request: Time Period for Event handler

### ISSUE THREAD

**Issue by iam333** [NagiosEnterprises/nagioscore#913]
Hi!
Thanks in advance!

I think it would be quite useful and would make the platform more versatile if a timeperiod could be applied to the execution of an event handler, since there are times, at least I have found them, when it is necessary that an event handler not be executed but if that the check of the monitored service continue to be carried out.

Regards!

**Comment by ericloyd** [comment]
Yes!

**Comment by sawolf** [comment]
This sounds pretty smart/achievable to me. No promises, but I'd like to look into this soon.
