### ISSUE TITLE
Nagios availability report

### ISSUE THREAD

**Issue by SrinivasKesiraju** [NagiosEnterprises/nagioscore#915]
I want to see Hostname and IP address in the Nagios availability reports. Please let me know how to get this feature.

**Comment by ericloyd** [comment]
Hostname is already there.  Do you need IP address as well?  If so, may I suggest naming your boxes by IP so that it shows up in the report?

**Comment by SrinivasKesiraju** [comment]
Thank you for your reply and will update IP too

**Comment by sawolf** [comment]
Hi, thanks @SrinivasKesiraju for reaching out (and thanks Eric for the answer)! I agree with what Eric said here and it looks like you have resolution, so I'm closing this issue.

**Comment by SrinivasKesiraju** [comment]
Thank you.
