### ISSUE TITLE
Icons no longer displaying in Host Status or Service Status pages

### ISSUE THREAD

**Issue by thebream** [NagiosEnterprises/nagioscore#917]
Have just upgraded from 4.4.8 to 4.4.12.

```
tim@ct-nagios2:~$ uname -a
Linux ct-nagios2 5.15.107-2-pve #1 SMP PVE 5.15.107-2 (2023-05-10T09:10Z) x86_64 GNU/Linux

tim@ct-nagios2:~$ /usr/local/nagios/bin/nagios --version

Nagios Core 4.4.12
```

Icons defined with **icon_image** in config file no longer display, instead get a "broken" icon indicating image is missing.

e.g. viewing page source for an icon on Host Status page shows this:
`img src="/nagios/logos/mynagios.png"`

(Icons ARE displayed correctly in Status Map and Legacy Status Map)

To work around this, I had to copy my icons from here:
/usr/local/nagios/share/images/logos
to here:
/usr/local/nagios/share/logos

i.e. seems to be looking in a different path?

Possibly related to this commit?
https://github.com/NagiosEnterprises/nagioscore/commit/5ca31625d90615d8552ac57c5aefb633a85ec3b9

I believe I was using the correct path (i.e. **images/logos**, not just **logos**):
`Images for hosts are assumed to be in the logos/ subdirectory in your HTML images directory (i.e. /usr/local/nagios/share/images/logos)` [1]

[1] https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html

**Comment by sawolf** [comment]
I agree that you were using that path and I can reproduce this behavior. The test environment I used yesterday didn't have any icons configured - that's fixed going forward. You can expect a release in the next couple of days (maybe next week at the worst).
