### ISSUE TITLE
Nagios® Core™ Version 4.3.4  - Uncaught ReferenceError: set_limit is not defined     

### ISSUE THREAD

**Issue by gataullinrn** [NagiosEnterprises/nagioscore#921]
I am observing an issue when I try to limit results from 100 to any other value. 
Here is the message I get: 
Uncaught ReferenceError: set_limit is not defined
    at HTMLSelectElement.onchange (status.cgi?host=all&servicestatustypes=28:124:99)

**Comment by sawolf** [comment]
Hi @gataullinrn, thanks for reaching out. I don't reproduce this on the latest version of Core (4.4.13) - it looks like `set_limit` is defined on status.c:586, and is only used at status.c:5609. I would recommend upgrading to the latest version to fix your problem.
