### ISSUE TITLE
duplicate hosts on map

### ISSUE THREAD

**Issue by sistemmsn** [NagiosEnterprises/nagioscore#929]
Is there a reason why the Nagios map is duplicating hosts

<img width="459" alt="image" src="https://github.com/NagiosEnterprises/nagioscore/assets/38023703/d2396742-42f4-4003-af0f-346b58e546dc">

Nagios core version 4.4.13
Nagios XI version 5.11.1
CentOS Stream 8

**Comment by WBACC** [comment]
Still seen in 4.5.1, does not happen in the legacy map

**Comment by sawolf** [comment]
This will be "fixed" next release (though maybe not in a way you guys like) by #963 - commenting here so that they're reachable from each other
