### ISSUE TITLE
4.5.0 -- Error munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by Eremius** [NagiosEnterprises/nagioscore#936]
Ubuntu 22.04
Nagios Core 4.5.0 using ndo2db

CLI startup:
root@nagios:~/build/nagioscore#  /usr/local/nagios/bin/nagios /usr/local/nagios/etc/nagios.cfg

Nagios Core 4.5.0
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2023-11-14
License: GPL

Website: https://www.nagios.org
Nagios 4.5.0 starting... (PID=7989)
Local time is Thu Dec 07 09:40:45 EST 2023
wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 7998;pid=7998
wproc: Registry request: name=Core Worker 7991;pid=7991
wproc: Registry request: name=Core Worker 7990;pid=7990
wproc: Registry request: name=Core Worker 7994;pid=7994
wproc: Registry request: name=Core Worker 7992;pid=7992
wproc: Registry request: name=Core Worker 7993;pid=7993
wproc: Registry request: name=Core Worker 7999;pid=7999
wproc: Registry request: name=Core Worker 7995;pid=7995
wproc: Registry request: name=Core Worker 7996;pid=7996
wproc: Registry request: name=Core Worker 8000;pid=8000
wproc: Registry request: name=Core Worker 7997;pid=7997
wproc: Registry request: name=Core Worker 8001;pid=8001
Event broker module '/usr/local/nagios/bin/ndomod.o' initialized successfully.
munmap_chunk(): invalid pointer
Aborted (core dumped)

I am happy to provide any additional information as necessary.

**Comment by sawolf** [comment]
Hi @Eremius - did you update the Nagios Core headers and recompile `ndomod`/`ndo2db` when you updated Core?
