### ISSUE TITLE
Incorrect changelog links for specific releases 4.4.8 and earlier

### ISSUE THREAD

**Issue by simonflood** [NagiosEnterprises/nagioscore#937]
On the basis that later releases* link to the changelog for that release then all releases from 4.4.8 and earlier link to the latest changelog and not to the specific one for each of those releases.

I'll also note that 4.4.9 links to a blob URL (which works) rather than the usual https://github.com/NagiosEnterprises/nagioscore/blob/nagios-X.Y.Z/Changelog URL

*with the exception of the (currently) latest release 4.5.0 which links to the changelog for 4.4.13 - already logged as #935

**Comment by sawolf** [comment]
Hi @simonflood - thanks for the heads-up. I did change the release process around version 4.4.9 to point to the actual changes for that release. I'm probably not going to go back through all the other releases to update their links though.

As far as 4.5.0, I handed off that process to another team recently, and we're still working through the kinks there. I'm updating the links and tags for Core/plugins today.
