### ISSUE TITLE
Nagios Service not starting

### ISSUE THREAD

**Issue by makwanapratikp** [NagiosEnterprises/nagioscore#941]
OS is Cent OS -7 

● nagios.service - Nagios Core 4.4.2
   Loaded: loaded (/usr/lib/systemd/system/nagios.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2024-01-17 15:35:28 IST; 5 days ago
     Docs: https://www.nagios.org/documentation
  Process: 16316 ExecStopPost=/usr/bin/rm -f /usr/local/nagios/var/rw/nagios.cmd (code=exited, status=0/SUCCESS)
  Process: 16313 ExecStartPre=/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg (code=exited, status=1/FAILURE)

Jan 17 15:35:28 nagios.kiya.ai systemd[1]: nagios.service: control process e...1
Jan 17 15:35:28 nagios.kiya.ai nagios[16313]: Check your configuration file(...d
Jan 17 15:35:28 nagios.kiya.ai nagios[16313]: directives and data definition...s
Jan 17 15:35:28 nagios.kiya.ai nagios[16313]: version of Nagios, you should ...s
Jan 17 15:35:28 nagios.kiya.ai nagios[16313]: may have been removed or modif...d
Jan 17 15:35:28 nagios.kiya.ai nagios[16313]: the HTML documentation regardi...e
Jan 17 15:35:28 nagios.kiya.ai nagios[16313]: 'Whats New' section to find ou....
Jan 17 15:35:28 nagios.kiya.ai systemd[1]: Failed to start Nagios Core 4.4.2.
Jan 17 15:35:28 nagios.kiya.ai systemd[1]: Unit nagios.service entered faile....
Jan 17 15:35:28 nagios.kiya.ai systemd[1]: nagios.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by everwatch** [comment]
FYI, Red Hat has made the announcement that CentOS 7 will reach end of life (EOL) on June 30, 2024. Once it's EOL, you will no longer be able to install or upgrade new software versions. Plus, if you want to perform a migration to a newer OS, you won't be able to install CentOS 7 on a test server for proper migration testing.  You may want to take this time to upgrade to CentOS Stream/RHEL 8/9 or a newer, supported version of Ubuntu and Debian if you can.  (Side note: we'd be happy to help you if you need it).

**Comment by sawolf** [comment]
Hi @makwanapratikp - I'm guessing there's an error in your configuration, but the service output is missing most of the important details. Can you show us the output of the following command?

`tail -50 /usr/local/nagios/var/nagios.log`

**Comment by makwanapratikp** [comment]
How i can configured Auto Email configuration in Nagios?

**Comment by makwanapratikp** [comment]
after reconfigured.
