### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by BlackMage2** [NagiosEnterprises/nagioscore#942]
Hello, i get ever the error in error.log at apache2 when i try to access the nagios site
`AH01620: Could not open password file: /usr/local/nagios/etc/htpasswd.users`

How i setup nagios?

**Comment by sawolf** [comment]
Hi @BlackMage2, thanks for reaching out! [Here](https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html) is our official setup document, which will cover user account setup.
