### ISSUE TITLE
Nagios Core 4.5.2 "/usr/local/nagios/bin" directory not created

### ISSUE THREAD

**Issue by buzzing-bee** [NagiosEnterprises/nagioscore#959]
OS Version: Ubuntu 22.04.4 LTS
Nagios Core Version: nagios-4.5.2

Steps Taken (as root): 
- tar -zxvf nagios-4.5.2.tar.gz
- ./configure
- make all
- make install-groups-users
- usermod -a -G nagios www-data
- make all
- make install-init
- make install-commandmode
- make install-config
- make install-daemoninit

> # Content of /usr/local/nagios/ Directory
> ls -lah /usr/local/nagios/
> total 24K
> drwxr-xr-x  6 root   root   4.0K May 14 11:52 .
> drwxr-xr-x 12 root   root   4.0K May 14 11:47 ..
> drwxrwxr-x  3 nagios nagios 4.0K May 14 12:09 etc
> drwxr-xr-x  2 root   root   4.0K May 14 11:52 libexec
> drwxr-xr-x  5 nagios nagios 4.0K May 14 11:53 share
> drwxr-xr-x  3 root   root   4.0K May 14 11:47 var

I'm planning to use nginx as the webserver, but upon finished compiling, I notice the binary folder is missing.
Already tried to downgrade the version to 4.5.0, but the result is still the same.

Need advise.

Thank you

**Comment by sawolf** [comment]
Hi @buzzing-bee - `make install` seems to be missing from your steps. You normally want to run it after `make all` and before `make install-init`.

**Comment by buzzing-bee** [comment]
> Hi @buzzing-bee - `make install` seems to be missing from your steps. You normally want to run it after `make all` and before `make install-init`.

silly me, I forgot to execute that `make install`.
Thanks, now it's working.
