### ISSUE TITLE
Quick search doesn't show hosts without services (service status detail page)

### ISSUE THREAD

**Issue by rcknag** [NagiosEnterprises/nagioscore#96]
Quick search only references the service status detail page, if there are no services defined then it identifies the 1 host. If this is the case, have it show the host status page for the 1 host.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/32242c78914ce7814349f894c1d7d6da4900ec9e

**Comment by BotFodder** [comment]
I understand and empathize with the original issue, except that the fix has broken expected functionality -

Now, if I search for hosts with services (particularly with a wildcard to match multiple hosts that may have similar service listings) I don't see the service listing for all the hosts - only the host list.

Searching without a wildcard will match the "first" host and show the service list for that host, but not other similar matches (that behavior has always been a tad odd).

**Comment by jfrickson** [comment]
New fix is in 'maint' branch. Reopen this issue if it still doesn't work correctly.

**Comment by dvoryanchikov** [comment]
Hi, John! Commit 32242c78914ce7814349f894c1d7d6da4900ec9e breaks the "noheader" option:
the num_services variable used in if condition is not calculated, because show_service_status_totals() is not executed with display_header=FALSE, thus with &noheader in url the style type improperly changes to host detail.
Temporary fix is to add display_header check to if condition:
```
--- cgi/status.c	2017-01-23 22:23:57.000000000 +0300
+++ cgi/status.c	2017-01-31 14:07:37.000000000 +0300
@@ -448,7 +448,7 @@
 		}
 
 	/* Special case where there is a host with no services */
-	if(display_type == DISPLAY_HOSTS && num_services == 0) {
+	if(display_type == DISPLAY_HOSTS && num_services == 0 && display_header == TRUE) {
 		display_type = DISPLAY_HOSTGROUPS;
 		group_style_type = STYLE_HOST_DETAIL;
 	}
```
