### ISSUE TITLE
A user reported a Segfault whenever they try to access Nagvis or the Nagios map after upgrading (4.4.14 => 4.5.2)

### ISSUE THREAD

**Issue by ne-bbahn** [NagiosEnterprises/nagioscore#961]
A user upgraded from 4.4.14 to 4.5.2 and are getting segfaults when they try to access Nagvis or the Nagios map.

> I have a problem with nagios core working with version 4.5.2 of Nagios, when I access the nagvis or nagios map, I saw that when this happens the nagios.cmd file is dead.

nagios.log:
> [1715895380] Caught SIGSEGV, shutting down...

https://support.nagios.com/forum/viewtopic.php?t=75312

**Comment by sawolf** [comment]
I answered this on the forum as well, but they'll need to recompile their NEB modules with the headers from Nagios Core 4.5.0
