### ISSUE TITLE
4.5.3 Release small in size (missing files)

### ISSUE THREAD

**Issue by spithash** [NagiosEnterprises/nagioscore#967]
Hello there, 

Isn't [this release ](https://github.com/NagiosEnterprises/nagioscore/releases/tag/nagios-4.5.3)a bit small in size? I mean the tar.gz is 1.96 MB

I had issues when trying to upgrade from 4.5.2 to 4.5.3, there were missing files such as map.php for example.

Looking at all the releases back in time, the tar archive was never that small...

Correct me if I'm wrong. I had to roll back to 4.5.2

**Comment by arnonerba** [comment]
Yes, the 4.5.3 release appears to be broken. See also https://github.com/NagiosEnterprises/nagioscore/issues/968.

**Comment by spithash** [comment]
Thank you for the quick response, looking forward to the next release then :)

**Comment by sawolf** [comment]
Hi @spithash - the reduced size is intended. Up until 4.5.2, we had a few pages in the interface that were relying on AngularJS (not the modern framework, but the one from the early 2010s). A user reported that several of the javascript dependencies in this project were out of date and showing on their vulnerability scanners. Given that there isn't a supported version of AngularJS anymore, we had the option to either rewrite the page (either in Angular or in another modern framework), or to remove the pages and update the links to point to the CGI version of the page.
