### ISSUE TITLE
modern map files are missing and the Map link points to the legacy one

### ISSUE THREAD

**Issue by ratmole** [NagiosEnterprises/nagioscore#968]
Hi, after https://github.com/NagiosEnterprises/nagioscore/commit/584fb2184f1307d8aba68a333e8da56a33b9cd5e
is seems that modern status map is removed, can you please let us know why?

thanks

**Comment by arnonerba** [comment]
See also https://github.com/NagiosEnterprises/nagioscore/issues/967.

**Comment by sawolf** [comment]
Hi @ratmole - thanks for reaching out. Up until 4.5.2, we had a few pages in the interface that were relying on AngularJS (not the modern framework, but the one from the early 2010s). A user reported that several of the javascript dependencies in this project were out of date and showing on their vulnerability scanners. Given that there isn't a supported version of AngularJS anymore, we had the option to either rewrite the page (either in Angular or in another modern framework), or to remove the offending pages and update the links to point to the CGI version of the page. We opted for the latter.

**Comment by geeksmooth** [comment]
Confirm this affect my installation. 
Distro: Archlinux

thanks

**Comment by pathia** [comment]
So that explains why the map files are missing...
So now we're back with the reaaaally old statusmap cgi.
Any plans for a rewrite or by any means a new version? I really hate the map layout of the default legacy map cgi version

**Comment by tsadpbb** [comment]
I can't promise anything but PR's are always welcome!
