### ISSUE TITLE
New network map overlays the nagios process with objects

### ISSUE THREAD

**Issue by jfrickson** [NagiosEnterprises/nagioscore#97]
If there is only one object (such as a host), it will overlay the nagios process in the new network map. If that object has a single child, that will also overlay the other two. It would probably continue further.

**Comment by jfrickson** [comment]
Should be fixed in commit https://github.com/NagiosEnterprises/nagioscore/commit/bedf586742301ac036eafda8a651c0f9626b945a
in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1

**Comment by dbareiro** [comment]
Hi, John.

I was testing it and I noticed also it solves the problem of duplicate hosts. That's great! Thanks!

A curious question (aesthetics): I had a feeling that after applying 7ca4de0, the hosts icons get better organized following a bouquet form based on the father of each hosts. Before I think this did not happen and the hosts appeared with crisscrossing lines. But now I see again the lines crisscrossing the hosts. It is not terrible (at least for my number of hosts) but I was curious if there was any relationship with this patch. Below a screenshot about the mentioned.

![crisscrossinglines](https://cloud.githubusercontent.com/assets/7597354/11722730/25fa502e-9f49-11e5-929a-a717c478b29c.png)

Thanks for your time.

Best regards,
Daniel

**Comment by jfrickson** [comment]
d3 seems to change things based on what seems to be minor unrelated changes. So it's difficult to say why it's showing up differently. To me, d3 is one HUGE mystery! :-)

**Comment by dbareiro** [comment]
What a mystery! :-)

Well, I think we've closed the issues that were important. It was good to contribute with you and I appreciate your time. If you ever see again this aesthetic detail (which probably is something minor regarding other issues), I would like to know the news.

Thanks again!

Best regards,
Daniel
