### ISSUE TITLE
[QUESTION] Nagios Core Repo for RHEL next update??

### ISSUE THREAD

**Issue by Guyver1wales** [NagiosEnterprises/nagioscore#972]
HI, I just upgraded our nagios core server at work to RHEL 9 and the repo installation of nagios-core and plugins.
the nagios repository currently has v4.4.14.

how often does this repo get updated and when is the next update planned and to which version of core??

EDIT
REPO:
epel

**Comment by Guyver1wales** [comment]
nagios installed

**Comment by Guyver1wales** [comment]
nagios actually installed with EPEL repo so question is when will the EPEL repo be updated and with which version?

**Comment by sawolf** [comment]
Hi @Guyver1wales - I think you'll want to reach out to the EPEL project on this one - Nagios Enterprises does not directly publish to any third-party RPM repositories
