### ISSUE TITLE
Feature request: Planned down host

### ISSUE THREAD

**Issue by sickel** [NagiosEnterprises/nagioscore#979]
In our system, we have hosts that may be taken down for a undefined time and then they will be returned to service, So, the host is down, but I do not need to be told.

As far as I can see, I can not use scheduled downtime as I have to set a planned time when the system is going to be back, In my case, I do not know when the system will be back, I just know it is OK it is down and it will come back on some later time. When it is back, I want the status of the host and any services running on it to be checked as normal.

I think the scheduled downtime system may be useable for my case, if it had been possible to define an unknown endtime on the downtime.

For the host that is set as planned down with unknown time for back up:
Nagios keeps on checking the host, but leaves the status as OK, As soon as the host is back up, checks are back to normal

**Comment by klaernie** [comment]
Isn't that what an acknowledgement doest?

**Comment by ericloyd** [comment]
You want flexible downtime.
