### ISSUE TITLE
Does 'CHANGE_CUSTOM_SVC_VAR' still work?

### ISSUE THREAD

**Issue by willemdh** [NagiosEnterprises/nagioscore#99]
Following this thread https://support.nagios.com/forum/viewtopic.php?f=16&t=35342
I did some basic tests with 'CHANGE_CUSTOM_SVC_VAR', but it doesn't seems to be working? Is a Nagios restart required?

http://old.nagios.org/developerinfo/externalcommands/commandinfo.php?command_id=140

**Comment by jfrickson** [comment]
When you give your command:
`/usr//bin/printf "[%lu] CHANGE_CUSTOM_HOST_VAR;localhost;_osinfo;CentOS10\n" $now > $commandfile`
the custom variable name should _not_ have the beginning underline. The above should be
`/usr//bin/printf "[%lu] CHANGE_CUSTOM_HOST_VAR;localhost;osinfo;CentOS10\n" $now > $commandfile`
Try it that way and see if it works.

**Comment by jfrickson** [comment]
If it doesn't work, leave a comment here and I'll reopen the issue.

**Comment by taucher4000** [comment]
Hi, I´ve to reopen this issue since I´m still facing the same problem with Nagios Core 4.1.1. I´m trying to execute an external command like:
/usr/bin/printf "[%lu] CHANGE_CUSTOM_SVC_VAR;server1;service name;custom_var_name;test\n" `date +%s` > ./command.cmd

and the debug log shows: 
[1465396675.794406] [128.2] [pid=2979] Raw command entry: [1465396675] CHANGE_CUSTOM_SVC_VAR;server1;service name;custom_var_name;test
[1465396675.794459] [128.1] [pid=2979] External Command Type: 148
[1465396675.794475] [128.1] [pid=2979] Command Entry Time: 1465396675
[1465396675.794482] [128.1] [pid=2979] Command Arguments: server1;service name;custom_var_name;test

But the Custom variable has not been changed.

Any thoughts?

**Comment by taucher4000** [comment]
I´ve created a new issue since this is already closed: https://github.com/NagiosEnterprises/nagioscore/issues/133

**Comment by dvoryanchikov** [comment]
Hi!
You should have custom variable defined like this:

define service{
; any other definitions
        service_description             service name
        host_name                       server1
        _custom_var_name           
        }

Does you have it in service config?

**Comment by taucher4000** [comment]
Yes, this is exactly what I did to define the custom variables in my service configuration.

**Comment by dvoryanchikov** [comment]
How do u checking that variable does not changed?
try to add in check script defined in service check command something like 
echo "${NAGIOS__SERVICECUSTOM_VAR_NAME}" >/tmp/test

**Comment by taucher4000** [comment]
I checked this via Nagios JSON API "objectjson.cgi?query=servicelist&details=true&hostname=server1" where you can see the whole host/service status including custom_configurations. Additionally I also redirected all nagios environment variable macros into a temp file as you recommended. But the custom vars are not changing.

**Comment by dvoryanchikov** [comment]
Seems objectjson.cgi can't access core runtime changes even after program restarts/reloads, it only shows initial configuration information, but commands CHANGE_CUSTOM_HOST/SVC/CONTACT_VAR are working well (I have 4.1.0rc1, not so old version) and new variable values can be accessible from whithin nagios checks in environment variables as in my example before, from macros in configuration or from mklivestatus query for example.
Do u have enable_environment_macros=1 in nagios config? If not, u can try to define test check command like this
command_line       path_to_test_script $_SERVICECUSTOM_VAR_NAME$

and in test script add
echo $1 >/tmp/test2

**Comment by taucher4000** [comment]
Hi dvoryanchikov, you are right, I always just tested if the objectjson returned the changed value but it just shows the configuration and not the actual value. If I get the custom var as a macro in a command-script, I can see the changed value.

So basically it looks that CHANGE_CUSTOM_SVC_VAR is working.
