### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [NagiosEnterprises/nagioscore#996]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Nagios application as shown [here](https://elest.io/open-source/nagios). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/nagios)

**Comment by ericloyd** [comment]
Nagios Core, as open source software, should not have a commercial "deploy me" button.  I applaud your successes with it as a company, but I believe this is the wrong place for you to get your advertising.  After all, if you get a deploy button, why shouldn't everyone else?

**Comment by everwatch** [comment]
Nagios Core, as open source software, should not have a commercial "deploy me" button. I applaud your successes with it as a company, but I believe this is the wrong place for you to get your advertising. After all, if you get a deploy button, why shouldn't everyone else?

**Comment by kaiwalyakoparkar** [comment]
I understand, is there a dedicated page that I can add this to? Like a third party/ commercial listings page?

**Comment by dylan-at-nagios** [comment]
@everwatch is correct. Closing this issue because I feel the matter has been resolved adequately.
